연락처관리 UI [STEP 2] Miro, Lust3r
tasty-code/ios-contact-manager-ui pull request #11
Opened 2023-02-02 01:54 UTC by llimental

안녕하세요 븨븨(@YebinKim)~~! 🙌🏻, Step1 PR을 통해서 몰랐던 target과 module에대한 개념을 확실히 이해할 수 있었어요!☺️
Step2에서는 Tableview 구현과 Dummy data 생성에 초점을 두어 프로젝트를 진행해봤어요. 감사합니다~! 🙇‍♂️🙇‍♂️ 

# 🧑🏼‍💻 작업 목록

‼️ **명세서에 있는 데이터를 그대로 복사해온 것이 아니라, 저희가 직접 랜덤 Dummy data를 만들어려고 했습니다!**

## 🎯 STEP 2 : [[스크럼](https://www.notion.so/UI-Ver-8cebb7785d734fb1a9953e1dcf42da53)]

- [x]  Table View를 활용하여 연락처 목록을 화면에 표시합니다
- [x]  각 행의 cell은 subtitle style을 사용합니다
- [x]  각 행(row)에 표시할 항목
  - 이름, 나이, 연락처

## 💭 학습 키워드

- Table View
- Table View Cell
- Enum computed property
- Random
- ClosedRange
- ContentConfiguration

## 🙋🏻 고민해보기

### 🫧 함수명과 변수명 설정하기

저희는 랜덤한 dummy data를 생성하기 위하여 `ContactInfo` 파일을 새롭게 추가하는 등, 다양한 변수명과 함수명을 설정했어요. 

최대한 함수명만 보고도 어떠한 역할을 하는 지 알 수 있게 명명을 하려고 노력해봤지만, 븨븨가 보셨을 때 아직 어색한 함수명 혹은 변수명이 있으실까요? 🤔 (ex, `configure(cell:, at indexPath:)` )

### 🫧 더미 데이터 생성하기(feat. enum computed property)

이번 Step2를 진행하면서, TableView의 설정이 끝나고, 실제 데이터를 대입하여 기능명세와 같이 표시되는지 확인할 필요가 있었습니다. 하지만 기존의 ContactManager는 콘솔로 진행되는 프로그램이었기에 Target만 추가한 지금의 App 상태로는 데이터를 받을 수 없었고, 직접 하드코딩하기에는 테스트 데이터여도 보기에 깔끔하지 않은 것 같았습니다.

그래서 더미 데이터를 생성해보기로 했고, 그 과정에서 단순히 반복문을 사용할지, 함수로 따로 빼서 사용할지 등 다양한 논의를 하다가 지난 프로젝트인 JuiceMaker에서 각 과일별 재고를 반환했던 enum 구조가 떠올랐습니다. 이에 enum도 조금 더 공부해보자는 생각에 사용을 해보게 되었습니다.

Contact에 들어갈 정보인 `이름(name), 나이(age), 전화번호(phoneNumber)`를 case로 두고, `random`이라는 연산 프로퍼티를 활용하여 각 케이스마다 어떻게 랜덤한 데이터를 반환할지 구현하였습니다.
이렇게 만든 무작위 데이터를 `makeRandomContact(count:)` 함수를 사용하여 넣어주게 되었습니다.

이와 같은 방식으로 데이터를 생성한 것에 대한 븨븨의 의견이 궁금합니다! 🤔

### 🫧 접근제어 설정하기

`ContactManagerUI Target`에서 `ViewController`와 `ContactInfo` swift 파일에 코드를 작성하면서 다른 곳에서 접근할 필요가 없어 내부에서만 사용되는 변수나 함수의 경우 `private`를 통해 접근제어를 높이고자 하였습니다. 혹시 “이 부분도 private가 설정되면 좋겠다”거나 “이 부분은 기본 수준으로 낮추는 것이 좋겠다”하는 곳이 있을까요? 🤔

2023-02-02 14:53 UTC, YebinKim requested changes
미로, 러스터 안녕하세요~!! 😄
Step2 진행까지 고생 많으셨습니다! (정말 빠르네요 🚀)

고민한 점들을 알려주셔서 어떤 생각으로 Step2를 진행하셨는지 쉽게 파악할 수 있었어요 😆👍
그럼 우선 질문주신 부분 먼저 답변 드릴게요~

---

### 1. 함수명과 변수명
수정을 꼭 해야 할 만큼 어색한 네이밍은 없었다고 생각합니다!
상세 내용은 라인별 코멘트로 남겨두었어요 😊

### 2. 더미 데이터 생성 방법
enum을 채택한 것이 독특하다고 생각했지만, 그 이유를 보고 납득했어요~
또한, 랜덤 방식으로 데이터를 생성하는 것이 많은 개수의 더미 데이터를 직접 타이핑하는 것 보다는 훨씬 효율적인 방법이라고 생각했습니다!

앞으로도 협업하다 보면 일정 상 API 명세서(서버에서 내려줄 파라미터의 이름과 타입 먼저 정의)만을 보며 실제 데이터 없이 작업해야 할 일이 종종 있을 거라고 생각되는데요.
더미 데이터로 우선 작업한 후 실제 데이터를 받아올 수 있는 환경이 되었을 때 **가능한 코드를 적게 변경**하는 게 더미 데이터로 작업하면서 가장 중요한 점이라고 생각해요.
즉, 실제 데이터를 적용할 때와 가장 유사한 환경으로 작업하고 필요에 따라 `실제 데이터 <-> 더미 데이터` 로의 전환이 쉽게 이루어지는 게 개발 속도도 맞추고 테스트에도 원활한 환경을 만들기 수월해질 수 있다고 생각합니다 😄

이 측면에서 현재의 코드는 `Contact` 타입을 활용해 테이블 뷰를 그려주고 있기 때문에 좋고 👍 실제 데이터를 입력받았을 때 `makeRandomContact(count:)` 를 사용하진 못 할 것으로 보여서 다소 아쉬워요.
현재는 이 단계 만으로 충분하다고 생각하지만, 다음에 또 더미 데이터를 작업할 일이 있다면 위와 같은 점을 생각해서 작업해보면 한 단계 더 나아갈 수 있지 않을까 합니다! 😆🚀

### 3. 접근제어 설정
이 질문도 상세 내용은 라인별 코멘트로 남겨두었습니다~

---

이번 스텝의 핵심 경험은 아래와 같았는데요.
<img width="238" alt="step2" src="https://user-images.githubusercontent.com/38066039/216357862-2053fd62-e782-421f-b6d6-1a5b98dd5ed3.png">

아래 사진과 같이 현재 테이블 뷰의 SafeArea 가 지켜지지 않아서 상단 상태바와 하단 컨트롤바를 보는 데 어려움이 있어요.
<img width="384" alt="ScreenShot1" src="https://user-images.githubusercontent.com/38066039/216358096-72033ba0-8d2e-4dcb-a8a6-3e08fcc30147.png">

이 부분은 수정이 필요해보여 Request Changes 로 요청드렸습니다 😊
혹시 코멘트 관련 및 그 외에도 궁금한 점이 있다면 편히 알려주세요! 🥳

2023-02-02 14:53 UTC, YebinKim commented on contactManager/ContactManagerUI/ContactInfo.swift
> +enum ContactInfo {
p4;

더미 데이터만을 위한 타입이라면 별도의 폴더를 만들거나 네이밍을 통해 실제로 사용할 `Contact` 타입과 구분해주면 어떨까요?
프로젝트를 처음 본 사람은 두 타입의 용도가 헷갈릴 수 있을 거 같아요!

2023-02-02 14:53 UTC, YebinKim commented on contactManager/ContactManagerUI/ViewController.swift
> +    private func makeRandomContact(count: Int) {
p4;

팩토리 역할을 하는 메서드로서 make 네이밍이 아주 자연스럽네요!! 🤩
> Begin names of factory methods with “make”, e.g. x.makeIterator().

그리고 특별히 어색할 정도는 아니지만.. `count` 대신 전치사(with 등)를 쓴다면 영문법상 더 자연스럽게 읽힐 수 있을 거 같아요~
> Prefer method and function names that make use sites form grammatical English phrases.

참고: Swift API Design Guidelines - [Strive for Fluent Usage](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage)

2023-02-02 14:53 UTC, YebinKim commented on contactManager/contactManager/AddContact.swift
> +var contacts : [Contact] = []
질문;

Set 타입에서 Array 타입으로 변경한 이유가 무엇일까요??

2023-02-02 14:53 UTC, YebinKim commented on contactManager/ContactManagerUI/ViewController.swift
> +    @IBOutlet weak var contactsTableView: UITableView!
p3;

`private` 처리가 필요해보여요 👀

2023-02-02 14:53 UTC, YebinKim commented on contactManager/ContactManagerUI/ContactInfo.swift
> +private let letters = "abcdefghijklmnopqrstuvwxyz"
p4;

현재의 `private` 처리도 괜찮지만, 4가지 상수를 enum의 연산 프로퍼티(get 전용 프로퍼티)로 넣어준다면 `ContactInfo` 와 관련 있는 타입임을 더 잘 보여줄 수 있을 거 같아요~

2023-02-03 01:17 UTC, longlivedrgn commented on contactManager/ContactManagerUI/ViewController.swift
> +    private func makeRandomContact(count: Int) {
with를 전달인자 레이블로, count를 매개변수로 설정하여 의미를 조금 더 명확하게 하면서 영문법 상으로도 알맞게 설정해보았습니다!

2023-02-03 01:18 UTC, llimental commented on contactManager/ContactManagerUI/ContactInfo.swift
> +enum ContactInfo {
더미 데이터임을 알아보기 쉽게 네이밍 앞에 Dummy를 붙여주었습니다.
>ContactInfo.swif -> DummyContactInfo.swift
enum ContactInfo -> enum DummyContactInfo

아래의 더미 데이터 범위 상수를 enum의 연산프로퍼티화 하는데에도 적용하였습니다.
>enum DummyContactRange

2023-02-03 01:22 UTC, llimental commented on contactManager/ContactManagerUI/ContactInfo.swift
> +private let letters = "abcdefghijklmnopqrstuvwxyz"
상수를 enum DummyContactRange로 묶어봤습니다!
다만 위의 세 상수는 타입이 ClosedRange<Int> 인데 letters는 String이어서 letters는 그대로 둔 채로 아래와 같이진행을 했는데요,
이 방법이 맞는 방향이었는지, 그리고 letters(변경된 코드에서는 lettersRange)도 같이 묶을 수 있는 방법이 있는지 궁금합니다! 🙌🏻

```swift
private let lettersRange = "abcdefghijklmnopqrstuvwxyz"

enum DummyContactRange {
    case nameRange
    case ageRange
    case phoneNumberRange
    
    var range: ClosedRange<Int> {
        switch self {
        case .nameRange:
            return 0...5
        case .ageRange:
            return 1...100
        case .phoneNumberRange:
            return 1...1000
        }
    }
}
```

2023-02-03 01:33 UTC, longlivedrgn commented on contactManager/contactManager/AddContact.swift
> +var contacts : [Contact] = []
먼저, Set은 요소들의 순서를 상관하지 않기에 매번 table view가 reload될 때 마다 table view의 순서가 변경되는 문제가 발생해요. 또한, indexPath를 활용하여 cell을 dequeue하는 과정에도 불편한 점이 있기에 array 타입으로 변경해주었어요!

2023-02-03 05:34 UTC, YebinKim commented on contactManager/contactManager/AddContact.swift
> +var contacts : [Contact] = []
아하 이해했습니다! 😄

2023-02-03 05:37 UTC, YebinKim commented on contactManager/ContactManagerUI/ContactInfo.swift
> +private let letters = "abcdefghijklmnopqrstuvwxyz"
앗 제가 생각한 방향은 switch 구문으로 분기하는 연산프로퍼티가 아닌 각각 분리된 연산프로퍼티였어요!

```Swift
var nameRange: ClosedRange<Int> {
    0...5
}
```

과 같은 프로퍼티를 4가지 만드는 방법을 생각했습니다 😄

private let 또는 enum 내 연산 프로퍼티로 통일시켜주는 게 깔끔해보일 거 같아요!

2023-02-03 05:39 UTC, YebinKim approved these changes
러스터, 미로 안녕하세요~
Step2 수정해주신 UI 및 코드 확인했습니다!
이번 스텝의 핵심 경험은 모두 달성되었다고 생각해 머지 진행할게요 😆🚀

또한, 이번 리뷰에 포함된 코드는 아니었지만 컴파일 워닝이 발생하고 있으니 다음 스텝에서는 확인을 부탁드려요.
<img width="262" alt="warning" src="https://user-images.githubusercontent.com/38066039/216521322-53b8ecfa-b698-4e20-9831-157a9298f99d.png">

Step3 진행도 화이팅입니다!! 💪🔥

2023-02-03 05:39 UTC, merged