연락처관리 UI [STEP 3] Joo & june
tasty-code/ios-contact-manager-ui pull request #18
Opened 2023-02-09 07:39 UTC by zhunhe

안녕하세요 소대(@zdodev) 😎 STEP1, 2 꼼꼼한 리뷰 감사했습니다 🙇🏻
STEP3에서는 연락처를 추가하는 기능을 추가해봤어요 !
ViewController간에 delegate 프로토콜을 사용해 데이터를 주고 받는 방식으로 구현했는데요,
더 좋은 구현방법이 있는지 소대라면 어떠한 방식으로 VC간 데이터 통신을 어떻게 구현할지 의견을 듣고 싶습니다.

그럼 이번 리뷰도 잘 부탁드릴게요 🙏

## 🚀 STEP 3 - 연락처 추가 기능 구현

### 정상동작
![Simulator Screen Recording - iPhone 14 Pro - 2023-02-09 at 16 15 45](https://user-images.githubusercontent.com/79438622/217743498-ee8af658-cb58-4623-a6ea-efe3d4dff1b6.gif)

### 취소기능
![Simulator Screen Recording - iPhone 14 Pro - 2023-02-09 at 16 12 09](https://user-images.githubusercontent.com/79438622/217742979-da726b8d-6ad5-4857-93a9-b113e3fb09a2.gif)

### 에러발생시
![Simulator Screen Recording - iPhone 14 Pro - 2023-02-09 at 16 17 19](https://user-images.githubusercontent.com/79438622/217743831-fe4d4165-b1a6-4697-ab3c-13abd48f3490.gif)

### ✔️ 요구사항
- [x] 연락처 목록 화면의 우상단 버튼을 통해 연락처 추가 화면에 진입할 수 있습니다
- [x] 오토 레이아웃과 스택뷰를 활용하여 화면을 레이아웃합니다
- [x] 각 필드에 맞는 키보드 종류를 지정합니다
- [x] 취소 버튼을 선택하면 정말 취소할 것인지 묻도록합니다
- [x] 저장 버튼을 선택하면 입력한 정보가 올바르게 입력되었는지 확인하도록 합니다
    - 이름은 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다
    - 나이는 숫자로만 입력해야하며, 세 자리수 이하여야 합니다.
    - 연락처는 중간에 -로 구분하며, -는 두 개 존재해야 합니다.
        - -을 제외하고 숫자는 9자리 이상이어야 합니다.
    - 올바른 사용자 입력 예시
        - james / 30 / 05-343-2334
        - ja mes / 30 / 013-3343-2343
        - james/30/013-3432-3433
    - 올바르지 않은 사용자 입력 예시
        - james / 서른 / 05-343-2334
        - ja mes / 30 / 01333432343
        - james/30세/013 3432 3433
        - james/013-3423-4432/30
- 모든 정보가 올바로 입력되었다면 저장 버튼을 선택했을 때 이전 화면으로 돌아가고, 추가한 연락처가 연락처 리스트에 추가됩니다

### ➕ 추가요구사항
전화번호 입력시 "-"를 커스텀 키보드로 구현하지 않고, 숫자만 입력가능하게 하고 아래와 같이 표시합니다.
전화번호 숫자의 개수가
`9개 이하`인 경우 `XX-XXX-XXXX`
`10개`인 경우 `XXX-XXX-XXXX`
`11개 이상`인 경우 `XXX-XXXX-XXXX`

### 🔑 핵심경험
- UIAlertController의 활용
- 오토레이아웃 구현
- 스택뷰 활용

### 🤔 고민 및 질문
1. 연락처를 추가하고 tableView에 반영하기 위해서 `reloadData()`는 전체적으로 다시 불러오는 거라서 비용이 크다는 것을 알고 `insertRows()`를 사용하여 한 개의 행만 추가하도록 하였습니다. `beginUpdates()`와 `endUpdates()`는 여러 update가 발생할 때만 쓰면되는 지 궁금합니다.
2. 추가요구사항에 대해 NewContactViewController.swift에 `func format(phone:)`에서 구현했는데, 개인적으로 문자 하나하나에 접근하여 format을 만드는 방식이 C언어스럽게 느껴지는데 Swift스럽게 작성할 수 있는 방식이 있는지, 더 좋은 방식이 있을지 소대의 의견을 듣고 싶습니다 :)
3. 요구사항에는 없었는데 새 연락처 화면에서 이름 TextField 입력 후 `return` 버튼을 누르면 키보드가 사라지도록 하는 것이 조금 더 사용성이 좋지 않을까 싶어서 구현을 해봤는데요. 소대의 생각은 어떠신가요 ?

2023-02-12 13:20 UTC, zdodev requested changes
안녕하세요. @ohdair , @zhunhe !

Step 3 구현 잘 진행해주셨습니다!👍
스텝 기능 제약조건과 오토레이아웃, 데이터 전달 기능도 잘 구현해주셨습니다!

먼저 질문에 대한 제 생각을 적어보았습니다.

❓ 연락처를 추가하고 tableView에 반영하기 위해서 reloadData()는 전체적으로 다시 불러오는 거라서 비용이 크다는 것을 알고 insertRows()를 사용하여 한 개의 행만 추가하도록 하였습니다. beginUpdates()와 endUpdates()는 여러 update가 발생할 때만 쓰면되는 지 궁금합니다.

- 말씀해주신 것 처럼 `insertRows` 을 사용하신 건은 좋은 선택이라고 생각합니다! beginUpdates()와 endUpdates() 도 table view 업데이트가 여러 번 발생할 때 한 번에 처리할 수 있도록 할 때 유용하게 사용할 수 있지 않을까 싶습니다!

❓ 추가요구사항에 대해 NewContactViewController.swift에 func format(phone:)에서 구현했는데, 개인적으로 문자 하나하나에 접근하여 format을 만드는 방식이 C언어스럽게 느껴지는데 Swift스럽게 작성할 수 있는 방식이 있는지, 더 좋은 방식이 있을지 소대의 의견을 듣고 싶습니다 :)

- 문자열의 길이, 입력 요소를 검증해야 하는 부분에서 지금과 같은 코드(요소에 직접 하는)가 없을 수는 없지 않을까 싶습니다.
- 현재 포맷에 맞는 문자열을 제공해줄 수 있도록 Formatter 를 구현해보는 것도 좋은 방법이 되지 않을까 싶습니다. (DateFormatter, NumberFormatter ...)


요구사항에는 없었는데 새 연락처 화면에서 이름 TextField 입력 후 return 버튼을 누르면 키보드가 사라지도록 하는 것이 조금 더 사용성이 좋지 않을까 싶어서 구현을 해봤는데요. 소대의 생각은 어떠신가요 ?

- 기능 명세에는 없지만 사용자의 사용성을 고려하여 반영한 점은 좋습니다!👍👍 좋은 고민이라고 생각합니다!

코멘트 확인 부탁드립니다!

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Protocol/NewContactViewControllerDelegate.swift
> +protocol NewContactViewControllerDelegate: NSObject {
Delegate 프로토콜을 구현해보셨네요!👍
`NSObject` 을 상속하신 이유가 있을까요?

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/ContactsViewController.swift
> +    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
`prepare` 를 사용하여 데이터를 설정해보셨네요.👍

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/ContactsViewController.swift
> +}
Delegate 패턴을 사용하여 데이터 전달을 해보셨네요!👍

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +        let alert = UIAlertController(title: "정말로 취소하시겠습니까?", message: nil, preferredStyle: .alert)
`showErrorAlert` 메서드처럼 `UIAlertController` 출력을 위한 메서드를 구현하여 호출하는 것은 어떨까요? 가독성도 더 좋아질 것 같습니다!

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +        })
`handler` 인자를 `Trailing Closures` 로 처리해도 좋을 것 같습니다!

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +extension NewContactViewController: UITextFieldDelegate {
`UITextFieldDelegate` 를 잘 활용해 보셨네요.👍

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +        let numbers = phone.filter({ $0.isNumber })
`filter` 를 `Trailing Closures` 로 처리해도 좋을 것 같습니다! 지금도 좋습니다!

2023-02-12 13:20 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +        }
번호 포맷 제약조건을 잘 표현해보셨네요.👍

2023-02-13 14:14 UTC, ohdair commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +        let alert = UIAlertController(title: "정말로 취소하시겠습니까?", message: nil, preferredStyle: .alert)
반복적으로 alert 만드는 부분을 아래와 같이 메서드를 구현하여 호출했습니다
```swift
private func showAlert(title: String, leftButtonTitle: String, rightButtonTitle: String? = nil) {
    let alert = UIAlertController(title: title, message: nil, preferredStyle: .alert)
    let leftButton = UIAlertAction(title: leftButtonTitle, style: .default)
    alert.addAction(leftButton)
    if rightButtonTitle != nil {
        let rightButton = UIAlertAction(title: rightButtonTitle, style: .destructive) { _ in
               self.dismiss(animated: true)
           }
        alert.addAction(rightButton)
    }
    present(alert, animated: true)
}
```

2023-02-13 14:22 UTC, ohdair commented on ContactManager/ContactManagerUI/Protocol/NewContactViewControllerDelegate.swift
> +protocol NewContactViewControllerDelegate: NSObject {
delegate 패턴을 사용하다보면 retain cycle에 의한 메모리 누수가 발생되는 문제를 막기 위해서 weak를 사용한다고 알고 있습니다. weak를 사용하기 위해서는 delegate에서 NSObject를 상속하라는 에러문구가 떠서 사용하였습니다.
안전한 동작을 위해 weak을 사용함으로써 `NSObject`를 상속하게 되었습니다

2023-02-14 02:34 UTC, zdodev commented on ContactManager/ContactManagerUI/Protocol/NewContactViewControllerDelegate.swift
> +protocol NewContactViewControllerDelegate: NSObject {
네 메모리 누수에 대한 내용은 맞습니다! 다만 `AnyObject` 대신 NSObject` 를 사용하신 이유가 궁금했습니다.
`항상 weak var를 사용하는 것보다는 retain cycle에 의한 메모리 누수되는 부분이 발생될 때에만 사용하는지` 에 대해서는
항상 weak var 를 사용하기 보다는 메모리 누수 및 레퍼런스 카운드를 염두하고 사용하면 좋을 것 같습니다!

2023-02-14 02:37 UTC, zdodev approved these changes
안녕하세요. @ohdair !

궁금증에 대한 의견 및 개선된 코드 잘 확인하였습니다!

추가 코멘트만 확인하면 될 것 같습니다!
Step 3 진행하시느라 고생하셨습니다!🎉

2023-02-14 02:37 UTC, zdodev commented on ContactManager/ContactManagerUI/Formatter/PhoneFormatter.swift
> +class PhoneFormatter: Formatter {
Formatter 를 구현해보셨네요!👍

2023-02-14 02:37 UTC, zdodev commented on ContactManager/ContactManagerUI/Controller/NewContactViewController.swift
> +    private func showAlert(title: String, leftButtonTitle: String, rightButtonTitle: String? = nil) {
좋습니다!👍

2023-02-14 02:38 UTC, merged