[Step 1] 연락처 관리 앱 - 컴도리, 재닌
tasty-code/ios-contact-manager-ui pull request #25
Opened 2023-10-06 08:25 UTC by janine-kang

리뷰어: @jryoun1
버드: @janine-kang, @comdori-wj

제이크, 안녕하세요! 
이번 프로젝트에서 제이크의 리뷰이가 된 재닌과 컴도리입니다! 🙇🏻‍♀️
 연락처 관리 앱 STEP 1의 PR 요청드립니다 🙌🏻

# Summary
TableView를 이용한 연락처 관리 앱 첫 화면 구현

## 구현 화면
![74993480e1a198f6](https://github.com/tasty-code/ios-contact-manager-ui/assets/76927263/029fa10c-2dbd-4083-843f-dd5f3ea9035c)

## 구현 사항
- [x]  Table View를 활용하여 연락처 목록을 화면에 표시
- [x] subtitle style을 사용하여 cell 구현
- [x] json 파일로 만들어진 mock data를 화면에 표시

## 폴더 구조
```
├── ContactManager
│   ├── Controller
│   │   ├── AppDelegate.swift
│   │   ├── ContactTableViewController.swift
│   │   └── SceneDelegate.swift
│   ├── Info.plist
│   ├── Model
│   │   ├── ContactInfo.swift
│   │   ├── ContactManager.swift
│   │   └── mockData.json
│   └── View
│       ├── Assets.xcassets
│       │   ├── AccentColor.colorset
│       │   │   └── Contents.json
│       │   ├── AppIcon.appiconset
│       │   │   └── Contents.json
│       │   └── Contents.json
│       └── Base.lproj
│           ├── LaunchScreen.storyboard
│           └── Main.storyboard
```

## 고려한 점
- contactList에 대한 은닉화를 위해 private으로 접근을 제어하였고, getContactList() 또는 setContactList()를 이용하여 데이터를 확인할 수 있도록 했습니다.
``` swift
    private var contactList: [ContactInfo] = []
    
    func getContact(uuid: UUID) -> ContactInfo? {
        guard let contact = contactList.first(where: { $0.uuid == uuid }) else { return nil }
        return contact
    }
    
    func getContactList() -> [ContactInfo] {
        return contactList
    }
    
    func setContactList(list: [ContactInfo]) {
        contactList = list
    }
```
- 이름 또는 핸드폰번호가 중복 가능하다는 점에서 고유 식별자로 사용할 수 없다고 판단하여 UUID를 통해 식별자를 정의했습니다.
``` swift
struct ContactInfo: Decodable {
    var name: String?
    var age: Int?
    var phoneNum: String?
    let uuid: UUID
    
    init(name: String, age: Int, phoneNum: String, uuid: UUID? = nil) {
        self.name = name
        self.age = age
        self.phoneNum = phoneNum
        guard let identifier = uuid else {
            self.uuid = UUID()
            return
        }
        self.uuid = identifier
    }
}
```
- JSON을 Decode하는 방식을 변경했습니다. 처음에는, json 파일에 접근하여 파일 내 모든 데이터에 대해 String()을 통해 모두 문자열화 시킨 다음 만들어놓은 DTO로 데이터를 사용하고자 했습니다. 그런데 이 방법에서 에러를 만나게 되었는데, 그 원인이 String()을 통한 문자열화임을 파악했습니다. json 파일 내에 적혀져있던 주석까지 데이터로 인식하게 되어 계속해서 에러를 뱉는걸 확인했는데요. 해당 방법이 안전성을 보장할 수 없다고 판단하여 Data() 객체를 통한 Decode방식을 선택하게 되었습니다. 
``` swift
// 이전 방식
guard let jsonString = try? String(contentsOf: URL(fileURLWithPath: jsonURL), 
                                     encoding: String.Encoding.utf8) else {
       return
}
do {
    let root = try JSONDecoder().decode(Root.self, from: Data(jsonString.utf8))
    contactManager.setContactList(list: root.data)
} catch {
    print(error)
}

```
``` swift
// 변경된 방식
do {
     let data = try Data(contentsOf: jsonURL)
      let root = try JSONDecoder().decode(Root.self, from: data)
      contactManager.setContactList(list: root.data)
} catch {
     print(error)
 }
```

## 궁금한 점
1. 연락처를 생성할 때, 1) 이름이 중복되는 경우 2) 핸드폰 번호가 중복이나 이름이 중복되지 않는 경우 이 두가지 경우에도 연락처가 생성되는 걸 확인했습니다. 그에 따라 이름이나 핸드폰 번호가 고유 식별자가 될 수 없다고 판단하여 UUID를 식별자로 생성하게 되었는데요.
- 고유 식별자를 생성하는 방법이 UUID 밖에 없나요? UUID가 아닌 랜덤값으로 고유 식별자를 만드는 방법은 어떤가요?
- 현업에서 주로 어떤 방식을 채택하여 고유 식별자를 생성하는지 궁금합니다!

2. mockData의 위치가 궁금합니다. 현재는 mockData.json이 Model 폴더에 들어가있는데요. 이런 경우, 주로 어떤 폴더 내에 넣어두는지 궁금합니다!

2023-10-09 10:33 UTC, jryoun1 requested changes
컴도리,재닌 두 분다 step1 고생하셨습니다! 

코드를 가독성 있게 잘 작성해주셔서 아주 좋았던 것 같아요 💯👍🏻
다만 몇 가지 개선되면 좋을 것 같은 부분들이 있어서 코멘트 남겨드려요! 
질문에 주신 부분도 코멘트에 같이 남겨드렸어요. 확인부탁드려요 🙏🏻

## 질문 답변

> mockData의 위치가 궁금합니다. 현재는 mockData.json이 Model 폴더에 들어가있는데요. 이런 경우, 주로 어떤 폴더 내에 넣어두는지 궁금합니다!

이 부분은 사실 컨벤션을 어떻게 정하는지에 따라서 다를 것 같긴하네요. 
mockData를 파일로 저장하는 경우에는 주로 해당 api의 endpoint에 관련된 코드를 작성한 폴더로 같이 그룹핑 해놨던 것 같네요 🙏🏻
정답은 없으니 두 분께서 상의해보시면 좋을 것 같습니다!

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/AppDelegate.swift
> +        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
이런 주석들은 전부 필요한 코드일까요? 
필요하지 않다면 프로젝트 전반적으로 불필요한 코드는 제거해도 괜찮을것 같습니다 🙏

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +//  TableViewController.swift
파일명과 내부에 있는 class명이 일치하지 않는 것 같아요~ 확인부탁드립니다!

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let count = contactManager.getContactList().count
contactManager에서 바로 count를 가져올 수 있는 property가 있으면 어떨까요?

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
이 부분은 연산프로퍼티를 사용할 수 있었을 것 같은데 메소드로 구현하신 이유가 궁금합니다 🙋‍♂️

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +final class ContactManager {
final 키워드를 사용해보셨네요 👏 
final은 어떤 이유로 사용하셨는지 궁금합니다!

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +class ContactTableViewController: UITableViewController {
여기는 final이 없어도 될까요? 🤔

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    private var contactList: [ContactInfo] = []
Swift에서는 주로 변수명을 붙일 때 리스트인경우에는 s를 붙여줍니다.
contacts라고 하는 것이 조금 더 Swift스러운 것 같습니다 🙏

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
이 두 함수에서 매개변수로 contact에 관련된 정보들을 전부 전달해주고 있는데, ContactInfo로 전달하지 않는 이유가 있을까요? 
만약 contactInfo에 emailAddress, homeAddress 이런 정보들이 추가된다면 여기 함수들도 같이 변경되어야 할 것이며, 함수의 매개변수가 너무 많아질 것 같은데 어떻게 생각하시나요?

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
또한 매개변수로 contactInfo를 전달하도록 한다면, 함수명도 사용하는측에서 가독성 좋게 작성해볼까요? 
```Swift
contactManager.add(contact) 
contactManager.update(contact, of: uuid) 
// 사용하는 쪽에서 위와 같은 식으로 된다면 좀 더 가독성이 좋아질 것 같네요! (예시입니다) 
```

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +struct ContactInfo: Decodable {
Decodable을 사용해보셨네요! 💯
Decodable은 언제 사용하는 걸까요?

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +    }
이 부분이 고민하셨던 부분이군요. 👏
말씀해 주신 것처럼 실제 iPhone의 연락처 앱에서도 동일한 이름 동일한 번호로 연락처에 추가해도 추가가 됩니다. 그래서 번호, 이름만으로는 고유하게 식별하기는 어렵다고 볼 수 있을 것 같네요. 

그래서 UUID를 통해서 고유식별자를 생성해주면 될 것 같습니다.
UUID는 무엇이며 언제 사용하는걸까요? <- 한 번 알아보시면 도움이 될 것 같아요.

현업에서는 주로 서버를 사용하기에 해당 데이터가 unique하다는 것은 서버측에서 관리를 해주게 됩니다. 만약 서버를 사용하지 않는 앱이라면 클라이언트 내에서 이를 관리해야할 것이고 이때도 unique함을 보장해주기 위해서는 UUID와 같은 값을 사용할 것 같네요!

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let phoneNumber = contactManager.getContactList()[indexPath.row].phoneNum ?? ""
만약 해당 배열에 접근할 때 indexPath.row보다 적게 있는 경우에 접근하게 되면 앱은 어떻게 될까요? 🚨🚨

이를 방지할 수 있는 방법에 대해서는 subscript에 대해서 알아보시면 좋을 것 같습니다!
hint: array subscript safe라고 검색해보세요 🔎

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let phoneNumber = contactManager.getContactList()[indexPath.row].phoneNum ?? ""
또한 값이 없다면 빈값과 0으로 표시해주는 것이 유저에게 좋을까요? 
아니면 아예 보여주지 않는 것이 좋을까요?

2023-10-09 10:33 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        cell.detailTextLabel!.text = phoneNumber
코드에 ! 는 사용하지 않는 것이 제약사항이였던 것 같습니다!

2023-10-10 01:47 UTC, comdori-wj commented on ContactManager/ContactManager/Controller/AppDelegate.swift
> +        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
네 반영하겠습니다!

2023-10-10 01:50 UTC, comdori-wj commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +//  TableViewController.swift
클래스 명이 다르면 주석처리된 부분인데도 오류가 발생하나요? 아니면 그냥 잘못된 정보라서 그런가요? 👀

2023-10-10 01:56 UTC, comdori-wj commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let count = contactManager.getContactList().count
네 수정하겠습니다. contactManager 모델에 넣도록 하겠습니다.

2023-10-10 02:24 UTC, janine-kang commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
설계 당시 의도는 `contactList`에 대한 은닉화를 유지하기 위함이며, 이를 위해 메서드를 통하여 접근하도록 했습니다.

연산 프로퍼티는 값이 저장되지 않고, 클로져 수행을 통해 접근 때마다 값을 리턴한다고 알고있는데, 이런 경우 기존의 contactList의 접근 제어를 유지하고 getter만을 사용하는 연산 프로퍼티를 추가하여 접근할 수 있도록 만드는 것이  저희가 의도했던 것과 상응할 수 있을지 제이크의 의견이 궁금합니다!

2023-10-10 02:29 UTC, comdori-wj commented on ContactManager/ContactManager/Model/ContactManager.swift
> +final class ContactManager {
ContactManager가 상속을 할 필요가 없어서 사용하였습니다.

2023-10-10 02:30 UTC, comdori-wj commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +class ContactTableViewController: UITableViewController {
수정 하였습니다. 😏

2023-10-10 02:38 UTC, comdori-wj commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +    }
### UUID = **U**niversally **U**nique **ID**entifier
실제로 사용할 때 중복될 가능성이 거의 없다고 인정된 범용 고유 식별자입니다. (줄여서 랜덤 고유 값)

### UUID는 언제 사용될까? 🧐
일반적인 목적은 고유한 식별자를 갖기 위함니다. UUID가 고유한 키를 생성하기 위한 유일한 방법이라기 보다는 고유한 키를 간단하게 생성해서 사용할 수 있기 때문에 사용합니다.

### UUID의 형식은?
총 36개의 문자열로 구성되어 있고, 이 문자는 32개의 실제 문자(숫자 또는 알파벳)와 4개의 하이픈으로 구성되어 있습니다.

> (8개의 문자) - (4개의 문자) - (4개의 문자) - (4개의 문자) - (12개의 문자)
- UUID는 128비트 식별자를 struct에 직접 저장하기 때문에 Heap에 할당할 필요가 없기 때문에 메모리 할당 및 해제 작업이 없습니다.

2023-10-10 04:12 UTC, janine-kang commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let phoneNumber = contactManager.getContactList()[indexPath.row].phoneNum ?? ""
오! Dictionary와 다르게 Array는 안전하지 않네요!
이 부분은 아래 부분과 연관지어, 만일 Array Index가 안전하지 않다고 판단 될 경우 nil값을 반환할 수 있도록 subscript를 커스텀했습니다!

2023-10-10 04:13 UTC, janine-kang commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let phoneNumber = contactManager.getContactList()[indexPath.row].phoneNum ?? ""
위의 변경 사항에 연동하여, guard let 처리를 완료했습니다.
더불어, View에 관련되어 cell의 textLable 등에 직접적으로 접근하는 방법이 deprecated된 것을 확인하여 구현 방법을 변경했습니다!

2023-10-10 04:14 UTC, janine-kang commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        cell.detailTextLabel!.text = phoneNumber
넵 확인했습니다!
해당 부분 리뷰 반영하기 위해 찾아보니, cell의 textLable 등에 직접적으로 접근하는 방법이 deprecated된 것을 확인하여 구현 방법을 변경했습니다!

2023-10-10 07:23 UTC, janine-kang commented on ContactManager/ContactManager/Utility/CustomArray.swift
> +}
Array Safety를 위해 위 처럼 구현했습니다 🙂

2023-10-10 07:27 UTC, comdori-wj commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +struct ContactInfo: Decodable {
Decodable은 외부 표현에서 자신을 디코딩할 수 있는 유형입니다.
제이슨 파일같은 타입은 파싱(parsing) 할 때 사용합니다.

2023-10-10 07:30 UTC, janine-kang commented on ContactManager/ContactManager/Model/ContactManager.swift
>          }
이 부분 또한 좀 더 간결하게 네이밍을 변경했습니다!
(지금 보니, delete() 메서드에 `of`를 추가하는 편이 더 직관적이고 명료하겠네요 😭 다음 STEP의 PR에서 반영하여 올리도록 하겠습니다!)

2023-10-10 07:31 UTC, janine-kang commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    private var contactList: [ContactInfo] = []
넵 해당 사항 반영하였습니다!

2023-10-10 07:32 UTC, janine-kang commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
해당 부분 반영했습니다!
https://github.com/tasty-code/ios-contact-manager-ui/pull/25#discussion_r1351723288

2023-10-10 07:33 UTC, janine-kang commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
맞습니다. 이 부분에서는 오히려 객체 자체를 넘겨주는 것이 더 확장성 측면에서 유연하겠네요!
해당 부분 반영하여 수정하였습니다 🙂

2023-10-10 13:43 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +//  TableViewController.swift
오류가 발생하지는 않습니다! 주석이 제대로 업데이트 되어있지 않다면 추후에 코드를 보는 사람이 헷갈릴 수 있기 때문에 가능하면 제대로 된 정보를 남겨두는게 좋을 것 같네요 🙏🏻

2023-10-10 13:50 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
contactList에 은닉화를 유지해 외부에서의 직접 접근을 통한 값의 추가/변경/삭제가 아닌 내부의 메서드를 통해서 변경하려고 하신 부분 아주 좋네요 👏
그렇다면 꼭 메서드를 사용할 필요없이 해당 변수(contactList) 자체를 private(set)으로 선언해서 외부에서 list에 대해서 값을 가져올 수 있지만, 값을 변경/설정하지는 못하게 할 수도 있을 것 같네요!

2023-10-10 13:51 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +final class ContactManager {
좋네요 👏 상속에 관련된 측면 뿐만 아니라 성능 측면에서의 장점도 있는데 이 부분 관련해서는 추후에 [WWDC16: UnderStanding Swift Performance영상](https://developer.apple.com/videos/play/wwdc2016/416/)을 한 번 참고해보시면 좋을 것 같네요!

2023-10-10 13:55 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactInfo.swift
> +struct ContactInfo: Decodable {
아하 다음스텝을 고려해주시는 것도 좋지만 각 step에서는 해당 스텝에서만 필요한 정도까지 구현되는것이 좀 더 좋을 것 같아요! 
왜냐하면 다음 스텝에 어떤 스펙이 있을지 모르는 상태에서 Codable로 작성하게 된다면, 이 코드를 읽는 다른 사람은 "이 객체가 decoding될 뿐만 아니라 encoding도 될 수 있는 객체인가?" 라고 착각할 수 있기에 처음에 작성하신 것 처럼 이번 스텝에서는 명확하게 Decodable만 있어도 될 것 같습니다!! 
(요약하면 실제로 필요할 때 추가되면 좋을 것 같습니다 👍🏻)

물론 이번에는 그대로 넘어가시죠~

2023-10-10 13:56 UTC, jryoun1 commented on ContactManager/ContactManager/Controller/ContactTableViewController.swift
> +        let phoneNumber = contactManager.getContactList()[indexPath.row].phoneNum ?? ""
아주 좋습니다 💯👏

2023-10-10 13:57 UTC, jryoun1 commented on ContactManager/ContactManager/Utility/CustomArray.swift
> +}
아주 좋네요 👏 💯

2023-10-10 14:01 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
>          }
매개변수의 명과 관련해서 wildcard pattern에 대해서도 한 번 보시면 좋을 것 같습니다.

```Swift
let contact = ContactInfo(~~~)
contactManager.add(contact: contact) // 지금 수정된 함수의 실제 사용되는 모습
```
이렇게 의미없는 contact가 두 번 들어가는 것보다는 아래의 경우가 더 가독성이 좋아 보이긴합니다! 
```Swift
let contact = ContactInfo(~~~)
contactManager.add(contact) 
```

꼭 wildcard pattern을 사용하라는 것이 아닌, 실제로 해당 코드를 사용할 때 어떻게 사용되는지에 대해서 생각해보면 좋을 것 같다는 이야기였습니다 🙏🏻

2023-10-10 14:05 UTC, jryoun1 approved these changes
두 분 다 step1 고생하셨습니다! 
전반적으로 잘 수정해주신 것 같고, 몇 가지 추가 코멘트를 남겨두긴했는데 다음 step에서 적용되어도 될 것 같아서 step1은 여기서 머지하도록 하겠습니다 🙏🏻

2023-10-10 14:05 UTC, jryoun1 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
이 부분도 연산프로퍼티로 만들수도 있을 것 같아요! 
관련해서 [참고할 만한 글](https://velog.io/@wonhee010/Computed-Property%EC%97%B0%EC%82%B0-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0-vs-Method) 하나 남겨드릴게요~

2023-10-10 14:05 UTC, jryoun1 commented on ContactManager/ContactManager/Utility/CustomArray.swift
> +//  CustomArray.swift
extension의 네이밍은 물론 컨벤션에 따라 다르겠지만 apple 공식문서나 이런 공식문서들의 참고해보시면
Array+Extension 혹은 Extension+Array와 같이 파일 네이밍을 하긴 한답니다! (참고사항입니다 🙏🏻)

뭔가 customArray라고 하면 실제로 Array인데 custom한 array객체가 구현되어있을 것 같다고 느껴지긴합니다 😂

2023-10-10 14:05 UTC, merged