연락처 관리 앱 [STEP1] Dora, JaeHyeok
tasty-code/ios-contact-manager-ui pull request #29
Opened 2023-10-10 01:46 UTC by SimJaeHyeok

리뷰어: @zdodev 
버드: @KSK9820, @SimJaeHyeok

## 소대, 안녕하세요! [STEP 1] PR 드립니다🙌🏻

## Summary ⛳️

### 구현 기능 및 상세

- `Struct`를 활용한 Model 타입 구현 (이름, 연락처, 나이)
-  연락처 보기(showContact), 연락처 추가(addContact), 연락처 삭제(deleteContact), 연락처 변경(changeContact) 기능 구현
-  `UITableView`를 활용한 UI 구현 
---

### 고민했던 점 👀

- 배열(`Array`)과 연결 리스트(`Linked List`)중 어떤 것을 사용하는 게 옳은 방법일까?
    - 연결 리스트는 주로 삽입 및 삭제 연산이 빈번하게 발생하는 상황에서 유용하며, 연락처 앱에서는 그렇지 않은 경우가 대부분입니다. 
    - 그렇기 때문에 단순한 구조와 연속된 메모리 공간으로 메모리 사용 측면에서 효율적인 배열을 선택을 하였습니다. 
- Model을 어떻게 구현할 것인가?
    - 연속된 공간에 저장되어 있는 대량의 데이터의 정렬을 깨뜨리는 연산이 많기 때문에, 이러한 오버헤드를 줄이고자 2차원 배열을 사용하게 되었습니다.
    -  2차원 배열의 첫 번째 차원을 (A to Z) 인덱스로 저장하고, 각 연락처의  이름의 첫 글자를 유니코드로 변환하여 첫 번째 배열에 (A to Z)로 분류되어 저장됩니다. 이러한 경우 두 번째 차원만을 범위로 한정하기때문에 삽입 및 삭제의 오버헤드를 줄일 수 있습니다. 
### 질문 사항
- 2차원 배열도 연속된 메모리에 할당되나요? <br>만약 할당되는 경우 arr[2]에 값을 추가하면, arr[3], arr[4]… 등 이후의 배열의 주소가 밀린다던지 등의 영향이 가지 않는지 궁금합니다.

- `C`나 `Java`에서 배열의 크기를 지정 해놓고 사용하는데, Swift에선 배열 초기 설정 시 배열의 크기에 따라 배열의 크기를 배수만큼 자동으로 늘려주는 것으로 알고 있습니다. 크기를 모를 경우에는 배열의 크기를 자동으로 늘려주는 것은 정말 유용하다고 생각이 드는데, 크기를 미리 알고 있는 경우에는 불필요하게 메모리가 늘어나게 되는데 왜 자동으로 늘려주는 것만 기본으로 탑재되어 있는지 궁금합니다.

2023-10-10 14:22 UTC, zdodev requested changes
안녕하세요~ @KSK9820 , @SimJaeHyeok !
 
 첫 번째 스텝 잘 구현해주셨습니다~
 요구사항의 내용처럼 모델과 Table View를 잘 구현해보셨네요.👍
 
 먼저 질문에 대한 제 생각을 얘기해보면
 
 1. 2차원 배열도 연속된 메모리에 할당되나요? 만약 할당되는 경우 arr[2]에 값을 추가하면, arr[3], arr[4]… 등 이후의 배열의 주소가 밀린다던지 등의 영향이 가지 않는지 궁금합니다.
 
 - 좋은 질문이에요! 직접 테스트 해보면 더욱 기억에 남을 것 같습니다. Swift에서 메모리를 확인하는 방법을 이용해서 2차원 배열의 요소별 주소를 확인해 보면 보다 명확하게 이해할 수 있을 것 같습니다.😁
 
 2. C나 Java에서 배열의 크기를 지정 해놓고 사용하는데, Swift에선 배열 초기 설정 시 배열의 크기에 따라 배열의 크기를 배수만큼 자동으로 늘려주는 것으로 알고 있습니다. 크기를 모를 경우에는 배열의 크기를 자동으로 늘려주는 것은 정말 유용하다고 생각이 드는데, 크기를 미리 알고 있는 경우에는 불필요하게 메모리가 늘어나게 되는데 왜 자동으로 늘려주는 것만 기본으로 탑재되어 있는지 궁금합니다.
 
 - 2번째 질문은 `크기를 미리 알고 있는 경우에는 불필요하게 메모리가 늘어나게 되는데` 살짝 이해가 안됩니다.😅
 - Array 타입의 동작 방식과 크기에 관한 내용과 관련 API들이 공식 문서에서 확인해 볼 수 있습니다. 한번 내용을 보고 다시 질문을 주시면 좋을 것 같습니다.😁
[Array Document](https://developer.apple.com/documentation/swift/array)

이외에도 여러 궁금증을 남겨보았습니다~
같이 고민해보면 좋을 것 같습니다😄

2023-10-10 14:22 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +    var addressBook: AddressBook!  = AddressBook()
`addressBook` 프로퍼티를 강제 언래핑 옵셔널 형태로 선언하신 이유가 있을까?

2023-10-10 14:22 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +        tableView.reloadData()
현재 시점에 `reloadData()` 메서드를 호출하는 이유가 궁금합니다!

2023-10-10 14:22 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +extension ViewController: UITableViewDelegate, UITableViewDataSource {
`UITableViewDelegate` 프로토콜을 채택한 이유가 궁금합니다!

2023-10-10 14:22 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Contact.swift
> +struct Contact {
연락처를 담을 모델을 구현해보셨네요.👍
변수명도 잘 지어주셨네요.🙂

2023-10-10 14:22 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getSectionSize() -> Int {
`get` 단어를 붙이지 않아도 의미가 전달될 것 같은데 의견이 궁금합니다!

2023-10-10 14:22 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getRowSize(_ section: Int) -> Int {
`get` 단어를 붙이지 않아도 의미가 전달될 것 같은데 의견이 궁금합니다!

2023-10-11 00:37 UTC, KSK9820 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +    var addressBook: AddressBook!  = AddressBook()
실수로 강제 언래핑 옵셔널 형태로 선언했습니다,, 바로 수정했습니다!

2023-10-11 00:41 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +        tableView.reloadData()
인위적으로 넣은 데이터인데, 사용자가 직접 추가한 데이터로 착각하였습니다. 피드백 확인 후 수정하였습니다.

2023-10-11 00:47 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +extension ViewController: UITableViewDelegate, UITableViewDataSource {
tableView 예제를 따라하면서 생각없이 코드를 작성한 것 같습니다. 현재 STEP에서 사용하지 않기 때문에 프토토콜을 삭제 하였습니다.
조금 더 꼼꼼히 코드를 작성하겠습니다

2023-10-11 00:53 UTC, KSK9820 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getSectionSize() -> Int {
사용자 입장에서 section의 개수를 받는다는 생각으로 이름을 지었는데, 실질적으로 사용자가 받는 것이 아니라 tableview함수가 받는 것을 생각하면 get을 붙이지 않아도 의미가 전달 될 것 같습니다. 

하지만 함수의 이름은 동사형으로 사용하라는 가이드라인을 따르려고 하는데, 그냥 get을 빼는 것이 더 나을까요?

2023-10-11 00:56 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getSectionSize() -> Int {
함수명은 작업이 자연스럽게 동사로 설명되는 경우 동사형으로 작성해야한다는 공식 API GuidLine에 의해
함수명은 동사형으로 작성하였습니다.

2023-10-11 00:56 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getRowSize(_ section: Int) -> Int {
함수명은 작업이 자연스럽게 동사로 설명되는 경우 동사형으로 작성해야한다는 공식 API GuidLine에 의해
함수명은 동사형으로 작성하였습니다.

2023-10-11 09:37 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getSectionSize() -> Int {
Swift API Design Guidelines 의 내용을 보면 동사형으로 시작하는 것을 권장하지만 함수, 메서드의 동작 형태에 따라 명사형을 사용하는 것을 권장하는 부분도 있습니다~
제 생각에는 해당 메서드를 명사형으로 이름을 지어도 괜찮겠다 생각이 들었습니다.😄 한 번 해당 부분을 확인해보면 좋을 것 같습니다👍

2023-10-11 09:37 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getRowSize(_ section: Int) -> Int {
위와 같은 생각입니다~

2023-10-11 09:40 UTC, zdodev approved these changes
안녕하세요~ @KSK9820 , @SimJaeHyeok !
리뷰어 소대입니다!

개선된 코드를 잘 반영해주셨네요~
자신의 생각을 코멘트로 잘 남겨주신 점도 좋았습니다!

스텝 진행하시느라 고생하셨습니다.
Step1은 여기서 마무리하도로 하겠습니다!👍

2023-10-11 09:40 UTC, merged

2023-10-12 00:47 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/AddressBook.swift
> +    func getSectionSize() -> Int {
말씀하신 내용 Swift API Design Guidelines을 통해 다시 한번 확인하였습니다!