연락처 관리 앱 [Step 2] 뉴준성, 밤삭
tasty-code/ios-contact-manager-ui pull request #31
Opened 2023-10-11 07:31 UTC by newJunsung

# 연락처 관리 프로젝트

## 리뷰어
@protocorn93

## 파일구조
- ios-contact-manager-ui
  - Utility
     - ContactValidityChecker 
  + Controller
     - ContactListViewController.swift 
  + Model
     - Contact.swift
        - Contact
        - ContactManager
  - Exception
     - ContactEception
  + View
     + ContactCell

## 새로 시도했던 점
### Unit Test
텍스트 필드의 입력 값이 유효한 지 검사하기 위해 `ContactValidityChecker`를 구현하는 과정에서, Unit test를 진행했습니다. Unit test에서 `XCTAssertEqual()`을 사용하기 위해 `ContactValidityChecker` 함수가 모두 리턴 값을 가지도록 했습니다.
```swift
import XCTest
@testable import ios_contact_manager_ui

final class ios_contact_manager_uiTests: XCTestCase {
    let contactValidityChecker = ContactValidityChecker()
    
    // MARK: - 이름
    func test_이름_빈_문자열인지() {
        let result = contactValidityChecker.checkNameValidation("")
        XCTAssertEqual(result, nil)
    }
    
    func test_이름_띄어쓰기_제거되는지() {
        let names: [(input: String, output: String?)] = [
            (input: " ", output: nil),
            (input: "  ", output: nil),
            (input: "j ames", output: "james"),
            (input: "j ame s", output: "james"),
            (input: "j a m e s", output: "james"),
            (input: "쫑", output: "쫑"),
            (input: "팜 하니", output: "팜하니"),
            (input: "뉴진스 ", output: "뉴진스"),
            (input: " 뉴진스 ", output: "뉴진스")
        ]
        
        for name in names {
            XCTAssertEqual(contactValidityChecker.checkNameValidation(name.input), name.output)
        }
    }
    
    // MARK: - 나이
    func test_나이_빈_문자열인지() {
        let age = ""
        XCTAssertEqual(contactValidityChecker.checkAgeValidation(age), nil)
    }
    
    func test_나이_띄어쓰기_제거되는지() {
        let ages = [
            (input: " ", output: nil),
            (input: "  ", output: nil),
            (input: "3 5", output: 35),
            (input: " 35", output: 35),
            (input: "35 ", output: 35),
            (input: "35 ", output: 35)
        ]
        
        for age in ages {
            XCTAssertEqual(contactValidityChecker.checkAgeValidation(age.input), age.output)
        }
    }
    
    func test_나이_숫자로_변환되는지() {
        let ages = [
            (input: " ", output: nil),
            (input: "  ", output: nil),
            (input: "a b", output: nil),
            (input: "a 3", output: nil),
            (input: "3 a 5", output: nil),
            (input: "3 5", output: 35),
            (input: " 35", output: 35),
            (input: "35 ", output: 35),
            (input: "35 ", output: 35)
        ]
        
        for age in ages {
            XCTAssertEqual(contactValidityChecker.checkAgeValidation(age.input), age.output)
        }
    }
    
    func test_나이_100살_미만인지() {
        let ages = [
            (input: "35", output: 35),
            (input: "100", output: nil),
            (input: "99", output: 99),
            (input: "-1", output: nil),
            (input: "0", output: nil),
            (input: "1", output: 1)
        ]
        
        for age in ages {
            XCTAssertEqual(contactValidityChecker.checkAgeValidation(age.input), age.output)
        }
    }
    
    // MARK: - 연락처
    func test_연락처_빈_문자열인지() {
        XCTAssertEqual(contactValidityChecker.checkPhoneNumberValidation(""), nil)
    }
    
    func test_연락처_길이가_11자리_이상인지() {
        let phoneNumbers = [
            (input: "111", output: nil),
            (input: "111-11-11", output: nil),
            (input: "1-1-1-1-1", output: nil),
            (input: "111-1111-111", output: "111-1111-111"),
            (input: "111-1111-1111", output: "111-1111-1111"),
            (input: "111-1111-11111", output: "111-1111-11111")
        ]
        
        for phoneNumber in phoneNumbers {
            XCTAssertEqual(contactValidityChecker.checkPhoneNumberValidation(phoneNumber.input), phoneNumber.output)
        }
    }
    
    func test_연락처_하이픈이_정확히_2개인지() {
        let phoneNumbers = [
            (input: "111", output: nil),
            (input: "111-111", output: nil),
            (input: "1-1-1-111", output: nil),
            (input: "111-1111-1111", output: "111-1111-1111"),
            (input: "111-1111-11111", output: "111-1111-11111")
        ]
        
        for phoneNumber in phoneNumbers {
            XCTAssertEqual(contactValidityChecker.checkPhoneNumberValidation(phoneNumber.input), phoneNumber.output)
        }
    }
    
    func test_연락처_하이픈이_올바른_위치에_있는지() {
        let phoneNumbers = [
            (input: "--111111111", output: nil),
            (input: "-111111111-", output: nil),
            (input: "111111111--", output: nil),
            (input: "111-111-111", output: "111-111-111"),
            (input: "11111--1111", output: nil),
            (input: "111-1111-1111", output: "111-1111-1111"),
            (input: "111-1111-11111", output: "111-1111-11111")
        ]
        
        for phoneNumber in phoneNumbers {
            XCTAssertEqual(contactValidityChecker.checkPhoneNumberValidation(phoneNumber.input), phoneNumber.output)
        }
    }
    
    func test_연락처_하이픈_제거하면_숫자만_있는지() {
        let phoneNumbers = [
            (input: "111-111-111", output: "111-111-111"),
            (input: "111-1111-1111", output: "111-1111-1111"),
            (input: "111-1111-111a1", output: nil),
            (input: "aaa-bbb-cccc", output: nil),
            (input: "#222-1111-11111", output: nil)
        ]
        
        for phoneNumber in phoneNumbers {
            XCTAssertEqual(contactValidityChecker.checkPhoneNumberValidation(phoneNumber.input), phoneNumber.output)
        }
    }
}

``` 

## 고민했던 점
### ContactManager -> 싱글톤 vs 의존성 주입
`EditContactViewController`의 연락처를 추가하는 과정에서 `ContactManager`의 연락처를 `ContactListViewController`와 동일한 데이터를 가지도록 하기 위해 `싱글톤`과 `의존성 주입` 중에 고민을 했습니다.
`싱글톤`으로 하기엔 `ContactListViewController`에서 `ContactManager`의 메소드를 사용하지 않기 때문에 싱글톤 패턴을 적용하지 않았습니다.
그리고 `ContactManager`의 인스턴스를 `EditContactViewController`에 `의존성 주입`을 해주기엔 주입해주는 VC가 많아지면 복잡해질 것 같아 적용하지 않았습니다.
그리하여 `ContactManager`의 `_contacts`딕셔너리를 타입 프로퍼티로 선언하여 두 뷰 컨트롤러가 동일한 연락처를 가지도록 했습니다. 또한 `NotificationCenter`를 통해서 딕셔너리의 값이 변경이 되면, `ContactListViewController`의 `tableView`가 새로고침 되도록 했습니다.

- ContactListViewController.swift
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    configureNavigationBar()
    self.tableView.dataSource = self
    NotificationCenter.default.addObserver(self, selector: #selector(reloadContacts(_:)), name: NSNotification.Name(rawValue: "Update Contacts"), object: nil)
}
```

- EditContactViewController.swift
```swift
private func checkContactValidation() throws {
    guard let validName = contactValidityChecker.checkNameValidation(nameTextField.text ?? "") else {
        throw ContactException.invalidInput(type: .name)
    }
    
    guard let validAge = contactValidityChecker.checkAgeValidation(ageTextField.text ?? "") else {
        throw ContactException.invalidInput(type: .age)
    }
    
    guard let validPhoneNumber = contactValidityChecker.checkPhoneNumberValidation(phoneNumberTextField.text ?? "") else {
        throw ContactException.invalidInput(type: .phoneNumber)
    }
    try contactManager.add(Contact(name: validName, age: validAge, phoneNumber: validPhoneNumber))
    NotificationCenter.default.post(name: NSNotification.Name("Update Contacts"), object: nil)
}
```

2023-10-12 07:25 UTC, protocorn93 requested changes
두 분 고생 많으셨어요. 

`ContactManager`에 대한 저의 생각은 아래와 같아요.

0. 먼저 싱글톤 vs 의존성 주입의 전제가 잘못되었어요. 싱글톤 객체도 의존성 주입을 통해 사용하도록 되어야 해요. 이를 위해선 프로토콜 추상화가 선행되어야 해요. 해당 프로토콜의 구현체로 싱글톤 객체를 주입해주어야 겠죠.
1. `ContactManager`는 저장소와의 역할과는 분리되어야 한다. (Contacts는 별도 저장소에 저장되어야 하고 해당 저장소에 접근할 수 있는 객체는 별도로 구현되어야 한다)
2. 저장소는 서비스가 확장되고 커짐에 따라 리모트 저장소(서버)가 될 수 있고 로컬 저장소가 될 수 도 있어요. 
3. 저장소에 접근하는 역할을 가진 객체를 보통 Repository라고 명명해요. Repository라는 개념에 대해 학습해보시면 제가 위에서 언급한 것들에 대해 감이 조금 생기실 수 있어요. 이는 Clean Architecture의 개념이 동반되곤해요. 
4. ContactManager를 싱글톤으로 구현하냐 마냐는 선택의 문제일 것 같은데, 싱글톤으로 구현하게 된다면 동시성 이슈에 대해 인지를 하시고 이를 방지할 수 있는 코드 추가가 필요해요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        }
이런 샘플 데이터는 올려주실 땐 제거해주시면 좋을 것 같아요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        print("yes cell \(indexPath.row)")
이런 출력 문구는 올려주실 땐 제거해주시면 좋을 것 같아요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(reloadContacts(_:)), name: NSNotification.Name(rawValue: "Update Contacts"), object: nil)
이것도 `addObservers` 와 같은 추상화된 네이밍의 메서드로 분리해주시면 좋을 것 같아요. 저는 1줄짜리 코드라도 보다 더 의미를 명확하게 전달할 수 있는 네이밍의 메서드로 분리하곤해요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        }
[이 생성자](https://developer.apple.com/documentation/uikit/uistoryboard/3213988-instantiateinitialviewcontroller)를 사용해서 의존성을 생성 시점에 주입해줄 수도 있어요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            let cell = ContactCell(style: .subtitle, reuseIdentifier: id)
ContactCell이 reuseIdentifier를 필요한 이유가 있을까요?

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/EditContactViewController.swift
> +    @IBOutlet weak var phoneNumberTextField: UITextField!
이 변수들에도 `private` 접근 제어자를 줄 수 있어요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/EditContactViewController.swift
> +    private let contactManager = ContactManager()
위에서 언급해드린 생성자를 통해 생성자를 통해 주입해주시면 좋을 것 같아요.

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/EditContactViewController.swift
> +        NotificationCenter.default.post(name: NSNotification.Name("Update Contacts"), object: nil)
Notification을 extension을 통해 상수화해주시면 좋을 것 같아요. 

```swift 
extension Notification { 
  static let didUpdateContacts = NSNotification.Name...
}
```

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Utility/ContactValidityChecker.swift
> +struct ContactValidityChecker {
구조체로 구현해주신 이유가 궁금해용 ㅎㅎ

2023-10-12 07:25 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +        }
given, when, then 패턴으로 주석과 함께 작성해주시면 좋을 것 같아요.

2023-10-12 09:06 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        }
뒤늦게 샘플 데이터를 삭제해야 하는 것 인지하게 됐습니다. 주의하도록 하겠습니다!

2023-10-16 00:53 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            let cell = ContactCell(style: .subtitle, reuseIdentifier: id)
`dequeueReusableCell`은 `identifier`가 있을 때 셀을 가져옵니다. 그러나 Cell이 없을 경우, ContactCell을 따로 만들어야 추후에 `dequeReusableCell`을 사용할 수 있기 때문에, 이를 확인하기 위한 `resueIdentifier`를 사용했습니다.
> 물론 저희는 셀을 `storyboard`에서 만들었기 때문에, 거기서 `dequeueReusableCell`을 해낸다는 사실을 알고 있지만, `storyboard`에 셀이 없을 경우를 대비해서 만들었습니다!

2023-10-16 00:59 UTC, bamsak commented on ios-contact-manager-ui/ios-contact-manager-ui/Utility/ContactValidityChecker.swift
> +struct ContactValidityChecker {
struct 내부에 프로퍼티가 없어서 dispatch만을 생각했을 때, class로 구현하는 것 보다 성능 상의 이점이 있다고 생각했습니다. class로 구현 했을 시 `final`키워드를 붙여 단일 dynamic dispatch로 구현했을 경우 static dispatch와 성능 상의 큰 차이를 없다고 하지만 struct 내부엔 heap에 참조하게 되는 프로퍼티 없이 오직 method만 가지고 있기 때문에 struct로 구현했습니다.

2023-10-16 01:04 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    }
observeUpdatedContacts 함수를 추가하여 분리하였습니다!

2023-10-16 01:07 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-ui/Extensions/Notification+Extension.swift
> +}
`Notification`에 연락처가 업데이트 되는 것에 대한 `Name`을 상수화했습니다!

2023-10-16 01:07 UTC, bamsak commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/EditContactViewController.swift
> +    @IBOutlet private weak var phoneNumberTextField: UITextField!
private 접근 제어자 추가 했습니다!

2023-10-16 01:11 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            present(UINavigationController(rootViewController: viewController), animated: true)
알려주신 `instantiateViewController`을 통해 생성 시점에 의존성을 주입받도록 했습니다.

2023-10-16 01:12 UTC, bamsak commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/EditContactViewController.swift
> +    }
이니셜라이저의 매개변수를 추가하여 ContactListViewController로부터 의존성 주입 받아서 구현했습니다.

2023-10-16 01:12 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +        }
각각의 테스트 케이스에 주석을 달아놓았습니다!

2023-10-16 08:10 UTC, merged