연락처 관리 앱 [Step2] 쫑, 록스
tasty-code/ios-contact-manager-ui pull request #35
Opened 2023-10-14 09:03 UTC by shlim0

### 리뷰어

[@forestjae](https://github.com/forestjae)

### 팀원

[@KimRoks](https://github.com/KimRoks), [@shlim0](https://github.com/shlim0)

# UML

```mermaid
classDiagram
class ContactDTO {
+name: String << read-only >>
+age: String << read-only >>
+phoneNumber: String << read-only >>
}

class JSONCodable {
<< protocol >>
+decodeJSON(): [ContactDTO]?
}

class DataSendable {
<< protocol >>
+send(data: ContactDTO)
}

class UITableViewDataSource {
<< protocol >>
+ tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) : Int
+ tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath): UITableViewCell
}

class JSONCodable {
<< protocol >>
}

class UITableViewDelegate {
<< protocol >>
}

class UIAlertController {
<< extension >>
+configureAlertController(title: String, message: String, defaultAction: String, destructiveAction: String, viewController: UIViewController)
+configureAlertAction(of: UIAlertController, defaultAction: String)
+configureAlertAction(of: UIAlertController, defaultAction: String, destructiveAction: String, viewController: UIViewController)
+configureDestructiveAlertAction(title: String, viewController: UIViewController): UIAlertAction
+configureDefaultAlertAction(title: String): UIAlertAction
}

class String {
<< extension >>
+formattingPhoneNumber(divider: Character): String
}

class ContactViewController {
-tableView: UITableView
-contactDTOs: [ContactDTO]
-alertController: UIAlertController << read-only >>

+viewDidLoad()
-touchUpAddButton(sender: Any)
}

class NewContactViewController {
-cancelButton: UIBarButtonItem
-nameTextField: UITextField
-ageTextField: UITextField
-phoneNumberTextField: UITextField
-alertController: UIAlertController << read-only >>
+delegate: DataSendable

-phoneNumberTextFieldEditingChanged(sender: UITextField)
-touchUpSaveButton(sender: Any)
-touchUpCancelButton(sender: UIBarButtonItem)
-checkName(): String?
-checkAge(): String?
-checkPhoneNumber(): String?
-catcher(of error: CheckContactErrors): String
}

class DecodingErrors {
<< enumeration >>
invaildPath
invaildData
invaildDecoding
}

class CheckContactErrors {
<< enumeration >>
invalidName
invaildAge
invalidPhoneNumber
unknown
}

JSONCodable ..> ContactDTO
JSONCodable --> DecodingErrors: throws
DataSendable ..|> AnyObject
DataSendable ..> ContactDTO
ContactViewController --|> UIViewController
ContactViewController ..|> DataSendable
ContactViewController ..|> JSONCodable
ContactViewController --o UIAlertController
ContactViewController --> String
ContactViewController --o ContactDTO
ContactViewController ..|> DataSendable
ContactViewController ..|> JSONCodable
ContactViewController ..|> UITableViewDataSource
ContactViewController ..|> UITableViewDelegate
ContactViewController --> CheckContactErrors: throws
NewContactViewController --|> UIViewController
NewContactViewController --o UIAlertController
```

# 프로젝트 구조
  <img width="296" alt="Untitled" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/7ffe931b-d9b1-4fc1-a7f9-badb5af6f151">

- 추가된 파일은 **볼드처리** 하였습니다. 이외 내용은 STEP 1과 동일합니다.
- protocols
    - `JSONCodable`: `.json` 파일을 decoding 하는 코드를 따로 분리하고 재사용 하기 위해 생성한 protocol 입니다.
    - **`DataSendable`: `NewContactViewController`에서 `ContactViewController`로 데이터를 delegate 방식으로 전달하기 위해 생성한 protocol 입니다.**
- Extenstions
    - `JSONCodable+Extension`: `.json` 파일을 decoding 하는 코드를 따로 분리하기 위해 생성한 extension 입니다. `JSONCodable`을 채택하는 class에서 따로 구현할 필요 없이 하기 위한 extension 입니다.
    - **`String+Extension`: 사용자로 부터 전화번호를 입력받을 때, 하이픈(`-`)을 추가하기 위해 생성한 extension 입니다.**
    - **`AlertController+Extension`**: **`ContactViewController`와  `NewContactViewController`에서 기존 alertController를 API 처럼 편하게 사용하기 위한 extension 입니다.**
- Models
    - `ContactJSON`: 연락처 정보가 있는 dummy `.json` 파일입니다.
    - `ContactDTO`: decoding 된`.json` 파일을 받을 모델입니다.
- Controllers
    - `ContactViewController`: 첫 번째 화면을 나타내는 VC 입니다. 연락처 정보가 없는 경우, cell을 불러오지 않습니다.
    - **`NewContactViewController`: 사용자가 `ContactViewController`에서 연락처를 추가하는 버튼을 터치했을 경우, 나타나는 VC 입니다. 사용자로부터 이름, 나이, 연락처를 입력받을 수 있습니다. 이에 대한 유효성 검사를 하며, 이는 저장 또는 취소 될 수 있습니다.**
- **ErrorCases**
    - **`DecodingErrors`: `JSONCodable+Extension`에서 `.json` 파일이 decoding 되지 않는 error를 정의한 enum 입니다.**
    - **`CheckContactErrors`: `NewContactViewController`에서 사용자로부터 입력 받은 이름, 나이, 연락처가 유효하지 않는 경우에 대한 error를 정의한 enum 입니다.**

# 고민했던 점
  ## 1. AlertController
- `UIAlertController`를 `extension`하여 역할별로 `methods`를 구분하고 재사용성을 높이고자 했습니다. 
     즉,`AlertController+Extension.swift`로 기능을 분리하였습니다.
   ### 기존 코드

![untitled](https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/d9d7b879-ec04-429e-96bf-ea297d0df0cd)
- 기능을 분리하기 위해 초기 생각한 컨셉입니다. 1번, 2번, 3번으로 구분하여 각 기능을 분리하려 했습니다.

- 기존 작성된 alert을 만드는 메서드입니다.
    
    해당 메서드는 1. `UIAlertController`를 정의하며, 2. action을 정의하고, 3. action을 추가하며, 4. 추가 화면에 `present()`하는 등 많은 일을 하나의 메서드에서 수행했습니다.
    
    이를 SOLID 중, S(`단일 책임 원칙`)를 따르도록 각 역할을 분리하였습니다.
    
    ### 변경 후 코드
    
    ```swift
    // AlertController+Extension.swift
    extension UIAlertController {
    
    // message와 두번째 alert action은 선택 사항으로 두었습니다.
    // 두번째 alert action를 .destructive 둔 이유는 UX 측면에서 alert이 뜨면 "예" 또는 "아니오"(또는 "확인" 또는 "취소")가 출력되는 경우를 종종 보았습니다. 이런 경우를 대비하였습니다.
      func configureAlertController(title: String, message: String?, defaultAction: String, destructiveAction: String?, viewController: UIViewController) {
          let alertController = UIAlertController(title: title,
                                                  message: message,
                                                  preferredStyle: .alert)
          
          if let destructiveAction = destructiveAction {
              configureAlertAction(of: alertController, defaultAction, destructiveAction, viewController)
              viewController.present(alertController, animated: true)
          } else {
              configureAlertAction(of: alertController, defaultAction)
              viewController.present(alertController, animated: true)
          }
      }
      
    // alert action이 하나인 경우를 처리합니다.
      func configureAlertAction(of alertController: UIAlertController, _ defaultAction: String) {
          alertController.addAction(configureDefaultAlertAction(title: defaultAction))
      }
      
    // alert action이 두개인 경우를 처리합니다.
      func configureAlertAction(of alertController: UIAlertController, _ defaultAction: String, _ destructiveAction: String, _ viewController: UIViewController) {
          alertController.addAction(configureDefaultAlertAction(title: defaultAction))
          alertController.addAction(configureDestructiveAlertAction(title: destructiveAction, viewController))
      }
    
    // .destructive alert action을 처리합니다.
      func configureDestructiveAlertAction(title: String, _ viewController: UIViewController) -> UIAlertAction {
          let destructiveAlertAction = UIAlertAction(title: title, style: .destructive, handler: { _ in
              viewController.dismiss(animated: true)
          })
          
          return destructiveAlertAction
      }
    // .default alert action을 처리합니다.
      func configureDefaultAlertAction(title: String) -> UIAlertAction {
          let defaultAlertAction = UIAlertAction(title: title, style: .default, handler: nil)
          
          return defaultAlertAction
      }
    }
    ```
    
- 사용법은 다음과 같습니다.
    
    ```swift
    //Alert 생성 예시
    alertController.configureAlertController(title: "데이터 불러오기 실패",
    		                                     message: nil,
                                             defaultAction: "예",
                                             destructiveAction: nil,
                                             viewController: self)
    ```
    
- 결과적으로 Alert를 반복적으로 작성하던 것을 줄이고, 메서드에서 원하는 기능만을 담은 Alert를 커스텀하여 생성할 수 있도록 변경되었습니다.

## 2. AlertController를 활용한 예외 처리

- 고민했던 점 1번을 진행 했음에도 `alertController`인해 사용자에게 입력이 잘못되었음을 알리는 코드가 길고, `return nil` 과 같은 불필요한 코드가 발생하였습니다.
    
    ### 기존 코드
    
    ```swift
    // NewContactViewCont [...]

2023-10-16 14:56 UTC, forestjae commented
스텝 2 하시느라 고생 많으셨어요, 많은 고민이 엿보이는 코드와 PR이네요 👍 👍 👍 

> # 고민했던 점
> ## 1. AlertController
> * `UIAlertController`를 `extension`하여 역할별로 `methods`를 구분하고 재사용성을 높이고자 했습니다.
>   즉,`AlertController+Extension.swift`로 기능을 분리하였습니다.

잘 만들어 주셨어요. 현업에서도 UIKit 기본 클래스에 extension 해서 이런 메서드들을 많이 만들어 둡니다.

> 
> ## 2. AlertController를 활용한 예외 처리
> * 고민했던 점 1번을 진행 했음에도 `alertController`인해 사용자에게 입력이 잘못되었음을 알리는 코드가 길고, `return nil` 과 같은 불필요한 코드가 발생하였습니다.

에러 처리로 방식 변경해주신 점 아주 좋습니다. 다만 catcher 메서드의 필요성은 생각 해 봐야 될 점이네요!

> 
> ## 3. delegate pattern와 observer pattern
> * `NewContactViewController`에서 `ContactViewController`로 사용자가 입력한 연락처 정보를 넘겨주려 할 때, 어떤 pattern을 적용할지 고민했습니다.
> 
> ![Untitled](https://user-images.githubusercontent.com/46235301/275174181-bb2d9be5-4324-425e-b64f-e0926db4816e.jpeg)
> 
> ![Untitled1](https://user-images.githubusercontent.com/46235301/275174213-b47553d3-c408-48c0-9f3c-de30a116f75e.png)
> 
> * [여기](https://softwareengineering.stackexchange.com/a/178045)를 참고했습니다.
> * **가장 큰 차이점**은 델리게이트 패턴은 `1:1` 관계만을 처리하고 옵저버 패턴은 `1:N`관계 까지도 처리 가능하다는 것입니다.
> * 그로인해 옵저버가 무분별하게 많아지면 가독성이 크게 떨어질것으로 보입니다.
>   ## delegate pattern을 적용한 이유
> * 현재 프로젝트에서는 `ContactViewController`**로만** 사용자가 입력한 연락처 정보를 넘겨줍니다.
> * _이름, 나이, 연락처_ 총 세 가지 정보를 전달하여야 하므로 한 가지 정보만 변경되어도 notification 되지 않아야 하기 때문입니다.
> * 따라서, observer pattern을 사용하는 것이 다소 불필요하다 생각하였습니다. **이에 대한 숲재의 의견을 듣고 싶습니다.**
> 

네 딜리게이트가 적절해보입니다!

> ## 4. reloadData() 대신 insertRows() 사용
> * tableView를 전부 업데이트하는 `reloadData()`를 사용하는 것 보다 추가된 cell만 업데이트하는 `insertRows()`를 사용하는 것이 메모리를 관리하는 측면에서 더 좋은 성능을 보일거라 생각했습니다.
> * 즉, cell의 수가 n인 경우, O(n)의 성능을 보인 것에서 O(1)이 되도록 했습니다.

저도 insertRows가 reloadData 보다는 리소스를 더 사용할 거라고는 추측이 되는데 혹시 찾아보신 관련 근거가 있을까요? reloadData가 O(n), insertRows가 O(1)의 개념은 아마 아닐거라고 생각됩니다.

> 
> # 궁금한점
> ## 1. Regex
> * 현재 저희 팀은 _iOS 16.0_ 미만에선 대응되지 않는 [Regex](https://developer.apple.com/documentation/swift/regex) 표현을 사용하고 있습니다.
> * 물론, **[NSRegularExpression](https://developer.apple.com/documentation/foundation/nsregularexpression)** 이용하여 호환성을 더 증대시킬 수 있으나 추후 코드가 수정되는 것과 현재 _iOS 16.0_ 이후 버젼 점유율을 고려하여 사용하지 않았습니다.
>   <img alt="Untitled2" width="287" src="https://user-images.githubusercontent.com/46235301/275174298-edc7ebaf-f8ea-4f3c-a850-eea52492b7e8.png">
> * iOS 16 점유율은 81% 입니다. (https://developer.apple.com/kr/support/app-store/)
> * 트래픽이 많은 서비스에서는 최대한 많은 사용자가 이용할 수 있도록 상대적으로 오래된 iOS 버젼(_i.e. iOS 14 이전_)도 지원하는 것으로 알고 있습니다.
> * 또한, 상황에 따라 스타트업의 경우 최신 기술을 상대적으로 적극 적용하는 것으로 알고 있습니다.
> * 결과적으로, 최신 기술과 사용자 수(호환성)간 trade-off라고 결론지었습니다. 이에 대한 숲재의 개인적인 의견이 궁금합니다.

이 부분은 개발자 혼자 결정할 수 있는 문제가 아니라 회사의 정책이기 때문에... 다양한 케이스가 있을 것 같습니다. 타겟이 되는 고객층에도 영향이 있을 수 있고요.
iOS 개발자로 취업을 하고 싶은 취준생 기준으로 생각해보자면,  현재 기준으로 대다수의 회사가 14, 15 버전을 마이너 타겟으로 정하고 있는 것으로 알고 있어요. 그래서 14나 15에서 사용하는 기술들도 면접에 중요하게 다뤄지는 것으로 알고있어요.

> ## 2. SOLID
> * 최근 `SOLID`에 관해 학습하여 조금이라도 적용시키려는 시도를 해보았는데 학습 중 사실상 모두 적용시키고 철저하게 지킨다는것이 어렵지않을까? 라는 생각이 들었습니다. 중요한것은 원칙과 작성자의 주관 사이의 공통분모를 찾아 적용시키는것이겠지만 `SOLID`는 얼마나 철저하게 적용되어야할까요?
> 

애플의 기본 클래스에도 SOLID 원칙을 위반한 사례가 있어요. SOLID를 얼마나 잘 지키는가 보다 왜 지켜야하는지 고민해보시면 좋을 것 같습니다. 

> ## 3. Design Pattern
> * AlertController의 재사용성을 높이면서 `extension`을 활용하였습니다. 해당 상황에서 `factory pattern`의 적용 또한 고민했는데 현재 진행중인 프로젝트 규모엔 `extension`이 더욱 적합한 선택지라는 생각이 들었습니다. 하지만 얼마나 큰 규모의 상황을 대처할것 인가에 대한 의문이 들었습니다. 새싹 과정을 진행하며 정확하게 요구된 사항내에서 진행을 하는것과 정말 기업이나 사업의 일환으로 생각하여 (?) 주어지지 않은 상황에 대한 유지보수까지 신경쓰는 것 어떤 방식을 선택하는것이 좋을까요?
> 

요구 사항을 만족하는 것은 1순위로 지켜져야할 문제입니다. 별개로 유지보수 + 추후에 변경될 수 있는 점을 고려해서 코드를 작성하는 게 개발자의 실력에 중요한 척도가 된다고 생각합니다. 자신만의 근거와 기준을 두면서 프로젝트를 진행해 나가 보세요~!

2023-10-16 14:56 UTC, forestjae requested changes

2023-10-16 14:56 UTC, forestjae commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +    private let alertController = UIAlertController()
alertController를 프로퍼티로 미리 선언해 두신 이유가 있을까요?

2023-10-16 14:56 UTC, forestjae commented on ContactManager/ContactManager/Errors/DecodingErrors.swift
> +}
에러로 처리하신 점 아주 좋습니다 👍

2023-10-16 14:56 UTC, forestjae commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +    }
nameTextField의 text를 꺼내오는게 아닌, 파라미터로 String 값을 받는 메서드를 만드는게 어떨까요? 그러면 리턴값 으로 String?가 아닌 String 리턴이 가능합니다.

check~ 메서드들에 공통되는 내용입니다.

2023-10-16 14:56 UTC, forestjae commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +        }
Error enum에 프로퍼티를 추가하는 방법이 더 좋을 것 같아요.

2023-10-16 14:56 UTC, forestjae commented on ContactManager/ContactManager/Extensions/AlertController+Extension.swift
> +    }
외부에서 쓰이지 않는 메서드는 private을 붙여주세요 ㅎ

2023-10-17 00:37 UTC, KimRoks commented on ContactManager/ContactManager/Extensions/AlertController+Extension.swift
> +    }
extension내에 선언된 methods라 private 처리를 하지 못했습니다!
혹시 저희가 모르는 방법이 있을까요?

2023-10-17 00:39 UTC, KimRoks commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +    private let alertController = UIAlertController()
UIAlertController에서 extension하여 작성해놓은 메서드를 사용하려고 인스턴스를 생성 해놓았습니다
더 나은 방법 또한 생각해보겠습니다!

2023-10-17 00:40 UTC, KimRoks commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +    }
확인했습니다!

2023-10-17 02:29 UTC, shlim0 commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +    }
Utilities - Validation 파일 안에 check 함수를 다음과 같이 수정하였습니다.
파리미터는 textField.text 특성상 String?으로 받았으며, return type을 String으로 변경했습니다.
```swift
struct Validation {
    func check(name: String?) throws -> String {
          let regex = /^\S+(\s+\S+)*$/
          if let name = name,
             let _ = name.wholeMatch(of: regex) {
              return name
          } else {
              throw CheckContactErrors.invalidName
          }
      }
...
}
```

2023-10-17 02:30 UTC, shlim0 commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +        }
CheckContactErrors 파일에서 다음과 같이 수정했습니다.
```swift
enum CheckContactErrors: Error {
    case invalidName
    case invalidAge
    case invalidPhoneNumber
    case unknown

    var description: String {
        switch self {
        case .invalidName:
            return "입력된 이름 정보가 잘못되었습니다"
        case .invalidAge:
            return "입력된 나이 정보가 잘못되었습니다"
        case .invalidPhoneNumber:
            return "입력된 연락처 정보가 잘못되었습니다"
        case .unknown:
            return "알 수 없는 에러입니다"
        }
    }
}
```

2023-10-17 02:37 UTC, shlim0 commented
> 저도 insertRows가 reloadData 보다는 리소스를 더 사용할 거라고는 추측이 되는데 혹시 찾아보신 관련 근거가 있을까요? reloadData가 O(n), insertRows가 O(1)의 개념은 아마 아닐거라고 생각됩니다.

어떤 출처가 있던 것은 아니었고, 추측한 것이었습니다. 다시 생각해보니 insertRow()가 O(1)은 아닐 것 같습니다. 단순히 마지막 row 뒤에 새로 row를 추가하는 것만 아니라 경우에 따라, 특정 위치에 row를 추가할 수도 있기 때문에 기존 row를 업데이트 하는 경우도 있을 것 같습니다. 이런 경우를 상정하면 O(n)은 걸릴 것 같습니다. 

그 외, 시간복잡도에 대한 search 및 document를 확인해 보았으나 알려진 게 없어 찾지 못했습니다.

2023-10-18 10:46 UTC, forestjae commented on ContactManager/ContactManager/Controllers/NewContactViewController.swift
> +    private let alertController = UIAlertController()
얼럿 컨트롤러를 미리 선언해 두면 항상 메모리를 차지하고 있을 것 같아요!

2023-10-18 10:47 UTC, forestjae commented on ContactManager/ContactManager/Extensions/AlertController+Extension.swift
> +    }
extension 외부에서 사용하지 않는 메서드에는  private을 붙여주세요!!

2023-10-18 10:49 UTC, forestjae commented
> > 저도 insertRows가 reloadData 보다는 리소스를 더 사용할 거라고는 추측이 되는데 혹시 찾아보신 관련 근거가 있을까요? reloadData가 O(n), insertRows가 O(1)의 개념은 아마 아닐거라고 생각됩니다.
> 
> 
> 
> 어떤 출처가 있던 것은 아니었고, 추측한 것이었습니다. 다시 생각해보니 insertRow()가 O(1)은 아닐 것 같습니다. 단순히 마지막 row 뒤에 새로 row를 추가하는 것만 아니라 경우에 따라, 특정 위치에 row를 추가할 수도 있기 때문에 기존 row를 업데이트 하는 경우도 있을 것 같습니다. 이런 경우를 상정하면 O(n)은 걸릴 것 같습니다. 
> 
> 
> 
> 그 외, 시간복잡도에 대한 search 및 document를 확인해 보았으나 알려진 게 없어 찾지 못했습니다.

네넵 애플 ui 프레임워크는 오픈소스가 아니라서 저희가 확인할 길이 없죠 😢

2023-10-18 10:49 UTC, merged