[Step 2] 연락처 관리 앱 - 컴도리, 재닌
tasty-code/ios-contact-manager-ui pull request #37
Opened 2023-10-16 02:27 UTC by comdori-wj

리뷰어: @jryoun1
버드: @janine-kang, @comdori-wj

제이크, 안녕하세요!
이번에 새 연락처 추가 화면을 스토리보드 없이 코드로만 구현하느라 좀 오래 걸렸습니다. 😅
연락처 관리 앱 STEP 2의 PR 요청드립니다 🙌🏻

## Summary
새 연락처 추가 기능 구현

## 구현 화면
![스탭2](https://github.com/tasty-code/ios-contact-manager-ui/assets/22284092/73bcf858-61c1-4c95-b4be-5f55f4debbce)

## 구현 사항

- [x] 추가기능을 구현하기 전에 동작에 대한 UML 을 작성하여 PR에 추가
- [x] 연락처 목록 화면의 우상단 버튼을 통해 연락처 추가 화면에 진입
- [x] 오토 레이아웃과 스택뷰를 활용하여 화면을 레이아웃
- [x] 각 필드에 맞는 키보드 종류 띄우기
- [x] 취소 버튼을 선택하면 정말 취소할 것인지 묻기
- [x] 저장 버튼을 선택하면 입력한 정보가 올바르게 입력되었는지 확인
- [x] 저장 버튼을 누르면 사용자가 중간에 이름을 띄어쓰기를 하더라도 띄어쓰기를 제거
- [x] 나이는 숫자로만 입력해야하며, 세 자리수 이하 입력
- [x] 연락처는 중간에 -로 구분하며, -는 두 개 존재 해야함
- [x] "-" 을 제외하고 숫자는 9자리 이상이어야 함

## UML
![UML](https://github.com/tasty-code/ios-contact-manager-ui/assets/22284092/9cb37149-5228-41f0-b174-aa77f67d8af2)

## 폴더 구조
```
ContactManager
├── Controllers
│   ├── ContactCreationViewController.swift
│   └── ContactTableViewController.swift
├── Enums
│   ├── InvalidError.swift
│   └── ValidateType.swift
├── Extensions
│   ├── Array.swift
│   ├── String.swift
│   ├── UIStackView.swift
│   └── UIView.swift
├── Info.plist
├── Models
│   ├── ContactInfo.swift
│   └── ContactManager.swift
├── Resources
│   ├── AppDelegate.swift
│   ├── Assets.xcassets
│   │   ├── AccentColor.colorset
│   │   └── Contents.json
│   │   ├── AppIcon.appiconset
│   │   │   └── Contents.json
│   │   └── Contents.json
│   ├── Base.lproj
│   │   └── LaunchScreen.storyboard
│   ├── SceneDelegate.swift
│   └── mockData.json
└── Views
    ├── Base.lproj
    │   └── Main.storyboard
    └── ContactCreationStackView.swift
```
## 고려한 점
연락처 추가 화면을 코드로 구현해보는 소소한 챌린지를 진행해봤습니다.
- 오토레이아웃을 코드로 잡는것이 생각보다 어려웠습니다.
- 스토리보드 상에선 알아서 처리해주던 것이 코드로 작성하니 공부할 것이 많다고 느꼈습니다.

## 궁금한 점
- 화면이동방식시 UINavigationController을 새로 생성하여 사용하여 이동하는 것이 맞는지 아니면 uiview컨트롤러를 사용하여 이동하는 것이 맞는지 궁금합니다. UINavigationController 사용했다면 네비게이션 바가 자동 생성되었는데 현재는 따로 네비게이션바를 추가 하였습니다. 단순히 이 기능 때문에 써야 된다고 느꼈지만 네비게이션 컨트롤이 이 기능만을 위해 사용하는 것은 맞지 않다고 생각되었습니다. 이런 경우에도 네비게이션 컨트롤을 사용하기도 할까요?
```
@IBAction func addButtonTapped(_ sender: UIButton) {
        let contactCreationViewController = ContactCreationViewController()
        let navigationController = UINavigationController(rootViewController: contactCreationViewController)
        navigationController.modalPresentationStyle = .popover
        navigationController.navigationBar.topItem?.title = "새 연락처"
        present(navigationController, animated: true)
    }
```
- extension시 확장의 의미보다는 기능을 나누는데도 많이 사용하는지 궁금합니다. 추가로 현업에서는 분류를 어떻게 하는지 궁금합니다.
```
// 사용 기능별로 분리       	
        nameLabel.text = "이름"
        nameField.borderStyle = .roundedRect
        nameField.widthAnchor.constraint(equalToConstant: 320).isActive = true
        
        ageLabel.text = "나이"
        ageField.borderStyle = .roundedRect
        ageField.keyboardType = .numberPad
        ageField.widthAnchor.constraint(equalToConstant: 320).isActive = true
        
        phoneNumberLabel.text = "연락처"
        phoneNumberField.borderStyle = .roundedRect
        phoneNumberField.keyboardType = .phonePad
        phoneNumberField.widthAnchor.constraint(equalToConstant: 320).isActive = true

// 메소드 종류에 따라 분리
	nameLabel.text = "이름"
        ageLabel.text = "나이"
        phoneNumberLabel.text = "연락처"

        nameField.borderStyle = .roundedRect
        phoneNumberField.borderStyle = .roundedRect
        phoneNumberField.keyboardType = .phonePad

        ageField.borderStyle = .roundedRect
        ageField.keyboardType = .numberPad

        nameField.widthAnchor.constraint(equalToConstant: 320).isActive = true
        ageField.widthAnchor.constraint(equalToConstant: 320).isActive = true
        phoneNumberField.widthAnchor.constraint(equalToConstant: 320).isActive = true
```

마지막으로 view 로직분리에 대해서 고민이 있습니다.
- UI를 코드로 작성하다 보니, 유저와 인터렉션하는 View 자체의 로직과 View Controller의 로직이 섞이면서 파일 크기가 방대해졌습니다 😓 때문에 View를 따로 분리하려고 시도했는데, delegate 등 유저의 액션을 받아 처리하는 VC로직이 View와 분리하여 존재시키기 어렵다고 생각하여 UIStackView만을 분리하게 되었습니다. 이런 경우, 보통 View를 어떻게 분리해야 전체적인 코드와 구조가 깔끔해질 수 있을까요?

2023-10-17 12:47 UTC, jryoun1 requested changes
안녕하세요 @janine-kang, @comdori-wj 🙌🏻

step2 정말 잘 구현해주셨네요!! 👏 
코드로만 화면 구성을 하는 것인데도 잘 진행해주셨네요! 💯👍🏻
다만 코멘트에 남겼듯이 9자리 일 때 요구사항과 다른 형식으로 보이는 것 같아서 확인부탁드릴게요 🙏 
몇가지 개선되면 좋을만한 부분들에 코멘트 남겨두었습니다 :) 

### 궁금한 점에 대한 답변 

> 1. 화면이동방식시 UINavigationController을 새로 생성하여 사용하여 이동하는 것이 맞는지 아니면 uiview컨트롤러를 사용하여 이동하는 것이 맞는지 궁금합니다. UINavigationController 사용했다면 네비게이션 바가 자동 생성되었는데 현재는 따로 네비게이션바를 추가 하였습니다. 단순히 이 기능 때문에 써야 된다고 느꼈지만 네비게이션 컨트롤이 이 기능만을 위해 사용하는 것은 맞지 않다고 생각되었습니다. 이런 경우에도 네비게이션 컨트롤을 사용하기도 할까요?

연락처를 추가하는 화면은 modal로 구현되는 것이 좋을까요 push로 구현되는 것이 좋을까요? 
이 부분에 대해서 고민해시면 UINavigationController를 사용해야할지 말지에 대한 답변이 될 것 같아요! 
(Hint: UINavigationController로 구현한다면 push가 가능해지게 되고, 그렇지 않은 경우에는 push가 불가능하게 된다는 점도 같이 생각해보시면 좋을 것 같아요!)

> 2. extension시 확장의 의미보다는 기능을 나누는데도 많이 사용하는지 궁금합니다. 추가로 현업에서는 분류를 어떻게 하는지 궁금합니다.

extension을 통해서 여러 파일에서 공통적으로 사용되는 부분들을 선언하고 사용할 수 있습니다. 
말씀주신 부분은 extension을 통한 내용보다는 그냥 각각의 프로퍼티들에 대한 부분들을 어떻게 그룹핑하는지에 대한 이야기인것 같아요! 

정답은 없지만 보는 관점에 따라서 label에 대한 것은 label끼리 묶는 방법도 있고, 
아니면 하나의 property에 관련된 것들끼리 묶는 경우도 있을 것 같아요. 
다만 지금 들어주신 예시라면 저라면 전자의 방법을 사용하는 것이 좀 더 가독성이 좋아보이긴합니다! 
두 분이 가독성 좋은 방향으로 convention을 정하시면 될 것 같아요!

> 3. 마지막으로 view 로직분리에 대해서 고민이 있습니다.

UI를 코드로 작성하다 보니, 유저와 인터렉션하는 View 자체의 로직과 View Controller의 로직이 섞이면서 파일 크기가 방대해졌습니다 😓 때문에 View를 따로 분리하려고 시도했는데, delegate 등 유저의 액션을 받아 처리하는 VC로직이 View와 분리하여 존재시키기 어렵다고 생각하여 UIStackView만을 분리하게 되었습니다. 이런 경우, 보통 View를 어떻게 분리해야 전체적인 코드와 구조가 깔끔해질 수 있을까요?

공통적으로 사용되는 화면이라면 customView를 생성하고, 내부에서 발생하는 action에 대한 처리를 delegate pattern을 통해서 처리할수도 있을 것 같네요. 
다만 지금 스펙에서는 따로 view로 분리할만한 것이 크게 보이지는 않는 것 같은데 말씀하시는 정확히 어떤 부분인지 말씀해주실 수 있을까요?

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager.xcodeproj/project.pbxproj
> +			path = Enums;
비슷한 역할을 하는 파일들끼리 폴더링도 해주셨군요 👏💯
다만 enum들만 모아두었다고 폴더명이 Enums인 것은 명확하지 않은 것 같아요!!
Error는 Error라는 곳에 따로 모을 수 있을 것 같고, ValidateType은 해당 타입을 사용하는 곳 중에서 같이 있으면 좋다고 생각하는 곳에 같이 두어도 좋을 것 같습니다! 🙏🏻

다른 곳들은 비슷한 역할을 하는 것끼리 잘 모아두셨는데, enum만 타입을 기준으로 모아두신 것 같아서 말씀드려요!!

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    public weak var delegate: ContactCreationVCDelegate?
public을 접근제어로 설정하신 이유가 궁금합니다! 
또한 weak var도 사용해주셨는데 어떤 이유로 사용하셨는지 이유가 궁금해요 🙋‍♂️

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +class ContactCreationViewController: UIViewController {
이 class는 상속받을 일이 있을까요?!

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    }()
stackview라는 이름보다는 containerStackview라던지 verticalStackView라고 네이밍 하면 좀 더 명확할 것 같습니다 🙏

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        self.view.backgroundColor = .systemBackground
두 분께서는 self를 사용하시는 기준이 있을까요? 🙋‍♂️

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        phoneNumStack.field.keyboardType = .phonePad
함수명과는 다르게 각 stackview 내부의 값들을 설정해주고 있는 것 같아요! 
명확하게 분리하면 가독성이 더 올라갈 것 같습니다 🙏

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        addNavigationBar()
add보다는 setup과 같은 동사는 어떨까요? 🙏🏻
위에 delegate를 설정하는 것도 아래 함수중에 하나에 같이 포함할 수 있을 것 같아보여요!
`setupLayout, setupAttributes, setupNavigationBar`

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        navbar.layer.shadowColor = UIColor.clear.cgColor
여기 코드들은 작성하신 의도가 어떤걸까요? 🤔

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        let saveButton = UIBarButtonItem(title: "Save", style: .plain, target: self, action: #selector(didTapSaveButton))
save의 style은 .plain으로 설정하는게 좋을까요? 다른 style을 선택하면 어떤 것이 변경될까요?

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +
함수 내에서 줄바꿈에 대한 convention이 정해져있을까요? 
다른 함수들과는 다르게 줄바꿈이 있는 것 같네요! 
convention이 잘 지켜지면 가독성이 더 좋아집니다 👍

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Extensions/String.swift
> +        case compress
String extension을 통해서 TextFormatType을 생성하고 함수들을 생성해주셨군요!! 👏 💯 
다만 compress는 압축이라는 뜻인데, 명확하지 않은 것 같습니다! 
실제로 formatter에서는 공백을 제거하는 것 같은데 명확하게 removeWhitespace는 어떨까요?

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +extension ContactCreationViewController {
내부에 함수들이 전부 private이라면 private extension을 통해서 선언하면 각 함수들에는 private을 붙이지 않아도 됩니다!

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    private func checkValidate(text: String, type: ValidateType) throws -> Void {
여기만 Void 반환타입을 명시하신 이유가 있을까요? 🤔

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +            break
여기는 각 case에 break가 붙은 이유가 있을까요? 🤔

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Extensions/String.swift
> +        let offset = sanitizedTarget.hasPrefix("02") ? 1 : 2
<img width="506" alt="image" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/45090197/59b48e4a-942d-4c4f-9bb4-fc133c51ca3c">

9자리 일 때 format에 맞는케이스가 02가 아니면 다르게 표시되고 있는 것 같습니다 🐛

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Models/ContactManager.swift
> +}
이 빈 함수는 어디에 사용되는걸까요? 🤔

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Extensions/UIStackView.swift
> +}
다른곳에서도 충분히 재사용될 수 있는 부분들을 extension으로 빼두셨네요 👏 💯

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Enums/InvalidError.swift
> +enum InvalidError: Error, CustomStringConvertible {
에러 처리도 좋네요 🥇 👍

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +}
delegate pattern을 사용해보셨네요 👏 
여기서 contactManger에 add를 해준뒤에 tableview자체를 reload시킬수도 있을 것 같은데 
tableview에 직접 insertRows를 해주신 이유가 궁금합니다 🙋‍♂️

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    }
반복될 수 있는 부분을 함수로 잘 빼주셨네요 👏

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +}
protocol의 네이밍의 뜻이 궁금합니다! 
물론 네이밍의 suffix에 delegate를 붙일 수도 있지만, 주로 able을 붙이거나 구체적으로 짓기도 합니다. 
지금 해당 프로토콜의 역할은 contact를 추가해주는 역할만 하는 것으로 보여서 조금 더 구체적인 네이밍이면 좋을 것 같아요. 🙏🏻

2023-10-17 12:47 UTC, jryoun1 commented on ContactManager/ContactManager/Views/ContactCreationStackView.swift
> +class ContactCreationStackView: UIStackView {
이 view는 다른 곳에서 상속받을 수 있을까요? 🤔

2023-10-18 00:52 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +class ContactCreationViewController: UIViewController {
앗! 없습니다 🥹 final 붙이도록 하겠습니다.

2023-10-18 00:57 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    }()
넵 명확한 네이밍으로 바꾸겠습니다. 🙂

2023-10-18 01:02 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        self.view.backgroundColor = .systemBackground
안써도 상관없다고 느끼지만, 혹시나도 다른곳에(?) 붙을수 있기에 자기자신에 사용되라는 명시성을 위해 self 프로퍼티를 사용하였습니다 😌

2023-10-18 01:24 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        phoneNumStack.field.keyboardType = .phonePad
네, 함수명을 수정하여 가독성을 높이겠습니다 😀

2023-10-18 01:26 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        addNavigationBar()
네 수정 하겠습니다.

2023-10-18 01:29 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        let saveButton = UIBarButtonItem(title: "Save", style: .plain, target: self, action: #selector(didTapSaveButton))
.done로 변경하면 글씨체가 Bold가 되네요! 저장하는 버튼이니깐 강조해주면 좋을것 같습니다. 😃

2023-10-18 02:38 UTC, janine-kang commented on ContactManager/ContactManager.xcodeproj/project.pbxproj
> +			path = Enums;
아하 폴더 구조를 잡을 땐 기능별로 나눠주는게 더 좋군요! 각각 Error 폴더와 Model 폴더로 이전했습니다. 
사실 ValidateType의 경우 VC에서 주로 사용하게 되는데, Controller 폴더와는 적합하지 않다는 생각이 들어 Model 폴더에 넣어두었습니다!

2023-10-18 02:40 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    public weak var delegate: ContactCreationVCDelegate?
public으로 설정한 이유는, 타 객체(VC)에서 해당 delegate 프로퍼티에 접근하여 값을 set해주어야 하기 때문입니다!
이 과정에서 서로 강한 참조를 일으킬 가능성이 있기 때문에 weak var를 사용하여 참조 사이클이 일어나는 것을 방지했습니다. 
또한 강한 참조가 일어나지 않더라도 습관적으로 weak var를 선언하는게 좋다고도 하더라고요 🙂 그 이유에서라도 weak var를 사용했습니다

2023-10-18 02:47 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        navbar.layer.shadowColor = UIColor.clear.cgColor
여기는 네비게이션 바의 색상과 아래쪽에 나타나는 선을 안보이게 하는 부분입니다!
찾다보니 이 방법 또는 이와 비슷한 방법들만 나와서 넣었는데, 혹시 더 손쉬운 방법이 있다면 알려주세요 😭

2023-10-18 02:49 UTC, janine-kang commented on ContactManager/ContactManager/Models/ContactManager.swift
> +}
미처 삭제하지 못했습니다 😭 해당 부분 삭제했습니다!

2023-10-18 02:51 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +            break
default 케이스를 제외하고 나머지는 break문이 없어도 정상적으로 작동하네요! 고쳐놓았습니다 😊

2023-10-18 02:52 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    private func checkValidate(text: String, type: ValidateType) throws -> Void {
없습니다 🫠 빠르게 치다 보니 명시해뒀는데, 컨벤션에 어긋나는 것 같네요! 해당 부분 변경했습니닷

2023-10-18 02:53 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +extension ContactCreationViewController {
오! 새로 알게 된 사실이네욥 👍🏻 해당 부분 반영했습니다!

2023-10-18 02:54 UTC, janine-kang commented on ContactManager/ContactManager/Extensions/String.swift
> +        case compress
trimming은 앞뒤 공백 제거처럼 느껴져서 가장 압축적으로 쓸 수 있는 단어를 고민하다보니, 오히려 뜻이 명료하지 않았던 것 같네요!
이 부분 변경했습니다

2023-10-18 02:55 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +
넵 수정했습니다! 급하게 많은걸 처리하려하다보니 여기저기 컨벤션이 맞지 않는 부분이 많네요 😭 다음부턴 좀 더 신경쓰도록 하겠습니다

2023-10-18 03:44 UTC, janine-kang commented on ContactManager/ContactManager/Extensions/String.swift
> +        let offset = sanitizedTarget.hasPrefix("02") ? 1 : 2
앗 02에 대해서만 처리했는데 잘못 알았었네요 😭 수정했습니다!

2023-10-18 03:46 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +}
이 프로토콜도 너무 명료하지 않은 것 같아, `ContactUpdatable`로 네이밍 변경했습니다!

2023-10-18 03:59 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +}
tableView를 전부 업데이트하는 reloadData()를 사용하는 것 보다 추가된 cell만 업데이트하는 insertRows()를 사용하는 것이 메모리를 관리하는 측면에서 더 좋은 성능을 보일거라 사용하였습니다.

2023-10-18 04:01 UTC, janine-kang commented on ContactManager/ContactManager/Views/ContactCreationStackView.swift
> +class ContactCreationStackView: UIStackView {
final 키워드 넣었습니다 😭

2023-10-18 07:46 UTC, comdori-wj commented
## 궁금증 정리
`extension을 통해서 여러 파일에서 공통적으로 사용되는 부분들을 선언하고 사용할 수 있습니다.
말씀주신 부분은 extension을 통한 내용보다는 그냥 각각의 프로퍼티들에 대한 부분들을 어떻게 그룹핑하는지에 대한 이야기인것 같아요!`

`정답은 없지만 보는 관점에 따라서 label에 대한 것은 label끼리 묶는 방법도 있고,
아니면 하나의 property에 관련된 것들끼리 묶는 경우도 있을 것 같아요.
다만 지금 들어주신 예시라면 저라면 전자의 방법을 사용하는 것이 좀 더 가독성이 좋아보이긴합니다!
두 분이 가독성 좋은 방향으로 convention을 정하시면 될 것 같아요!`

이 부분에 대해서 저도 작성하면서 다른 질문인데 같이 질문 해버렸네요 😵‍💫 😵‍💫

extension은 `기존의 클래스, 구조체, 열거형, 또는 프로토콜 타입에 새로운 기능 확장` 또는 기능 분리로 알고 있으면 되고,
프로퍼티 그룹핑은 팀내에서 정한 컨벤션을 따라 가면 되는것으로 정리하겠습니다. 😊

그리고 연락처 추가 화면 이동은 네비게이션 컨트롤을 통해서 `push`-`pop`할 필요가 없으니 모달 방식으로 이동하면 되는것으로 알겠습니다.

2023-10-18 07:55 UTC, janine-kang commented
> > 3. 마지막으로 view 로직분리에 대해서 고민이 있습니다.
> 
> UI를 코드로 작성하다 보니, 유저와 인터렉션하는 View 자체의 로직과 View Controller의 로직이 섞이면서 파일 크기가 방대해졌습니다 😓 때문에 View를 따로 분리하려고 시도했는데, delegate 등 유저의 액션을 받아 처리하는 VC로직이 View와 분리하여 존재시키기 어렵다고 생각하여 UIStackView만을 분리하게 되었습니다. 이런 경우, 보통 View를 어떻게 분리해야 전체적인 코드와 구조가 깔끔해질 수 있을까요?
> 
> 공통적으로 사용되는 화면이라면 customView를 생성하고, 내부에서 발생하는 action에 대한 처리를 delegate pattern을 통해서 처리할수도 있을 것 같네요. 다만 지금 스펙에서는 따로 view로 분리할만한 것이 크게 보이지는 않는 것 같은데 말씀하시는 정확히 어떤 부분인지 말씀해주실 수 있을까요?

이부분은 UIView를 코드로 처음 짜다보니, 파일 자체의 라인이 너무 길어져서 가독성과 직관성이 떨어질 수 있다고 생각하게 되었고, 단순히 View와 VC를 분리할 수 있지 않을까라는 고민에서 나왔던 궁금증이었습니다! 이런 경우 재사용성 자체에는 의의가 없기 때문에 나누지 않고 이대로 진행하나보네요 👀 그렇다면 View가 VC로부터 분리되는 순간은, 주로 View의 재사용성이 보장될 때 인가요?

2023-10-18 15:08 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +    public weak var delegate: ContactCreationVCDelegate?
타객체에서 접근할 수 있는 접근제어는 public 외에도 다른 것들이 있는데 접근제어에 대해서도 한 번 공부해보시면 좋을 것 같아요! 
weak var에 대해서는 잘 알고 계시는군요 👍🏻👏

2023-10-18 15:09 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        self.view.backgroundColor = .systemBackground
전반적인 코드내에서 self를 사용할때도 있고, 안 할 때도 있는 것 같아서 두 분께서 convention을 만드시면 좋을 것 같네요. 
예를 들면 self를 꼭 붙여야만 하는 상황이 아니고서는 self를 붙이지지 않는 것이 convention이 될 수도 있겠네요 🙏🏻

2023-10-18 15:23 UTC, jryoun1 approved these changes
>  마지막으로 view 로직분리에 대해서 고민이 있습니다.
UI를 코드로 작성하다 보니, 유저와 인터렉션하는 View 자체의 로직과 View Controller의 로직이 섞이면서 파일 크기가 방대해졌습니다 😓 때문에 View를 따로 분리하려고 시도했는데, delegate 등 유저의 액션을 받아 처리하는 VC로직이 View와 분리하여 존재시키기 어렵다고 생각하여 UIStackView만을 분리하게 되었습니다. 이런 경우, 보통 View를 어떻게 분리해야 전체적인 코드와 구조가 깔끔해질 수 있을까요?

공통적으로 사용되는 화면이라면 customView를 생성하고, 내부에서 발생하는 action에 대한 처리를 delegate pattern을 통해서 처리할수도 있을 것 같네요. 다만 지금 스펙에서는 따로 view로 분리할만한 것이 크게 보이지는 않는 것 같은데 말씀하시는 정확히 어떤 부분인지 말씀해주실 수 있을까요?

> 이부분은 UIView를 코드로 처음 짜다보니, 파일 자체의 라인이 너무 길어져서 가독성과 직관성이 떨어질 수 있다고 생각하게 되었고, 단순히 View와 VC를 분리할 수 있지 않을까라는 고민에서 나왔던 궁금증이었습니다! 이런 경우 재사용성 자체에는 의의가 없기 때문에 나누지 않고 이대로 진행하나보네요 👀 그렇다면 View가 VC로부터 분리되는 순간은, 주로 View의 재사용성이 보장될 때 인가요?

말씀주신것처럼 대부분은 view가 재사용이 가능하다고 판단할 때 분리를 하게 되는 것 같네요. 
다만 꼭 재사용이 되지 않더라도 말씀주신 것처럼 파일이 너무 길어질까봐 따로 분리할 수도 있을 것 같긴합니다!

------

step2 수정해주신 부분들 확인했습니다! 
잘 수정해주셨군요 👍🏻👏 
이번 스텝도 여기서 머지해도 될 것 같아서 merge하겠습니다! 
고생하셨고, step3도 화이팅입니다!!

2023-10-18 15:23 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        ])
이 부분은 layout과 관련된 코드라서 layout쪽 함수에 들어가도 좋을 것 같네요!

2023-10-18 15:23 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        view.backgroundColor = .systemBackground
이 부분도 setupAttributes에 포함될 수 있지 않을까요?

2023-10-18 15:29 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        navbar.layer.shadowColor = UIColor.clear.cgColor
아하! backgroundColor와 shadow를 없애기 위함이였군요!
작성해주신 방법대로 진행해도 될 것 같습니다.

또 다른 방법은 아래처럼 작성해도 될 것 같네요. 
barTintColor만 설정해도 백그라운드 색상을 변경할 수 있을 것 같네요. [문서](https://developer.apple.com/documentation/uikit/uinavigationbar/legacy_customizations)

<img width="500" alt="image" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/45090197/85b25254-c9bb-4f60-a986-ad28fef08326">


```Swift
    private func addNavigationBar() {
        let navbar = UINavigationBar(frame: CGRect(x: 0, y: 0, width: view.frame.width, height: 50))
        navbar.barTintColor = .white
        navbar.shouldRemoveShadow(true)
        // ...
}

extension UINavigationBar {
    func shouldRemoveShadow(_ value: Bool) -> Void {
        if value {
            self.setValue(true, forKey: "hidesShadow")
        } else {
            self.setValue(false, forKey: "hidesShadow")
        }
    }
}
```

2023-10-18 15:31 UTC, merged

2023-10-19 00:42 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        view.backgroundColor = .systemBackground
네 마져 못봤었네요 🥲 수정하겠습니다.

2023-10-19 00:47 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactCreationViewController.swift
> +        ])
네 수정하겠습니다 🙂