연락처 관리 앱 [STEP2] Dora, JaeHyeok
tasty-code/ios-contact-manager-ui pull request #38
Opened 2023-10-16 08:19 UTC by KSK9820

리뷰어: @zdodev
버드: @KSK9820, @SimJaeHyeok

## 소대, 안녕하세요! [STEP 2] PR 드립니다🙌🏻

## Summary ⛳️

### 구현 기능 및 상세

- UML

    ![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/68066104/6c4dbd7e-6b19-4a7c-a6c8-28f47d25f566)
    
- 연락처 추가 화면에 진입합니다.
- 오토 레이아웃과 스택뷰를 활용하여 화면을 레이아웃합니다.
- 각 필드에 맞는 키보드 종류를 지정합니다.
- 취소 버튼을 선택하면 정말 취소한 것인지 묻습니다.
- 저장 버튼을 선택하면 입력한 정보가 올바르게 입력되었는지 확인합니다.
    - 이름 - 띄어쓰기 제거
    - 나이 - 999이하의 숫자
    - 연락처 - 9자리 이상의 숫자와 하이픈 두 개를 포함
- 모든 정보가 올바르게 입력되었다면 저장 버튼을 선택했을 때 이전 화면으로 돌아가고, 추가한 연락처가 연락처 리스트에 추가됩니다.

---

### 고민했던 점 👀

- 하이픈을 넣는 케이스 분류를 하였습니다.
    - 010으로 시작하는 핸드폰 번호 - 13자리
    - 02로 시작하는 서울 지역번호 - 11자리
    - 그외의 번호(031, 051 등) - 12자리 / 13자리
- `@objc func didChangePhoneNumberTextField(_ send: Any?)` 함수는 input의 변화를 감지하여 동작합니다. 머물러 있는 함수가 아니라, 상태가 변화할 때만 동작하는 함수이다 보니 현재 UITextField의 text를 지우는 상황인지 / 값을 추가하여 입력하고 있는 상황인지를 구분할 수 없습니다.
- `하이픈` 을 넣고 삭제하는 상황을 함수 스스로가 인지할 수 없어서 외부의 전역변수 `isHyphen`을 사용하였습니다.
- 이러한 경우 외부에 너무 의존을 하고 있는 것이 아닌지, 또는 너무 복잡하게 분류해서 코드를 짠 것이 아닌지 고민입니다.

---

### 질문 사항

- 2차원 배열로 데이터 타입을 선정하여, 1차원 배열은 이름의 첫 글짜를 따서 인덱스로 사용하고자 했습니다. 이때 의도하고자 한 바는 새로운 연락처를 추가할 때 해당 인덱스의 2차원 배열에서만 값을 밀고 당겨 오버헤드를 줄이고자 하였습니다. 
하지만 2차원 배열들은(array[0][1]과 array[1][0]) 연속된 메모리에 저장되기 때문에 의도했던 오버헤드를 줄일 수 없고 단순히 2차원 배열은 색인의 용도로만 남게 되었습니다.
    - 이정도의 오버헤드는 괜찮은 수준일까요?
    - 보통 2차원 배열은 어떤 경우에 사용하나요?
    - 오버헤드를 줄일 수 있는 방법은 다른 타입을 사용해야하나요?

- weak var delegate의 사용
    
    ```swift
      protocol SendDelegate: class {
          func sendContact(newContact: Contact)
      }
    
      protocol SendDelegate: AnyObject {
          func sendContact(newContact: Contact)
      }
    
    ```
    
    - 프로토콜이 어디에서 사용되는지가 명시되지 않으면 reference count 관리를 위해 사용되는 weak 키워드를 사용할 수가 없습니다. 그렇기 때문에 weak 키워드를 사용하기 위해 class만 채택할 수 있도록 프로토콜에 명시를 해두었습니다.
    하지만 컴파일러는 AnyObject를 사용을 권장하고 있습니다. AnyObject를 따르도록 한다면 struct에서도 해당 프로토콜을 채택할 수 있는데 현재는 struct를 사용하지 않고 있습니다. 지금 단계에서는 class만 사용하고 있기 때문에 class만 명시해두면 안 될까요?
    - AnyObject를 따르도록 해도, 결국 클래스에서만 사용할 수 있는 프로토콜이됩니다. 이런 경우 왜 class라고 쓰지 않고 AnyObject를 쓰라고 권장하는지 알고싶습니다.
    - 추가로 struct와 class 모두에서 사용하고자 하는 프로토콜인 경우에도 weak를 사용하려면 프로토콜을 분리해줘야 하나요?
<br/>

2023-10-16 16:03 UTC, zdodev requested changes
안녕하세요. @KSK9820 , @SimJaeHyeok !

두 번째 스텝 잘 구현해주셨습니다~
연락처 입력 및 추가를 잘 구현해보셨네요.👍

먼저 질문에 대한 제 생각을 얘기해보면

1. 2차원 배열에 대한 질문

- 현재 구현단계에서는 2차원 배열이 굳이 필요할까 싶은 생각이 들었습니다. 색인 용도로만 남게된 경우, 오히려 가독성이 떨어져보일 것 같았습니다.
- 2차원 배열의 경우 테이블이나 행렬과 같은 데이터를 표현하는 데 많이 사용합니다. 꼭 이런 용도가 아니더라도 2차원 구조(자료구조)로 표현할 수 있는 경우 유용하게 사용할 수 있습니다.
- 오버헤드를 줄이기 위해서는 어떤 타입(자료구조)를 사용하는 것이 좋을까요? 이 부분은 배열보다 (연락처를 관리하기) 더욱 유용한 타입이 있을 지 고민해보면 좋을 것 같습니다!


2. weak var delegate 의 사용

- 질문을 보면 Swift 메모리 참조와 reference counting 에 대한 이해가 조금 더 필요한 것 같습니다!
- Swift 에서 `class` 키워드와 `AnyObject` 키워드의 정의를 확인해보면 좋을 것 같습니다.
- `AnyOject` 를 채택한 프로토콜을 `struct` 타입에서 채택할 수 있을까요?
- Delegate 패턴에서 `weak` 을 사용할 때와 사용하지 않을 때의 차이점이 무엇일까요?
[참고 문서](https://github.com/apple/swift-evolution/blob/main/proposals/0156-subclass-existentials.md#class-and-anyobject)

이외에도 여러 궁금증을 남겨보았습니다~
같이 고민해보면 좋을 것 같습니다😄

2023-10-16 16:03 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
>      var addressBook: AddressBook  = AddressBook()
공백이 두 번 삽입된 것 같습니다!

2023-10-16 16:03 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +extension ViewController: UITableViewDataSource, UITableViewDelegate {
개인적으로 하나의 `extension` 에 하나의 프로토콜을 채택하는 편입니다. 참고만 해주세요🙂

2023-10-16 16:03 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
>          return addressBook.getSectionSize()
`return` 키워드를 생략하는 형태를 사용하기도 합니다. 참고해보면 좋을 것 같습니다!🙂

2023-10-16 16:03 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +        guard let vc = storyboard?.instantiateViewController(withIdentifier: "NewContactViewController") as? NewContactViewController else { return }
지금은 뷰 컨트롤러가 하나라서 괜찮을 수 있지만, 생략형(`vc`)보다는 전체 이름을 지어주는 습관을 들이는 건 어떨까요?

2023-10-16 16:03 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/NewContactViewController.swift
> +    @objc func didChangePhoneNumberTextField(_ send: Any?) {
요구사항의 내용보다 많이 복잡하게 구현된 것 같습니다. 연락처 숫자 개수와 포맷만 고려해보는 것은 어떨까요?
현재 9자리 입력한 경우, 요구사항의 포맷과 다른 결과가 출력됩니다. 이를 수정해볼 수 있을까요?
`UITextFieldDelegate` 를 활용해보는 것은 어떨까요? 고민한 내용중에 해결할 수 있는 부분이 있지 않을까 싶어요!

2023-10-17 00:22 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
>      var addressBook: AddressBook  = AddressBook()
확인하고 수정하였습니다!

2023-10-17 00:27 UTC, SimJaeHyeok commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +        guard let vc = storyboard?.instantiateViewController(withIdentifier: "NewContactViewController") as? NewContactViewController else { return }
확인하고 수정하였습니다. 축약형이 아닌 전체 이름으로 작성하는 습관을 가지도록 하겠습니다

2023-10-17 00:29 UTC, KSK9820 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
> +extension ViewController: UITableViewDataSource, UITableViewDelegate {
저번에 수정한 줄 알았는데, 수정이 되지 않았네요. 하나의 `extension` 에 하나의 프로토콜을 채택하고, 당장 사용하지 않는 UItableViewDelegate는 삭제하였습니다.

2023-10-17 00:38 UTC, KSK9820 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController.swift
>          return addressBook.getSectionSize()
함수가 하나의 표현식만을 포함하고 있다면 return 키워드를 생략할 수 있다는 것을 알게 되었습니다.😁

2023-10-17 05:33 UTC, KSK9820 commented on ios-contact-manager-ui/ios-contact-manager-ui/NewContactViewController.swift
> +    @objc func didChangePhoneNumberTextField(_ send: Any?) {
3가지 케이스만으로 포멧을 분류하였습니다.
- 9자리: 12-345-6789
- 10자리: 12-3456-7890
- 11자리: 123-4567-8901

또한 UITextFieldDelegate를 사용하는데 해결되지 않아 여쭤보고 싶은 것이 있습니다.
- UITextFieldDelegate의 함수 중에서 `func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool`해당 함수에서 하이픈을 넣는 것을 시도하였습니다.
- 이때 phoneNumberTextField의 text의 count를 세어서 해당 케이스마다 하이픈을 넣으려고 하였으나, count값이 한 박자 느리게 반응하는 현상 때문에 실시간으로 업데이트되는 range.location을 사용하였습니다.
- count값이 한 박자 느리게 반응하는 것을 shouldChangeCharactersIn 때문이라고 추측하였는데, 이것이 맞는지 그리고 박자 맞게 동작하는 다른 딜리게이트 함수가 있을까요?

2023-10-17 13:50 UTC, zdodev commented on ios-contact-manager-ui/ios-contact-manager-ui/NewContactViewController.swift
> +    @objc func didChangePhoneNumberTextField(_ send: Any?) {
해당 delegate 메서드에서 박자가 느린 것은 `shouldChangeCharactersIn` 때문이라기 보다는 입력한 텍스트 변경 여부를 판단하는 메서드라서 지금과 같이 동작하는 것으로 보입니다. 해당 메서드의 동작 원리를 조금 더 파악해보는 것은 어떨까요?🙂
박자에 맞는 메서드는 저도 아직 못본 것 같습니다😅

2023-10-18 01:22 UTC, zdodev approved these changes
안녕하세요. @KSK9820 , @SimJaeHyeok 

기능 동작에 대해서 잘 확인했습니다!
코드도 적절하게 개선도 잘 해주셨습니다!

이번 스텝은 여기서 마무리하도록 하겠습니다.
Step 2 진행하시느라 고생하셨습니다.🎉

2023-10-18 01:22 UTC, merged