연락처 관리 앱 [STEP 3] 뉴준성, 밤삭
tasty-code/ios-contact-manager-ui pull request #39
Opened 2023-10-17 04:32 UTC by bamsak

# 연락처 관리 프로젝트

## 리뷰어
@protocorn93

## 파일구조
- ios-contact-manager-ui
  - Utility
     - ContactValidityChecker 
  + Controller
     - ContactListViewController.swift 
  + Model
     - Contact.swift
        - Contact
        - ContactManager
  - Exception
     - ContactEception
  + View
     + ContactCell

## 새로 시도했던 점
### 다이나믹 타입 적용
스토리보드에서 각 라벨의 폰트 사이즈를 body로 하여 손쉬운 사용의 폰트 사이즈의 설정 값마다 앱 내의 폰트 사이즈가 달라지게 했습니다.
<p align="center">
    <img src="https://hackmd.io/_uploads/rJGJoYjW6.png" align="center" width="32%">
  <img src="https://hackmd.io/_uploads/SyGkoFjb6.png" align="center" width="32%">
  <img src="https://hackmd.io/_uploads/ByZJiKi-a.png" align="center" width="32%">
</p>

### 검색 기능 추가
검색 바가 확성화 되어 있을 때만, 자신이 찾고 싶은 연락처가 보이게끔 만들었습니다.

```swift
private var filteredContacts = [Contact]()
private var isActive: Bool {
    navigationItem.searchController?.isActive ?? false
}
```

```swift
private func makeSearchBar() -> UISearchController {
    let searchController = UISearchController(searchResultsController: nil)
    searchController.obscuresBackgroundDuringPresentation = false
    searchController.searchResultsUpdater = self
    return searchController
}
```

```swift
func updateSearchResults(for searchController: UISearchController) {
    if let text = searchController.searchBar.text{
        filteredContacts = contactManager.contacts.filter { $0.name.localizedCaseInsensitiveContains(text) }
        tableView.reloadData()
    }
}
```

```swift
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return isActive ? filteredContacts.count : contactManager.contacts.count
}

func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let id = "ContactCell"
    let contact = isActive ? filteredContacts[indexPath.row] : contactManager.contacts[indexPath.row]
    
    guard let cell = tableView.dequeueReusableCell(withIdentifier: id, for: indexPath) as? ContactCell else {
        let cell = ContactCell(style: .subtitle, reuseIdentifier: id)
        cell.configureCell(contact)
        return cell
    }
    cell.configureCell(contact)
    return cell
}
```

2023-10-18 00:32 UTC, protocorn93 requested changes
검색 결과까지 훌륭하게 적용해주셨네요! 애플 UIKit의 다양한 컴포넌트를 활용해보는 것은 이후에 많은 도움이 될 것 같아요. 

피드백만 확인 부탁드릴게요

2023-10-18 00:32 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    private var filteredContacts = [Contact]()
이렇게 되면 같은 `홍길동(010-7142-4682)` 라는 데이터가 `filteredContacts` 와 `contactManager` 두 곳에 모두 위치하게 되는데요. 이렇게 되면 개발자의 실수로 데이터 정합성에 문제가 발생할 수 있어요. 그리고 그 원인을 찾기 힘들겠죠! 

여기선 SSOT 라는 개념이 필요한데 데이터의 원천은 한 곳에 위치해야한다는 개념이에요. 이후에는 이런 부분도 신경써주시면 좋을 것 같아요.

2023-10-18 00:32 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        let searchController = UISearchController(searchResultsController: nil)
하나의 테이블 뷰로 검색 결과와 일반 연락처 목록 둘 모두룰 표현하기 보단 `searchResultsController`를 활용해보는 것은 어떨까요

2023-10-18 00:32 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactCell.swift
> +        phoneNumberLabel.text = "연락처: \(contact.phoneNumber)"
이후에는 Cell 이 직접 포맷팅(`age` > `"나이: \(age)"`)을 하는 것이 아니라 포맷팅된 결과만 셀에 전달해주고 셀은 단순히 할당만 해주는 것이 좋을 것 같아요. 이를 위해선 Presentation layer를 담당하는 별도 객체가 있어야겠죠!

2023-10-18 00:32 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactCell.swift
> +    private let imageName = ["person.fill", "paperplane.fill", "trash.fill", "graduationcap.fill"]
이미지도 마찬가지에요. 외부에서 전달해주는 것이 바람직해요.

2023-10-19 07:41 UTC, newJunsung commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    private var filteredContacts = [Contact]()
Single Source Of Truth에 대하여 찾아보니, 이 개념이 contacts와 테이블뷰 셀들과의 정합성(ex. 삭제 시, 셀과 연락처 간의 개수 차이)로 인해 필요하다는 것도 알게 되었습니다. 이를 해결하기 위해 DiffableDatasource와 Snapshot을 사용하는 것 같던데 맞나요?

2023-10-19 13:27 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    private var filteredContacts = [Contact]()
네네 하나의 방법이 될 수 있죠. 결국엔 모델도 계층 분리가 필요해요. Contact와 같은 엔티티 계층과 뷰모델 계층의 분리가 필요하죠

2023-10-19 13:30 UTC, protocorn93 reviewed
수정 사항 잘 확인했습니다!

2023-10-19 13:30 UTC, protocorn93 commented on ios-contact-manager-ui/ios-contact-manager-ui/Extensions/UITableViewCell+Extension.swift
> +    static let contactCell = "ContactCell"
좀 더 범용적으로 사용될 수 있눈 reuse identifier를 위한 extension을 찾아보시면 더 좋을 것 같아요. 다른 커스텀 셀이 추가 되어도 별도로 정의하지 않아도 되는 방향이죠!

2023-10-19 13:46 UTC, merged