연락처 관리 앱 [Step3] 쫑, 록스
tasty-code/ios-contact-manager-ui pull request #42
Opened 2023-10-19 07:52 UTC by shlim0

리뷰어
[@forestjae](https://github.com/forestjae)

팀원
[@KimRoks](https://github.com/KimRoks), [@shlim0](https://github.com/shlim0)

--- 

# 프로젝트 구조

<img width="344" alt="111" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/b421b0fc-ef38-48c4-b404-9628dcf430f3">

- 아래는 추가된 파일입니다.
- Utilities
    - `Validation`: `struct Validation`에 연락처 정보를 검사하는 함수를 둔 파일입니다.
- Views
    - `CustomTableViewCell`: 커스텀 셀입니다.
- ContactManagerTests
    - `ContactManagerTests`: `Validation`을 테스트하는 파일입니다.

# 변경한 점

- regex 유효성에 대한 유닛 테스트를 추가했습니다.
    - 영문자 및 한글 입력이 가능합니다.
    - 띄어쓰기가 가능합니다.
    - 숫자 및 특수문자가 가능합니다.

        <img width="347" alt="222" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/c761e4eb-e67a-4d88-abc4-f4f44cedfb8f">

- Custom Table Cell을 구현했습니다.
    - 추후 `UIImagePicker`를 활용한 프로필 사진 변경 가능하도록 CustomCell 적용했습니다.
        
        <img width="338" alt="333" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/54ec0bb8-6b05-4876-9c97-d9ea35d21f0c">
        

- 고차함수를 활용해 `searchBar()`를 구현했습니다.
    
    ```swift
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
      filteredContact = contactDTOs.filter({
          $0.name.localizedCaseInsensitiveContains(searchText) ||
          $0.phoneNumber.localizedCaseInsensitiveContains(searchText)
      })
      
      tableView.reloadData()
    }
    ```
    
    https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/3ad8f7f3-dabd-4c57-8d47-63bcd7580335

- 스와이프하여 삭제를 구현했습니다.
    
    https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/28ccf890-86f3-40db-aa15-3b5cccb61335

- Dynamic Type을 적용했습니다.
    <img width="338" alt="333" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/74d0c868-d155-4025-b356-3e97e21a44c6">

# 고민한 점

## 트러블 슈팅

- 서치바 사용 중 밀어서 삭제 적용이 안됐습니다. 이를 해결 하였으나, 애니메이션 효과가 적용되지 않는 것을 깨달았습니다. `deleteRows()`를 통해 해결했으나, 마지막 셀을 삭제할 때 `reloadData()`를 사용하지 않으면 런타임 에러가 납니다. 이에 대한 해결책을 찾지 못했습니다.
    
    ```swift
    if !filteredContact.isEmpty {
        tableView.deleteRows(at: [indexPath], with: .fade)
    } else {
        searchBar.text = ""
        tableView.reloadData()
    }
    ```
    https://github.com/tasty-code/ios-contact-manager-ui/assets/46235301/2f81b1dd-202d-463a-a9d9-6264e43c6575

# 궁금한 점

## 1. STEP BONUS 토의

- 시간상, STEP 3까지만 진행하였지만 STEP BONUS에 관한 궁금중이 있어 이에 대한 숲재의 의견이 궁금합니다.
1. Edit VC를 만든다? (X)
    - 데이터를 건드리는 로직이 같은데 굳이 따로 둘 이유가 없다고 판단했습니다.
    - 재사용성이 떨어진다고 생각했습니다.
2. 하나의 VC에서 한다? (X)
    - 나중에 프로젝트의 규모가 커지면 스파게티 코드가 될 것 같다고 판단했습니다.
    하나의 기능만 갖지 않게 되기 때문입니다.
    - VC마다 파일로 두는게 유지보수 측면에서 더 좋지 않다고 생각했습니다.
3. [1번과 2번의 절충안] 상속을 한다? (X)
    - SOLID 원칙에 의거하면, 상속은 의존성을 해치기 때문에 제외했습니다.
4. 프로토콜에 공통되는 기능을 두고 각 VC에서 다른 기능을 둔다? (O)
    - 프로토콜을 채택하는 클래스마다 매번 구현을 해야하는 것이 cost가 필요하나, VC별로 구별되고 재사용성도 괜찮다고 판단했습니다.

## 2. Unit Test 단위

- 이번 스텝에서 연락처 추가시 데이터가 유효한지에 대해 Unit Test를 적용하였습니다. 데이터 로직에 대한 테스트를 진행하였으나, View에 대한 테스트는 직접 하였는데

## 3. 현재 구조에 관한 의견

- 저희가 작성한 코드에서 리팩토링을 할 수 있는 부분을 알고 싶습니다. 이번 프로젝트를 진행할 때, 전반적인 구조는 어떻게 잡고 시작하는 편이 좋을까요? 사소한 의견이라도 좋습니다.

## 4. PR 스타일

- 저희 새싹 iOS 개발자 클래스 내에서도 팀마다 PR 스타일이 다릅니다. 숲재께서 PR을 작성할 때 꼭 넣는 내용이 있을까요?

2023-10-19 12:22 UTC, forestjae commented
마지막까지 고생 많으셨어요, 동작 이상 없는 것 확인했고 잘 작성해주셨습니다.

> # 고민한 점
> ## 트러블 슈팅
> * 서치바 사용 중 밀어서 삭제 적용이 안됐습니다. 이를 해결 하였으나, 애니메이션 효과가 적용되지 않는 것을 깨달았습니다. `deleteRows()`를 통해 해결했으나, 마지막 셀을 삭제할 때 `reloadData()`를 사용하지 않으면 런타임 에러가 납니다. 이에 대한 해결책을 찾지 못했습니다.
>   ```swift
>   if !filteredContact.isEmpty {
>       tableView.deleteRows(at: [indexPath], with: .fade)
>   } else {
>       searchBar.text = ""
>       tableView.reloadData()
>   }
>   ```

delete나 insertRows 메서드를 사용하실 땐 많은 주의를 기울이셔야 해요. 테이블 뷰가 가지고 있는 데이터소스의 싱크가 맞지 않아 발생하는 문제에요. insertRows나 deleteRows를 호출하면, numberOfRowsInSection가 호출되게 되는데 현재 구조로는 이미 삭제한 순간 if 문의 첫번째 플로우를 타지 않기 때문에 발생하는 문제입니다.

> # 궁금한 점
> ## 1. STEP BONUS 토의
> * 시간상, STEP 3까지만 진행하였지만 STEP BONUS에 관한 궁금중이 있어 이에 대한 숲재의 의견이 궁금합니다.
> 
> 1. Edit VC를 만든다? (X)
>    
>    * 데이터를 건드리는 로직이 같은데 굳이 따로 둘 이유가 없다고 판단했습니다.
>    * 재사용성이 떨어진다고 생각했습니다.

👍 

> 2. 하나의 VC에서 한다? (X)
>    
>    * 나중에 프로젝트의 규모가 커지면 스파게티 코드가 될 것 같다고 판단했습니다.
>      하나의 기능만 갖지 않게 되기 때문입니다.
>    * VC마다 파일로 두는게 유지보수 측면에서 더 좋지 않다고 생각했습니다.

프로젝트 규모가 커지더라도, 내부의 다른 뷰 컴포넌트나 로직들을 다른 객체로 분리하게 되면 큰 문제는 되지 않을 것 같아요.

> 3. [1번과 2번의 절충안] 상속을 한다? (X)
>    
>    * SOLID 원칙에 의거하면, 상속은 의존성을 해치기 때문에 제외했습니다.

상속이 의존성을 해친다는게 어떤 의미일까요?

> 4. 프로토콜에 공통되는 기능을 두고 각 VC에서 다른 기능을 둔다? (O)
>    
>    * 프로토콜을 채택하는 클래스마다 매번 구현을 해야하는 것이 cost가 필요하나, VC별로 구별되고 재사용성도 괜찮다고 판단했습니다.
> 

좋은 방법이네요! 

> ## 2. Unit Test 단위
> * 이번 스텝에서 연락처 추가시 데이터가 유효한지에 대해 Unit Test를 적용하였습니다. 데이터 로직에 대한 테스트를 진행하였으나, View에 대한 테스트는 직접 하였는데
> 

질문이 짤렸습니다 ㅜ.ㅜ

> ## 3. 현재 구조에 관한 의견
> * 저희가 작성한 코드에서 리팩토링을 할 수 있는 부분을 알고 싶습니다. 이번 프로젝트를 진행할 때, 전반적인 구조는 어떻게 잡고 시작하는 편이 좋을까요? 사소한 의견이라도 좋습니다.
> 

아직은 프로젝트의 구조가 그렇게 복잡하지 않고, 잘 해주셨기 때문에 구조에 대해서 조언드릴 만한 내용은 없을 것 같아요.
아직은 과정 초기이기 때문에, 전체적인 구조 보다는 하나의 객체 안에서 벌어지는 일들에 집중하는게 더 좋을 것 같아요. 
스토리 보드를 사용하지 않고 코드로만 작성해보는 리팩터링을 추천드립니다.

> ## 4. PR 스타일
> * 저희 새싹 iOS 개발자 클래스 내에서도 팀마다 PR 스타일이 다릅니다. 숲재께서 PR을 작성할 때 꼭 넣는 내용이 있을까요?
저 같은 경우는 1) 어떤작업을 했는지, 2) 고민하거나 트러블 슈팅을 한 내용, 3) 모르겠는 내용, 4) 나중에 개선하고 싶은점

이정도로 쓰는 것 같습니다.

2023-10-19 12:22 UTC, forestjae requested changes

2023-10-19 12:22 UTC, forestjae commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +    @available(iOS 16.0, *)
미니멈 타겟을 16으로 설정하는 방법도 있습니다

2023-10-19 12:22 UTC, forestjae commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +        let alertController = UIAlertController()
do 일때는 얼럿을 노출할 필요가 없는것 같은데, 위치를 옮겨도 좋을 것 같아요

2023-10-19 12:22 UTC, forestjae commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +        searchBar.placeholder = "찾을 사람을 검색하세요."
네이밍과 관련없는 일까지 수행하는 것 같아요

2023-10-19 12:22 UTC, forestjae commented on ContactManager/ContactManager/Views/CustomTableViewCell.swift
> +        nameAge.text = "\(contact.name) (\(contact.age))"
일반메서드는 override 메서드 밑에 있는게 보기 좋은 것 같습니다.

2023-10-20 01:10 UTC, KimRoks commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +        let alertController = UIAlertController()
catch시에만 알럿의 인스턴스를 생성하도록 수정하였습니다!

2023-10-20 01:13 UTC, KimRoks commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +        searchBar.placeholder = "찾을 사람을 검색하세요."
placeholder를 스토리보드에서 설정해 주었습니다
이 외에도 search bar의 옵션이 많아진다면
configureSearchBar() 등의 메서드를 작성하는 방법도 고려할 수 있을 것 같습니다!

2023-10-20 01:17 UTC, KimRoks commented on ContactManager/ContactManager/Views/CustomTableViewCell.swift
> +        nameAge.text = "\(contact.name) (\(contact.age))"
수정하였습니다!
기존에는 생명주기를 기준으로 위에 프로퍼티를 위치시키고 그 아래 메서드를 위치시켰습니다
이 또한 생명주기가 override된 메서드라 기준이 되는것일까요?
또, IBOutler이나 IBAction같은 경우 어떤식으로 위치시키는것이 보기 좋을까요?

2023-10-20 01:37 UTC, KimRoks commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +    @available(iOS 16.0, *)
<img width="502" alt="image" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/113083860/c8523a44-36b1-4e77-a3e2-373dbc63ee80">

iOS Deployment Target을 설정하는 부분을 말씀해주신게 맞을까요?

2023-10-20 04:28 UTC, shlim0 commented
>[1번과 2번의 절충안] 상속을 한다? (X)
>
>SOLID 원칙에 의거하면, 상속은 의존성을 해치기 때문에 제외했습니다.
> > 상속이 의존성을 해친다는게 어떤 의미일까요?

표현을 잘못했었네요. 상속을 하면 의존성이 강화된다는 말을 하고 싶었습니다!

2023-10-20 07:56 UTC, forestjae commented on ContactManager/ContactManager/Controllers/ContactViewController.swift
> +    @available(iOS 16.0, *)
네 맞습니다!

2023-10-20 07:58 UTC, forestjae commented on ContactManager/ContactManager/Views/CustomTableViewCell.swift
> +        nameAge.text = "\(contact.name) (\(contact.age))"
저같은 경우는 override 끼리 묶는게 보기 편한데 생명주기 메서드들이 override 다 보니까 위쪽에 위치하게 하는 편이에요
IB요소들은 최상단에 위치하게 합니다.

2023-10-20 08:01 UTC, forestjae commented
> > [1번과 2번의 절충안] 상속을 한다? (X)
> > SOLID 원칙에 의거하면, 상속은 의존성을 해치기 때문에 제외했습니다.
> > > 상속이 의존성을 해친다는게 어떤 의미일까요?
> 
> 표현을 잘못했었네요. 상속을 하면 의존성이 강화된다는 말을 하고 싶었습니다!

상속에서 SOLID를 위배하는 경우가 종종 발생하긴 하지만, 현업에서 많이 쓰는 방법이에요. 나중에 프로토콜과 상속을 사용하는데 장단점을 비교해보고 느낄 수 있는 프로젝트를 해보실 수 있을거에요!

2023-10-20 08:01 UTC, merged