[Step 3] 연락처 관리 앱 - 컴도리, 재닌
tasty-code/ios-contact-manager-ui pull request #45
Opened 2023-10-19 08:37 UTC by janine-kang

리뷰어: @jryoun1
버드: @janine-kang, @comdori-wj

제이크, 안녕하세요! 
연락처 관리 앱 STEP 3의 PR 요청드립니다 🙌🏻
마지막 PR이 되겠네요 😊 잘부탁드립니다~!

# Summary
STEP3 및 보너스 STEP 기능 전체 구현 완료

## 구현 화면
![Simulator Screen Recording - iPhone 15 Pro - 2023-10-19 at 17 35 33](https://github.com/tasty-code/ios-contact-manager-ui/assets/76927263/9c05c736-6a3a-4af7-8b1a-095933500701)

## 구현 사항
- [x] TableCell 스와이프 동작으로 연락처 삭제
- [x] 검색 기능 통해 리스트 필터링 기능 추가
- [x] TableCell Custom하여 레이아웃 추가
- [x] Dynamic Type 이용하여 접근성 대응
- [x] 기존 연락처 수정 기능 추가

## 폴더 구조
```
ContactManager
├── Controllers
│   ├── ContactModifierViewController.swift
│   └── ContactTableViewController.swift
├── Errors
│   └── InvalidError.swift
├── Extensions
│   ├── Array.swift
│   ├── String.swift
│   ├── UIStackView.swift
│   └── UIView.swift
├── Info.plist
├── Models
│   ├── ContactInfo.swift
│   ├── ContactManager.swift
│   └── ValidateType.swift
├── Resources
│   ├── AppDelegate.swift
│   ├── Assets.xcassets
│   │   ├── AccentColor.colorset
│   │   │   └── Contents.json
│   │   ├── AppIcon.appiconset
│   │   │   └── Contents.json
│   │   └── Contents.json
│   ├── Base.lproj
│   │   └── LaunchScreen.storyboard
│   ├── SceneDelegate.swift
│   └── mockData.json
└── Views
    ├── Base.lproj
    │   └── Main.storyboard
    ├── ContactModifierStackView.swift
    └── ContactTableViewCell.swift
```

## 고려한 점 
- STEP2 PR 리뷰에서 delegate 프로퍼티의 `public` 제어자에 대해 언급해주셨는데요! public과 internal의 차이점을 정확하게 알지 못해서 public을 붙였던 것 같습니다 😭 이 부분을 `internal` 로 설정할까 생각해보니, delegate 프로퍼티를 private으로 만들어도 init()을 통해 Set해줄 수 있겠더라구요! 그래서 해당 부분을 변경해두었습니다. 이 부분이 과연 괜찮을까에 대한 의문이 조금 남아있어, 제이크의 의견이 궁금합니다 🙇🏻‍♀️

## 궁금한 점
- UI를 코드로 짤 때 레이아웃 배치를 쉽게 할 수 있는 방법이 없을까요? UI를 짜고 시뮬레이터로 확인하는 빈도가 많은가요? 아니면, LLDB를 이용하여 확인하는 횟수가 더 많은가요? 현업의 바이브가 궁금합니다 👀

2023-10-20 12:40 UTC, jryoun1 requested changes
고생하셨습니다! 
step2에 이어서 바로 step3까지 잘 마무리해주셨네요. 
연락처 프로젝트를 진행하는동안 저도 컴도리와 재닌의 코드에 대한 근거를 찾으려고 하시는 모습과 공부를 열심히 하시고 작성하는 부분들을 보면서 동기부여가 되었네요 💯 👏 
방학동안 리프래쉬도 하시고 이번 주말도 잘 보내세요~

### 질문에 대한 답변
> 1. STEP2 PR 리뷰에서 delegate 프로퍼티의 public 제어자에 대해 언급해주셨는데요! public과 internal의 차이점을 정확하게 알지 못해서 public을 붙였던 것 같습니다 😭 이 부분을 internal 로 설정할까 생각해보니, delegate 프로퍼티를 private으로 만들어도 init()을 통해 Set해줄 수 있겠더라구요! 그래서 해당 부분을 변경해두었습니다. 이 부분이 과연 괜찮을까에 대한 의문이 조금 남아있어, 제이크의 의견이 궁금합니다 🙇🏻‍♀️

코멘트 남겨두었습니다. 🙏 

> 2. UI를 코드로 짤 때 레이아웃 배치를 쉽게 할 수 있는 방법이 없을까요? UI를 짜고 시뮬레이터로 확인하는 빈도가 많은가요? 아니면, LLDB를 이용하여 확인하는 횟수가 더 많은가요? 현업의 바이브가 궁금합니다 👀

현업에서는 회사에 따라서 다르겠지만, 제가 있는 곳은 코드로만 작성합니다.
이유는 storyboard, xib로 작성하게되면 코드리뷰가 어려울뿐만 아니라 여러명이 협업을 한다면 conflict이 발생할 가능성이 크고, 해결이 쉽지 않기 때문입니다!

처음이라서 익숙하지 않으실 수 있겠지만, 하다보면 언젠가는 코드로 짜는게 더 편리해지는 시점이 오긴합니다 ㅎㅎ (저도 처음에는 익숙하지 않았던 것 같네요 😂 )
물론 지금처럼 activate를 직접 호출하지 않고 [Snapkit](https://github.com/SnapKit/SnapKit)이라는 외부 라이브러리를 사용해서 훨씬 간편하게 코드로 작성하게 됩니다. 

말씀하신 부분이 코드로 작성하는 것이 어려운 것인지, 확인이 어려운지에 대해서 여쭤보신 것 같아서 현업에서도 코드로 어느정도 작성하고 시뮬이나 실기기에 연결해서 확인해봅니다. 물론 SwiftUI의 preview처럼 Xcode에서 macro를 사용해서 Swift에서도 preview를 사용할 수도 있지만 그렇게까지 하고 있지는 않네요!!
[관심있으시면 한 번 살펴보시면 좋을 것 같네요.](https://developer.apple.com/documentation/swiftui/previews-in-xcode)

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        phoneNumStack.field.text = current.phoneNum
여기서 만약 currentContact가 없다면 기존에 field의 keyboardType은 설정되지 않을 것 같은데 괜찮을까요? 🤔

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        let title = currentContact == nil ? "새 연락처" : "기존 연락처"
삼항연산자를 사용해서 깔끔하네요 👍🏻

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        }
newContact를 update하는 것은 이상한 것 같습니다! 
네이밍 변경이 필요하지 않을까요? 🙏

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +final class ContactModifierViewController: UIViewController {
modifier보다는 modify, creation보다는 create가 좀 더 자연스러운것 같습니다. 🙏🏻
`ContactModifyVC`, `ContactCreateVC`

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
>  }
이미 protocol의 네이밍에 Contact가 들어가서 아래처럼 함수들의 네이밍에는 Contact가 없어도 될 것 같은데 어떻게 생각하시나요?

```Swift
        let newContact = ContactInfo(name: name, age: ageToInt, phoneNum: phoneNum)
        if let current = currentContact {
            delegate?.update(newContact, of: current.uuid)
        } else {
            delegate?.add(newContact)
        }
```

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +    @IBOutlet weak var searchBar: UISearchBar!
외부에서 접근될 일이 있을까요?

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        self.searchBar.delegate = self
이 부분도 setupAttributes에 포함될 수 있을 것 같아요! 
또한 self에 대해서도 통일성 있게 사용하면 좋을 것 같네요 🙏

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        let content = isFiltering ? contactManager.filteredList[indexPath.row] : contactManager.contactsList[indexPath.row]
항상 배열에 접근할 때는 안전한지를 확인해보는 것이 좋을 것 같아요 🙏 
지난번에 extension으로 구현하신 safeIndex를 사용하는 습관을 들이면 좋을 것 같습니다!

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +            let uuid = contactManager.contactsList[indexPath.row].uuid
여기도 동일합니다!

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        tableView.reloadData()
add는 insertRows를 사용했었는데 여기서는 reloadData()를 호출하시는 이유가 궁금합니다 🙋‍♂️

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Models/ContactManager.swift
> +                    let phoneNum = $0.phoneNum else { return false }
indent가 안맞는것 같네요 🙏

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +            delegate?.updateContact(newContact, of: current.uuid)
기존 업데이트 로직이 새로운 contact를 만들어서 아예 해당 index에 대체시켜주고 값을 대체시켜주고 있는 것 같은데, 그렇게 하면 기존에 생성된 uuid 자체가 바뀌어 버리는데 괜찮을까요? 🤔

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
>      @IBAction func addButtonTapped(_ sender: UIButton) {
이 함수도 외부에서 접근될 일이 있을까요?

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Views/ContactTableViewCell.swift
> +    }
실제로 super만 호출하고 있는데, 이 함수를 override한 이유가 궁금합니다 🙋‍♂️

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Views/ContactTableViewCell.swift
> +    func setAttributes() {
접근제어를 신경쓰면 좋을 것 같습니다 🙏

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +    }
말씀하신 부분이 여기군요!
지금 작성해주신 것처럼 initializer를 통해서 주입할수도 있고, 외부에서 직접 접근해서 설정해줄수도 있을 것 같네요. 
만약 중간에 delegate를 변경해야할 일이 있다면 후자의 방법을 사용해야만 할 것이고, 그렇지 않다면 둘 다 상관없을 것 같네요. 🙏

2023-10-20 12:40 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        fatalError("init(coder:) has not been implemented")
fatalError가 발생하면 앱이 어떻게 될까요? 
fatalError가 아닌 다른 형태로 변경해 볼 수 있을까요 🙏

2023-10-23 02:08 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        phoneNumStack.field.text = current.phoneNum
맞습니다 🥲 해당 부분 업데이트 해두었습니다!

2023-10-23 02:10 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
>  }
아하 그러네요! contact를 명시하지 않는 편이 좀 더 깔끔할 것 같습니다! 해당 부분 반영해놓겠습니다 😃

2023-10-23 02:15 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        }
넵넵 해당 부분 `contact`로 변경했습니다!

2023-10-23 02:17 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +final class ContactModifierViewController: UIViewController {
업데이트 로직이 섞여있기 때문에, `ContactModifyVC`로 변경했습니다! 명사로만 네이밍을 고려하다 보니 부자연스러워졌던 것 같네요 🙂

2023-10-23 02:18 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +    @IBOutlet weak var searchBar: UISearchBar!
없습니다! 이 부분 반영 완료했습니다 😃

2023-10-23 02:19 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        self.searchBar.delegate = self
넵 setupAttributes로 이동했고, `self` 키워드도 명시하지 않아도 되므로 제거했습니다 🙂

2023-10-23 02:30 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        let content = isFiltering ? contactManager.filteredList[indexPath.row] : contactManager.contactsList[indexPath.row]
아하 제가 safeIndex를 제대로 사용하지 않았었네요! 이번 기회에 습관으로 들이도록 하겠습니다 🙇🏻‍♀️ 좋은 가르침 주셔서 감사합니다!
``` swift
guard let content = isFiltering && searchBar.text != "" 
           ? contactManager.filteredList[safeIndex: indexPath.row] 
           : contactManager.contactsList[safeIndex: indexPath.row] else { return cell }
        
cell.configure(content: content)
return cell
```

2023-10-23 02:31 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +            let uuid = contactManager.contactsList[indexPath.row].uuid
넵 반영하였습니다!

2023-10-23 02:33 UTC, janine-kang commented on ContactManager/ContactManager/Models/ContactManager.swift
> +                    let phoneNum = $0.phoneNum else { return false }
변경했습니다 😭

2023-10-23 02:35 UTC, janine-kang commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
>      @IBAction func addButtonTapped(_ sender: UIButton) {
private 처리 했습니다! 신경쓰지 못한 부분들이 많아서 부끄럽네요 🥹

2023-10-23 02:35 UTC, janine-kang commented on ContactManager/ContactManager/Views/ContactTableViewCell.swift
> +    func setAttributes() {
넵 🥹 해당 부분도 반영했습니다

2023-10-23 04:41 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        tableView.reloadData()
add는 새 연락처를 테이블에 새로운 row를 추가하는데, update는 새로운 추가가 아닌 같은 행의 데이터만 변경하는 것이므로 reloadData를 사용하는 게 맞아 호출하였습니다.

2023-10-23 04:49 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +            delegate?.updateContact(newContact, of: current.uuid)
기존에 생성된 UUID는 업데이트되면서 새롭게 생성된 UUID로 변경되는 것에 대해서 문제가 없다고 판단하였습니다. 어차피 사용자는 바뀐 UUID를 확인도 못할뿐더러, 변경된 UUID가 사용하더라도 중복된 이름, 연락처를 식별할 수 있기 때문입니다.

2023-10-23 07:16 UTC, comdori-wj commented on ContactManager/ContactManager/Views/ContactTableViewCell.swift
> +    }
필요없는 함수라서 제거하였습니다.

2023-10-23 07:41 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +        fatalError("init(coder:) has not been implemented")
스토리보드로 ui를 구현할 때는 required init(coder: NSCoder)를 자동으로 상속받아 굳이 서브 클래스에서 구현해 줄 필요가 없지만, 코드로 구현시에는 새로 지정 생성자를 구현해줘야 한다고 합니다. 
그래서 fatalError가 발생하면 앱이 강제로 크래쉬 나게 되어 꺼지게 됩니다. 다른 형태로 변경해보면  `super.init`로 명시하여 앱이 자동으로 꺼지지 않게 하였습니다.

2023-10-23 11:50 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        tableView.reloadData()
tableView에서는 [reloadRows](https://developer.apple.com/documentation/uikit/uitableview/1614935-reloadrows), [insertRows](https://developer.apple.com/documentation/uikit/uitableview/1614879-insertrows), [deleteRows](https://developer.apple.com/documentation/uikit/uitableview/1614960-deleterows)와 같이 각각의 rows 자체에 대해서 수행할 수 있는 메소드가 있습니다!

지난번 Insert에서는 성능상으로 reloadData대신 insert를 해주셨다고 하셨던 것 같아서, 말씀하신대로라면 여기서도 reloadData보다는 reloadRows가 성능상으로 좋아보이긴하네요 🙏

2023-10-23 11:53 UTC, jryoun1 commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +            delegate?.updateContact(newContact, of: current.uuid)
이미 생성되었던 것을 다시 삭제하고 새롭게 만들어서 넣는 것은 지금으로서는 문제가 없겠지만, 평범하지는 않은 flow인 것 같습니다.

새로운 연락처의 생성일 때는 당연히 uuid를 새롭게 생성하고, 이후에 update시에는 이미 생성된 uuid로 기존의 uuid를 찾고 그 값을 업데이트 해주는 것이 일반적으로 기대되는 것 같습니다. 
지금은 uuid를 클라이언트에서 관리한다지만 추후에 서버가 붙어서 uuid를 서버에서 받는 다고 가정한다면 서버에서 받는 uuid 자체가 없어지는 문제가 발생할 수 있을 것 같네요! 🙏🏻

2023-10-23 12:13 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactTableViewController.swift
> +        tableView.reloadData()
아 그렇군요.. `reloadRows` 메소드가 있었는지 몰랐습니다. 참고하겠습니다! 😅

2023-10-23 12:16 UTC, comdori-wj commented on ContactManager/ContactManager/Controllers/ContactModifierViewController.swift
> +            delegate?.updateContact(newContact, of: current.uuid)
네 추후 서버 사용을 한다면 기존의 값을 사용하는 게 맞을 것 같네요. 참고하도록 하겠습니다. 🙂

2023-10-24 09:24 UTC, jryoun1 commented
3주동안 고생하셨습니다 :)

2023-10-24 09:24 UTC, jryoun1 approved these changes

2023-10-24 09:24 UTC, merged