연락처 관리 앱 [STEP 1] LJ, 라마
tasty-code/ios-contact-manager-ui pull request #51
Opened 2024-01-04 07:55 UTC by ijs1103

2024-01-05 02:15 UTC, yim2627 requested changes
안녕하세요 엘제이, 라마!

스텝1 고생 많으셨습니다. 스텝1의 경우엔 모델 설계등 기반 설계가 대부분이라 크게 리뷰할 부분이 없었네요.

피드백들은 하위에 달아놓았고 질문 사항에대한 답변도 확인부탁드립니다. 질문이 더 있으시다면 언제든지 DM 주세요.

### 질문 사항 답변

제 개인적으로는 `@discardableResult`를 잘 사용하지 않습니다. 
리턴을 해야하는 용도로 생성한 메서드를 리턴값을 사용하지 않기위해 사용하는 것이기 때문에 함수가 제 역할을 하지 못하게된다고 생각해요.  
다만 이건 개인적인 의견이기때문에 여러분들이 타당한 이유만 있다면 사용해도 문제가 없다고 생각합니다. 메서드의 갯수가 많아져도 쓸데없이 분리한게 아닌 용도가 분명하다면 상관없다고 생각해서 `validateContactExists`를 사용하신 방법이 저는 더 보기 쉽다고 생각이 드네요!

새해부터 고생많으셨고 새해 복 많이 받으세요.

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Application/SceneDelegate.swift
> +        self.window = UIWindow(windowScene: windowScene)
UIWindow는 어떤 역할을 하는 객체일까요?

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Application/SceneDelegate.swift
> +        self.window?.makeKeyAndVisible()
makeKeyAndVisible은 어떤 역할을 할까요?

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Application/SceneDelegate.swift
> +    }
사용하지 않는 메서드는 제거해주시는 것이 좋습니다!

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/ContactManager.swift
> +struct ContactManager {
타입을 구조체로 선택하신 이유가 있을까요?

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/ContactManager.swift
> +    mutating func addContact(_ contact: Contact) throws {
mutating 메서드는 어떻게 동작을 할까요?

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/ContactManager.swift
> +            throw ContactManagerError.duplicateContact
예외처리 👍👍

2024-01-05 02:15 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/ViewController.swift
> +            preconditionFailure("ContactCell load Failed")
preconditionFailure은 fatalError와 다른 것이 무엇일까요?

2024-01-05 07:21 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Application/SceneDelegate.swift
> +    }
네 제거하였습니다!

2024-01-06 08:01 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Application/SceneDelegate.swift
> +        self.window?.makeKeyAndVisible()
`UIWindow` 객체를 사용자와의 상호 작용이 가능한 Key Window로 설정합니다. `UIWindow`는 기본적으로 보이지 않는 상태인데, 해당 윈도우를 화면에 보이게 하는 역할을 합니다.

2024-01-06 08:02 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Controller/ContactManager.swift
> +struct ContactManager {
Apple 공식 문서에서 `class` 사용을 권장하는 상황은 다음의 2가지입니다. 

- Objective-C 상호 운용성이 필요할 경우
- 모델링하는 데이터의 ID를 제어해야 할 경우

이에 해당하지 않을 때는 “기본적으로 구조체(`struct`) 사용”을 권장하므로 `struct`를 선택했습니다.

2024-01-06 08:02 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Controller/ContactManager.swift
> +    mutating func addContact(_ contact: Contact) throws {
`struct, enum`과 같은 값 타입의 `mutating` 메서드 내부에서 해당 프로퍼티의 변경을 허용해 주는 역할을 합니다.

2024-01-06 08:04 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Controller/ViewController.swift
> +            preconditionFailure("ContactCell load Failed")
`preconditionFailure`는 오류 조건이 릴리즈 빌드에서 무시될 수 있는 경우에, `fatalError`는 프로그램의 실행을 중지시켜야 하는 치명적인 오류 상황에서 사용됩니다.

- `preconditionFailure` : preconditionFailure이 위반될 때, 즉 사전에 설정해 둔 조건이 false일 때 프로그램이 중지됩니다. 디버그 빌드에서는 항상 이 조건을 검사하며, 최적화된 릴리즈 빌드에서는 이 검사를 생략할 수 있습니다. 릴리즈 빌드에서는 실패하지 않을 것으로 예상되는 조건에 사용됩니다.

- `fatalError`: 이 함수는 불변성이 깨진 경우나 아직 구현되지 않은 부분 등, 프로그램이 더 이상 안전하게 계속 실행될 수 없는 상황에서 호출됩니다. `fatalError`는 디버그 빌드와 릴리즈 빌드 모두에서 항상 프로그램을 중지시킵니다.

2024-01-06 08:04 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Application/SceneDelegate.swift
> +        self.window = UIWindow(windowScene: windowScene)
사용자 인터페이스를 화면에 나타내고 앱의 메인 화면이나 배경을 나타내며 뷰 컨트롤러와 뷰를 통해 사용자 인터페이스를 구성합니다.
또한, 사용자가 발생시킨 이벤트를 다른 객체로 전달하는 역할을 맡습니다.

2024-01-08 04:17 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/ContactManager.swift
> +    mutating func addContact(_ contact: Contact) throws {
mutating은 역할보다 동작 과정을 아시는 것도 중요합니다.

시간나실 때 공부해보시는 것도 좋을 것 같아요.
https://stackoverflow.com/questions/51128666/what-does-the-swift-mutating-keyword-mean

2024-01-08 04:18 UTC, yim2627 approved these changes

2024-01-08 04:19 UTC, merged