연락처 관리 앱 [STEP 1] 댄, Sidi
tasty-code/ios-contact-manager-ui pull request #52
Opened 2024-01-05 01:46 UTC by eensungkim

Step 1
멤버 : @eensungkim, @jus1234
리뷰어 : @keeplo

연락처 관리 앱 프로젝트의 첫번째 Step입니다! 
정리하여 PR 드립니다. 감사합니다!

# 이번 스텝을 통해서 배운 점
- TableView
    - TableView의 생명주기
    - UITableViewDataSource 프로토콜 메서드의 호출 시점
    - dequeueReusableCell 동작방식 연구
- 오토레이아웃을 코드로 구현하기
- JSON 파싱

# 구성
## Model
### Contact.swift
- Contact 구조체
    - property : 이름, 전화번호, 나이

### ContactList.swift
- ContactList 모델 구조체
    - property: [전화번호: Contact 구조체]

    - method: ContactList 보기, Contact 추가(변경), 삭제, JSON 파일 로드

## View
### ContactTableViewCell.swift
- ContactTableViewCell 커스텀 클래스

## Controller
### ContactListViewController.swift
- ContactListViewController : 연락처 리스트 뷰 컨트롤러

# 질문
![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/73898006/7de51ace-42f9-4bbd-8780-7cdf466cc75d)
- 스토리보드를 활용하지 않는 경우, 초기 생성된 ViewController.swift 파일을 삭제하니 아래와 위 이미지와 같은 메시지가 뜨는 것을 확인했습니다. 앱 작동에는 지장이 없는 경우라서 에러라고 보이지는 않는데, 만약 스토리보드를 활용하지 않는 앱을 구상할 경우 보통 어떻게 처리하는지 궁금합니다.
저희는 활용하지 않더라도 ViewController.swift 파일을 유지하는 것으로 진행했습니다.

2024-01-05 15:00 UTC, keeplo requested changes
안녕하세요! 말꼬입니다!
@eensungkim, @jus1234

이번 프로젝트 진행하는 동안 잘 부탁드립니다! 🙏🙏🙏
프로젝트 첫 주로 한 팀이 되어가는 과정도 쉽지 않으셨을텐데
한 주간 고생 많으셨습니다!

우선 프로젝트 구성해주신 점을 보면서 너무나 깖끔한 설계와 구성에, 
두 분의 개발 경험 히스토리가 궁금해졌습니다.
새싹이 처음은 아니라는 느낌을 확 받았어요! 
아무래도 성장에 도움이 되어야 하니 좀 더 깊은 내용이나 놓친 부분은 없는지
꼼꼼히 리뷰를 해보겠습니다! ㅎㅎ

---

### 리뷰하면서 인상 깊었던 점
##### 테스트 코드
   테스트 코드라니 ㅎㅎㅎㅎ 처음입니다. 리뷰하면서.. 앞으로 기대가 됩니다!
   저도 테스트 코드에 관심이 많은데 함께 성장하는 기회가 되었으면 좋겠어요!

### 리뷰하면서 보였던 고민해볼만한 영역
##### 프로젝트 진행방식
   두 분이 어느정도 경험이 있다는 느낌을 많이 받고 있습니다. 그래서 그런지 새싹 교육을 온전히 믿고 잘 따라오고 있으신게 맞을까?! 
몇몇 포인트에서 의심이 들었습니다. 우선 합리적 의심에 출발점은 커밋입니다.
   
   `*이번 프로젝트 수행시 제약사항` 꼭 지켜지면 좋을 것 같습니다!
   두 분이 같이 코드를 완성하고 커밋을 나누셨더라도 한 커밋 단위로 각자 커밋을 남기면,
   번갈아가면서 연습도 되고 실수를 하더라도 당사자가 해결해보면서 연습이 됩니다!
   지금처럼 커밋구성이 되면 저는 구현을 파트별로 나눠서 하셨다고 느껴집니다 ㅠㅠ   
`*한 커밋의 코드를 짝꿍 모두가 설명하지 못하면 다음 커밋으로 넘어가지 않습니다.` 
이 규칙도 꼭 지켜지도록 노력해주세요!
어떤 실무 팀을 가던 두사람 이상 모이면 실력에 차이가 발생하게 됩니다!
리더와 팔로워 역할에서 모두 잘 할 수 있도록 수시로 배려하고 소통하는 연습을 하면 좋아요!

##### 커밋 단위
   커밋 단위에 제목과 바디에 작성된 내용만 코드가 포함되면 좋을것 같아요!
   일례로 [chore: contacts.json 파일 추가](https://github.com/tasty-code/ios-contact-manager-ui/pull/52/commits/bff99e9567334db4726b3a5c672dda7edc8bfae7) 커밋에 경우 뜬금없이 테이블뷰 관련 코드가 포함되어 있습니다.
   개발 업무를 하다보면 에러에 원인을 찾다보면 이전 커밋 버전으로 돌아가보기도 하고 덧붙여서 머지되기도 하는데요
   그런 상황에서 인지할 수 있는 커밋이외에 코드가 숨어 들어오면 원인모를 이슈가 더 발생할 수도 있습니다!
   지금부터 연습으로 신경쓰다보면 나중에 습관처럼 잘지켜지는 좋은 개발자가 되는 연습이 될 수 있다고 생각합니다!

##### 요구사항 체크
   제가 최근 일을 하면서 크게 느끼고 신경쓰는 부분이라서 더 크게 느껴졌습니다.
   저의 경우 기획자가 남겨주는 기획서(와이어프레임)를 이용해서 프로토타입 앱을 제공했는데요.
   실수로 몇가지 디테일을 놓치거나 잘못 이해해서 기획자의 의도와 다른 기능을 구현하게 되었고
   이런 점을 기획자 분들은 단순 실수로 받아들여지기 이전에 개발자가 원하는 기능을 강요한다고 느끼시기도 합니다.
   좀 길었지만 제 사례를 소개해드린 이유는 단순히 규칙 지켜라 라는 단순한 요구가 아니라 두 분이 좋은 개발자로써 작은 습관부터 만들어가는데 중요한 교육의도라고 생각되기 때문에 말씀드리게 되었습니다.

우선 리뷰에서 언급한 `subtitle style` 부분이 한가지 있구요!
아래 사진을 보시면 실제 구동되는 앱과 요구사항에서 제공되는 앱에 이미지가 미세하게 다른 점을 보실 수 있습니다. 이런 부분도 어떤 차이로 인해 발생하는지 알아보고 해결해보면 좋을것 같아요!
![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/24707229/4f9107a3-8b6f-41c7-a0a9-8df9f96c6eed)

---

### 남겨주신 질문 답변
남겨주신 답변처럼 `Warning`으로 앱 실행에는 문제가 없지만 무언가 놓친 부분이 있어서 발생하는게 맞습니다
우선 저런 이슈가 있을때 차분히 문장을 보면 디버깅이 쉬워집니다.
문장에서 `_TtC22...ui14` 처럼 이해하기 힘든 부분을 제외하고 문장을 확인하면 
`알 수 없는 클래스, 인터페이스 빌더 파일 안에`
정도는 해석할 수 있을것 같아요!

저희는 스토리보드 파일이 있는데 그걸 `인터페이스 빌더 파일`로 유추하실수 있을거라 생각해요
또 답변해주신것 처럼 활용하지 않기 때문에 빌드시 스토리보드 파일은 사용되지 않는데

스토리보드 파일을 제거하거나 아니면 내부에 사용되는게 없도록 수정해야할 것 같아요!

사실 직접 알려드리는 것보다는 찾아내시는게 좋긴한데..
이정도면 힌트는 충분하다고 생각합니다;; 대신 ViewController.swift 파일을 제거하고
Warning이 발생하지 않는 프로젝트로 만드는 걸 이번 미션으로 해보시죠..
> 시간이 너무 오래걸리거나 어려움이 있으시면 언제든 디코로 디엠 주세요! 어차피 불가능한 시간대나 바쁘면 답이 늦습니다. 편하게 보내놔 주세요! 주말 새벽 불금! 언제든 괜찮습니다 ㅎㅎ

---

이번 PR에서 설계나 구성은 너무나 흠잡을대 없이 깔끔하고 좋은 구현을 잘 해주셨어요!!
그렇기 때문에 어떻게 보면 별로 안중요하게 느껴지거나 작게 보이던 부분들을 더 집어봤어요!
어느정도 이유와 철학을 가지고 리뷰 드린 부분이라 한번쯤 고민해주시면 좋을것 같아요
또 바로바로 해결된다면 그것과 이어지는 제 큰그림도 같이 이야기해보시죠! ㅎㅎ

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +    var sut: ContactList!
와우 테스트 코드를 작성해주셨군요?! 대단합니다 ㅎㅎ

sut로 네이밍 지어 주셨는데 관련해서 테스트 더블에 관해 두분 다 이해하고 계신걸까요?

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +    func test_updateContactList_호출시_제대로추가가되나요() {
한글 네이밍 아주 좋은것 같습니다 ㅎㅎ 🤣 

뭔가 의미 전달에 오해가 있을 수 있을것 같아요..
딕셔너리를 두고 추가한다는 개념은 update 메서드를 사용하는건 개체는 알지만

`ContactList` 내부 프로퍼티가 딕셔너리라는걸 외부는 알 수가 없을 것 같아요.
그런점에서 함수 네이밍과 연결해서 테스트 결과 문장도 조금 변경이 되면 좋을것 같아요!

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +        }
이 부분도 `given`으로 가는게 좀 더 어울릴거 같다고 생각이 드는데
두 분은 어떻게 생각하시는지 궁금합니다!

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +        sv.alignment = .fill
네이밍을 간략한 표현은 좋지만 줄임말은 사용하는걸 지양하는게 좋을것 같아요!

작지만 코드 컨벤션의 일관성을 해칠 수 있는 요소가 되어 스노우볼 효과를 일으킬 수 있습니다!

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    }
UIStackView를 이용해서 UI Component 를 하나에 View처럼 묶어주셨군요!

어떤 의도로 이 컴포넌트를 사용하셨는지 알려주실 수 있을까요?

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +        super.init(style: .default, reuseIdentifier: reuseIdentifier)
Step 1의 요구사항에서는 cell을 `subtitle style`을 사용하라고 명시가 되어있는데,
커스텀 Cell로 구성하신 의도가 있으신가요?

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +            nameLabel.heightAnchor.constraint(equalToConstant: 22)
nameLabel은 stackView 내부에 컴포넌트인데 직접 contentView에 오토레이아웃을 적용하면 문제점은 없을까요?
혹시 line 58 조건을 stackView - contentView로 작성하면 원하는 기대동작이 되는지 궁금합니다!
또 높이를 지정해주셨는데 지정하지 않으면 cell 높이가 지정이 안되는지 궁금합니다!

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        tableView.rowHeight = 50
크기 지정의 조건은 어떤 기준으로 정했는지 궁금합니다!
혹시 유연한 높이 조절을 할 수 없을까요?

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +final class ContactListViewController: UIViewController {
`final` 키워드를 사용해주셨군요!

어떤 효과가 있는지 간략하게 설명해주실 수 있나요?
> 이쯤되면 한번쯤 질문 받으셨을 수 있지만 혹시나해서 드려봅니다..

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactList.swift
> +                partialResult[contact.phoneNumber] = contact
이 부분 구현을 보다가 생각난 점인데

저희가 일반적으로 생각하는 연락처 앱에서 `전화번호`나 `이름`이 같으면 저장이 되지 않나요?
key 값이 같으면 이전 값이 덮어씌워질 위험성은 없을까요?

2024-01-05 15:00 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactList.swift
> +    }
JSON 파일을 이용해서 데이터를 불러오는 형태로 구현하셨군요!
너무 좋습니다! 
직접 코드에 작성하는 것보다 외부 데이터를 불러오는 형태를 유지하면
DB나 네트워크 환경으로 교체될 수 있는 아주 유연한 구조라고 생각해요!

2024-01-05 15:00 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    private var contactList: Dictionary<String, Contact>
딕셔너리를 선택하신 이유가 있을까요?

2024-01-05 15:00 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    }
함수명은 `ContactList 보여주기` 로 해석될 수 있을것 같은데
직관적으로 함수의 의도를 설명하지 않는다고 생각해요!
의미에 초점을 갖거나 기능에 초점을 갖는건 두 분의 컨벤션 영역이라고 생각되는데
어떤 방향이거나 좀 더 직관적으로 설명되는 네이밍으로 
내부기능을 전혀 몰라도 함수명과 반환 값만으로 기대동작을 이해할 수 있는 그런 네이밍이면 좋을것 같아요!

> 제가 느끼기엔 비정렬 컬렉션 데이터를 정렬 컬렉션 데이터로 정제하는 기능적인 느낌과   
> Model 내부에서 View를 그리기위한 DataSource를 가져온다는 의미적인 느낌을 받았어요!

2024-01-05 15:00 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    mutating public func deleteContact(contact: Contact) {
[API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)  는 거의 유일하게 Swift 언어 오피셜 컨벤션이기 때문에 완전히 외워질때까지 반복적으로 봐주시면 좋을 것 같아요!

Naming - Strive for Fluent Usage 파트의
> Prefer method and function names that make use sites form grammatical English phrases.

참고하시면서
Conventions 파트도 참고해주세요!

메서드와 반환값까지 마치 영어 문장을 읽는 듯한 느낌을 주게 인수와 파라미터 네이밍까지 고려하면 좋을 것 같아요!

`deleteContact(contact: Contact)`

현재 네이밍 구성을 조금 더 고민해보고 개선해보면 좋을것 같아요!
힌트는 "영어 문장으로 말이되게"

2024-01-08 01:16 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +    var sut: ContactList!
테스트 더블이라는 표현을 처음 들어봐서 검색을 좀 해봤는데요. "테스트를 하기 위해 사용하는 모방된 객체" 로 이해했습니다. 
테스트를 공부하면서 통상 sut(system under test) 라는 변수명으로 테스트를 진행할 객체를 불러온다고 이해했고, 해당 변수명이 통용되는 컨벤션이라고 알고 있습니다.
메서드의 기능을 확인하는 차원에서, 테스트를 위한 객체를 만들고 관리하기 위한 과정이라고 생각합니다.

2024-01-08 01:22 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +    func test_updateContactList_호출시_제대로추가가되나요() {
말씀주신 대로 ContactList 내부에서 저장을 담당하는 객체가 딕셔너리라는 것을 외부가 알지 못할거 같습니다. 이 점을 명확히 하기 위해 메서드 명을 `test_updateContactList_호출시_내부_딕셔너리에_제대로_추가될까요`로 변경하면 좋을거 같습니다.

2024-01-08 01:26 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +        }
생각해보니 `deleteContact`를 테스트하기 위한 메서드에서 해당 내용은 상황을 만드는 코드라 `given`으로 들어가는 것이 더 정확한거 같습니다.

2024-01-08 01:28 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +        sv.alignment = .fill
`stackView`라는 변수를 생성하기 위한 클로저 내부에서 `stackView`는 중복 네이밍이라 `sv`로 줄여 사용했지만 줄임말 사용은 지양하도록 하겠습니다!

2024-01-08 01:32 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    }
오토레이아웃을 코드로 구현하는 방법을 공부하기 시작하면서 액세서리 영역에 대해 잘 알지 못하는 상태에서, 액세서리 영역을 버튼이라고 인지했었습니다. 그래서 텍스트 영역과 버튼 영역을 구분해주기 위해 레이블들을 스택으로 묶는 과정에서 스택뷰를 활용하게 되었습니다.

서브 타이틀 형식을 적용하게 되면 해당 코드는 제거될 예정입니다.

2024-01-08 01:34 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +        super.init(style: .default, reuseIdentifier: reuseIdentifier)
현재 과정이 학습을 위한 과정이다 보니 오토레이아웃을 코드로 구현하는 과정을 처음으로 공부하기 위해서 주어진 요구사항을 건너뛰어도 된다고 판단했었습니다.

2024-01-08 01:41 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +            nameLabel.heightAnchor.constraint(equalToConstant: 22)
stackView - contentView로 작성하고 테스트 해보니 원하던 기대효과가 나타났습니다! 높이의 경우는 정확한 크기대로 하기 위해 지정을 했지만 높이도 지정하지 않고 테스트해보니 제대로 지정이 되었습니다.

2024-01-08 01:41 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        tableView.rowHeight = 50
크게 기준이 있었다기보다는 임의의 조건으로 지정했었구요.
유연한 높이 조절에 대해서는 알아보고 추후 추가로 댓글을 남겨보겠습니다.

2024-01-08 01:46 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +final class ContactListViewController: UIViewController {
final 키워드를 사용하면 재정의를 방지할 수 있게 됩니다. 이렇게 하면 해당 클래스가 정적 디스패치(static dispatch) 로 동작하게 되어 런타임에서 성능적인 이점을 가져올 수 있습니다.

2024-01-08 01:50 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactList.swift
> +                partialResult[contact.phoneNumber] = contact
전화번호는 유일한 정보이다 보니 전화번호에 따라 연락처 정보가 저장되어야 한다고 생각했습니다. ios의 연락처 앱을 보니 연락처와 이름이 중복되더라도 저장되기는 했습니다. key 값이 같으면 이전 값이 덮어 씌어지는 시스템이긴 하지만 전화번호의 중복을 방지하는 것이 우선이라고 생각했습니다. 추후 유효성 검사 등 기획에 따라 저장 방식은 변경될 수 있다고 생각합니다!

2024-01-08 01:51 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    private var contactList: Dictionary<String, Contact>
위에서 답변드린 내용과 같습니다. 전화번호는 유일한 정보이다 보니 전화번호에 따라 연락처 정보가 저장되어야 한다고 생각했습니다. 기획 의도에 따라 변경될 수 있는 내용이라고 생각 합니다!

2024-01-08 01:52 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    }
내부적으로 정렬된 데이터를 가져온다는 점에서, `showSortedContactList` 라는 이름으로 변경하도록 하겠습니다.

2024-01-08 01:58 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    mutating public func deleteContact(contact: Contact) {
영어 문장으로 말이 되도록 `delete(_ contact: Contact)`로 변경하도록 하겠습니다! 매번 네이밍을 신경쓰지만 가장 어려운 부분인거 같습니다ㅜㅜ

2024-01-08 06:35 UTC, eensungkim commented
@keeplo 
리뷰 주신 내용을 반영하여 리팩토링 마무리하고 커밋했습니다. 감사합니다.

2024-01-08 13:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +            nameLabel.heightAnchor.constraint(equalToConstant: 22)
오.... 저 안 짜보고 감으로 질문드려봤는데.. 되다니... 
저 아직 안죽었네요 ㅎㅎㅎㅎ 🤣
요즘 근 1년간.. 스유 프로젝트만 했거든요;;; ㅎㅎ;; 

---

`StackView`에 메서드나 프로퍼티 값을 이용해서 다양한 형태 수정이 가능합니다.
`StackView` 에 들어간 뷰는 직접 오토레이아웃을 지정하기 보다 `StackView` 자체적으로 적용되도록 관리하는 편이 
좋을것 같아요!

테이블 뷰가 그려지는 과정에서 UIKit은 기기 화면 크기라거나 그려질 높이가 지정되어야하는데요,
버전이 올라갈때마다 조금씩 편해지고 있지만 기초적인 이해는 필요할것 같아요
[intrinsicContentSize](https://developer.apple.com/documentation/uikit/uiview/1622600-intrinsiccontentsize) 키워드에 대해서 학습해보시고 알아두면 좋을것 같습니다!

2024-01-08 13:07 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +        super.init(style: .default, reuseIdentifier: reuseIdentifier)
음 학습을 하는 과정으로써 구현해보셨군요! 이유가 있었다면 아주 좋습니다!

특별한 이유가 없다면 요구사항을 꼼꼼하게 살펴서 지켜지면 좋을것 같아요
실제 업무에서는 기획자나 디자이너의 요구사항을 전달 받고 구현하는데,
구현 불가능하거나 힘들어서 조율하지 않고 요구사항이 지켜지지 않으면 오해가 생길 수도 있습니다.

작은 부분일 수 있지만 이 또한 학습과 연습의 연장선으로 봐주시고 지켜보면 좋을것 같아요!

2024-01-08 13:09 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        tableView.rowHeight = 50
아주 좋습니다! 아마 레퍼런스가 많이 있을거에요!
이 기회에 `UITableView`에 관련된 메서드나 프로퍼티를 싹다 한번 살펴보는 것도 추천드려봅니다 ㅎㅎ

2024-01-08 13:27 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactList.swift
> +                partialResult[contact.phoneNumber] = contact
그렇군요! 전화번호를 식별자로 사용되는게 충분히 괜찮은거 같긴합니다 ㅎㅎ

두 가지 정도 한번 생각해보시면 좋을만한 부분을 말씀드려볼게요!

앱 뿐아니라 개발으로 만들어진 상품은 `업데이트` 라는 좋은 장치가 있다보니
계속 기능이 추가되면서 성장하게 되는데요. 
`추후에 특정한 이슈로 인해 식별자가 전화번호에서 다른 걸로 바뀌는 등`에, 
유지보수는 작아보이지만 어쩌면 엄청난 비용을 발생할 수 있다고 생각해요!
그런 점에서 항상 `확장에는 열린` 방향성을 가지고 설계하면 좋을것 같습니다! 
> SOLID 원칙에서 OCP에 대해서 찾아보시면 좋을것 같아요!

그런면에서 두번째로 언급할 내용은 id 입니다
식별자를 결정하는 방법은 여러가지가 있는데 `Identifier` 와 `Hashable` 등의 프로토콜을 소개해드릴 수 있을것 같아요.
두 가지 프로토콜과 사용예시 등을 한번 봐두시고 다음에 구현에 참고하시면 더 다양한 설계를 고민해볼 수 있을것 같아요!

2024-01-08 13:34 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    }
이 부분은 경험에 영역도 있을 것 같아서 한번 더 언급을 하게되었습니다;; ㅎㅎ

[Swift 개발자처럼 변수 이름 짓기](https://soojin.ro/blog/english-for-developers-swift) 
제가 학습할때나 저희팀 컨벤션 결정에서 많은 도움을 얻는 아티클 중 하나입니다.
> 노수진님의 D2 발표도 있는데 보시면 아주 좋습니다 (뒷부분 토론까지)

`#6 스위프트의 getter` 부분을 참고해보시면 Apple에서는 전통적인 Java 스타일과 다른 네이밍을 하는걸 볼 수 있어요
저도 `private(set)` 같은 키워드 또는 프로퍼티 감시자 같은 Swift의 기능을 잘 활용한 방향이라고 생각하는데요!

현재 메서드는 정렬된 데이터의 getter의 성격을 가진다고 생각해요.
`보여주다`라는 표현을 사용할일이 앞으로 UI 관련된 부분에서 많이 사용되기 때문에
> Display 또는 Present Show 등등

제가 드린 레퍼런스 같은 부분도 한번 살펴보시고 네이밍을 고민해보면 좋을것 같습니다!

> 개인적으로 `show`동사에 꽃혀서 리뷰를 남겼었어요 ㅎㅎ 그래서 좀더 배경설명을 드려봅니다;

2024-01-08 13:36 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactListModel.swift
> +    mutating public func deleteContact(contact: Contact) {
맞아요.. 아무리 해도 대단히 좋아지지 않더라구요..
개인적으로 제일 좋은건 지금처럼 리뷰에서 서로 봐주는게 젤 효과적인거 같아요.
구현부를 모르는 제 3자가 메서드명과 반환값만 접해도 코드가 이해되야 하는데 
`뭐지?, 어라?` 하면 좋은 네이밍이 아니거든요 ㅎㅎ

계속 연습해보시죠!

2024-01-08 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    }
커스텀 셀을 구현할때 액세서리 영역 디자인을 유사하게 가져가면,
결국은 말씀해주신 방향이 젤 좋을거 같아요! 아주 좋습니다!

2024-01-08 13:45 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +    var sut: ContactList!
오.. 잘 조사해주시고 학습해주셨네요 저도 말씀해주신 방향으로 이해하고 있습니다!

사람마다 생각에 차이가 있어서 조심스럽긴 하지만,
저는 말씀해주신 형태로 System under test를 지켜주는 형태가 변수명으로 사용되려면
위 코드처럼 일반적으로 테스트 파일하나의 소속된 개체가
>  `final class ios_contact_manager_uiTests: XCTestCase {`

하나에 개체(타입)에 대해서만 테스트한다는 전재가 되어야 한다고 생각하고 있어요

`final class ContactListTests: XCTestCase`  같이 블록을 만들고 var sut: ContactList!
그리고 개체의 메서드 중심으로 테스트를 함수를 추가하면서 하는 형태입니다. 

지금처럼 `ios_contact_manager_uiTests` 네이밍을 가져가면 
sut 역할을 하는 개체가 다른것도 들어올 수도 있을것 같아서 언급드렸습니다.

2024-01-08 13:55 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-uiTests/ios_contact_manager_uiTests.swift
> +    func test_updateContactList_호출시_제대로추가가되나요() {
제 의도와 살짝 비껴간 것 같습니다.

말씀해주신 부분 다 좋은데 외부가 모르니까 `내부_딕셔너리에_제대로_추가될까요` 가 어색할 것 같아요.
sut를 테스트한다면 sut 인스턴스 개체를 사용하는거니까 딕셔너리는 마찬가지로 내부사항이라 모르는 전재가 맞지 않을까요?
저는 `test_updateContactList_호출시_Contact데이터_추가된다` 로 작성할 것 같아요.

---

이렇게 미세해보이는 영역인데 따지는 이유는 두 가지가 있을것 같아요

첫번째는 `테스트코드는 하나의 설명서가 된다`입니다. 
개발서적에서 공통적으로 UnitTest 부분에서 언급되는 공통영역이라서 따로 설명은 하지 않을게요 ㅎ
작아보여도 큰 차이가 있지 않을까 생각해요!

두번째는 `메서드명(함수명)은 테스트까지 명료하게 만든다`입니다.
이번 문장은 저의 개인적인 기준일 수도 있는데요!
이 테스트가 제가 리뷰에서 `updateContactList`메서드를 언급하고 따로 디엠 주실때 언급한 이유가 될 것 같아요.
추가되는 테스트와 수정하는 테스트가 각각 생길텐데, 메서드명이 같은것 만으로도 혼동을 줄 수도 있고
`함수는 하나의 일만 해야한다` 같은 개발 공통 참고 사항을 위배하는 설계가 될 수 있을것 같아요!

2024-01-08 14:00 UTC, merged

2024-01-08 14:00 UTC, keeplo commented
두 분 고생많으셨습니다!

수정 요청했던 요구사항 관련부분 잘 수정해주셔서 Step1 부분은 머지해도 좋을것 같아요!
추가적으로 언급하거나 설명이 있는 부분은 Step 2에서 꼭 필수적으로 수정할 필요는 없고
두 분이서 함께 고민해보시거나 학습해보시고 결정하시면 될 것 같아요!

제가 설명드리거나 언급하는 부분들이 개인적인 기준이나 제 주변에서만 벌어지는 패러다임일 수도 있지만,
기준점이 없을때는 다양한 기준이 나의 기준을 만드는데 도움이나 영향을 줄 수 있지 않을까 생각해서 제 스타일이나 예시를 소개했습니다. 
개발에는 정답이 없고 저도 영향을 받거나 오류가 있을 수 있으니, 잘 검열해서 필요하거나 좋은 정보만 얻어가시면 좋겠어요!