연락처 앱 [STEP 1] 노움, 샘
tasty-code/ios-contact-manager-ui pull request #53
Opened 2024-01-05 04:53 UTC by Gnoam-R

## 프로젝트 PR

안녕하세요, 시온(아이디 모름)!

Sam(@ParkChanH), 노움(@Gnoam-R)입니다.

<div align="center">
<img src="https://github.com/tasty-code/ios-contact-manager-ui/assets/67363759/f47d1f60-7e95-4e6d-b771-7633909d5fb6"/>
</div>

### Step1 요구사항

> **STEP 1 - 연락처 목록 구현**
> 
> 
> **Step 1-1 모델타입 구현**
> 
> - 아래 내용 고려하여 **Model 타입을 구현**합니다.
>     - 연락처 관리앱은 사용자로부터 이름, 연락처, 나이에 대한 정보를 전달받습니다.
>     - 연락처를 관리하기 위해 필요한 기능은 아래와 같습니다.
>         - 연락처 보기
>         - 연락처 추가
>         - 연락처 삭제
>         - 연락처 변경(optional)
> 
> **Step 1-2 TableView의 사용**
> 
> <img src="https://github.com/tasty-code/ios-contact-manager-ui/assets/67363759/b1b6c38c-91df-43be-9aff-b246d35c4815" width="200" height="400"/> 
> 
> - Table View를 활용하여 연락처 목록을 화면에 표시합니다
> - 각 행의 cell은 **subtitle style**을 사용합니다
> - 각 행(row)에 표시할 항목
>     - 이름, 나이, 연락처
>         - 이름옆에 괄호로 나이가 위치합니다.
>         - 연락처는 `이름(나이)` 아래에 위치합니다.

## **설계 및 구현 설명**

### 연락처 모듈 구현

사용자의 연락처 정보(이름, 연락처, 나이) `ContactList` 생성했습니다.

클래스 `ContactListStorage` 에서 `ContactList`를 참조하여 연락처 정보에 대한 보기, 변경, 추가, 삭제에 대한 기능들을 구현 했습니다.

`ContactListStorage`의 프로퍼티 `contactList`는 `ViewController`와 같은 외부 클래스에서 직접 접근 하지 못하도록 private로 선언했습니다. 외부에서 접근 하기 위해서는 해당 클래스에서 구현된 메서드를 통해서만 접근이 가능합니다. 

## TableView 적용 구현 상세

`extension ViewController`를 사용하여 `UITableViewDataSource`와 `UITableViewDelegate`메서드를 ViewController의 주요 기능에서 분리함으로써, 코드의 단일 책임 원칙을 잘 준수하였습니다.

- `UITableViewDataSource` 구현:
    - `numberOfRowsInSection`: `contactListStorage`에서 연락처 개수를 반환하는 방식으로, TableView의 행 수를 결정합니다.
    - `cellForRowAt`: 각 행에 표시될 셀을 구성합니다. 여기서 `showContact(who:)` 메서드를 통해 각 연락처의 정보를 가져와 셀에 표시합니다.
- `UITableViewDelegate` 구현:
    - `didSelectRowAt`: 행 선택 시의 동작을 정의합니다. 현재는 선택된 행의 하이라이트를 해제하는 간단한 애니메이션만 포함되어 있습니다.

## 질문

안녕하세요, 리뷰어님. 이 PR에 대한 리뷰를 부탁드리며, 몇 가지 질문 사항이 있습니다. 귀중한 의견을 주신다면 감사 드리겠습니다.

1. **MVC 구조 적용**: 현재 `ContactsManager`를 도입하여 모델을 분리했습니다. 이러한 구조가 MVC 패턴을 잘 따르고 있는지, 추가적으로 개선할 부분이 있는지 궁금합니다.
2. **코드 최적화**: 제공된 코드에서 성능적인 측면이나 최적화할 수 있는 부분이 있을까요? 특히, 테이블 뷰의 데이터 처리와 관련하여 더 효율적인 방법이 있는지 알고 싶습니다.

감사합니다. 리뷰어님의 의견을 듣고 프로젝트를 더 발전 시키겠습니다!

2024-01-06 07:09 UTC, LeeZion94 commented on .gitignore
> +.DS_Store
gitignore란 무엇이고 왜 사용하셨나요?

.DS_Store는 어떤것이길래 gitignore에 추가해주셧나요?

2024-01-06 07:29 UTC, LeeZion94 commented
안녕하세요 노움, 샘! 연락처 앱 리뷰를 맡게된 시온이라고 합니다.
Step1 구현해주시느라 고생많으셧어요!

## 질문해 주셧던 부분
----
### MVC 구조 적용
- MVC를 적용했다기 보다는 Cocoa MVC를 적용했다고 말씀을 해주시고 싶었던 것 같아요!! Cocoa MVC가 기존 MVC와 어떤 차이점을 가지는 지도 알아보시면 좋을 것 같습니다. 또한, ContactManager를 만들어주신건 Model을 분리했다는 측면에 부합하는 것 같습니다 보기에 좋아보여요!! 아직 연락처 기능에 대한 추가적인 기능이 없기 때문에 아키텍처의 역할 분리에 대해서는 Step2에서 얘기를 다시나눠보면 좋을 것 같아요. 현재로서는 각각의 기능에 맡게 잘 분리되어 있다고 생각되요!

### 코드 최적화
- 코드 최적화에 대한 부분들은 현재 구현된 부분에서 할 수 있는 것들에 대해서 코멘트로 남겨놨어요. 이 부분은 코멘트를 확인해주시면 좋을 것 같고 Step이 진행됨에 따라 최적화 시킬 수 있는 부분에 대해서는 지소적으로 코멘트 드릴게요!

2024-01-06 07:30 UTC, LeeZion94 requested changes

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +
다른 부분과는 맞지 않는 컨벤션으로 보여져요 ㅎㅎ 의도하신 부분인가요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +class ViewController: UIViewController {
ViewController는 현재 상속하고 있는 부분이 없어보여요. 다른부분과 다르게 final키워드를 사용하지 않는 이유가 있을까요?

또한 final 키워드에 대해서 설명해주시고, Performance 적인 부분에 있어서도 설명해주세요

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +    private var contactListStorage = ContactListStorage()
contacListStorage를 내부에서 들고 있는 형태를 가지네요?
D.I (Dependency Injection)에 대해서 공부해보시면 좋을 것 같아요.
D.I의 방법에대해 공부해보시고 저한테 소개해주시면 좋을 것 같아요.

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
해당 IBOutlet은 왜 weak 키워드가 사용되고 '!'가 사용되어야 하나요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +    override func viewDidLoad() {
viewDidLoad가 호출되는 시점은 언제인가요? 그리고 override 키워드는 왜 사용되어야하는거죠?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +        UI_테스트(Storage: contactListStorage)
앞에 self 키워드를 붙이는 컨벤션이 조금 맞지 않는 것 같아요. 통일성을 부여해보는게 어떨까요?

또한 테스트 로직이 ViewController내부에 존재하고 있는게 조금은 부자연스러워보입니다. 해당로직이 필요한 이유는 무엇인가요?
해당 메서드로 정말 UI를 테스트 할 수 있나요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +    private func contact(forID id: Int) -> ContactList {
contact, showContact 메서드의 역할이 겹치는 것 같아요 하나로 통일하는 건 어떨까요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +    private func contact(forID id: Int) -> ContactList {
forID이긴 하지만 전달받는 값은 index로 보여요, index는 ID값으로 활용할 수 있나요? 활용할 수 있다면
그 이유를 설명해주세요

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +        cell.textLabel?.text = "\(item.name) (\(item.age))"
cell의 기본적으로 textLabel과, detailTextLabel에 접근해서 사용할 수 있는 이유는 무엇인가요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +extension ViewController: UITableViewDelegate {
UITableViewDelegate란 무엇이고 어떤역할을 하나요?
또한 Delegate Pattern에 대해 설명해주세요

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Model/ContactListError.swift
> +    case ContactListNotFound
지금 상황에서 꼭 필요한 에러인가요?
앞으로 어떻게 활용하실 예정일까요? 궁금해요 ㅎ

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Model/ContactListStorage.swift
> +    func showContact(who pos: Int) -> ContactList {
show는 보여준다는 의미가 강한 단어로 보여요 ㅎㅎ
여기서는 어떤걸 show한다는 의미로 사용되었나요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Model/ContactListStorage.swift
> +        self.contactList[pos]
pos는 어떤의미의 단어인가요? 축약어가사용 된 것이라면 축약어 사용을 지양하면 좋을 것 같아요.
swift API guideline를 한번 참조해보면 좋을 것 같습니다!

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Model/ContactListStorage.swift
> +    func addContact(_ contacts: ContactList) {
Wildcard Pattern이 어떤 곳에서는 사용되고 어떤 곳에서는 사용되지 않는 것 같아요!
어떤 기준으로 구분해주셧나요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Test/UiTest.swift
> +extension ViewController {
해당 로직이 ViewController내에 속해야하는 이유가 있나요?

또한 UI_test, Unit_Test를 진행하는 방법에 대해서 다시 한번 공부해보시면 좋을 것 같아요.
프로젝트 생성시에 Test를 할 수 있는 환경이 주어져있음에도 이런 코드가 해당코드를 생성하신 이유가 궁금합니다.

ContacList를 출력하기 위해 meta Data가 필요한 것이였다면, Dummy Data에 대해서 한번 공부해보시는 건 어떨까요?

2024-01-06 07:30 UTC, LeeZion94 commented on contact-management/contact-management/Model/ContactListStorage.swift
> +final class ContactListStorage {
ContacListStorage는 왜 class 여야하나요? struct와 class의 차이점 및 class로 해당 타입을 만든 이유에 대해서 설명해주세요

2024-01-06 07:32 UTC, LeeZion94 requested changes

2024-01-06 07:32 UTC, LeeZion94 commented on contact-management/contact-management.xcodeproj/project.pbxproj
> +				CCADE3062B43A91D00E4EE30 /* Assets.xcassets */,
Asset과 LaunchScreen은 View범위에 속하는게 맞나요?

2024-01-06 07:32 UTC, LeeZion94 commented on contact-management/contact-management.xcodeproj/project.pbxproj
> +		CCD4C8CF2B44ED6500B69E9F /* Model */ = {
노움과 샘이 생각하시는 Model의 역할과 기능에 대해서 설명해주세요

2024-01-08 01:08 UTC, Gnoam-R commented on .gitignore
> +.DS_Store
프로젝트의 디렉토리 내에 존재하는 특정 파일들을 `git`에 업로드 하지 않는 기능 입니다.

`.DS_Store`는 맥에서 시스템 os가 finder로 파일에 접근하게 될때 생기는 파일이라고 알고 있습니다

프로젝트와는 별개의 파일이기 때문에 `gitignore`에 추가하게 되었습니다.

2024-01-08 01:23 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +
전체 프로젝트의 컨벤션과 동일하게 맞추기 위해서 `ViewController`의 네이밍을 `ContactListView`로 변경했습니다

2024-01-08 01:25 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +class ViewController: UIViewController {
`final` 키워드를 사용하는게 맞는 것 같습니다.
`final`은 유일한 클래스를 생성하기 위한 키워드로 붙이게 되면 다른 클래스에서 상속 받을 수 없습니다
성능 면에서는 해당 키워드를 사용한 클래스가 런타임 시점에서 이점을 가지게 됩니다
`final, private`는 `static Dispath`로 컴파일 시기에 이미 호출이 정의된 메서드로 일반적인 `Dinamic Dispath`와는 달리 런타임 시기에서 호출이 정의되지 않기 때문입니다

2024-01-08 01:56 UTC, ParkChanH commented on contact-management/contact-management/Controller/ViewController.swift
> +    private var contactListStorage = ContactListStorage()
Dependency Injection은 저희가 작성한 코드처럼 클래스 내부에서 필요한 객체의 인스턴스를, 
클래스 내부에서 생성하는 것이 아니라 외부에서 생성한 후
이니셜라저 또는 setter를 통해 내부로 주입받는 형식입니다. 

* 이니셜라이져의 타입은 프로토콜을 활용해서 내부에서는 만든 프로토콜 메서드를 사용하는 방법이 있습니다.

2024-01-08 01:59 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +
옷! 제가 말씀드린 부분은 타입을 선언하고 개행이 하나 들어가잇는 부분이였어요!

2024-01-08 02:01 UTC, LeeZion94 commented on contact-management/contact-management/Controller/ViewController.swift
> +    private var contactListStorage = ContactListStorage()
initializer Injection, property Injection, method Injection의 각각의 차이에 대해서 설명해주세요!

2024-01-08 06:20 UTC, Gnoam-R commented on contact-management/contact-management.xcodeproj/project.pbxproj
> +		CCD4C8CF2B44ED6500B69E9F /* Model */ = {
`Model`은 앱에서 화면을 나타내는 영역 `View` , 제어를 수행하는 `Controller` 와 다르게 데이터의 처리를 담당합니다. 
`Model`은 `View`에 적용된 데이터를 `Controller`로 가져와 조작 및 처리하여 다시 `Controller`를 통해 `View`에 뿌려줍니다.

2024-01-08 06:39 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +
아하! 해당 부분의 컨밴션은 생각 하지 못한 부분이였네요.. 해당 부분은 따로 컨벤션 관리해서 수정하도록 하겠습니다

2024-01-08 06:40 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListStorage.swift
> +final class ContactListStorage {
`LaunchScreen`은 `storyBoard`에서 다른 뷰들과는 달리 앱이 처음 실행할때 일정 시간동안만 화면에 출력되는 화면으로 `View`의 범위에 속한다고 생각합니다. 다만 `Asset`의 경우 뷰에 적용되는 이미지 데이터에 해당되는 파일로서 `View`에 포함된다 라는 표현이 어렵습니다. info 파일과 같이 밖에 분류하고자 하는데 시온은 어떻게 생각하시나요?

2024-01-08 06:52 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListStorage.swift
> +final class ContactListStorage {
`클래스`는 참조, `구조체`는 값 타입으로 `클래스`의 경우 ARC로 메모리 관리를 하며 인스턴스 생성시 생성된 인스턴스가 다른 위치에서 생성된 인스턴스에 영향을 주게 됩니다. 반대로 `구조체`는 생성된 인스턴스가 값으로써 메모리에 할당되기 때문에 여러 인스턴스를 만들게 되더라도 각 인스턴스에 영향을 주는 일이 없습니다

`ContactListStorage`의 경우 해당 클래스의 프로퍼티 `contactList` 가 해당 클래스가 아닌 다른 클래스에서도 동일한 값으로 사용되기 위해서 클래스를 사용하게 되었습니다.

2024-01-08 06:56 UTC, Gnoam-R commented on contact-management/contact-management.xcodeproj/project.pbxproj
> +				CCADE3062B43A91D00E4EE30 /* Assets.xcassets */,
`LaunchScreen`은 `storyBoard`에서 다른 뷰들과는 달리 앱이 처음 실행할때 일정 시간동안만 화면에 출력되는 화면으로 `View`의 범위에 속한다고 생각합니다. 다만 `Asset`의 경우 뷰에 적용되는 이미지 데이터에 해당되는 파일로서 `View`에 포함된다 라는 표현이 어렵습니다. info 파일과 같이 밖에 분류하고자 하는데 시온은 어떻게 생각하시나요?

2024-01-08 07:13 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListStorage.swift
> +final class ContactListStorage {
`UITest`파일을 만들게 된 이유는 생성된 `UI tableView`에 적용되는 데이터가 요구사항으로 정의가 된 데이터가 아니라 개발을 하게 되면서 임의로 만들게 된 테스트 코드이기 때문 입니다. 따라서 저희는 `ViewController`에서 정의를 하는것 보다는 테스트 파일을 만들어서 진행하는게 좋은 방법이라고 생각했어요... 당연히 이부분은 `UI_test`, `Unit_Test`와는 다르기 때문에 네이밍 적으로 오해할 많나 문제인거 같네요
`Dummy Data`에 대해 몇가지 방법을 찾아봤는데 `json`을 사용하면 위 방식이 아니라도 구현이 가능할거 같네요 Step-2에서 이 방법으로 구현하도록 해보겠습니다!

2024-01-08 07:15 UTC, Gnoam-R commented on contact-management/contact-management/Test/UiTest.swift
> +extension ViewController {
`UITest`파일을 만들게 된 이유는 생성된 `UI tableView`에 적용되는 데이터가 요구사항으로 정의가 된 데이터가 아니라 개발을 하게 되면서 임의로 만들게 된 테스트 코드이기 때문 입니다. 따라서 저희는 `ViewController`에서 정의를 하는것 보다는 테스트 파일을 만들어서 진행하는게 좋은 방법이라고 생각했어요... 당연히 이부분은 `UI_test`, `Unit_Test`와는 다르기 때문에 네이밍 적으로 오해할 많나 문제인거 같네요
`Dummy Data`에 대해 몇가지 방법을 찾아봤는데 `json`을 사용하면 위 방식이 아니라도 구현이 가능할거 같네요 Step-2에서 이 방법으로 구현하도록 해보겠습니다!

2024-01-08 07:46 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListStorage.swift
> +    func addContact(_ contacts: ContactList) {
같은 클래스 내의 메서드인 `showContact`의 경우 연락처를 보여주려고 하는데 누구의 연락처를 보여줘야 하는거지? 라는 이유로 who를 넣게 되었습니다. 하지만 다른 메서드 생성하게 되었을 때 테이블 뷰의 `pos`값을 매개변수로 전달 받는 상황에서 해당 네이밍이 적절한가? 라는 의문을 가지게 되어서 사용하지 않게 되었습니다. 이런 식의 생각으로 여러 다른 메서드를 생성하다 보니 별다른 구분 없이 통일성 없는 코드를 작성하게 된거 같아요

2024-01-08 08:00 UTC, LeeZion94 commented on contact-management/contact-management.xcodeproj/project.pbxproj
> +		CCD4C8CF2B44ED6500B69E9F /* Model */ = {
두분이 생각하시는 데이터의 처리란 무엇인가요?
모델이 view에 적용된 데이터를 Controller로 가져와 조작 및 처리하여 다시 Controller를 통해 View로 뿌려주는 주체가 될 수 있나요?
<< 이 부분에 대해서 자세히 설명해주실 수 있을까요?

2024-01-08 08:02 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListStorage.swift
> +    func showContact(who pos: Int) -> ContactList {
초기 코드 구성에서는 모듈에 대한 생각보다는 사용자에 UI에 연락처 정보를 보여준다 라는 구상을 하게 되었습니다.
연락처 모듈로 봤을때 `show`보다는 내부 저장소에서 연락처 정보를 가져온다 `getContact`, `accessContact`라는 네이밍이 더 적절할거 같습니다!

2024-01-08 08:23 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListError.swift
> +    case ContactListNotFound
현재 상황에서는 필요하지 않지만 앞으로 연락처 앱에 대한 여러 기능들이 구현될 거라 판단되었습니다. 향후 다른 기능들이 구현되게 된다면 그에 맞춰 에러 처리가 추가될 예정입니다.

2024-01-08 08:25 UTC, Gnoam-R commented on contact-management/contact-management/Model/ContactListStorage.swift
> +        self.contactList[pos]
pos는 position의 약어 입니다. 말씀하신대로 축약어를 사용하지 않는게 좋을거 같습니다.

2024-01-08 12:03 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +extension ViewController: UITableViewDelegate {
`UITableViewDelegate`란 프로토콜로 프로토콜에서 정의한 기능들을 `ViewController`에서 사용하게 역할을 위임하는 기능을 가집니다.
`Delegate Pattern`은 위임자를 생성하여 다른 객체가 자신의 일을 대신해서 수행하도록 만드는 디자인 패턴입니다.
이러한 사용 방식은 프로토콜을 통해 생성된 기능들을 실제 위임을 받은 객체에서만 구현되기 때문에 코드 재사용성과 유지보수에 유용합니다

2024-01-08 12:29 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +        UI_테스트(Storage: contactListStorage)
UI_테스트 함수에 대해서는 `UI 테스트`와 같이 화면에 대한 상태 동작의 여부를 확인 하는것이 아닌 화면에 Dummy data를 적용하여 저희가 정의한 테스트 데이터를 적용하는것을 목적으로 만들게 되었습니다. 
실제 'UI 테스트'를 진행하기 위해서는 'XCTestCase'를 상속받은 클래스에서 예상되는 결과 값을 넣은 변수와 특정 연산이나 처리를 완료한 결과를 비교하는 방식으로 이루어 집니다.

2024-01-08 15:08 UTC, ParkChanH commented on contact-management/contact-management/Controller/ViewController.swift
> +    private var contactListStorage = ContactListStorage()
이부분을 공부하면서 정말 많이 도움이 되었습니다!! 감사합니다!!

1. Initializer Injection
클래스나 구조체가 생성될 때 생성자를 통해서 의존성 주입 하는 방식

다른 의존성 주입 방법과 다른점은 주입 시점이 초기화 시점에서 이루어진다는 점입니다.
```swift
protocol B부품Protocol {
    func 작업()
}

class B부품: B부품Protocol {
    func 작업() {
        // B부품의 작업 구현
    }
}

class A부품 {
    var b부품: B부품Protocol
    
    init(b부품: B부품Protocol) {
        self.b부품 = b부품
    }

    func 사용() {
        b부품.작업()
    }
}

// 외부 주입
let 망치 = B부품()
let a부품 = A부품(b부품: 망치)
```

2. Property Injection
프로퍼티로 의존성을 주입하는 형태

다른 의존성 주입 방법과 다른점은 컴파일이 일어나는 순간 주입하고 있기 떄문에 바뀔위험이 있다는겁니다.
```swift
class B부품 {
	var 이름: String = "너트"
}

var A부품 = B부품()
A부품.이름 = "볼트"
```
3. Method Injection
객체의 메서드를 통해 의존성을 주입하는 방식
이 방법은 특정 작업을 수행할 때 필요한 의존성을 유연하게 제공할수 있습니다.
```swift
class A부품 {
	func 망치질(_ 힘: 강도, 망치: 어떤망치)-> Data? {
		return nil
	}	
}
```

2024-01-08 15:17 UTC, ParkChanH commented on contact-management/contact-management/Controller/ViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
1. IBOutlet은 왜 weak 키워드가 사용해야하는가
- weak 키워드 사용: MainView가 하위 View들의 기본 소유자이기 때문에, 이들에 대한 강한 참조가 필요하지 않습니다. weak를 사용함으로써 상호 강한 참조를 피하고, 강한 참조 주기(Strong Reference Cycle)로 인한 메모리 누수를 방지할 수 있습니다.

- 강한 참조 주기 문제: 강한 참조 주기는 객체들이 서로를 강하게 참조함으로써, 참조가 해제되어도 연관된 인스턴스들이 메모리에서 해제되지 않는 현상을 말합니다. 이는 애플리케이션의 성능 저하와 메모리 부족을 야기할 수 있습니다.

2. '!' 가 사용되는 이유
- IBOutlet은 기본적으로 앱의 사용자 인터페이스에 연결되므로, 인터페이스가 로드될 때 항상 유효하다는 것을 가정합니다. !는 암시적으로 추출된 옵셔널을 나타내며, 이는 IBOutlet이 nil이 아니라고 확신할 때 사용합니다. 
스토리보드 상에서 연결할 떄 유효한 값을 선언하는 방식이기 떄문에 확신하고 강제언랩핑 하게됩니다.

2024-01-09 01:37 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +        cell.textLabel?.text = "\(item.name) (\(item.age))"
변수 `cell`은 초기화시  `Identifier`와 `indexPath`를 지정한 dequeue 재활용 셀을 전달 받게 됩니다.
`cell`은 `tablewVIewCell`에 대한 `ID`와  행을 식별하는 인덱스 경로(indexPath)를 통해  `tablewViewCell`의 각각의 `cell`에 대한 `textLabel`과 `detailTextLabel`에 접근이 가능합니다

2024-01-09 01:50 UTC, Gnoam-R commented on contact-management/contact-management.xcodeproj/project.pbxproj
> +		CCD4C8CF2B44ED6500B69E9F /* Model */ = {
앱의 비지니스 데이터를 처리하는 작업입니다. 
각 앱의 특성에 따라 다를거라고 생각되지만 일반적으로 데이터 저장과 같은 로직 처리가 있습니다. 
모델이 주체가 된다? 라는 표현보다는 모델은 전달받은 데이터를 처리만 한다, 뷰가 하는 일은 모른다 라는게 더 맞을거 같아요. 
모델은 수행 만을 하는것일 뿐 그것이 뷰에 어떻게 나타 나는지는 알수 없습니다 따라서 모델은 주체가 될수 없다고 생각되네요

2024-01-10 01:29 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +    private func contact(forID id: Int) -> ContactList {
맞습니다 현재 작성된 코드에서는 입력되는 index값을 기준으로 연락처 정보가 담긴 배열의 값에 접근하는 방식을 취하고 있어요.
index를 사용하면 해당하는 배열에 쉽게 접근할 수 있고  tableView에 row정보를 쉽게 매치 시킬수가 있어서 사용했는데요. index를 ID 값으로 활용하기는 어려울거 같습니다. 연락처와 같은 사용자에 중요 정보가 담겨진 저장공간에 index로 접근을 하게 된다면 오류가 많아질거라는 생각이 들어서요. 때문에 다른 방법을 사용하고 싶은데 어떤게 있을까요?

2024-01-10 01:53 UTC, Gnoam-R commented on contact-management/contact-management/Controller/ViewController.swift
> +    override func viewDidLoad() {
viewDIdLoad는 view를 만들고 매모리에 올리는 viewLoad 다음에 실행되어 뷰가 로드 되고 나서 호출되게 됩니다. 그 밖에도 뷰가 화면에 나타나기 전을 알리는 viewWillApper,  애니메이션이 종료되고 뷰가 화면에 완전히 나타나고 난 뒤에 호출되는 viewDidApper 등이 있는데 이것들을 생명주기라고 합니다. 생명주기는 앱의 화면에 언제 나타나고 언제 사라지며 앱이 종료하는 시점을 나타내는데 이는 상위 클래스 UIViewController 내에 있는 메서드를 override 해서 사용하기 때문에 해당 키워드가 사용됩니다.

2024-01-11 00:45 UTC, merged