연락처 관리 앱 [STEP 1] 미르, 루피
tasty-code/ios-contact-manager-ui pull request #55
Opened 2024-01-05 06:58 UTC by kimdj1102

안녕하세요~ 두두! @FirstDo

미르, 루피 입니다! 연락처 관리 앱 STEP1 PR 보냅니다!
첫 PR 잘 부탁드립니다~😀

## 프로젝트 구현 요구사항

**Step 1-1 모델타입 구현**

- 아래 내용을 고려하여 Model 타입을 구현합니다.
    - 연락처 관리앱은 사용자로부터 이름, 연락처, 나이에 대한 정보를 전달받습니다.
    - 연락처를 관리하기 위해 필요한 기능은 아래와 같습니다.
        - 연락처 보기
        - 연락처 추가
        - 연락처 삭제
        - 연락처 변경(optional)

**Step 1-2 TableView의 사용**
- Table View를 활용하여 연락처 목록을 화면에 표시합니다
- 각 행의 cell은 subtitle style을 사용합니다
- 각 행(row)에 표시할 항목
    - 이름, 나이, 연락처
        - 이름옆에 괄호로 나이가 위치합니다.
        - 연락처는 이름(나이) 아래에 위치합니다.

## 🤔고민이 되었던 점

### 테이블뷰에 셀을 어떻게 구성해야할지 고민했습니다.
- 테이블뷰에 셀의 제약을 스토리보드로 구현할지 코드로 구현할지 고민을 했었습니다. 스토리보드로 오토레이아웃 제약을 주게되면 코드리뷰에 어려움이 있을수도 있고, 오토레이아웃 제약을 주기 어려운 점이 있다고 생각하여 코드로 구현을 하였습니다. 
```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        let item = contact[indexPath.row]
        
        var content = cell.defaultContentConfiguration()
        
        content.text = item.nameAge
        content.secondaryText = item.phoneNumber
        
        cell.contentConfiguration = content
        
        return cell
      }
```
### 테이블뷰에 구성되어 있는 정보들을 어떻게 구현해야할지 고민했습니다.
- UI에 구성되어 있는 연락처정보들을 Contact 구조체에 배열에 정보들을 지정해줘야 할지, JSON 데이터형식으로 정보들을 입력해 파싱해서 정보들을 불러들어올지에 대한 고민을 했었습니다. 구조체내에 정보들을 배열해놓으면 가독성측면에서 안좋아보여 JSON데이터 형식으로 정보들을 읽어오는 식으로 구현해줬습니다. JSON파일형식을 만들어 Assets에 파일들을 저장해놓고, Decoder를 통해 데이터형식을 코드로 읽어오게 디코딩하여 decode메서드를 통해 데이터를 읽어오는식으로 파싱해서 정보들을 불러오는 식으로 구현해줬습니다.
```swift
extension ViewController {
    func parse() {
        guard let asset = NSDataAsset(name: "data") else { return }
        
        do {
            contact = try JSONDecoder().decode([Contact].self, from: asset.data)
        } catch {
            print(error.localizedDescription)
        }
    }
}
```

### 테이블뷰 셀을 클릭했을때 회색으로 변하지 않게 어떻게 구현해야할지 고민했습니다.
- 일단 테이블뷰의 꼭필요한 객체인 데이터소스와 델리게이트가 무엇인지를 알아봤습니다. 데이터 소스는 테이블 뷰를 생성하고 수정하는데 필요한 정보를 테이블뷰 객체에 제공하고, `func tableView(UITableView, cellForRowAt: IndexPath)`, ` func tableView(UITableView, numberOfRowsInSection: Int)`메서드를 필수로 구현해줘야 합니다. 델리게이트는 테이블뷰의 시각적인 부분 수정, 행의 선택 관리, 액세서리뷰 지원 그리고 테이블뷰의 개별 행 편집을 도와준다. 또한, 델리게이트 메서드를 활용하면 테이블뷰의 세세한 부분을 조정할 수 있다라는 점이 있어 여기서 셀을 클릭했을때 회색으로 변하지 않게 구현을 해줬습니다.
```swift
extension ViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
}
```

## 🙏조언을 구하고 싶은 점 

### 테이블뷰와 셀을 코드로 구현하는 과정 중 생긴 의문 
- Cell의 id를 지정해줘야하는 상황에서, 저희는 코드로 구현을 하려고 했기 때문에 `CustomCell` 클래스를 만들어 Cell의 id를 코드로 지정해주어야 했습니다. 
    ```
    class CustomCell: UITableViewCell {
        static let identifier = "cell"
    }
    ```
    그 후 tableView에 register를 통해서 tableViewCell를 등록했습니다. 
    ```
    table.register(CustomCell.self, forCellReuseIdentifier: "cell")
    ```
    이 방식으로 테이블 뷰를 만들고 id등록을 통해 tableView에 register를 진행했는데, 잘 진행한건지, 혹시 코드로 셀을 출력할 수 있는 더 괜찮은 방법이 있을 지 궁금합니다.

2024-01-07 23:53 UTC, FirstDo requested changes
두분 안녕하세요!
연락처 관리앱 잘 부탁드립니다!

## 칭찬 드리고 싶은점

- 스토리보드를 사용하지 않고, 코드로 TableView의 레이아웃을 잡으신점이 좋았습니다
두분 의도대로 확실히 리뷰하기가 편하네요!!
- 모델을 Json파일로 만들고, 그 파일을 파싱해서 사용한 점이 좋았습니다
- PR본문을 잘 써주셔서, STEP의 요구사항을 저도 명확히 알고, 리뷰할 수 있어서 좋았습니다

## 질문에 대한 답변

### Q. 테이블뷰와 셀을 코드로 구현하는 과정 중 생긴 의문

코맨트에 자세히 써놨습니다!

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/AppDelegate.swift
> +}
주석들을 지워주고 긴 매서드들은 개행해서 정리하면 좀 더 깔끔하게 보일것 같아요!

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +class ViewController: UIViewController {
`ViewController` 보단 조금 더 역할에 어울리는 이름이 붙이는게 좋겠습니다
추가로 상속될 필요없는 모든 클래스에는 성능, 가독성 측면에서 final 키워드를 붙이는 습관을 들이시면 더 좋을것 같네요!

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/SceneDelegate.swift
> +}
마찬가지로 주석들을 지워주고 긴 매서드들은 개행해서 정리하면 좀 더 깔끔하게 보일것 같아요!

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Contact.swift
> +}
모델 만드신것 좋습니다
특히 연산프로퍼티로 nameAge라고 만드신것이 좋아요
다만 nameAndAge가 더 나을것 같아요

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +extension ViewController: UITableViewDelegate {
델리게이트 사이에는 마크다운으로 구분해주시면 더 좋습니다!

/// 원래 코드

MARK: - UITableViewDelegate

/// UITableViewDelegate 코드

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +final class ContactManager {
ContactManager를 만드신것 좋습니다
이 친구는 다음스텝에서 쓰려고 만들어 놓으신거겠죠??

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/View/CustomCell.swift
> +}
static let으로 id를 고정하시것은 좋지만 이렇게 쓰신다면, Cell이 늘어나면 무조건 헷갈리고 실수하게 됩니다.
보통 아래처럼 하는 편입니다

+ final 키워드를 추가해주세요!

```swift
extension UITableViewCell {
  static var identifier: String {
      return String(describing: Self)
   }
}

ableView.dequeueReusableCell(withIdentifier: CustomCell.self , for: indexPath)
```

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    private let table = UITableView()
보통 UI관련 네이밍은, 아래처럼 하는 편입니다

table`View`
collection`View`
title`Label`
done`Button`

View, Label, Button과 같이 접미사로 붙여주는게 좋습니다~

그리고 프로퍼티 초기화 시점에 초기화 할 수 있는 속성은 그때 하는게 가독성 측면에서 좋다고 생각합니다

```swift

private let tableview: UITableView = {
  let view = UITableView()
  view.translatesAutoresizingMaskIntoConstraints = false
  /// 기타 tableview 관련 설정
  return view
}()
```

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    private var contacts: [Contact] = []
현재 테이블뷰가 모델을 사용하고 있습니다.
모델이 업데이트 되면? 당연히 View도 업데이트 되어야 겠죠?
contacts가 변할때마다 tableview를 업데이트 시키는 방법을 생각해보시고 적용해보시면 좋겠네요 :)

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +        table.trailingAnchor.constraint(equalTo: view.safeAreaLayoutGuide.trailingAnchor).isActive = true
코드로 레이아웃을 잡으셨군요!!

`translatesAutoresizingMaskIntoConstraints` 는 대체 뭘까요?

또 지금 방식도 상관은 없으나 NSLayoutConstraint.activate 형태를 쓰는게, 좀더 같은 View끼리 묶어줘서 가독성에 좋은것 같습니다
```swift
      NSLayoutConstraint.activate([
        // tableview 관련코드
      ])

      NSLayoutConstraint.activate([
        // collecitonView 관련코드
      ])
```

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +        table.register(CustomCell.self, forCellReuseIdentifier: "cell")
프로퍼티 초기화 시점에 할 수 있을것같아요!
또 Identifier도 다른 코맨트 참고해서 바꿔주심 좋을것 같습니다

2024-01-07 23:53 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    }
json에서 파싱해서 가져오는거 정말 좋습니다!
추가로 개선의 여지가 있는부분을 말씀드리면

1. 이게 ViewController에 있어야할까요?
- ContactManager와 같은 맥락입니다

2. 좀 더 일반적으로 만들수 있을것 같아요
- 현재는 이름이 "data"고, 타입이 [Contact]인 친구만 파싱이 가능한데요, 이 두가지를 매개변수로 받으면 좀더 일반적인 parser를 구현하실 수 있을것 같아요

3. 에러처리는 alert이라도 띄우는게 좋겠네요

2024-01-08 01:17 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +final class ContactManager {
넵 맞습니다! 현재 `STEP1` 명세서에서는 해당 모델로 UI구현이 없어서 다음스텝에서 구현될예정입니다😄

2024-01-08 02:38 UTC, kimdj1102 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/CustomCell.swift
> +}
```
final class CustomCell: UITableViewCell {
    static var identifier: String {
        return String(describing: self)
    }
}

let cell = tableView.dequeueReusableCell(withIdentifier: CustomCell.identifier , for: indexPath)
```
수정완료하였습니다!

return값에서 describing에  `Self`를 넣어주었더니 오류가 나서 `self`로 넣어주고 withIdentifier 값을 `CustomCell.identifier`로 변경해주었습니다.

2024-01-08 07:18 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    }
json에서 파싱한 타입메서드를 모델파일에 분리하여 뷰컨트롤러에서 타입메서드를 불러오는 식으로 구현해줬습니다. assetName과 data정보가 오류가 있을때 UIViewController의 확장을 통해 알럿창을 띄워 확인할수 있게 구현해줬습니다.
```swift
struct AssetDecoder<Element: Decodable> {
    func parse(assetName: String) throws -> Element {
        
        guard let asset = NSDataAsset(name: assetName) else { throw DecoderError.assetName }
        
        guard let jsonData = try? JSONDecoder().decode(Element.self, from: asset.data) else { throw DecoderError.jsonData }
        
        return jsonData
    }
}
```
```swift
extension UIViewController {
    func showErrorAlert(_ error: Error) {
        let alertTitle: String = "오류"
        var message: String {
            switch error {
            case DecoderError.assetName:
                return "에셋네임을 알수 없습니다."
            case DecoderError.jsonData:
                return "데이터를 알수 없습니다."
            default:
                return "시스템오류가 발생했습니다."
            }
        }
        
        let cancelTiltle: String = "취소"
        let retryTitle: String = "재시도"
        
        let alert = UIAlertController(title: alertTitle, message: message, preferredStyle: .alert)
        
        let cancelAction = UIAlertAction(title: cancelTiltle, style: .default)
        let retryAction = UIAlertAction(title: retryTitle, style: .default)
        
        alert.addAction(retryAction)
        alert.addAction(cancelAction)
        
        self.present(alert, animated: true)
    }
}
```

2024-01-09 04:28 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    private var contacts: [Contact] = []
UUID를 통해 각 연락처 정보들의 고유의 id를 넣어줘서 기존의 id가 수정하려는 id와 일치하면 정보가 수정이 되도록 코드를 구현해봤습니다. UI에서는 현재 STEP에서 구현하기 힘들어 구현한 모델로 추후 UI에서 기존의 정보들 업데이트가 되도록 구현할 예정입니다!
```swift
func update(contact: Contact) {
        let contactIndices = contacts.indices
        let editContact = contactIndices.filter { contacts[$0].id == contact.id }
        editContact.forEach { contacts[$0] = contact }
    }
```

2024-01-09 07:12 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    private var contacts: [Contact] = []
테이블뷰에서 사용되는 model이 업데이트 된다면
tableview 역시 reload되어야 한다는 말이었습니다..!

다음스텝에 적용해주심 될것같아요

```swift
private var contacts: [Contact] {
  didSet {
     self.tableview.reloadData()
  }
}
```

2024-01-09 07:14 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController.swift
> +    }
만드신 `AssetDecoder` 정말 좋네요..!

2024-01-09 07:37 UTC, FirstDo approved these changes
고생하셨어요 :)

츄가적인 부분은 다음스텝에서 더 개선해보도록 합시다!

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/AppDelegate.swift
> +    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) { }
주석정리나 개행은 정말 사소하지만 나중에 사전과제하실때 이런거 하나하나도 도움이 될 수 있을것 같아요

긴 매서드의 경우 보통 개행해주는 편입니다

```swift
func application(
  _ application: UIApplication, 
  didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
) -> Bool {
  // Override point for customization after application launch.
  return true
}
```

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactViewController.swift
> +final class ContactViewController: UIViewController {
바뀐이름 좋습니다!

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Contact.swift
> +    var nameAndAge: String {
good!

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/View/CustomCell.swift
> +}
제가 잘못썼네요 ㅋㅋ
좋습니다!

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactViewController.swift
> +        tableView.register(CustomCell.self, forCellReuseIdentifier: "cell")
`tableView.register(CustomCell.self, forCellReuseIdentifier: "cell")`
이친구도 초기화 시점에 할 수 있지 않을까요?

+
lazy 프로퍼티를 사용하면 아래 작업들도 초기화 시점에 할 수 있습니다 (바꾸라는 말은 아닙니다. 그냥 취향차이)

```swift
tableView.dataSource = self
tableView.delegate = self
```

lazy 키워드에 대해 찾아보고 장단점을 파악해보시면 좋을것 같아요!

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactViewController.swift
> +        tableView.register(CustomCell.self, forCellReuseIdentifier: CustomCell.identifier)
보통 이렇게 많이쓰는 편입니다

조금더 추가하자면
tableview를 extension해서 아래 매서드를 만들면 좀 더 편하게 사용할 수도 있겠네요!

`tableview.register(CustomCell.self)`

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ViewController+.swift
> +}
좋습니다! 다만 재사용성이 떨어지는 문제가 있겠네요

title이나 action이 바뀐다면..?
매서드를 하나 더 만들어야겠죠?

이러면 결국 매서드 개수가 계속 늘어나게 됩니다.
모든 데이터를 매개변수로 받아서 Alert을 생성하는게 좋습니다

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Error.swift
> +}
에러타입을 정의하셔서 사용하신 점 너무 좋습니다

2024-01-09 07:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +    }
이 코드는 훨씬 간단하게 쓸 수 있지 않을까요?

결국 배열에서 바꿀려는 contacts를 찾아서 수정하면 되는거니까 아래처럼 쓰면 될것 같아요

```swift
      if let targetIndex = contacts.firstIndex(where: { $0.id == contact.id }) {
        contacts[targetIndex] = contact
      }
```

2024-01-09 07:38 UTC, merged