연락처 관리 앱 [STEP 1] 폴, 세제
tasty-code/ios-contact-manager-ui pull request #56
Opened 2024-01-05 07:57 UTC by suojae3

# Tasty Code

**리뷰어:** <br/>
@cherrishRed

**버드:** <br/>
@earths-voluble
@suojae3

안녕하세요 Red!
첫번째 PR 잘부탁드립니다 ☺️

---

<br/>

## 프로젝트 소개

### 파일 구조

<pre>

ios-contact-manager-ui/
│ 
├── App/
│    ├── AppDelegate.swift
│    ├── SceneDelegate.swift
│    └── Container.swift
│
├── View/
│    ├── HeaderView.xib
│    ├── HeaderView.swift
│    ├── TableView.xib
│    └── TableView.swift
│
├── ViewController/
│   └── PhoneBookViewController.swift
│
└── Model/
     ├── PhoneBook.swift
     └── User.swift

</pre>

### 다이어그램

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/126137760/2d1c4793-3b30-4bce-bc49-590013203c00)

---

<br/>

## 고민한 부분

### 객체간의 의존성을 최대한 낮추어보기

####  의존성을 관리하는 컨테이너 객체 사용

```swift 
//SceneDelegate.swift
Container.shared.bind(service: PhoneBook.self) { _ in
    return PhoneBook()
}
        
Container.shared.bind(service: PhoneBookViewController.self) { resolver in
     let phoneBook = resolver.resolve(PhoneBook.self)
     let phoneBookViewController = PhoneBookViewController()
     phoneBookViewController.phoneBook = phoneBook
     return phoneBookViewController
 }
        
let phoneBookViewController = Container.shared.resolve(PhoneBookViewController.self)
```

장점
1. 하나의 객체가 의존성을 관리함으로써 향후 의존성 주입된 객체를 사용할 때 실수를 줄일 수 있습니다
2. 향후 테스트 코드를 작성하게 된다면 Mock 객체를 만들어 넣을 수 있어 테스터블한 코드에 기여할 수 있습니다
3. 의존성이 복잡해질 경우에도 단순한 로직(`bind` - `resolve`)으로 대처할 수 있습니다

단점
1. 추상화 레벨이 높아져 코드가 다소 복잡해집니다.
2. 기본적으로 싱글톤이기 때문에 안티패턴으로 이어질 수 있습니다
 
짝과 현장에서 충분한 의사소통을 교환할 수 있는 환경이었기 때문에 단점보다는 장점이 더 크다 생각되어 사용하게 되었습니다.

#

### categorizedContactInfo[Int:User]의 구현

#### 정렬 및 검색 등의 기능 추가를 위한 구조
추후 연락처를 가나다 순으로 정렬하기 위해 일단 가나다순의 섹션을 정의했습니다. 아직 해당 초성 이름이 없는 섹션도 표시되는 등의 문제가 있어서 리팩토링 등을 통해 개선하고, 가나다순 정렬기능을 도입하고자 합니다.
또한 연락처 앱인 만큼 검색 기능을 구현하기 위한 안배가 필요하다고 생각했습니다. 마침 저희는 한글 초성 순의 섹션도 구현하고 있었기에, 한글 초성 섹션에 맞게 파싱되는 김에 검색 시에도 초성 섹션 내부에서만 검색하도록 한번 필터링을 하면 검색 시행 횟수를 줄일 수 있지 않을까 하는 생각을 하게 되었습니다. 그 결과 categorizedContactInf는 [Int : [User]]의 형식으로 구현되었습니다.
해당 딕셔너리의 키값인 Int는 초성 섹션과 대응이 되고, 초성 섹션에 해당하는 초성의 연락처들이 [User] 배열에 들어가게 됩니다.

#### 이중구조의 문제점
하지만 결론적으로 이와 같은 딕서너리-배열의 이중 구조는 Step1의 명세사항을 충족하기는 충분했지만 테이블뷰와 섹션을 구현할 때의 접근에 애로사항을 초래했고, 이는 인터페이스 구현의 어려움으로 이어졌습니다. 난해한 접근으로 인해 섹션 인터페이스의 정렬 등을 완전히 해결할 수 없었고, 때문에 비어 있는 섹션 바가 계속 표시되고 있습니다. 검색 시의 약간의 효율 개선에 비해서 사이드이펙트가 크다고 판단되어 현재는 구조적인 리팩토링을 고민 중에 있습니다.

새롭게 알게 된 점
TableViewCell에서 chevron이나 title-subtitle등의 설정이 미리 정의되어 있다는 사실. 많은 커스텀이 들어가지 않는 경우는 기본 설정만으로도 깔끔하고 통일성있는 UI 구현이 가능할 것 같습니다.

2024-01-05 19:22 UTC, cherrishRed requested changes
안녕하세요! 
폴 세제 수고 많이 하셨습니다. 
이번 프로젝트 잘 부탁드립니다. 😆

### 🍑 페어 프로그래밍을 지켜주세요.  페어가 쉽지 않다는 것을 알지만, 그래도 최대한  한사람 한사람 번갈아 가면서 커밋을 남겨주세요. 

### 🍑 구현 요구사항을 지켜주세요.
우선 두분이 열심히 코드를 작성했고 연락처 관리 앱에 들아가야 할 기능은 무엇일까? 생각을 많이 하셨다는 것 알고 있습니다. 
그렇지만 지금 구현한 내용이 구현 요구사항과 조금 다릅니다. 
구현 요구 사항에는 없지만, 실험을 해보고 싶은 마음 이해합니다.
하지만, 지금의 경우 추가 구현이 전체 코드에 너무 많은 영향을 미치고 있는 것 같습니다. 

현업으로 따지면, 기획자 디자이너의 요구사항을 지켜야 하는 것과 같습니다. 기획이 이상한데… 라고 생각할 때도 있고 이런 기능이 있었으면 좋겠다 싶을 때도 있지만, 팀으로 이뤄지는 일이기 때문에 각각의 역할이 있습니다. 개발자는 우선 요구사항대로 개발해야 합니다.

가 나 다 순으로 이름을 정렬하는 기능을 넣으셨지요.
섹션을 나눠본 것에는 칭찬드립니다. 

그런데, 영어로 이름을 가진 사람은 어떻게 되는 걸까요?  ㄱ 이름인 사람들 안에서의 정렬을 어떻게 이루어지는 걸까요?

그리고 이중구조가 table view 관리를 힘들게 만들고 있다는 점을 인지하셨으니, 이부분과 같이 구조를 바꿔 보는 것을 추천드립니다! 검색 기능을 때어내라! 이런게 아니라, 요구사항을 다 구현하고 넣어도 늦지 않다 입니다. 

### 🍑 객체의 의존성
컨테이너를 만들어서 의존성을 관리하셨군요! 직접의존성을 관리하는 객체를 만들다니! 좋은 시도 입니다! 
그런데, 말해주신 장점도 단점도 저는 이 코드에서는 체감적으로 느끼진 못했습니다. 저에게 설명을 부탁드립니다.  컨테이너를 쓰면 이런 장점이 있다. 라는 글이 아니라,  직접 코드안에서 쓰면서 느낀 장단점을 듣고 싶습니다. 

나머지 사항들은 댓글에 남겨 놓았습니다. 
수고 많으셨습니다!

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/App/AppDelegate.swift
> +
사용하지 않는 메서드들은 지우시는 것이 좋습니다!

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/User.swift
> +}
userID 를 만들고 UUID로 하셨군요! 너무 좋습니다 👏🏻👏🏻👏🏻

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/View/HeaderView.swift
> +    }
이 메서드가 해주는 역할은 무엇인가요?🤔

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/View/HeaderView.swift
> +    }
header view 를 xib로 구현하고 연결하셨군요! 좋습니다!
그런데, `setupHeaderView` 를 extension 에 구현한 이유는 무엇일까요?

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/View/TableViewCell.swift
> +}
`TableViewCell` 네이밍이 너무 일반적인 것 같습니다. 
전화번호부 table view 에 사용하는 cell 의 용도를 강조한 네이밍을 지어보는 것은 어떨까요?

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        tableView.dataSource = self
class 내부에 직접적으로 private func 으로 구현하지 않고 private extension 으로 빼서 구현한 이유는 무엇인가요?

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        size.width = UIScreen.main.bounds.width
이 사이즈는 어떻게 정해지게 되는 건가요?

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +    }
UITableViewDataSource 를 활용하셨군요! 너무 좋습니다!

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: TableViewCell.reuseID, for: indexPath) as! TableViewCell
as! 는 사용하지 말아주세요.

2024-01-05 19:22 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        let userNumber = user?[indexPath.row].phoneNumber
user?[indexPath.row] 가 3번 반복으로 들어가 있는데, 조금 더 깔끔하게 바꿔볼까요?

2024-01-08 01:20 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/App/AppDelegate.swift
> +
사용하지 않는 메서드 제거 완료했습니다! 감사합니다

2024-01-08 01:24 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/HeaderView.swift
> +    }
위 메서드의 역할은 헤더뷰의 초기 사이즈를 잡아주는 역할을 수행합니다

스토리보드에서 헤더뷰의 기본 사이즈를 잘잡아준다면 따로 써주지 않아도 되지만
혹시 모를 스토리보드에서의 실수 (스토리보드에서 높이를 144로 잡아야하는데 130으로 잡아준다던가 등)를 한 번 더 잡아줄 수 있습니다.

2024-01-08 01:29 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/HeaderView.swift
> +    }
저의 뇌피셜일 수도 있지만.. ㅇㅅㅇ;
제가 생각하기에 코드는 마치 글을 쓰듯이 작성해야한다고 생각합니다. 이때 Extension을 글의 문단을 나누어 주는 역할로 사용했습니다.
하나의 문단에는 하나의 주제만 들어가야 한다 생각했고 첫 문단에는 프로퍼티 초기화와 deinit메서드, Headerview의 초기셋팅의 내용은 Extension으로 나누어 작성했습니다

2024-01-08 01:35 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        tableView.dataSource = self
하나의 문단에는 하나의 주제만 들어가야 한다 생각했습니다! Class 내부에는 프로퍼티 초기화 및 deinit 메서드를 넣고 이외의 주제는 Extension을 통해 구분해주었습니다

2024-01-08 02:03 UTC, earths-voluble commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: TableViewCell.reuseID, for: indexPath) as! TableViewCell
as?로 대체 후 guard let으로 바인딩했습니다~

2024-01-08 02:03 UTC, earths-voluble commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        let userNumber = user?[indexPath.row].phoneNumber
guard let 바인딩에 user상수를 포함시키고 [indexPath.row] 삽입해서 반복적인 바인딩과 할당을 제거했습니다.

2024-01-08 03:55 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        size.width = UIScreen.main.bounds.width
`systemLayoutSizeFitting`란 호출하는 뷰의 내부크기를 계산한뒤 결과를 반환해줍니다.
이 메서드의 특징은 오토레이아웃이 적용된 크기를 계산해서 얻을 수 있다는 점입니다.

이 메서드를 활용해 UIViewController에서 오토레이아웃에 따라 변경되는 Width값을 넣어줌으로써 
헤더뷰의 사이즈를 잡아주었습니다


**[질문]**
systemLayoutSizeFitting에는 두 가지 파라미터가 있습니다 
1. layoutFittingExpandedSize
2. layoutFittingCompressedSize

지금까지 아무생각없이 1번만 써오다 이번 기회에 두 파라미터의 차이점을 열심히 찾아보았으나 최소크기 최대크기에 대한 단서만 얻고 확 와닿는 차이를 못 찾았습니다. ㅠ 두 파라미터에 대한 차이가 궁금합니다!

2024-01-08 08:18 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +    }
감사합니다 ㅇㅅㅇ/

2024-01-08 08:20 UTC, earths-voluble commented on ios-contact-manager-ui/ios-contact-manager-ui/View/TableViewCell.swift
> +}
PhoneBookTableCell으로 수정하면서 HeaderView도 PhoneBookHeaderView로 수정해보았습니다!

2024-01-08 08:22 UTC, suojae3 commented
요구사항에 맞게 데이터 구조를 array형태로 수정했습니다!

사실 이번 스텝에서 Container를 사용하지않고 주입하는 것과 Container를 사용하고 주입한 것의 차이는 크게 없었습니다..ㅠ
하지만 의존성의 방향을 단방향으로 가자는 협의를 통해 향후 객체가 늘어나는 것을 컨테이너로 심플하게 묶을 수 있겠다는 생각을 하였습니다!

2024-01-10 03:49 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/PhoneBookViewController.swift
> +        size.width = UIScreen.main.bounds.width
[답변]
말 그대로 최소크기 최대크기에 대한 이야기 입니다.

UILabel로 예를 들면, "안녕" 이라는 텍스트가 들어있을 때랑 "안녕하세요" 라는 텍스트가 들어있을 때의 크기의 차이가 다릅니다. 
"안녕" 일 때 사이즈가 10, "안녕하세요" 는 25 정도라고 가정 해 봅시다. 
그런데, "안녕하세요" 라벨의 사이즈를 더 줄이면 안되는 것은 아니고 "안..." 이런식으로 나오겠지요. 
이런 차이 입니다.

2024-01-10 04:03 UTC, cherrishRed approved these changes
폴, 세제 두분 모두 수고하셨습니다!

코멘트 남겨 놓으신 부분 모두 잘 반영 된 것 같습니다!

container 부분은 숙제로 남겨두고, 앞으로 잘 생각해 보시면 좋을 것 같습니다!
Approve 드립니다!

2024-01-22 08:44 UTC, closed without merging