연락처 관리 앱 [STEP 1] 이안, 진
tasty-code/ios-contact-manager-ui pull request #57
Opened 2024-01-05 08:25 UTC by ianK0909

리뷰어: @Mino777

버드: @wlsdud_dev , @ianK0909

안녕하세요.

연락처 관리앱 프로젝트를 진행하는 Jin과 이안입니다.

첫번째 PR 보내드립니다!

요즘 감기가 많이 독한것 같아요. 감기 조심하시고

천천히 보신 후, 피드백 부탁드립니다.

---

<h3>요구 사항</h3>
Step 1-1 모델타입 구현

아래 내용 고려하여 Model 타입을 구현합니다.
연락처 관리앱은 사용자로부터 이름, 연락처, 나이에 대한 정보를 전달받습니다.
연락처를 관리하기 위해 필요한 기능은 아래와 같습니다.

- 연락처 보기
- 연락처 추가
- 연락처 삭제
- 연락처 변경(optional)

Step 1-2 TableView의 사용

Table View를 활용하여 연락처 목록을 화면에 표시합니다
각 행의 cell은 subtitle style을 사용합니다
각 행(row)에 표시할 항목
이름, 나이, 연락처
이름옆에 괄호로 나이가 위치합니다.
연락처는 이름(나이) 아래에 위치합니다.

---

<h3>질문사항</h3>

1 . 은닉화 방법의 차이

```
private var phoneNumber: String

var fetchPhoneNumber: String {
        return phoneNumber
}
```

phoneNumber 프로퍼티의 값을 읽기 위해  fetchPhoneNumber 메서드를 생성하여 get 하는 방식으로 구현했습니다.

이렇게 getter를 사용하는 것 처럼 할 수도 있지만 `private(set) `을 사용해 읽기만 허용해주는 방법도 있는데 어떤걸 사용하는것이 더 좋을까요?

2. error 출력 질문

```
    func jsonDecoder() {
        let decoder = JSONDecoder()
        guard let dataAssets: NSDataAsset = NSDataAsset(name: "Dummy") else { return }
        
        do {
            let dummyData = try decoder.decode([Contact].self, from: dataAssets.data)
            contactStorage.initalContact(contactData: dummyData)
        } catch {
            print(error.localizedDescription)
        }
    }
```

에러출력을 프린트로 출력을 하고 있습니다. 에러를 프린트로 말고 얼럿창으로 보여주게 하는게 더 좋은 방법 일까요?

2024-01-07 03:55 UTC, Mino777 requested changes
안녕하세요!! 이안, 진!

STEP 1 진행하시느라 정말 수고 많으셨습니다!!🥳

리뷰를 진행하기전에 제가 드리는 말들이 모두 정답이 아니라는걸 꼭 인지하시면 좋을 것 같아요!

학습을 하시면서 많은분들이 말씀하시겠지만, 코드에는 정답이 없답니다!

만약 제가 코멘트를 달았던 부분에 대해서 여러분들의 코드에 근거가 있고, 이게 더 나은 방향인 것 같은데 라는 생각이 드신다면 저를 설득시키고, 토론하는 과정 또한 저와 여러분 모두에게 정말 좋은 경험이 되실 것 같아요!

언제든지 궁금하신 점이 생기시면 바로바로 말씀해주세요😁

## 코멘트

### 칭찬 드리고 싶은 점
- TableView를 사용해보신 점👏
- json 형식의 Mock Data를 사용해보신 점👏
- Cocoa MVC 구조를 사용해보신 점👏
---------------------------

### 질문사항
> 은닉화 방법의 차이

아마 추후에 연락처 수정 기능 때문에 변수로 사용하신 것 같네요!
단순하게 생각해보시면 좋을 것 같아요! 외부에서는 온전히 읽기만 필요하고, 내부에서는 변경 가능성이 있다면 private(set)을 사용하는 것이 좋을 것 같고, 만약 약간의 가공이 필요한 상황이라면 연산프로퍼티로, 많은 가공이 필요하다면 메서드로 사용하는게 좋겠죠?!

그리고 TMI를 덧붙여보자면, 나중에 잘게 쪼개어진 아키텍처들을 사용하고, 백엔드의 데이터들을 사용하게 되면 private(set) 접근제어자를 거의 사용하지 않게 됩니다. 
데이터를 다룰 때 대부분 object 단위로 다루는 이유가 가장 크고,  DB -> DTO -> Repository -> Entity -> UseCase -> Interactor OR ViewModel 같이 프로세스가 잘게 쪼개져 있기에 애초에 이런 Model 까지 오기 전에 이미 가공되어서 initializer 에서 가공된 채로 초기화가 되는 경우가 대부분이라서 외부에서는 읽기만 필요하고, 내부에서는 변경 가능성이 있는 상황이 거의 오지 않아요! 그래서 왠만하면 데이터는 상수로만 사용하게 됩니다ㅎㅎ

> error 출력 질문

해당 로직으로 인해서 사용자에게 직접적인 영향이 아주 조금이라도 간다고 판단되면, 무조건 알럿으로 사용자에게 어떤 이유로 기능 동작이 되지 않는지 알려주어야 합니다!
그리고 이렇게 알럿을 띄워주어야 어떤 이슈가 생겼을 때 사용자가 개발자에게 어떤 에러가 발생했는지 쉽게 알려줄 수 있겠죠?!👍

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/AppDelegate.swift
> +    }
지금은 상관 없지만 나중에 기업 과제를 진행하거나 할 때 불필요한 줄바꿈, 주석들을 제거 해주면 첫인상이 좋아집니다ㅎㅎ

```swift
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        return true
    }

    // MARK: UISceneSession Lifecycle

    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
        return UISceneConfiguration(name: "Default Configuration", sessionRole: connectingSceneSession.role)
    }

    func application(_ application: UIApplication, didDiscardSceneSessions sceneSessions: Set<UISceneSession>) {}
}
```

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +        let decoder = JSONDecoder()
메서드 네이밍이 적절하지 않아 보여요!
어떤 동작을 하는 메서드는 동사로 시작하는것이 좋습니다.
load~ / decode~ + ContactData 요런 느낌이면 좋을 것 같아요! 한번 고민해보시고 네이밍을 수정해봅시다!

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +            print(error.localizedDescription)
PR 메세지에 남겨주신 부분이네요!
지금은 상관없지만, 에러처리는 당연히 알럿으로 하시는게 더 좋습니다!
알럿으로 바꿔볼까요~?

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +    }
contactManager.fetchContact(index:)를 두번 호출하고 있네요! 
물론 지금은 기능에 영향은 없지만 그래도 불필요한 메서드 호출은 줄여주는게 좋습니다!

```swift
let contact = contactManager.fetchContact(index: indexPath.row)
```

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +        return contactManager.contacteCount
오타 발견!

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    func initalContact(contactData: [Contact]) {
여기도 오타 발견!

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    private var storage: [Contact] = []
캡슐화 좋습니다👍

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
만약 storage 배열 범위를 벗어난 인덱스값이 들어오면 어떻게 될까요?!
인덱스에 대한 유효성 체크가 필요해보입니다!
방식은 여러분들이 한번 찾아보시고 좋아보이는 방식으로 해보세요!

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    func initalContact(contactData: [Contact]) {
그리고 어떤 동작을 하는 메서드의 경우 항상 동사로 하시면 좋습니다!
initialize~

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +final class ContactMananger {
final 키워드를 사용해보셨네요!

final 키워드에 대해서 설명해주세요!

그리고 class를 사용한 이유에 대해서도 알려주세요!
(잘못 사용하셔서 질문드리는게 아니고 한번 더 학습 해보시라고 질문드리는거에요!)

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/Contact.swift
> +struct Contact: Codable {
Codable을 사용해보셨네요!

Codable에 대해 설명해주세요!

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Assets.xcassets/Dummy.dataset/MOCK_DATA.json
json 형식의 Mock Data Set 활용 너무 좋습니다!👍👍

2024-01-07 03:55 UTC, Mino777 commented on ContactManager/ContactManager/Model/Contact.swift
> +    }
연산 프로퍼티의 네이밍의 경우 보통 동사를 붙이지 않습니다.
어떤 계산된 값을 리턴해주는 메서드, 연산 프로퍼티의 경우에는
~ed 같이 분사 형태로 시작해주거나, 아예 리턴 해주는 타입 자체로 네이밍 해주는게 좋습니다.
fetchedNameAndAge / nameAndAge 요런식으로요!

그리고 이렇게 And 가 붙는 경우는 경험상 Model에서 주는 것 보단, 받는 곳에서 각각의 데이터를 쓰는게 좋을 때가 많습니다.
뭔가 Model에서 이렇게 한번 더 정의하는 것이 많아지다 보면 개발자 입장에서 작업 영역의 뎁스가 한뎁스 늘어나는 느낌이 드실 수 있어요!

2024-01-09 05:18 UTC, wlsdud-dev commented on ContactManager/ContactManager/AppDelegate.swift
> +    }
[0d07de7](https://github.com/tasty-code/ios-contact-manager-ui/pull/57/commits/0d07de78ad19b07e5181803831ac36dfdb036d01) 불필요한 주석을 제거 했습니다! 생각하지 못한 부분인데 감사합니다

2024-01-09 05:20 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +        let decoder = JSONDecoder()
`loadContactData` 로 동사를 넣어 주어 메서드임을 명확하게 했습니다.

2024-01-09 05:25 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +    }
``` swift
let contact = contactManager.fetchContact(index: indexPath.row)
        
switch contact {
case .success(let data):
    cell.textLabel?.text = data.fetchedNameAndAge
    cell.detailTextLabel?.text = data.fetchedPhoneNumber
case .failure(let error):
    showAlert(title: "알림", message: error.errorMessage)
}
```
메서드를 한번만 호출 하도록 수정하였습니다. 메서드를 호출이 성능의 영향에 미친다는 미처 것을 생각 못했는데 감사합니다.

2024-01-09 05:28 UTC, wlsdud-dev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
``` swift
func fetchContact(index: Int) -> Result<Contact, ContactManangerError> {
    if storage.isEmpty { return .failure(.contactEmpty) }
    if (0 > index || storage.count <= index) { return .failure(.contactExist) }
    return .success(storage[index])
}
```
리절트 타입으로 범위를 벗어난 인덱스의 값을 처리 해주었습니다.

2024-01-09 05:31 UTC, wlsdud-dev commented on ContactManager/ContactManager/Model/ContactManager.swift
> +final class ContactMananger {
class에 final 키워드를 사용하면 다이나믹 디스패치에서 스태틱 디스패치가 되어 성능의 향상을 볼 수 있습니다.

`ContactManager` 를 class로 선언한 이유는 class는 참조 타입으로 다른 객체에서 해당 클래스를 사용할 경우 인스턴스의 주소값만을 넘겨주어, 주소값 만으로 해당 인스턴스의 접근해 사용할 수 있는 이점이 있습니다.

2024-01-09 06:20 UTC, ianK0909 commented on ContactManager/ContactManager/Model/Contact.swift
> +struct Contact: Codable {
Codable은 
typealias Codable =  Encodable + Decodable 

Encodable은 data 를 원하는 형태로 encoder 에서 변환해주려는 것
Decodable은 data 를 원하는 모델로 decode 해주는것

Class, Enum, Struct에서 모두 사용이 가능합니다.

2024-01-09 06:24 UTC, ianK0909 commented on ContactManager/ContactManager/Model/Contact.swift
> +    }
fetchedNameAndAge,  fetchedPhoneNumber로 연산프로퍼티 이름을 바꾸웠습니다.

구현조건에 각 행의 cell은 subtitle style을 사용합니다 라고 되어있어서  UI Component(라벨)을 추가하고싶은데 subtitle style 찾아봐도 방법을 찾지 못해서 수정하지못했습니다.

혹시 다른방법이 있을까요?

2024-01-09 06:44 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +            print(error.localizedDescription)
``` swift
func showAlert(title: String, message: String) {
    let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
    alertController.addAction(UIAlertAction(title: "확인", style: .default))
    self.present(alertController, animated: true)
}
```
얼럿 메서드를 만들어주고 에러일 경우 얼럿메서드를 호출 하여 얼럿창을 띄우려고 하였습니다.
하지만 `loadContactData` 메서드가 `viewDidLoad`에서 호출되기 때문에 뷰가 화면에 나오기 전에 얼럿을 호출 하여 의도대로 동작하지 않았습니다.
`viewDidAppear` 를 사용할 경우 뷰를 다시 로드 해야하는 문제점이 있었고 `DispatchQueue`를 사용하여 지연실행을 하면 의도대로 동작은 하지만 맞는 처리방식인지 의문이 들어 수정하지 못했습니다.

2024-01-09 06:50 UTC, ianK0909 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    func initalContact(contactData: [Contact]) {
initializeContact 로 수정하였습니다.

2024-01-09 08:35 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +            print(error.localizedDescription)
DispatchQueue를 사용하여 "지연실행"을 하셨다는건 asyncAfter 메서드를 통해 처리하셨다는 말씀일까요??

제가 봤을 땐 DispatchQueue.main.async{} 만 사용하셔도, 작업을 "지연"시키는 것이 아닌, 해당 작업을 메인 스레드의 이벤트 처리 큐에 "예약"해서 비동기적으로 안전하게 여러분들이 의도하시는 동작을 할 수 있을 것 같네요!

asyncAfter 메서드는 thread sleap을 통해 작위적으로 앱 동작을 지연시키는 것으로 예측하지 못한 오동작이 발생할 수 있기에 최대한 지양하는 것이 좋습니다!

2024-01-09 08:42 UTC, Mino777 commented on ContactManager/ContactManager/Model/Contact.swift
> +    }
아마 구현조건은 UITableView가 가지고 있는 기본적인 Cell Style들을 사용해보라는 취지인 것 같아요!
그럼 이미 기본적인 스타일은 사용해보았으니, 좀 더 챌린지를 해보면 좋을 것 같네요!

기본적인 UITableViewCell을 사용하지 않고, Custome UITableViewCell을 UITableView에 적용시켜서 여러분이 원하는데로 Cell의 UI Component를 배치해보면 좋을 것 같습니다ㅎㅎ

2024-01-09 08:51 UTC, Mino777 commented on ContactManager/ContactManager/Model/ContactManager.swift
> +    }
좋습니다!
또, Array를 Extension해서 subscript를 통해 옵셔널 반환 처리로 사용하는 방식도 있습니다ㅎㅎ 해당 방식도 알아두시면 좋을 것 같습니다~!

2024-01-09 08:54 UTC, Mino777 approved these changes
연초부터 STEP1 진행하시느라 정말 고생많으셨습니다~!

이번에 드린 코멘트들은 다 다음 스텝에서 수정하셔도 무방해보이기 때문에
머지하도록 하겠습니다!

STEP2도 빠이팅입니다!!💪💪💪

2024-01-10 02:11 UTC, merged