연락처 관리 앱 [STEP 1] 이지, 카일
tasty-code/ios-contact-manager-ui pull request #58
Opened 2024-01-05 08:30 UTC by Changhyun-Kyle

@junbangg
안녕하세요, 알라딘!
**`STEP1 PR`** 보내드립니다! 확인 부탁드립니다!

---
## 🧐 고민했던점

- ### `UUID()` 도입
    - 연락처를 관리할 때(변경 등) 이름, 나이, 전화번호로는 중복될 가능성이 있어 특정 연락처를 구분할 수 없다고 판단하여 고유한 `ID` 값을 가질 수 있게 `UUID()`를 도입하였습니다.
    
        ```swift
        struct Contact: Decodable {
            var id = UUID().uuidString
            let name: String
            let phoneNumber: String
            let age: Int
    
            var nameAndAge: String {
                return self.name + "(\(self.age))"
            }
        }
        ```
- ### 역할과 책임에 따른 객체 분리
    - `Contact` 구조체는 데이터의 모델에 해당합니다. 
    - `ContactManager` 클래스의 경우 연락처 및 연락처 관리를 담당합니다.
    - `ContactListViewController`는 뷰의 역할을 합니다.
    - `ContactTableViewCell` 테이블뷰 셀에 데이터를 표시해 줍니다.
    - 따라서, `ContactListViewController`는 `ContactManager`를 통해 모든 로직이 수행되고 `ContactManager`는 `Contact` 모델을 통해 데이터를 관리할 수 있도록 구현하고자 했습니다.

- ### `ContactTableViewCell` 파일 추가
    - `func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell` 구현 시 `cell`에 대한 관리를 해주기 위해 `UITableViewCell()`이 아닌 `ContactTableViewCell`을 생성하여 `cell`에 대한 구현 로직을 분리하였습니다.
    
        ```swift
        // ContactListViewController
        // 수정 전
        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
            let cellIdentifier: String = "contactCell"
            let cell: UITableViewCell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath)
            let contact: Contact = contactManager.contacts[indexPath.row]
            cell.textLabel?.text = contact.nameAndAge
            cell.detailTextLabel?.text = contact.phoneNumber
        
            return cell
        }
        // 수정 후
        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
            guard
                let cell: ContactTableViewCell = tableView.dequeueReusableCell(withIdentifier: ContactTableViewCell.cellID, 
                                                                               for: indexPath) as? ContactTableViewCell
            else {
                let cell: UITableViewCell = tableView.dequeueReusableCell(withIdentifier: ContactTableViewCell.cellID, 
                                                                          for: indexPath)
                cell.textLabel?.text = "셀을 불러오는데 실패하였습니다. 다시 실행해주세요."
                return cell
            }
            let contact = contactManager.contacts[indexPath.row]
            cell.setUpCell(contact: contact)
            return cell
        }
        ```

## 🤔 조언을 얻고 싶은 부분
- ### MVC 디자인 패턴?
    - 의존성 주입과 객체 분리에 대한 고민을 하며 `[Contact]` 및 비즈니스 로직을 어떻게 관리할 것인지 생각했습니다.  
    - 따라서, 연락처의 데이터를 담은 `[Contact]`는 `ContactListViewController`의 생성자를 통해 생성하고 `JSON` 데이터를 불러왔습니다.
    - 또한, 비즈니스 로직과 `ViewController`에서 표시할 데이터를 가공하는 부분을 모두 `ContactManager`에서 처리할 수 있게 분리했습니다.
    - 위와 같이 리팩토링을 하다보니,
        - `Contact` -> `Model`
        - `ContactTableViewController` -> `View`
        - `ContactManager` -> `Controller`
    - 형식으로 구분할 수 있다고 생각하는데 과연 올바른 판단인지 알라딘의 의견이 궁금합니다!
- ### `UITableViewCell` 타입 `custom initialize`
    - 아래 코드와 같이 `ContactManager`에 대한 의존성을 외부해서 주입하기 위해 생성자를 사용하였습니다.
        ```swift
        class ContactTableViewCell: UITableViewCell {
            static let cellID: String = "contactCell"
            private let contactManager: ContactManager
    
            init(contactManager: ContactManager) {
                self.contactManager = contactManager
                super.init()
            }
    
            required init?(coder: NSCoder) {
                fatalError("init(coder:) has not been implemented")
            }
    
            func setUpCell(row: Int) {
                let contact = contactManager.contacts[row]
                textLabel?.text = contact.nameAndAge
                detailTextLabel?.text = contact.phoneNumber
            }
        }
        ```
    - 하지만, `required init?`에서 `fatal error`가 발생하여 [관련 자료](https://vaibhavsingh-54243.medium.com/why-uitableview-cells-cant-have-a-custom-init-4caa8ab03a57)를 찾아보니 ***"사용자 정의 초기화를 구현 시 tableView에서 셀을 재사용할 수 없고 사용자 정의 초기화를 추가할 수 있더라도 셀에 대한 초기화가 한 번만 호출된 후 재사용될 수 있기 때문에 몇 가지 문제가 발생할 수 있다"*** 라고 확인했습니다. 이러한 경우, 의존성을 주입할 수 있는 방법이 있는 지 궁금합니다!
        ![image](https://hackmd.io/_uploads/r1Ned4S_T.png)

- ### `@IBOutlet` VS `Default Value`
    - `ContactTableViewCell` 구현 시 `@IBOutlet`을 연결하여 추가하는 방법과 `textLabel` 및 `detailLabel`로 구현할 수 있었습니다.
    - `@IBOutlet`으로 구현 시 장점은 데이터를 명확하게 주입할 수 있다는 것이고,
    - `Default Value`로 구현 시 장점은 `cell`의 스타일이 변경되어도 전체 데이터가 유실될 위험이 적다는 것이라고 생각합니다.
    - 이러한 경우, 어떤 방법이 더 효율적일 지 알라딘의 의견이 궁금합니다!
        ```swift
        // @IBOutlet 구현
        class ContactTableViewCell: UITableViewCell {
    
            static let identifier: String = "contactCell"
            @IBOutlet weak var titleLabel: UILabel!
            @IBOutlet weak var subtitleLabel: UILabel!
    
            func setupCell(contact: Contact) {
                titleLabel.text = contact.nameAndAge
                subtitleLabel.text = contact.phoneNumber
            }
        }
        // default value 구현
        class ContactTableViewCell: UITableViewCell {
            static let cellID: String = "contactCell"
    
            func setUpCell(contact: Contact) {
                textLabel?.text = contact.nameAndAge
                detailTextLabel?.text = contact.phoneNumber
            }
        }
        ```
- ### 연산 프로퍼티 네이밍
    - 현재 연산 프로퍼티를 사용하여 cell의 타이틀을 정의해주고 있습니다.
    - `contactTitle`과 `nameAndAge`라는 네이밍을 두고 고민을 했습니다.
    - `contactTitle`은 구현부에서 실제 사용되는 이름이지만 `name`과 `age`를 합치는 로직을 표현하기엔 불명확한 부분이 있고 `nameAndAge`는 명확하지만 `And`라는 키워드가 익숙치가 않습니다.
    - 이때, 어떤 네이밍이 괜찮을 지 알라딘의 의견이 궁금합니다!
        ```swift
         var nameAndAge: String {
            return self.name + "(\(self.age))"
        }
        ```

- ### `UIContextualAction.Handler`
    - 테이블뷰 셀 (연락처)의 삭제를 위한 스와이프가 실행 될때 동작하는 `handler`가 가진 파라미터 `action`, `sourceView` 역할이 궁금합니다. 
    - `view`와 `action`에서 어떤 역할을 하는지 알고 싶어 [공식문서](https://developer.apple.com/documentation/uikit/uicontextualaction/handler)를 확인했을 때 `action`은 선택한 액션에 대한 정보가 포함된 개체이고 `sourceView`는 액션이 표시된 보기라고 정의되어 있었습니다. 하지만, `handler` 내부에서 여러가지 시도를 해보았지만 변화를 찾을 수가 없었습니다. 따라서, 활용방법이 궁금합니다!
        ```swift
        // handler 정의
        typealias Handler = (action: UIContextualAction,
                             sourceView: UIView, 
                             @escaping (Bool) -> Void) -> Void
        // 시도한 방법들
        func tableView(_ tableView: UITableView, trailingSwipeActionsConfigurationForRowAt indexPath: IndexPath) -> UISwipeActionsConfiguration? {
            let deleteAction = UIContextualAction(style: .destructive, title: "삭제") { [weak self] action, view, complete in
                guard let self else { return }
                view.backgroundColor = .red
                action.backgroundColor = .systemPink
                contactManager.deleteContact(index: indexPath.row)
                tableView.deleteRows(at: [indexPath], with: .fade)
                action.title = "추가"
                complete(true)
                view.backgroundColor = .blue
            }
            return UISwipeActionsConfiguration(actions: [deleteAction])
        }
        ```

2024-01-08 15:55 UTC, junbangg requested changes
수고하셨습니다!!
요렇게 조렇게 고민한 흔적도 많이 느껴지고 
전반적으로 읽기 편한 코드였어요!! 
리뷰 내용 확인해주세요~

## 질문 주신 사항

> MVC 디자인 패턴?

고민 후 리팩토링하신 점 너무 좋습니다! 
근데 MVC를 어떻게 이해하고 계신지부터가 조금 궁금하네요!
- Model, View, Controller 가 각각 어떤것으로 이해가고 계신지 
- 그리고 Controller를 왜 ContactManager 라는 타입에게 역할을 맞긴건지 궁금해요!🙋🏻‍♂️

> UITableViewCell 타입 custom initialize

제가 리뷰했던 코드랑 첨부하신 코드의 형태가 조금 다르네요?! 
의존성 주입에 대해서 고민을 하고 계신것 같은데
의존성 주입을 왜 하고싶으신건지 궁금합니다!

> 이러한 경우, 의존성을 주입할 수 있는 방법이 있는 지 궁금합니다!

요렇게 질문을 주셨는데, 지금 리팩토링하신 방법 (메서드로 Contact 를 넣고 있는 형태)도
의존성 주입의 한가지 방법이긴 합니다!👍

> @IBOutlet VS Default Value

요 질문은 제가 제대로 이해를 못한것 같아요ㅜㅜ

> ContactTableViewCell 구현 시 @IBOutlet을 연결하여 추가하는 방법과 textLabel 및 detailLabel로 구현할 수 있었습니다.

Default Value (두번째 방법) 이 뭔지 다시 좀 설명해주실 수 있을까요???🙏

> 연산 프로퍼티 네이밍

자꾸 제가 역질문을 드리는것 같긴한데ㅎㅎ
해당 로직(name 이랑 age 합치는 로직) 을 모델에서 연산 프로퍼티로 구현하기로 결정하신 특별한 이유가 있을까요??
그리고 요 방법 말고, 고민하신 다른 방법도 혹시 있을까요??

개인적으로 네이밍은 좋은거 같아요!👍


## 개선되면 좋을것 같은 점! 

ViewController와 같은 코드는 조금만 커지고 기능이 추가되면 관리가 굉장히 까다로워져요! 
그래서 추후에 코드를 누군가가 볼때 이해하기 어려울 수 있어요ㅜㅜ
그래서 적당히 정리 정돈을 해주면 아주 좋을것 같은데 
mark 주석, 그리고 익스텐션을 활용해서 
ContactListViewController 를 한번 정리해보시면 어떨까 싶었습니다~ 
팁이 필요하시다면 언제든지 불러주십쇼

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    @IBOutlet weak var contactTableView: UITableView!
요건 private 안될까요?!

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            return cell
오오 요 셀이 나오는 케이스 테스트 해보셨을까요??

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            guard let self else { return }
오 self를 사용 안하고있지 않나요??🤔

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        let contactTdices = contacts.indices
오타 있어요!

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        let willEditContactID = contactTdices.filter { contacts[$0].id == contact.id }
오 이거 변수명만 봤을때는 bool 냄새가 나는데 배열 타입인거죠?🤔

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        willEditContactID.forEach { contacts[$0] = contact }
질문이 있어요! 혹시 여기서 willEditContactID라는 배열의 id가 제대로된 인덱스일 보장이 있을까요?🤔(인덱스 에러가 발생하면 앱 크래시날까봐요!)

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    static let identifier: String = "contactCell"
흠 이건 정답은 없지만 특별한 이유가 없다면 보통은 타입명을 identifier 로 그대로 사용하는 경우가 많아요!

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    @IBOutlet weak var subtitleLabel: UILabel!
Private 가능할것 같습니다🙋‍♂️

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    func setUpCell(contact: Contact) {
`with contact: Contact` 느낌으로다가 하는것도 가능하겠네요ㅎㅎ

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            contactManager.deleteContact(index: indexPath.row)
오잉 아닌데.! contactManager가 저장 프로퍼티라 여기 self 필요하지 않나요?
컴파일러가 뭐라 안하던가요?🤔

2024-01-08 15:55 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +final class ContactManager {
요거 클래스로 구현하신 이유가 있으신가용?? (틀렸다는것은 아닙니다~)

2024-01-09 01:55 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        let contactTdices = contacts.indices
앗.. 🤦‍♂️

2024-01-09 02:05 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            contactManager.deleteContact(index: indexPath.row)
[Swift 5.8 업데이트](https://github.com/apple/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md)에 따르면 `weak self` 키워드로 약한 참조로 `self` 캡처 시 `self`가 언래핑된 경우 암시적 `self`도 허용된다고 확인했습니다!(단, 중첩 클로저 제외)

2024-01-09 02:09 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            guard let self else { return }
아래 `contactManager.deleteContact(index: indexPath.row)` 메서드 호출 시 `contactManager`에 접근하기 위해 `self`가 사용됩니다!

2024-01-09 02:32 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    @IBOutlet weak var contactTableView: UITableView!
됩니다 ㅎㅎ

2024-01-09 02:49 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            return cell
단순히 `UITableViewCell()`을 반환하는 것이 아니라 예외처리를 해주기 위해 작성했던 로직인데 테스트를 해보진 못했습니다...
알라딘의 리뷰 이후 `identifier`를 수정해보고 다운캐스팅을 실패하게 해보면서 `else문`으로 분기되는 경우를 시도해봤는데 모두 실패했습니다...혹시 `else문`으로 분기되는 경우를 테스트해보려면 어떻게 해야하나요?

2024-01-09 03:39 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +    @IBOutlet weak var contactTableView: UITableView!
수정했습니다!

2024-01-09 04:04 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        willEditContactID.forEach { contacts[$0] = contact }
아직 이번 `STEP`에서 편집(수정) 기능은 없지만 해당 기능이 생긴다면 수정될 개체를 선택한 후 로직이 실행될 것이다라고 생각했습니다. 따라서 `.indices`를 통해 `contacts`의 `index range`를 받아오기 때문에 `index` 값에 대한 명확한 존재를 확인하고  해당 `index`를 순회하여 같은 `id`인 `contact` 객체를 찾는다고 생각하여 올바른 `index`일 것이다라고 판단했습니다. 하지만 알라딘의 리뷰 이후 `safe index`에 대한 키워드로 찾아보았는데 아래와 같이 수정할 수 있었습니다. 혹시 이런 부분에서의 예외처리를 말씀하신 것이 맞을까요?
```swift
    func editContact(contact: Contact) {
        let contactTdices = contacts.indices
        let filteredContact = contactTdices.filter {
            guard let contact = contacts[safe: $0] else { return false }
            return contact.id == contact.id
        }
        filteredContact.forEach { contacts[$0] = contact }
    }
}

extension Array {
    subscript (safe index: Int) -> Element? {
        return indices ~= index ? self[index] : nil
    }
}
```

2024-01-09 04:09 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        let contactTdices = contacts.indices
감사합니다. 수정했습니다!

2024-01-09 04:09 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        let willEditContactID = contactTdices.filter { contacts[$0].id == contact.id }
'수정될 연락처의 ID' 를 직역하여 indexOfContactToBeEdited 라고 하는것이 좋을까요? 너무 장황해 지는 느낌도 있네요..
contactIndexToBeEdited 로 하면 인덱스가 수정될 것이라고 해석될 수도 있는것 같아서.. 알라딘이라면 어떤 네이밍을 선호 하시는지 궁금합니다..!

2024-01-09 04:32 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    static let identifier: String = "contactCell"
```
    static var identifier: String {
        return String(describing: self)
    }
```

df

2024-01-09 04:40 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +final class ContactManager {
ContactManager가 소유한 연락처 저장소인 contacts 를 여러곳에서 참조할 수 있게 class로 선언했습니다.
값 타입인 struct로 선언하면 값 복사가 일어나 변경된 연락처 정보가 저장소에 반영되지 않는 이슈가 발생합니다!
또한, final 키워드를 사용해 다이나믹 디스패치를 하는 class를 static 디스패치를 할 수 있게 만들었습니다.

2024-01-09 06:26 UTC, Changhyun-Kyle commented
### MVC 디자인 패턴?
> 고민 후 리팩토링하신 점 너무 좋습니다! 근데 MVC를 어떻게 이해하고 계신지부터가 조금 궁금하네요!
> 
> * Model, View, Controller 가 각각 어떤것으로 이해가고 계신지
> * 그리고 Controller를 왜 ContactManager 라는 타입에게 역할을 맞긴건지 궁금해요!🙋🏻‍♂️

[Cocoa MVC 패턴](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Model-View-Controller/Model-View-Controller.html#//apple_ref/doc/uid/TP40010810-CH14)에서 
- `Model`: 데이터 포맷팅
- `Controller`: Model에서 받아온 데이터를 View와 상호작용하며 비즈니스 로직을 처리
- `View`: 사용자에서 보여지는 UI 요소

따라서, 현재 프로젝트를 보면 `Model(Contact)`은 `JSON 데이터`를 받아오기 위한 포맷팅이 되어있고, `Controller(ContactManager)`는 `model`에서 받아온 데이터를 가공하고, 마지막으로 `View(ContactListViewController)`는 `Controller`에서 받아온 데이터를 UI에 표시하는 역할을 한다고 생각했습니다.
- `Model(Contact)`: 연락처 데이터 모델
- `Controller(ContactManager)`: 연락처 관리(추가, 편집, 삭제, 불러오기)
- `View(ContactListViewController)`: 테이블뷰 및 네비게이션바 아이템

하지만, 다시 고민해보니 `Storyboard`가 `View`의 역할을 하고,` ViewController`가 `Controller`, `ContactManger`가 `Model`로 구분하는 것이 옳을 것 같다는 생각이 들었습니다. 사실 `UIViewController`타입 자체가 `View/Controller`로 나누기 모호한 느낌입니다...

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/101093592/2ecebe08-30de-4ec4-9ddf-93ecc7f597ee)

### UITableViewCell 타입 custom initialize
> 제가 리뷰했던 코드랑 첨부하신 코드의 형태가 조금 다르네요?! 의존성 주입에 대해서 고민을 하고 계신것 같은데 의존성 주입을 왜 하고싶으신건지 궁금합니다!

`ContactManager`의 `contacts`는 연락처를 담고 있는 중요한 데이터이기 때문에 수정에 대해서 개방적이면 안된다고 판단했습니다. 본래 의도는 contacts에 private 접근제어자를 사용하기 위해 의존성 주입을 하려고 했는데 지금 다시 보니 애초에 잘못된 로직이었던 것 같습니다...! 따라서, 아래와 같이 수정을 했는데 반환값이 있는 함수의 경우 네이밍을 어떻게 해야할지 궁금합니다.
```swift
// 선언부
// ContactManager
final class ContactManager {
    private var contacts: [Contact]
    {/*code*/}
    func contact(row: Int) -> Contact {
        return contacts[row]
    }

// 구현부
// ContactListViewController
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    {/*code*/}
        let contact = contactManager.contact(row: indexPath.row)
        cell.setUpCell(contact: contact)
        return cell
    }
```
 
### @IBOutlet VS Default Value
> Default Value (두번째 방법) 이 뭔지 다시 좀 설명해주실 수 있을까요???🙏

`UITableViewCell` 타입이 기본적으로 가지고 있는 `textLabel`과 `detailTextLabel`을 사용하는 방법 입니다!
![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/101093592/c1ef17bd-0814-486c-85da-e2f2cfeb08d0)

### 연산 프로퍼티 네이밍
> 자꾸 제가 역질문을 드리는것 같긴한데ㅎㅎ 해당 로직(name 이랑 age 합치는 로직) 을 모델에서 연산 프로퍼티로 구현하기로 결정하신 특별한 이유가 있을까요?? 그리고 요 방법 말고, 고민하신 다른 방법도 혹시 있을까요??

명세서에 제시된 연락처의 title이 이름(나이)로 되어 있어서 cell 생성 시 
```swift
contacts[indexPath.row].name + "(\(contacts[indexPath.row].age))"
```
위와 같은 로직을 수행해야 되기 때문에 가독성을 높이고 편리하게 사용할 수 있다고 생각하여 연산프로퍼티로 구현했습니다!

> ## 개선되면 좋을것 같은 점!
> ViewController와 같은 코드는 조금만 커지고 기능이 추가되면 관리가 굉장히 까다로워져요! 그래서 추후에 코드를 누군가가 볼때 이해하기 어려울 수 있어요ㅜㅜ 그래서 적당히 정리 정돈을 해주면 아주 좋을것 같은데 mark 주석, 그리고 익스텐션을 활용해서 ContactListViewController 를 한번 정리해보시면 어떨까 싶었습니다~ 팁이 필요하시다면 언제든지 불러주십쇼

현재 `ContactListViewController`에는 `tableView`를 구성하는 `extension`과 추후 구현될 `navigationBar Button`에 대한 액션이 추가되어 있는데  `mark 주석`, 그리고 `익스텐션`을 어떻게 활용할 수 있을 지 감이 잡히지 않습니다...아예 UI적인 요소와 메서드 부분을 `extension`으로 나눠야할까요??

2024-01-09 16:00 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            return cell
아하 질문 드린 이유는 41, 42 번째 줄에 dequeue를 시도하는게 의미가 없지 않나? 싶어서였어요~ 
이미 가드문에서 ContactTableViewCell.identifier 를 이용해서 dequeue 를 시도했을때 해당 로직을 타게 되는것일텐데
dequeue 가 여기서도 안되지 않을까 싶은거였습니당

보통(?)은 해당 가드문에서 `return UITableViewCell()` 을 하고 마는데
지금 해주신것처럼 에러 상황을 처리하고 싶으시다면 ErrorCell 을 따로 만들어서 그걸 dequeue 해서 표시하는 방법도 있을것 같네요!

2024-01-09 16:12 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            contactManager.deleteContact(index: indexPath.row)
헉...저거 아예 까먹었었네요😅 
저렇게 하면 캡쳐 후에 로컬 변수인지 전역 변수인지 한눈에 안보이는게 개인적으로 좀 마음에 안들었어서 self 붙여주는게 습관이 돼가지고..
알려주셔서 감사합니다ㅎㅎ

2024-01-09 16:20 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    static let identifier: String = "contactCell"
너무 좋네요!

2024-01-09 16:24 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        let willEditContactID = contactTdices.filter { contacts[$0].id == contact.id }
indexOfContactToBeEdited 로 가신거죠?? 
이게 근데 배열이긴 해서, indicesOfContactsToBeEdited 가 더 정확할것 같긴 하네욥
이건 사람마다 스타일이 다르긴한데, 저는 요정도는 괜찮다고 생각합니다ㅎㅎ
조금은 길어지더라도, 먼미래에 코드를 누군가가 봤을때 한눈에 어떤 값인지 알 수 있는게 더 중요하다고 생각해요!

2024-01-09 16:38 UTC, junbangg approved these changes

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactError.swift
> +enum ContactError: LocalizedError {
오 에러를 추가 해주셨군요 ..! 👍

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +        willEditContactID.forEach { contacts[$0] = contact }
너무 정확하십니다
safe 사용을 권장(?) 드리고 싶었어요..! 
뭐 사실 권장이라기 보다는, 지금 꼭 넣으실 필요는 없을 수도 있는데
앞으로 배열을 다루는 경우가 정망정말 많으실텐데 인덱스에 대한 실수, 또는 예상하지 못한 에러가 발생할 여지가 굉장히 많아요(나중에 누군가가 코드 수정했을때 실수 할 수도 있고)
그래서 safe 가 아니더라도, 인덱스 에러 크래시로부터 보호 받을 수 있는 방법에 대해서 고민하시면 좋을것 같아서 말씀을 드려봤어요!

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/AddContactViewController.swift
> +                                                      phoneNumberTextField: phoneNumberTextField)
크 요렇게 역할을 분리해준것 너무 좋네요..!

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateUI), name: Notification.Name("updateUI"), object: nil)
노티피케이션이 추가된 이유가 있나요??🤔

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateUI), name: Notification.Name("updateUI"), object: nil)
addObserver 를 했다면, remove 도 해주면 좋을것 같네요ㅎㅎ

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/AddContactViewController.swift
> +            NotificationCenter.default.post(name: NSNotification.Name("updateUI"), object: nil)
dismiss 실행 후에 노티 쏘는게 의도이실까요??(dismiss도 completion이 있는데 비교를 하신건지 궁금해서 질문 드립니다)

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +            let name = nameTextField.text,
guard 랑 let 사이에 이렇게 줄바꿈 처리는 두분이서 정하신 컨벤션 일까용?

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +        let trimmingName = name.replacingOccurrences(of: " ", with: "")
trimmedName이 더 알맞을것 같아요!

2024-01-09 16:38 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +struct InputValidator {
👍👍👍👍

2024-01-09 16:53 UTC, junbangg commented
> MVC 디자인 패턴?

MVC 의 한계에 몸소 부딪혀 보고 계신 점 너무 좋은것 같습니다:)
말씀하신대로 MVC에서 ViewController의 역할이 굉장히 크죠
근데 지금 해주신것처럼 각종 타입들 (ContactManager 라던지, InputValidator 같은) 을 통해 ViewController의 로직을 분리 해준것 너무 좋은것 같아요,,! 
이런 불편사항, 그리고 한계점들을 직접 느끼셔야 다른 아키텍쳐들이 왜 나왔고, 왜 쓰고, 어떻게 쓰는지까지 이해하시는 데 도움이 될것 같네요ㅎㅎ
👍👍👍

> 반환값이 있는 함수의 경우 네이밍을 어떻게 해야할지 궁금합니다.

일단 의존성 주입에 대해 고민하신거 👍
지금과 같은 방법도 좋습니다..! 보통 저렇게 제일 많이 하기도 하고요

네이밍 같은 경우에는 요건 어떠신가요?
```
    func contact(at row: Int) -> Contact {
        return contacts[row]
    }
```

> 연산 프로퍼티 네이밍... 위와 같은 로직을 수행해야 되기 때문에 가독성을 높이고 편리하게 사용할 수 있다고 생각하여 연산프로퍼티로 구현했습니다!

Contact 모델에 연산 프로퍼티로 구현하신거 좋은거 같아요..!
나중에 뷰모델이라는 것에 대해서 공부 해보시고 직접 구현하실때 또 고민이 되실것으로 보입니다ㅎㅎ 지금은 지금대로 좋은거 같아요 근데
코멘트에도 남겼지만 nameAndAge 였나요? 저는 괜찮은거 같아요


> @IBOutlet VS Default Value

아하 설명 감사합니다 이해했어요! 
물론, IBOutlet 이 필요 없는 경우에는 두번째 방법도 뭐 나쁠건 없어 보여요..!
그치만, 확장성이라는 고민이 들어오면 이야기가 달라질 수는 있을것 같아요
변경에 용이한게 어떤지 고민해보셔도 좋을것 같습니다. 
저는 개인적으로 IBOutlet 이던, 스토리보드 없이 개발할때 UI 직접 저장 프로퍼티로 두던, 명시적으로 나타내는 쪽이 좋은것 같긴 합니다..! 
답변이 됐을지 모르겠네용


> mark 주석, 그리고 익스텐션을 어떻게 활용할 수 있을 지 감이 잡히지 않습니다

결국에는 코드 가독성, 유지보수성과 연관된 이야기 인데요..!
보통은 코드를 여러 개발자와 함께 관리를 하다보니까, 최대한 잘 정리 해놓는게 좋습니다~
그래서 한가지 방법으로 mark 주석, 익스텐션을 말씀 드린건데
제가 생각한 정리된 코드의 예시를 하나 디스코드 DM으로 보내드릴게요!

2024-01-10 16:41 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +            let name = nameTextField.text,
네 맞습니다 ☺️

2024-01-10 16:48 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +        let trimmingName = name.replacingOccurrences(of: " ", with: "")
그렇네요.. 수정하겠습니다~

2024-01-11 02:09 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/AddContactViewController.swift
> +            NotificationCenter.default.post(name: NSNotification.Name("updateUI"), object: nil)
헉...dismiss가 completion이 있다는 걸 처음 알았네요..! 아래와 같이 수정했습니다. 감사합니다!
```swift
    @IBAction private func tappedSaveButton(_ sender: UIBarButtonItem) {
        let inputValidator = InputValidator()
        let validation = inputValidator.validateInput(nameTextField: nameTextField,
                                                      ageTextField: ageTextField,
                                                      phoneNumberTextField: phoneNumberTextField)
        switch validation {
        case .success(let contact):
            contactManager.addContact(contact: contact)
            dismiss(animated: true, completion: {
                NotificationCenter.default.post(name: NSNotification.Name("updateUI"), object: nil)
            })
            
        case .failure(let error):
            makeAlert(message: error.localizedDescription,
                      actions: [UIAlertAction(title: "확인",
                                              style: .default)])
        }
    }
```

2024-01-11 02:16 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateUI), name: Notification.Name("updateUI"), object: nil)
> 노티피케이션이 추가된 이유가 있나요??🤔

위 부분이 `Step2`에 해당하는 부분이었습니다...ㅠ
우선, `AddContactViewController`가 모달로 `present` 되기 때문에 `View Lifecycle` 내에서 뷰를 업데이트 할 수 없었습니다. 또한 `contactManager`에 대한 의존성을 `AddContactViewController`에 주입했기 때문에 `ContactListViewController`와 같은 객체를 바라보고 있습니다. 그러므로, 모달창이 `dismiss` 시 `tableView.reloadData()`를 해주기 위해 `NotificationCenter`를 추가했습니다! `Delegate Pattern`과 고민했는데 해당 사항은 `Step2 PR`에 반영하겠습니다!

> addObserver 를 했다면, remove 도 해주면 좋을것 같네요ㅎㅎ

수정했습니다. 감사합니다!

2024-01-12 06:46 UTC, merged