Step1
tasty-code/ios-contact-manager-ui pull request #60
Opened 2024-01-06 06:32 UTC by angryeon7

> 리뷰어 : @minsson
버드 : @angryeon7 (토미) @andyanappdev (앤디)
> 

안녕하세요. 민쏜-! 이번에 연락처 프로젝트를 같이 진행하게 된 Andy과 Tommy입니다!

읽어보시고 편하게 피드백해 주세요!! 잘 부탁드립니다 :)

벌써 2024년이네요-! 새해복 많이 받으세요☀️

---

## 프로젝트 구조

아키텍처는 모델 역할을 하는 ContactManager, 컨트롤러 역할을 하는 ContactsViewController 및 다양한 뷰 관련 클래스를 사용하여 MVC(Model-View-Controller) 패턴을 사용했습니다.
**Folder Structure**
```brash
├──  App
│   ├── Delegate
│   │   └── AppDelegate
│   │   └── SceneDelegate
├──  Models
│   │ └── Contact
│   │ └── ContactManager
│   │ └── ContactManagerImplement
│   │ └── ContactManagerMock
├──  View
│   │ └── ContactsView
│   │ └── ContactTableViewCell
├── ViewControllers
│   │ └── ContactsViewController
└───
```

## 프로젝트 설명 (Code Base UI)

1. **ContactManager protocol:**

- 역할: 이 프로토콜은 연락처를 관리하기 위한 계약을 정의합니다. 모든 연락처를 표시하고, 새로운 연락처를 추가하고, 특정 인덱스에서 연락처를 삭제하고, 특정 인덱스에서 연락처를 업데이트하는 방법을 선언합니다.
- 장점: 추상화 및 분리. 이 프로토콜을 준수하는 모든 클래스는 상호 교환적으로 사용될 수 있으므로 연락처 관리 구현을 쉽게 전환하거나 확장할 수 있습니다.

2. **ContactManagerMock 클래스**:

- 역할: `ContactManager` 프로토콜의 모의 구현입니다. 테스트 목적으로 만들어진 연락처의 목록을 제공합니다.
- 장점: 실제 데이터 소스와 상호 작용하지 않고 테스트하는 데 유용합니다.

3. **ContactManagerImplement 클래스**: 

- 역할: `ContactManager` 프로토콜의 구체적인 구현입니다. 런타임 중에 연락처를 동적으로 관리합니다.

4. **ContactsViewController 클래스:**

- 역할: 테이블 뷰에 연락처를 표시하는 역할을 담당하는 뷰 컨트롤러입니다.
- 뷰 컨트롤러는 UI 관련 작업에 초점을 맞추고 연락처 관리는 `ContactManager`에 위임됩니다.

## 조언을 얻고 싶은 부분 🤔

- 옵셔널 처리를 한 이유
    - 사용자가 모든 데이터를 입력한다는 확신이 없다고 판단했습니다.
    - 사용자로부터 입력받는 상황에 대한 정보를 전혀 알 수 없음.
    - 따라서 값이 없을 수 있는 상황을 대비하기 위해 옵셔널 처리를 사용하였습니다.
- 데이터 옵셔널 처리로 인한 이슈
    - 모델 자체에서 모든 값이 옵셔널인것이 데이터로서의 역할을 못한다고 생각합니다.
        - 데이터 무결성을 보장하기 위한 특정 기본값이 없다.
    - 정보가 부족한 경우 개발자입장에서 최대한 가능성을 열어두는것이 맞는지 궁금합니다.
    - 그 반대로 데이터 관점에서 바라봐야하는지 궁금합니다.
- cell의 subtitle style이 주어졌지만 ****Custom Cell**** 사용하는건 어떨까요?
    - 더 효율적이지 못한건가요..?
    - 오히려 변화에 더 유연하지않을까요?
- 목데이터의 사용
    - 목데이터 파일을 만들어서 모의구현을 하는것에 대한 조언을 얻고싶습니다.

### 기타 질문

지금 주어진 명세서에서만 집중하는게 좋을지 아니면 예상가능한 범위는 어느정도 고려해서 작성하는게 좋을지 궁금합니다.

2024-01-08 15:26 UTC, minsson requested changes
안녕하세요, 토미, 앤디!
새해 축하 인사 감사드려요. 두 분도 새해 복 많이 받으시기 바라요! ☺️

STEP 1 수행하시느라 고생 많으셨어요!

우선 프로젝트 구조, 프로젝트 설명, 조언을 얻고 싶은 부분을 무척 잘 정리해주셔서 감사해요! 코드를 파악하고, 어떤 게 궁금하신 건지 이해하는 데 많은 도움이 됐어요.

자세한 코멘트는 코드 코멘트로 상세히 남겨놓았으니 참고 바랄게요! 여기서는 `조언을 얻고 싶은 부분`에 대한 답변을 드려보려고 해요. 먼저 말씀 드리자면, 모든 코멘트, 답변은 제 개인적인 생각일 뿐이에요. 제가 잘못된 의견을 전달할 수도 있으니, 늘 비판적인 자세로 제 코멘트를 바라봐주셨으면 좋겠어요! 만약 '이게 정답이다!'라는 게 있다면 그렇게 써놓을게요. (그럴 일은 없겠지만요.)

>- Contact 옵셔널 처리를 한 이유
>  - 사용자가 모든 데이터를 입력한다는 확신이 없다고 판단했습니다.
>  - 사용자로부터 입력받는 상황에 대한 정보를 전혀 알 수 없음.
>  - 따라서 값이 없을 수 있는 상황을 대비하기 위해 옵셔널 처리를 사용하였습니다.

> - 데이터 옵셔널 처리로 인한 이슈
>   - 모델 자체에서 모든 값이 옵셔널인것이 데이터로서의 역할을 못한다고 생각합니다.
>     - 데이터 무결성을 보장하기 위한 특정 기본값이 없다.
>   - 정보가 부족한 경우 개발자입장에서 최대한 가능성을 열어두는것이 맞는지 궁금합니다.
>   - 그 반대로 데이터 관점에서 바라봐야하는지 궁금합니다.

> - 지금 주어진 명세서에서만 집중하는게 좋을지 아니면 예상가능한 범위는 어느정도 고려해서 작성하는게 좋을지 궁금합니다.

위 세 개의 질문은 모두 같은 질문이라고 생각해도 될 것 같아요.
위 질문은 결국 `앞으로 앱이 어떻게 될지 모르겠는데, 어디까지 고려하면서 개발해야 할까요?` 라는 질문이 될 것 같아요.

현업이라면 당연히 기획자, 디자이너와 최대한 자세히 소통해야하는 부분이에요. 정확히 어떤 기능인지 묻고 이해하고, 개발자로서 향후 예상되는 부분에 대해 질문해볼 수 있을 거예요. 가령, '이 기능과 관련해 추후 고도화 작업이 있다면 어떤 기능이 추가될 것인지, 이런이런 엣지케이스가 예상되는데 어떻게 하면 좋을지, 이런 상황도 예상되는데 이런 점도 혹시 고려하신 건지' 등에 대해 질문할 수 있을 거예요.

'최대한 가능성을 열어두는 것'이라고 말씀하셨는데, 최대한이라는 말에는 많은 비용이 발생해요. 어디까지 고려해야 최대한 가능성을 열어두는 게 될까요? 최대한 모든 상황, 모든 확장성을 고려하면 좋겠지만 당연히 그만큼 더 많은 고민과 개발 시간이 필요할 거예요. 당연히 적정선에서 멈추는 게 좋은데, 기획자, 디자이너와 대화하며 그 적정선을 찾아가면 좋을 것 같아요.

이와 관련해 YAGNI에 대해 찾아봐도 좋을 것 같아요. 

위와 같이 말씀드리기는 했지만, 아쉽게도 지금은 학습 과정이므로 소통할 기획자도, 디자이너도 없는 상황이에요. 그렇다면 새싹의 매니저 분들이나 리뷰어인 저와 소통했어도 좋았을 것 같아요. 기획안에 고려되지 않은 상황이 있다면, '이정도까지는 고려해서 개발하겠다, 아니면 이런 확장성까지 고려하는 건 오버엔지니어링이 될 수 있으므로 관련 기능이 없을 것이라고 가정하겠다' 등에 대해 논의하고 의사결정할 수 있었을 것 같아요.



> - cell의 subtitle style이 주어졌지만 Custom Cell 사용하는건 어떨까요?
>   - 더 효율적이지 못한건가요..?
>   - 오히려 변화에 더 유연하지않을까요?

이 질문은 정확히 어떤 방식으로 Custom Cell을 구현하시려는 건지 알 수 없어 답변 드리기가 어려울 것 같아요. 혹시 스스로 왜 써야 하는지 명확한 이유를 제시하기 어려워서 이런 질문을 주신 거라면, 이런 경우에는 Custom Cell을 쓰지 않아도 된다고 생각해요.

주어진 기본 API만으로는 원하는 걸 만들 수 없어서 Custom을 하는 건데, 지금은 기본 API만으로도 주어진 디자인대로 구현할 수 있으니까요.

다만 '학습 용도로 Custom Cell을 구현해보는 경험해보고 싶다'와 같은 목적이 있다면 사용해봐도 좋다고 생각합니다.

> - 목데이터의 사용
>   - 목데이터 파일을 만들어서 모의구현을 하는것에 대한 조언을 얻고싶습니다.


지금은 ContactManager 프로토콜의 구체 타입인 ContactManagerImplement, ContactManagerMock은 contactList의 값만 다르지, 나머지는 모두 동일한 상황이에요. 

현재 관점에서만 본다면, 저 개인적으로는 불필요한 구현이라고 생각해요. 저라면 ContactManagerMock 객체 없이 ContactManagerImplement에 mock 데이터를 넣어놨을 것 같아요. 즉, 지금의 ContactManagerImplement에 ContactManagerMock의 코드가 들어가야 한다고 생각해요. ContactManagerMock은 필요하지 않고, 이에 따라 ContactManager 프로토콜도 없어도 될 것 같고요.

현재 ContactManagerMock에 넣어놓으신 contactList의 값들은 결국 앱이 완성되기 전에 UI를 보며 작업하기 위한 임시 수단이라고 생각해요. 나중에는 결국 없어질 값들이고요. 그렇다면 그냥 구현 과정에서는 ContactManagerImplement에 넣어놓고, 나중에 제거해주면 될 것 같아요.

일반적으로 지금 구현해주신 것처럼 프로토콜로 추상화하고, 이를 채택한 구체 타입과 Mock 타입을 만드는 건 테스트를 진행하기 위함이에요. 관련해서 의존성 주입에 대해 검색해보셔도 좋을 것 같아요. 이 부분은 차차 알아가시면 좋을 것 같습니다!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/App/AppDelegate/AppDelegate.swift
> +
불필요한 주석, 개행 등은 제거해주셔도 좋을 것 같아요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/App/AppDelegate/SceneDelegate.swift
> +
불필요한 주석, 개행 등은 제거해주셔도 좋을 것 같아요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Contact.swift
> +}
모든 프로퍼티를 옵셔널로 해주셨군요! 이 부분에 대해서는 PR 본문에 질문을 남겨주셨으니 본문에 대한 코멘트로 피드백을 남겨볼게요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +
종종 개행이 한 줄이 아니라 두 줄인 경우가 보이는데, 어떤 기준을 바탕으로 개행하신 건지 궁금해요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactTableViewCell.swift
> +    static let reuseIdentifier = "ContactTableViewCell"
오타를 방지하는 것도 좋고, 외부에서 호출할 때도 쓰기 좋아보여 편리해보이네요!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactTableViewCell.swift
> +class ContactTableViewCell: UITableViewCell {
- 다른 class 객체에서는 final 키워드를 붙여주셨는데, 여기에서는 어떤 이유로 안 붙이셨나요?
- final 키워드는 무엇을 의미하나요?
- 붙이면 어떤 장점이 있나요?

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +extension ContactsViewController: UITableViewDataSource {
UITalbeViewDataSource 프로토콜을 채택하는 부분을 따로 빼주고, 관련 델리게이트 메서드를 모아놓으니 가독성이 좋아졌네요!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        cell.configureTableViewCell(with: contact)
별 거 아니지만, 네이밍이 조금 어색하게 느껴져요. cell 스스로 configure하는 건데, 다른 셀을 configure 해주는 것 같은 인상을 받았어요. 개인적으로는 `cell.configure(with: contact)`라고 써도 좋을 것 같아요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        let contact = contactManager.showUpAllContacts()[indexPath.row]
showUp이라는 단어는 언어적으로 자연스러워보이지만, 호출하는 쪽에서 정확히 어떤 동작을 하는지 이해하기 어려울 수 있다고 생각해요. `fetchAllContacts`와 같이 이런 용도로 흔히 사용되는 네이밍을 선택하는 것도 좋아보여요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        let contact = contactManager.showUpAllContacts()[indexPath.row]
그리고 ContactManager 프로토콜의 구현 타입에서 contactList를 private var가 아니라 private(set) var로 선언해 외부에서 접근하는 방법도 있을 것 같아요. 

그럼 호출부가 아래처럼 변할 거예요.
`let contact = contactManager.contactList[indexPath.row]`

이렇게 하면 showUpAllContact라는 별개의 메서드를 굳이 만들지 않아도 된다는 이점이 있을 것 같아요.

또, 네이밍을 조금 바꿔서 아래처럼 써도 좋을 것 같고요.
`let contact = contactManager.contacts[indexPath.row]`

제 개인적인 의견일 뿐이므로, 두 분이 장단점을 생각하시고 선택해주시면 될 것 같습니다!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +}
ContentManager라는 프로토콜을 만들고, ContactManagerImplement, ContactManagerMock이라는 구체타입을 만들어주셨어요. 프로토콜을 사용해주신 점이 좋네요!

- 그런데 프로토콜은 어떤 이유로 사용하신 건가요? 어떤 효용을 위해 사용하고 계신 건지 궁금해요.
- 프로토콜, 그리고 의존성 주입에 대해 설명해주실 수 있나요?

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +    func updateContact(at index: Int, with updateContact: Contact)
개인적으로는 updateContact를 updatedContact 또는 newContact라고 해도 괜찮을 것 같아요. update가 동사처럼 읽혀서 조금 혼란스러웠어요.

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +    func updateContact(at index: Int, with updateContact: Contact)
deleteContact와 updateContact 메서드에서 index를 활용하고 있군요. 제 개인적인 생각으로는 Contact 객체에 id라는 프로퍼티를 만드는 방법도 있을 것 같아요. 만약 그렇게 하면 이쪽 코드는 가령 `deleteContact(at index: Int)`가 아니라 `delete(_ contact: Contact)` 정도가 될 수 있을 것 같아요. 

이것도 제 생각일 뿐이니 두 분이 생각해보시고 더 좋은 방향으로 선택하시면 됩니다!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +protocol ContactManager {
프로토콜의 네이밍은 보통 -able, -Interface, -Protocol 등으로 적는 편이에요.

이 중에서 저는 -Protocol이라는 네이밍을 가장 선호해요. 웬만하면 -able로 통일하고 싶은데, 그렇지 않은 것들이 많아서 -Protocol이라는 네이밍을 붙이고 있어요.

 저 개인적으로는 ContactManager라는 네이밍이 하나의 구체 타입처럼 느껴져요. 저라면 ContactManagerProtocol이라고 선언하고, 구체 타입을 ContactManager, MockContactManager라고 네이밍할 것 같아요.

이또한 정답은 없고, 제 생각일 뿐이니 두 분도 생각해보시면 좋을 것 같아요!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +protocol ContactManager {
다만 이와 관련해서 어떤 언어를 사용하느냐에 따라 네이밍 컨벤션이 많이 달라질 수도 있는데요. Java, Kotlin 쪽에서 Implement, Impl 이라는 네이밍을 봤던 것 같은 기억이 있어요. 분야별로 네이밍 컨벤션이 달라진다는 점도 인지해주시면 좋을 것 같아요!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManagerMock.swift
> +}
이 부분이 PR 본문에 `목데이터 파일을 만들어서 모의구현을 하는것에 대한 조언을 얻고싶습니다.` 라고 남기신 것과 관련 있어 보이네요. PR 본문 코멘트로 답변할게요!

2024-01-08 15:26 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactsView.swift
> +}
현재의 구현만 봐서는 ContactsView가 사실상 UITableView와 다르지 않아 보여요. ContactsViewController에서 자신의 TableView로 갖고 있어도 될 것 같은데, ContactView라는 객체로 분리하신 이유가 궁금해요. 어떤 장단점이 있나요?

2024-01-09 04:06 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +protocol ContactManager {
민쏜이 말해준 데로 Java 에서 주로 사용되는 네이밍 입니다.
앞으로는 알려 주신 " -able, -Interface, -Protocol"을 사용하여 프로토콜을 네이밍 하도록 하겠습니다.

저도 개인적으로 -Protocol이 가장 적합하다고 생각 합니다.

2024-01-09 04:10 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +    func updateContact(at index: Int, with updateContact: Contact)
어제 STPE2 명세서 open 된 후
토미와 논의했던 사항 입니다. 좀 더 구체적인 ID 부여 방법 등의 논의를 거쳐 STEP 2에 반영 예정 입니다.

2024-01-09 04:15 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +
기본적인 개행은 한줄로 하고 MARK 를 이용하여 나름 섹션을 나누어 두고 있습니다.
예를 들어 Property, Method, Life Cycle 과 같이 클래스 내부를 섹션으로 나누고 그 섹션들 간의 간격은 2줄로 개행 하기로
저희만의 컨벤션으로 지정하고 지키고 있습니다.

2024-01-09 04:21 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/App/AppDelegate/SceneDelegate.swift
> +
불필요한 주석, 개행 모두 제거하였습니다!!

2024-01-09 04:42 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactTableViewCell.swift
> +class ContactTableViewCell: UITableViewCell {
- 다른 class 객체에서는 final 키워드를 붙여주셨는데, 여기에서는 어떤 이유로 안 붙이셨나요?
     -  final을 한번에 처리한 뒤 cell분리 작업을 하여 빼먹은 부분입니다..하핳
     - 보통 `final` 을 사용하지 않는 경우(이유)는
          -  클래스에 대한 `final`은 상속을 금지하는 것이므로, 이 클래스를 상속해 새로운 기능을 추가하거나 수정하고자 할 때에는 `final`을 사용하지 않는 것이 좋습니다.
          - 만약 클래스를 상속하여 확장할 필요가 있다면, `final`을 사용하지 않아야 합니다.
- final 키워드는 무엇을 의미하나요?
     -  Final은 서브클래스에서 특정 method, property, subscript 가 오버라이드 되지 않도록 하기위해서 final 키워드를 사용합니다. final을 사용한 클래스는 가장 하위의 클래스로 상속이 일어나지않습니다.
- 붙이면 어떤 장점이 있나요?
     - 오버라이드로 인한 예기치 않은 동작을 방지할 수 있습니다.
     - 클래스의 경우 원래 다이나믹 디스패치가 사용되지만 final을 사용하게되면 class도 static dispatch 할수 있습니다  따라서 메모리 성능이 좋아집니다.

2024-01-09 07:00 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +}
1. **다형성 구현:**
    - `ContentManager` 프로토콜을 따르는 여러 구현체를 만들 수 있음
    - 이렇게 하면 동일한 프로토콜을 따르는 다양한 객체를 동일한 인터페이스로 다룰 수 있다.
2. **의존성 주입 및 테스트 용이성:**
    - `ContentManager` 프로토콜을 사용하여 `ContactsViewController`가 `ContactManager`를 의존하는데, 이는 의존성 주입을 통해 테스트 용이성을 높임
    - 테스트 시 `ContactManager`의 구현체를 주입하여 테스트하는 방식
3. **모듈성과 확장성:**
    - 프로토콜은 관련 기능을 논리적으로 그룹화할 수 있어 모듈성을 증가.
    - 새로운 기능이나 모듈을 추가할 때 해당 기능을 제공하는 프로토콜을 따르는 새로운 클래스를 만들어서 확장성을 높일 수 있다.
4. **가독성 및 유지보수성:**
    - 코드를 읽거나 유지보수할 때 프로토콜을 통해 해당 타입이 어떤 기능을 제공하는지 명시적으로 확인 가능. →  가독성을 높이고 코드의 의도를 명확하게 전달 할 수 있음
### 프로토콜 사용 이유:

1. **추상화와 유연성:** 
    1. 프로토콜은 특정 기능을 정의하는데 사용. 
    2. 이는 구현 세부 사항을 숨기고 특정 기능에 대한 추상화를 제공하여 코드의 유연성을 높임. 프로토콜을 사용하면 구현 세부 사항을 신경쓰지 않고도 해당 기능을 사용할 수 있음
2. 다형성 구현:
    1. 프로토콜을 사용하면 다양한 객체가 동일한 프로토콜을 따를 수 있다.
    2. 이를 통해 코드의 재사용성을 높이고, 다형성을 지원 → 객체지향프로그래밍
3. 의존성 분리:
    1. 코드의 결합을 낮추고, 유지보수를 높임

### 의존성 주입:

의존성 주입은 한 객체가 다른 객체에 대한 의존성을 외부에서 주입받는 패턴입니다. 이를 통해 코드의 유연성을 높이고 테스트 용이성을 증가시킵니다.

1. **테스트 용이성:** 프로토콜과 의존성 주입을 함께 사용하면 테스트를 용이하게 만들 수 있습니다. 
    1. ex. `ContactManagerImplement`와 `ContactManagerMock`이 `ContentManager` 프로토콜을 따르기 때문에, 이를 사용하는 클래스에서는 실제 `ContactManagerImplement` 대신에 테스트에 활용할 수 있는 `ContactManagerMock`을 주입하여 테스트를 수행
2. **유연성:** 의존성 주입을 통해 객체 간의 결합이 감소하고, 유연성이 향상
    1. 즉, 특정 구현체에 의존하는 대신에 프로토콜에 의존하므로, 나중에 다른 구현체로 쉽게 교체 가능합니다.
3. **확장성:** 새로운 기능이나 모듈을 추가할 때, 기존 코드를 수정하지 않고도 새로운 구현체를 주입하여 확장성 좋습니다.

이러한 이유들로 프로토콜과 의존성 주입은 코드의 품질과 유지보수성을 높이는데 기여합니다.

2024-01-09 07:06 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactsView.swift
> +}
### 장점:

1. **모듈성과 재사용성:**
    - `ContactsView`를 별도의 클래스로 분리하면 해당 뷰를 다른 화면에서 재사용할 수 있다.
    - 예를 들어, 다른 화면에서도 연락처 목록을 보여주는 뷰가 필요하다면 `ContactsView`를 재사용할 수 있다
2. **단일 책임 원칙:**
    - `ContactsView` 클래스는 주로 레이아웃 및 서브뷰 관리에 책임지고 있습니다.
    - `UIView`를 상속받아 뷰의 레이아웃과 서브뷰 관리에 대한 역할을 수행하고 있습니다.
    - 단일 책임 원칙을 지킨다고 볼 수 있습니다.
3. **의존성 분리:**
    - `ContactsViewController`에서 `ContactsView`를 사용함으로써, 뷰 관련 로직을 분리하고 `ContactsViewController`는 주로 데이터 및 비즈니스 로직에 집중할 수 있습니다.

### 단점:

1. **뷰 계층이 복잡하지 않을 경우 불필요한 추상화:**
    - 만약 앱의 규모가 작고 `ContactsView`의 역할이 단순하다면, 별도의 클래스로 분리하지 않고 `ContactsViewController`에서 직접 `UITableView`를 관리하는 것이 더 간단할 수 있다.
    
    → 리뷰어님(민쏜)이 말씀하신 부분
    
2. **코드량 증가:**
    - 비슷한 내용이긴하지만,
    - 뷰를 별도의 클래스로 분리하면 클래스 간의 상호 작용 및 코드량이 늘어남.
    - 작은 규모의 앱에서는 이를 위한 별도의 클래스가 약간 필요하지 않은 느낌.
    
프로젝트의 규모, 유지보수성 요구사항 및 팀의 개발 스타일에 따라 다를 수 있는데 작은 프로젝트에서는 간단한 구현이 더 적절할 수 있지만, 중대형 프로젝트에서는 모듈성과 재사용성을 고려하여 뷰를 별도의 클래스로 분리하는 것이 유용할 수 있다고 생각합니다.
→ 현재 해당 프로젝트는 크기가 작은 앱이며, 테이블뷰라는 단순한 모양이지만, 단일책임원칙을 따르고, MVC 패턴을 강력하게 따르기 위해서 작성하였습니다
→ 연습훈련을 위해서 일부러라도 해당 방식으로 작성했습니다.!!!

2024-01-09 12:45 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactManager.swift
> +}
현재로서는 의존성 주입이 되고 있지 않아서 여쭤본 거였어요! 필요하시다면 나중에 적용해보셔도 좋을 것 같습니다 ☺️

2024-01-09 12:46 UTC, merged