연락처 관리 앱 프로젝트 [STEP 1] Matthew, Asher
tasty-code/ios-contact-manager-ui pull request #61
Opened 2024-01-08 01:56 UTC by kimbs5899

# 연락처 관리 앱 프로젝트 [STEP 1]

멤버 : @kimbs5899, @tawans

리뷰어 : @ictechgy

연락처 관리 앱 프로젝트의 첫번째 Step입니다!

정리하여 PR 드립니다. 감사합니다!

# 이번 스텝을 통해서 배운 점

- Storyboard remove
    - 삭제 과정중 기존 스토리보드로 세팅된 부분에 대한 수정
    - plist, Build settings 에 대한 중요성
- TableView
    - 코드로 작성하는 UIkit
    - UITableViewDataSource 대리자 패턴의 장점
    - dequeueReusableCell을 사용하여 Cell의 재사용
    - defaultContentConfiguration을 사용한 기본 목록 콘텐츠 구성
- ContactManager
    - 연락처관리의 CRUD를 위해 ContactManager에 매서드 구현
    - UUID에 대한 고민과 내부 저장에 대한 방향성 고민 (json, coreData)
- 연락처 Model 설계
    
    ```swift
    class Contact {
        var name: String
        var age: Int
        var phoneNumber: String
    
        init(name: String, age: Int, phoneNumber: String) {
            self.name = name
            self.age = age
            self.phoneNumber = phoneNumber
        }
    }
    ```
    

# 구성

## Model

### Contact.swift

- Contact Class
    - property : 이름, 전화번호, 나이

### ContactListManager.swift

- ContactListManager
    - property: 싱글톤 패턴을 위한 shared, contactArray
    - method: ContactList 생성, ContactList 보기, Contact 추가(변경), Contact 삭제

## View

### ContectManagerListView.swift

- ContectManagerListView 커스텀 UIView 클래스

## Controller

### ContectManagerListViewController.swift

- ContectManagerListViewController : 연락처 리스트 뷰 컨트롤러

# 질문

- 초기에 삭제한 스토리보드로 인해 기존에 연결된 ViewController.swift 파일을 사용하지 않게 되었습니다.
이로 인해 불필요하기 때문에 삭제를 해야 하는지 그냥 두고 사용해야 하는지 만약 삭제한다면 어떤 세팅을 잡아야 할지 아직 불확실하여 그냥 둔 상태입니다. 혹시 현업에서 코드 베이스로 UI를 작성하실 때 생성한 storyboard와 viewcontroller는 삭제 후 필요한 걸 재생성 하시는지 아니면 그대로 활용하시는지 궁금합니다!

2024-01-08 16:16 UTC, ictechgy requested changes
안녕하세요 @kimbs5899 , @tawans !   
두 분의 리뷰를 맡게 된 코든입니다!   

[STEP1] 진행하시느라 고생하셨습니다 😆  
(오토레이아웃을 문제없이 정말 잘 설정해주셨더라구요!!!  🔥👍 커밋 메시지도 깔끔하고 명확! ✨)
 
궁금한 점, 다시 고민해보면 좋을 것 같은 점들은 라인별 코멘트로 남겨두었습니다~!   
여기서는 질문주신 내용에 대한 답변을 드려보겠습니다.   

<br/>   

> 초기에 삭제한 스토리보드로 인해 기존에 연결된 ViewController.swift 파일을 사용하지 않게 되었습니다.
이로 인해 불필요하기 때문에 삭제를 해야 하는지 그냥 두고 사용해야 하는지 만약 삭제한다면 어떤 세팅을 잡아야 할지 아직 불확실하여 그냥 둔 상태입니다. 혹시 현업에서 코드 베이스로 UI를 작성하실 때 생성한 storyboard와 viewcontroller는 삭제 후 필요한 걸 재생성 하시는지 아니면 그대로 활용하시는지 궁금합니다!

<br/>   

불필요한 파일이라면 삭제해야하지 않을까 저는 생각하는데요! 현업에서도 사용하지 않는 파일들은 삭제하고 필요한 파일들만 그 때 그 때 생성하여 사용합니다. 사용하지 않는데 존재하는 파일들은 앱의 크기를 늘리기만 하지 않을까요?   

필요없는 파일들은 한번 제거해보시면 어떨까요?   
(만약 제거 과정에서 해결하기 어려운 문제가 생긴다면 제게 말씀주세요!)


<br/>   
STEP1 PR에서는 몇가지 네이밍 등만 잡아주시면 머지 할 수 있을 것 같습니다~!! 라인별 코멘트 확인해주시고 수정 부탁드릴게요!

2024-01-08 16:16 UTC, ictechgy commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,objective-c,xcode,swiftpackagemanager,cocoapods
gitignore 템플릿을 사용하셨군요! 👏       
현재 프로젝트에서는 사용하지 않는 환경(objc 환경 등)들도 추가하신 것 같은데 따로 이유가 있을까요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/AppDelegate.swift
> +        return true
아래 SceneDelegate에서도 UIWindow를 만들고 `makeKeyAndVisible`을 해주고 있는데요! 이 곳에서도 동일한 작업이 이루어지고 있네요~   
두 작업이 동시에 있어야 할까요?? 👀

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +class ContectManagerListViewController: UIViewController {
혹시 final 키워드에 대해 들어본 적이 있으실까요?

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +    var contactListView: ContectManagerListView = ContectManagerListView()
두 인스턴스는 생성된 뒤에 변하지 않는 것으로 보이는데 var로 선언하신 이유가 있을까요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +    var contactListView: ContectManagerListView = ContectManagerListView()
또, `contactManager`는 타입 어노테이션이 없는데 `contactListView`는 타입 어노테이션이 있네요! 다른 이유가 있을까요?

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +    }
두 initializer들을 별도로 직접 선언해주신 이유가 있을까요?   
다른 동작을 하지 않는다면 상위 UIViewController의 생성자를 그대로 받아도 될 것 같습니다!

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        view = contactListView
`loadView`를 오버라이딩 하셨군요! `loadView`는 어떤 역할을 하는 함수일까요?

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +extension ContectManagerListViewController: UITableViewDataSource {
프로토콜 채택을 extension으로 분리하셨군요! 👍

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +extension ContectManagerListViewController: UITableViewDataSource {
프로젝트 전체적으로 Contect 오타 한번만 확인 부탁드릴게요!

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        return cell
`defaultContentConfiguration`을 이용해서 요구조건을 잘 구현해주셨네요!! 😆👍

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "contactCell", for: indexPath)
`contactCell`을 직접 지정하는 것은 개발자 휴먼에러가 충분히 발생 할 수 있는 부분일 것 같은데요!       
해당 값을 지정하는 더 좋은 방법은 없을까요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Controllers/ViewController.swift
> +    }
이 친구는 꼭 있어야 하는걸까요? 🤔

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/Contact.swift
> +class Contact {
struct가 아닌 class를 선택하신 이유가 있을까요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/Contact.swift
> +    var phoneNumber: String
var로 선언해주신 이유는 무엇인가요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +import UIKit
이 파일에는 UI적인 요소가 없는 것 같은데, 꼭 UIKit을 import 해야할까요?!

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +    static let shared = ContactManager()
싱글톤을 택하게 된 이유 설명 부탁드립니다! 😆

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +    private var contactArray: [Contact] = [
contactArray라는 타입이 붙은 이름 대신에 여러가지 Contact들을 포괄하는, 좀 더 명확한 네이밍은 어떨까요?

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +    }
CRUD에 맞는 네이밍으로 함수명들을 지어주셨네요! 👍

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +        if let result = contactArray.firstIndex(where: { $0.name == name }) {
result라는 이 변수의 이름은 한번 더 고민해봐주시면 좋을 것 같습니다!

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
혹시 AppDelegate와 SceneDelegate가 어떤 역할을 하는 친구들인지 알고 계실까요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Views/ContectManagerListView.swift
> +class ContectManagerListView: UIView {
Manager라는 이름은 꼭 들어가지 않아도 될 것 같은데 어떻게 생각하시나요?

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Views/ContectManagerListView.swift
> +        return tableView
테이블 뷰 설정과 생성을 동시에 잘 해주셨네요! 👍👍

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Views/ContectManagerListView.swift
> +    }
혹시 두 initializer가 어떤 차이를 가지는지 알고 계실까요??

2024-01-08 16:16 UTC, ictechgy commented on ios-contact-manager/Views/ContectManagerListView.swift
> +        ])
오토레이아웃 잘 설정해주셨네요~!! 👏🔥

2024-01-09 01:26 UTC, tawans commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,objective-c,xcode,swiftpackagemanager,cocoapods
추후에 objc 관련 코드들도 사용할 수도 있기때문에 미리 대비차 넣어놨습니다.

2024-01-09 01:27 UTC, tawans commented on ios-contact-manager/AppDelegate.swift
> +        return true
이 부분은 앱 델리게이트 쪽에 뷰컨트롤러 연결해주는 작업을 놓쳐서 이부분도 관련 수정하여 놓도록 하겠습니다.

2024-01-09 01:28 UTC, tawans commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +class ContectManagerListViewController: UIViewController {
상속이 추후에 필요하지 않고 마지막 Depth로 사용하는 클래스에 대해 final 붙여서 명시하는 키워드로 알고 있습니다.

2024-01-09 01:31 UTC, tawans commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +    var contactListView: ContectManagerListView = ContectManagerListView()
> 두 인스턴스는 생성된 뒤에 변하지 않는 것으로 보이는데 var로 선언하신 이유가 있을까요??
변하지 않는 인스턴스인데 놓쳤던 것 같습니다. let으로 수정하도록 하겠습니다.
> 또, `contactManager`는 타입 어노테이션이 없는데 `contactListView`는 타입 어노테이션이 있네요! 다른 이유가 있을까요?
타입 어노테이션을 붙이는 것으로 코딩 컨벤션을 정했는데
contactManager 에서 타입 어노테이션 작성을 놓친 것 같습니다. 붙이도록하겠습니다.

2024-01-09 01:32 UTC, tawans commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +    }
불 필요 한 코드인데 놓쳤던 것 같습니다. 수정하도록 하겠습니다.

2024-01-09 01:34 UTC, tawans commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        view = contactListView
뷰를 메모리에 올리는 과정, 뷰를 바꿀수 있는 시점 
스토리보드를 사용하면 해당 로드뷰를 호출해도 화면 로드가 안됩니다.
그래서 코드로 UI를 짤 때 사용됩니다.

2024-01-09 01:34 UTC, tawans commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +extension ContectManagerListViewController: UITableViewDataSource {
네 오타 수정하겠습니다 !

2024-01-09 01:35 UTC, tawans commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "contactCell", for: indexPath)
해당 부분 CustomString 타입으로 지정해서 휴먼에러를 방지하도록 하겠습니다.

2024-01-09 01:35 UTC, tawans commented on ios-contact-manager/Controllers/ViewController.swift
> +    }
삭제하도록 하겠습니다. 불필요한 부분이었네요.

2024-01-09 01:37 UTC, tawans commented on ios-contact-manager/Models/Contact.swift
> +class Contact {
다시 생각해보니 struct가 적절했던 것 같습니다. 수정하겠습니다.

2024-01-09 01:38 UTC, tawans commented on ios-contact-manager/Models/Contact.swift
> +    var phoneNumber: String
변경이 필요치 않기 때문에 let이 적절한것같습니다. 수정하겠습니다.

2024-01-09 01:40 UTC, tawans commented on ios-contact-manager/Models/ContactManager.swift
> +import UIKit
Foundation을 포함하고 있는 UIkit 을 전체적으로 적용하여 발생할 수 있는 휴먼에러를 방지하고자 전체적용을 기준으로 코딩컨벤션을 정했습니다.

2024-01-09 01:41 UTC, tawans commented on ios-contact-manager/Models/ContactManager.swift
> +    static let shared = ContactManager()
현재 해당 데이터를 내부 저장소로 저장하고 있지 않아서 데이터를 가져오기위해 싱글톤을 적용했는데
추후 내부 저장을 json으로 하게되면 수정하도록하겠습니다.

2024-01-09 01:42 UTC, tawans commented on ios-contact-manager/Models/ContactManager.swift
> +    private var contactArray: [Contact] = [
네이밍 더 고민해서 수정하겠습니다.

2024-01-09 01:43 UTC, tawans commented on ios-contact-manager/Models/ContactManager.swift
> +        if let result = contactArray.firstIndex(where: { $0.name == name }) {
네 해당 부분은 고민해서 수정하겠습니다.

2024-01-09 01:46 UTC, tawans commented on ios-contact-manager/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
AppDelegate : 앱의 전반적인 라이프 사이클을 관리
앱이 시작, 종료, 백그라운드로 돌아갈때 등의 시점에서 호출되는 메서드들을 제공

SceneDelegate : 멀티태스킹 및 멀티윈도우 환경에서 여러개의 화면(씬)들을 관리
각각의 앱 씬은 화면 상태와 관련된 정보를 관리하며 화면을 생성하고 유지하는 역할을 한다.

이렇게 알고 있습니다.

2024-01-09 01:47 UTC, tawans commented on ios-contact-manager/Views/ContectManagerListView.swift
> +class ContectManagerListView: UIView {
네이밍 관련 고민해서 Manager는 뺴도록 하겠습니다.

2024-01-09 01:50 UTC, tawans commented on ios-contact-manager/Views/ContectManagerListView.swift
> +    }
ovverride 생성자는 상위 클래스의 정의되어있는 생성자를 상속받아 재 설정하는 코드이고

required 생성자는 하위 클래스에서 필수로 생성해야하는 생성자로 안 만들면 에러 나기때문에 필수로 만들어줘야 합니다.
생성시 발생하는 fatal에러를 required에서 잡아주는 것으로 알고 있습니다.

2024-01-10 16:06 UTC, ictechgy commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,objective-c,xcode,swiftpackagemanager,cocoapods
그렇군요! 혹시 objc를 써보신 경험이 있으신걸까요??

2024-01-10 16:07 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +class ContectManagerListViewController: UIViewController {
성능적으로도 이점이 있는데요!   
이 부분은 나중에 시간이 되실 때 [Understanding Swift Performance](https://developer.apple.com/videos/play/wwdc2016/416/) 이 영상을 참고해보시면 좋을 것 같습니다

2024-01-10 16:22 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        view = contactListView
좋은 설명 감사합니다.      

혹시 "스토리보드를 사용하면 해당 로드뷰를 호출해도 화면 로드가 안됩니다." 라고 해주신 것은 정확히 어떤 상황인건지 설명해주실 수 있을까요?

2024-01-10 16:29 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +import UIKit
발생할 수 있는 휴먼에러는 어떤 상황을 말씀해주시는 걸까요??

2024-01-10 16:31 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +    static let shared = ContactManager()
설명 감사합니다.       
제가 말씀드리고자 한 것은 쓰지 말라고 하는 것이 아니었어요! 정말 이유가 궁금해서 여쭤본 것이었습니다 😆

2024-01-10 16:31 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +    private var contactArray: [Contact] = [
혹시나 잘 떠오르지 않는다면 꼭 말씀해주세요!

2024-01-10 16:37 UTC, ictechgy commented on ios-contact-manager/SceneDelegate.swift
> +class SceneDelegate: UIResponder, UIWindowSceneDelegate {
좋은 설명 감사합니다!! 😆👍

2024-01-10 16:45 UTC, ictechgy commented on ios-contact-manager/Views/ContectManagerListView.swift
> +    }
설명 감사합니다!      

코드로 직접 뷰를 생성할 때와 스토리보드를 통해 생성할 때 어떤 initailizer가 호출되는지도 나중에 확인해보시면 좋을 것 같습니다

2024-01-11 17:16 UTC, ictechgy commented
제가 남겨드린 코멘트들 꼭 반영 부탁드립니다! PR은 우선 머지하도록 할게요!

2024-01-11 17:16 UTC, merged

2024-01-12 02:44 UTC, kimbs5899 commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,objective-c,xcode,swiftpackagemanager,cocoapods
코드베이스로 사용하는 버튼의 Action의 Selector 함수에 사용하거나, CoreData를 사용할때, UI를 작성하는 도충 NSAttributedString등 에서 사용했습니다! 정확히 이부분이 objc라고 장담할수는 없지만 혹시나 하는 마음에 추가했습니다!

2024-01-12 02:48 UTC, kimbs5899 commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        view = contactListView
스토리보드에 정의된 뷰 컨트롤러는 스토리보드 자체에서 뷰를 자동으로 로드하는걸로 알고있습니다!
스토리보드에서 초기 뷰 컨트롤러와 연결된 스토리보드 파일이 로드되면 해당 뷰 컨트롤러의 loadView() 메서드는 호출되지 않습니다.

2024-01-15 01:52 UTC, kimbs5899 commented on ios-contact-manager/Models/ContactManager.swift
> +import UIKit
String을 직접 입력할때 개발자도 사람이기에 오타를 낼수 있기 때문에 이런 부분을 휴먼에러라고 부른다고 알고있습니다!
그래서 최대한 그런 부분을 방지하기 위해 String 및 Int로 처리되는 부분들을 enum의 하나의 케이스로 정의하여 그곳에서 수정하고 추후 유지보수에도 유리하다고 생각합니다!!

2024-01-15 15:36 UTC, ictechgy commented on .gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,swift,objective-c,xcode,swiftpackagemanager,cocoapods
그렇군요!   
확인해봤는데 swift에 대한 gitignore 템플릿과 objc에 대한 gitignore 템플릿이 크게 차이는 안나더라구요..!    
이 부분은 조금 더 확인이 필요할 것 같네요!

2024-01-15 15:41 UTC, ictechgy commented on ios-contact-manager/Controllers/ContectManagerListViewController.swift
> +        view = contactListView
정말인가요?! 이 부분은 한번 테스트 해보시면 좋을 것 같아요!

2024-01-15 15:46 UTC, ictechgy commented on ios-contact-manager/Models/ContactManager.swift
> +import UIKit
결국 enum과 같은 형태를 이용해서 개발자가 직접 값을 입력하는 경우를 줄이고자 하신다는 말씀으로 이해했는데요~. 그러면 UIKit은 굳이 import하지 않아도 될 것 같습니다! (물론 해도 큰 문제는 없지만요 😆)