연락처관리 앱 [STEP 1] Hoi, Harry
tasty-code/ios-contact-manager-ui pull request #63
Opened 2024-01-08 07:57 UTC by hemil0102

@songda515

안녕하세요~ 다나! Hoi(@happykwon), Harry(@hemil0102)입니다! 
연락처관리 앱 STEP1 PR을 우여곡절(?) 끝에 보내드립니다.
팀원 모두 서로 경험이 부족하여서 아주 기초적인 것 부터 조언 및 제안 그리고 어떤 질문이든 해주시면 언제든 환영합니다!
불타는 학구열~ 🔥 
리뷰해주셔서 감사합니다! 

## 🔍 What is this PR?

STEP 1 기능 구현
- STEP 1-1 연락처 목록 구현
- STEP 1-2 TableView의 사용
 
## 📝 PR Point

### 1. 모델 구현 
- Contact 구조체를 통해 name, age, phoneNumber 프로퍼티를 정의
- 이후 ViewController에서 contactList: [Contact] 배열 형식 정의
 
### 2. Json
- mockJson 파일을 통해서 연락처 데이터를 생성
- Json Parsing을 통해 contactList에 데이터를 로드

### 3. 테이블 뷰 구현
- 프로토콜(UITableViewDataSource, UITableViewDelegate)을 채택 및 DataSource 필수 함수를 구현
- 연락처 보기 구현
- 연락처 추가 구현, 배열에 append()를 통해 데이터 추가, 
  UITableView insertRows()를 통해 셀 추가 
- 연락처 삭제 구현, 배열에 remove()를 통해 데이터 삭제,
  UITableView editing mode 구현으로 선택한 행을 deleteRows()로 셀 삭제 구현
- 연락처 수정 구현, Alert textfield()로 입력받은 index 번호에 해당하는 셀을 목업 데이터로 변경,
  UITableView reloadRows()를 통해 수정된 행의 셀만 새로고침

### 4. Alert Extension
- Alert Extension 파일을 별도로 작성하여 Alert을 재활용할 수 있게 구현

### 5. scrollToBottom()
- 해당 메서드는 셀이 추가될 때 마지막 행으로 이동하여 추가된 셀을 용이하게 확인
- 다만, 내부 디스패치는 아직 학습하지 않은 내용으로 검증 편의적인 구현

## 📸 Screenshot
구현 내용 | 구동 영상
-- | --
구동화면 | ![Simulator Screen Recording - iPhone 15 - 2024-01-08 at 16 46 34](https://github.com/tasty-code/ios-contact-manager-ui/assets/83139316/afd77d30-0994-4af4-a3c8-af990037d386) | 

## **+** 질문 및 고민한 부분
### 고민한 부분
- 초반에 reloadData()로 추가, 삭제, 수정 이후에 데이터를 로드하였으나, 
애플 공식 문서 확인 시 insert()와 delete()수행에서 사용 비권장으로 inserRows(), deleteRows(), reloadRows()를 활용하여 구현했습니다. 

### 질문
1. MVC패턴을 활용해서 구현하려고 했으나 왠지 ViewController에 모든 기능이 구현된 것 같아요. 어떤 형식으로 MVC 구현을 하면 좋을지 가이드를 받을 수 있을까요? 
2. 다른 팀의 프로젝트를 보면 ...Manager 형식으로 데이터 추가 삭제 수정을 구현하는 것 같은데, 이런 형식의 관리가 MVC 어디에 포함되는 것일까요? 
3. Edit 버튼을 누르면 콘솔 창에 메세지가 뜨고 Alert 창이 비교적 늦게 뜨는 것 같아요, 왜 이럴까요?
4. 또 UUID를 만들어주는 것을 보았는데 저희도 구현을 해야하는 것일까요?

2024-01-08 16:16 UTC, songda515 requested changes
연락처관리 앱 Step 1 고생많으셨습니다 🙌 
TableView 와 JSON 모델도 함께 활용하는거라 더욱 의미있는 프로젝트같아 보이네요 ㅎㅎ
전반적으로 잘 구현해주셨고, 질문도 잘 정리해주셔서 감사합니다 😌
개별 코멘트만 한번 고민해주시면 좋을것 같아요~

그리고 질문주신 부분에 대한 답변입니다 🤗
1. MVC 패턴에서는 일반적으로 C (Controller) 역할을 ViewController 가 주로 하게됩니다. 그래서 tableview 를 관리하는 로직이 들어가는건 괜찮아보여요. 다만 M (Model) 역할에 가까운 JSON 을 파싱하는 부분을 따로 빼주면 더 코드가 간결해질 수 있어보이네요. 🙂
2. Manager 에 작성되어 있는 코드가 어떤건지 따라 달라지겠지만, ViewController 에서 수행되는 비즈니스 로직에 관한 코드로 따로 분리한 것일수도 있겠네요.
3. 앱 실행해보니 alert 가 열릴땐 아니고, 취소로 닫을때인데 콘솔에 `-[UIKeyboardTaskQueue lockWhenReadyForMainThread] timeout waiting for task on queue` 워닝이 발생할때가 있네요. 클로져나 핸들러에서 thread 관련해 이슈될 부분이 있나 찾아보면 좋을것 같습니다. 
4. UUID 를 추가하면 각 모델의 id 처럼 지정해줄 수 있을것 같은데요. 필수는 아니라서 구현상 장점이 어떤게 있나 고민해보시면 될것 같아요~

2024-01-08 16:16 UTC, songda515 commented on ios-contact-manager-ui/Controller/ViewController.swift
> +final class ViewController: UIViewController {
앱에서 화면이 하나인 경우가 아니면, ViewController 보다는 어떤 화면인지를 나타내는 클래스명이 더 좋을 것 같아요

2024-01-08 16:16 UTC, songda515 commented on ios-contact-manager-ui/Controller/ViewController.swift
> +        let lastRowOfIndexPath = numberOfLastRow - 1
`numberOfLastRow` 변수가 `contactTableView.numberOfRows(inSection: 0)` 의 값을 가져오기 때문에 일반적으로 `lastRowOfIndexPath` 의 값이 스크롤 가능한 범위일것 같은데요~

- 혹시나 `contactTableView` 의 row 가 0 개일때의 케이스도 고려해주시면 좋을것 같습니다. 
- 그리고 존재하지 않는 indexPath 로 이동하려고 할 때 어떤 일이 일어나는지도 확인해주세요 😄

2024-01-08 16:16 UTC, songda515 commented on ios-contact-manager-ui/Controller/ViewController.swift
> +            return
여기 케이스처럼 얼리 리턴이 필요한 경우엔 guard 구문을 써주시면 더욱 간결하게 표현할 수 있어보여요.

2024-01-08 16:16 UTC, songda515 commented on ios-contact-manager-ui/Extension/UIViewController + Extension.swift
> +extension UIViewController {
자주 사용하는 Alert 재사용할 수 있게 extension 으로 잘 활용하신것 같네요! 👍

2024-01-08 16:16 UTC, songda515 commented on ios-contact-manager-ui/Model/Contact.swift
> +}
Model 타입도 잘 구현해주셨네요! `Contact` 구조체가 `Codable` 프로토콜을 채택하도록 하신 이유도 궁금해요~ 👀

2024-01-08 16:16 UTC, songda515 commented on ios-contact-manager-ui/Controller/ViewController.swift
> +        let cell: UITableViewCell = contactTableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
여기서도 어떤 cell 인지 명확하게 identifier 를 지정해주시는게 좋습니다

2024-01-09 03:31 UTC, happykwon commented on ios-contact-manager-ui/Model/Contact.swift
> +}
`loadData()`메서드에서 파싱을 하기위해 Codable을 채택했습니다, 추후 스텝에서 어떻게 진행될지 몰라
`Decodable`과 `Encodable`모두 사용 가능한 `Codable`을 채택했습니다.

2024-01-09 03:35 UTC, happykwon commented on ios-contact-manager-ui/Controller/ViewController.swift
> +final class ViewController: UIViewController {
432e20b4e9324cfc1c475e46a092ec60ce6f16cd
화면이 많아져도 명시적으로 보일 수 있게 클래스명 수정 완료했습니다

2024-01-09 03:38 UTC, happykwon commented on ios-contact-manager-ui/Controller/ViewController.swift
> +        let lastRowOfIndexPath = numberOfLastRow - 1
e753556525c8f4928dfa67f2dd8cef7ee1c837d0
- 조건문을 추가해서 0 또는 이상일 경우에만 실행될 수 있도록 했습니다.
- 현 코드에서는 문제가 없었지만, 서비스중인 앱이나 규모가 큰 것들에서는 예상치 못한 문제가 야기될 수 있기 떄문에 명확하게 조건을 추가해주는 것이 좋을 것 같습니다

2024-01-09 03:42 UTC, happykwon commented on ios-contact-manager-ui/Controller/ViewController.swift
> +            return
841959aa02779720053b03dd14eaf99182c02ecc
 가드문으로 수정 완료했습니다. 👍

2024-01-09 03:46 UTC, happykwon commented on ios-contact-manager-ui/Controller/ViewController.swift
> +        let cell: UITableViewCell = contactTableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
da1e53785e94cc52acd25f164dbf86024d34989c
테이블셀 이름 변경 완료했습니다! 👍

2024-01-09 05:50 UTC, hemil0102 commented on ios-contact-manager-ui/Controller/ViewController.swift
> +        let lastRowOfIndexPath = numberOfLastRow - 1
1af238af00cef2d2852f59b3b1b252315c21be16
scrollToBottom() 내부에 lastRowOfIndexPath 관련 안정성 확보가 필요하여 NSNotFound를 사용해 보완했습니다.
NSNotFound를 활용하지 않아도 조건문으로 해결할 수 있는데, 적용해보고 싶어서 해봤습니다. 
이 방향이 맞을지 모르지만 확인 부탁드리겠습니다. 😁

해결 내역
`scrollToRow()`메서드 문서에서 row가 0이면 `NSNotFound`를 활용해서 처리할 수 있다는 내용을 발견하여,
`contactTableView.numberOfRows(inSection: 0)`의 값이 0이거나 유효하지 않을 경우 `lastRowOfIndexPath`를 `NSNotFound`로 지정하여 `scrollToRow()`에서 스크롤이 되지 않도록 구현했습니다. 

보완 사유
```swift
    @IBAction private func addButtonTapped(_ sender: UIButton) {
        addMockData()
        scrollToBottom()
    }
```

위에서 셀 데이터를 추가한 이후에 스크롤 동작이 되어` lastRowOfIndexPath`의 값이 0이하로 내려갈 일이 없어 에러가 검출이 안되었던 것 같습니다. 다만, modifyTableCell()에서도 수정된 셀로 이동하게끔 적용을 하였는데, 현재 오동작을 하고 있긴하지만, 여기서는 셀이 없다면 lastRowOfIndexPath의 값이 -1이 되어 오류가 발생할 수 있습니다. 따라서 보완이 필요한 상태입니다. 

modifyTableCell() 내부 원하는 셀 위치로 이동하지 않는 문제는 STEP1 이후 STEP2 기능 구현하면서 필요할 경우 수정하겠습니다.

2024-01-09 07:23 UTC, hemil0102 commented on ios-contact-manager-ui/Extension/UIViewController + Extension.swift
> +extension UIViewController {
감사합니다!

2024-01-09 07:39 UTC, hemil0102 commented
> 연락처관리 앱 Step 1 고생많으셨습니다 🙌 TableView 와 JSON 모델도 함께 활용하는거라 더욱 의미있는 프로젝트같아 보이네요 ㅎㅎ 전반적으로 잘 구현해주셨고, 질문도 잘 정리해주셔서 감사합니다 😌 개별 코멘트만 한번 고민해주시면 좋을것 같아요~
> 
> 그리고 질문주신 부분에 대한 답변입니다 🤗
> 
> 1. MVC 패턴에서는 일반적으로 C (Controller) 역할을 ViewController 가 주로 하게됩니다. 그래서 tableview 를 관리하는 로직이 들어가는건 괜찮아보여요. 다만 M (Model) 역할에 가까운 JSON 을 파싱하는 부분을 따로 빼주면 더 코드가 간결해질 수 있어보이네요. 🙂
> 2. Manager 에 작성되어 있는 코드가 어떤건지 따라 달라지겠지만, ViewController 에서 수행되는 비즈니스 로직에 관한 코드로 따로 분리한 것일수도 있겠네요.
> 3. 앱 실행해보니 alert 가 열릴땐 아니고, 취소로 닫을때인데 콘솔에 `-[UIKeyboardTaskQueue lockWhenReadyForMainThread] timeout waiting for task on queue` 워닝이 발생할때가 있네요. 코드상으로는 큰 문제가 없어보이는데, 클로져나 핸들러에서 thread 관련해 이슈될 부분이 있나 찾아보면 좋을것 같습니다. 🤔
> 4. UUID 를 추가하면 각 모델의 id 처럼 지정해줄 수 있을것 같은데요. 필수는 아니라서 구현상 장점이 어떤게 있나 고민해보시면 될것 같아요~


안녕하세요 다나, 리뷰 시간내서 해주셔서 감사합니다. 😃
아래와 같이 주신 답변을 검토하였어요. 

1. MVC 패턴에서는 일반적으로 C (Controller) 역할을 ViewController 가 주로 하게됩니다. 그래서 tableview 를 관리하는 로직이 들어가는건 괜찮아보여요. 다만 M (Model) 역할에 가까운 JSON 을 파싱하는 부분을 따로 빼주면 더 코드가 간결해질 수 있어보이네요. 🙂
> 0e42c2e021b06f0ca52259e29b89358b11dc0f18 에 적용 했습니다. 이와 동시에 JSON 파싱에서 에러가 발생할 경우 에러 처리를 구현해주었습니다. 향후 STEP2에서 조금 더 체계적으로 에러를 관리해볼 예정입니다.

2. Manager 에 작성되어 있는 코드가 어떤건지 따라 달라지겠지만, ViewController 에서 수행되는 비즈니스 로직에 관한 코드로 따로 분리한 것일수도 있겠네요.
> 이 부분은 STEP에서 기능이 많아지면서 분리할 비즈니스 로직이라는 생각이 들면 별도 파일로 만들어 볼게요! 

3. 앱 실행해보니 alert 가 열릴땐 아니고, 취소로 닫을때인데 콘솔에 `-[UIKeyboardTaskQueue lockWhenReadyForMainThread] timeout waiting for task on queue` 워닝이 발생할때가 있네요. 코드상으로는 큰 문제가 없어보이는데, 클로져나 핸들러에서 thread 관련해 이슈될 부분이 있나 찾아보면 좋을것 같습니다. 🤔
> thread 관련해서 아직 배우질 않았지만 에러를 찾아보니 문제의 부분을 메인 Queue에서 동작하게끔 해줘야 하는 것 같아요. 다만 dispatchQueue는 이후의 학습 내용이어서 현 단계에서는 이런 내용이 있다는 정도로만 남겨놓고, 학습 이후에 조금 더 알아보면 좋을 것 같습니다! https://stackoverflow.com/questions/50625317/swift-4-error-uikeyboardtaskqueue-waituntilalltasksarefinished-may-only-be

4. UUID 를 추가하면 각 모델의 id 처럼 지정해줄 수 있을것 같은데요. 필수는 아니라서 구현상 장점이 어떤게 있나 고민해보시면 될것 같아요~
> 이 부분은 설명을 들었을 때 만약에 동일한 이름, 동일한 나이, 동일한 연락처로 추가된 어떤 데이터가 다른 것을 나타내야할 경우 UUID를 활용할 수 있다고 합니다. 

조금 더 많이 다듬고 PR을 드리면 좋을텐데, 
STEP2를 구현하면서 구조 변경될 부분이 보여서 어떤 것은 추후에 다듬어 보려고 합니다. 
감사합니다. 추가로 리팩토링이나 질문이 있으시면 언제든 남겨주세요!

2024-01-09 13:55 UTC, songda515 commented on ios-contact-manager-ui/Controller/ViewController.swift
> +        let lastRowOfIndexPath = numberOfLastRow - 1
크래시가 발생하기 때문에 개발하면서 신경써줘야하는 부분인데 잘 수정해주셨네요 🙂🙌

`NSNotFound` 를 개발자가 직접 값을 입력하는게 일반적인 경우는 아니지만, 명시적으로 나타내고싶다면 가능은 할것 같아요. 다만 개인적으로는 `NSNotFound` 값이 정수형의 특정 값을 나타내는거라 필요하다면 Bool 타입의 변수를 두는게 더 간단명료할 것 같아요!

2024-01-09 13:57 UTC, songda515 commented
두분 코멘트 사항 반영하시느라 고생많으셨습니다! 👍 
수정사항의 커밋을 남겨주시니까 확인하기 편하네요~
STEP 1 은 머지하도록 할게요~~ 이번주도 화이팅하세요!

2024-01-09 13:57 UTC, songda515 approved these changes

2024-01-09 13:58 UTC, merged