연락처 관리 앱  [STEP 1] Hong, Effie
tasty-code/ios-contact-manager-ui pull request #64
Opened 2024-01-08 08:11 UTC by hyeffie

안녕하세요, 라이언(@ryan-son)! 이번 연락처 관리 앱 프로젝트 진행하게 된 에피(@hyeffie), 홍(@ujhong7)이라고 합니다.

이번 step에서는 MVC 구조 기반에서 각 객체 역할과 관심사를 충분히 분리하도록 설계하고 구현하는 것을 주안으로 두고 작업했습니다. 추가로 각 역할에 충실한 커스텀 뷰를 만들어 사용하고, 확장을 고려해 객체 간의 관계를 인터페이스로 연결하려는 시도를 했던 한 주였던 것 같습니다. 그럼 첫 리뷰 잘 부탁드리겠습니다!

## 구조

기본적으로 MVC 구조에서 delegation 방식으로 데이터를 전달하도록 구현했습니다.

- Domain
    - Entity
        - Contact
            이름, 나이, 전화번호를 가지고 있는 연락처 타입
        - ContactList
            연락처를 배열로 관리하고, 연락처 관련 기능을 가지고 있는 타입
    - UseCase
        - ListContactUseCase
            Contack 목록 화면에서 리스팅과 관련된 기능을 제공하는 타입
- Data
    - Repository
        - ContactRepository
            다양한 소스로부터 Contact 에 대한 기능을 처리하고 결과를 가져오는 타입
- Presentation
    - ViewController
        - ListContactViewController
            연락처 목록 화면의 view를 관리하는 객체
    - View
        - ContactListView
            연락처 목록을 표시하는 테이블 뷰 객체

## 설계 아이디어

### ListContactViewControllerFactory를 구현한 이유

ListContactViewController와 관련된 객체를 생성하고 주입하는 코드가 이전에는SceneDelegate에 위치해 있었는데, 이를 인터페이스 메서드에서 하는 것보다는 작업을 담당하는 별도의 객체가 있으면 좋겠다고 생각해서 make 메서드를 제공하는 Factory 객체(사실상 네임스페이스와 메서드)를 만들었습니다.

### ContactRepository 계층을 추가한 이유

원래는 UseCase 객체가, 사용할 ContactList 참조에 직접 접근하는 방식으로 구현되어 있었습니다. 그런데 처음에 목록에 표시할 데이터를 생성하는 위치를 결정하려다 보니, use case에서 직접 생성하거나 이전 계층에서 생성하고 주입하는 흐름은 해당 객체들의 역할에 어울리지 않는다고 생각했습니다. 그래서 어떤 소스로부터 데이터를 가져오든, 또는 하드 코딩되어 있든 이 역할을 하는 별도의 객체가 필요하다고 생각해 구현하게 되었습니다.

### UITableViewDiffableDataSource를 사용한 이유

만약 테이블 뷰에 표시할 데이터에 변화가 생기면 table view의 reloadData 메서드를 호출해 전체 테이블을 다시 그려야 했습니다. 그렇지 않으면 타겟 cell을 변경하기 위해 indexPath를 직접 계산해야 하는 문제가 있었습니다.

UITableViewDiffableDataSource를 사용하면 snapshot 을 이용해 view에 표시할 데이터를 관리할 수 있고, 내부적으로 hash 값을 사용해 diff를 인식하고 처리하기 때문에 처리 효율을 높이고, 제공하는 애니메이션을 사용할 수 있는 장점이 있어 채택하게 되었습니다.

## 질문

### UITableViewCell 과 같은 view가 도메인 모델인 Contact를 직접 가지는 구현

```swift
// cell이 Contact 를 속성으로 가지고 있고, didSet에서 view 를 업데이트하는  구현 방식

class TableViewCell: UITableViewCell {
    var contact: Contact? {
        didSet {
            guard let contact = contact else { return }
            
            let contactAge = contact.age != nil ? "(\(contact.age!))" : ""
            let nameAgeText = "\(contact.name!) \(contactAge)"
            
            textLabel?.text = nameAgeText
            detailTextLabel?.text = contact.phoneNumber
        }
    }
    ...
}
```

```swift
// 파라미터로 전달받은 Contact 인스턴스로 view 를 업데이트 하는 방식

final class ContactListCell: UITableViewCell {
		...
    func update(with newContact: Contact) {
        let info = "\(newContact.name)(\(newContact.age))"
        self.infoLabel.text = info
        self.phoneNumberLabel.text = newContact.phoneNumber
    }
}
```

저희가 여러 버전으로 구현하면서 커스텀 cell이 직접 도메인 모델인 Contact 를 가지고 있고, didSet 으로 view를 업데이트하는 방식의 구현도 시도해봤었는데요.

이 방식은 cell.contactID에 값을 재할당해서 간편하게 처리할 수 있는 장점이 있었습니다. 다만, 파라미터로 Contact 타입을 전달해서 view를 업데이트하는 아래 구현과는 또 다르게 두 타입 간에 의존성 이상의 관계가 생긴다고 판단해서 현재의 구현을 선택하게 되었습니다.

라이언은 두 가지 구현 방식에 대해 어떻게 생각하시는지 궁금합니다.

### required init(coder:)의 구현

```swift
final class ListContactViewController: UIViewController {
		...
    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }
    
    init(useCase: ListContactUseCase) {
        self.listContactUseCase = useCase
        super.init(nibName: nil, bundle: nil)
        self.listContactUseCase?.presenter = self
    }
```

```swift
final class ListContactViewController: UIViewController {
    ...
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```

저희처럼 스토리보드와 xib 대신 code base로 UI를 구현하는 경우에는, NSCoder 를 전달받는 인터페이스가 호출되지 않고, 호출되지 않아야 하는데요.

구현 상으로는 호출될 가능성이 없지만, required 처럼 구현이 강제되는 경우 어떤 식으로 구현하는 게 좋을지 고민입니다. Xcode가 제안하는 것처럼 fatalError를 발생시키는 것도 괜찮은 방법일까요?

### table view가 data source를 직접 소유하는 형태도 괜찮을까?

현재 PR을 보내고 있는 브랜치의 구현에서는 ViewController에서 table view와 table view의 data source를 각각 속성으로 참조하고 있는데요.

view controller가 data source 를 업데이트하는 방식을 의도해서 이렇게 구현했지만, data source 파일을 어느 그룹에 포함시켜야 할지 고민하다보니, 문득 data source는 MVC 에서 어느 곳에 위치하고 있을까…? 라는 의문이 들며.. view에 가깝다면 view가 포함하는 구현은 어떨까? 라는 아이디어가 떠올랐습니다.

그래서 table view가 커스텀 data source를 속성으로 갖도록 구현해보았는데요.([코드](https://github.com/hyeffie/ios-contact-manager-ui/tree/step1/data-source-in-view)) 결론적으로 이런 구현은 view controller에서 data source에 직접 접근하지 않기 때문에 코드가 깔끔해지고 읽기 쉬워지는(?) 장점이 있지만, 

내부적으로는 data source 를 생성하는 시점에 전달한 table view의 delegate 로 self를 할당할 것이라 추측되기 때문에, 결과적으로 table view가 data source를 두 개의 속성으로 들고 있게 되는 문제가 있더라고요.

최종 코드에는 반영하지 않았지만, 라이언은 이런 구현 방식에 대해 어떻게 생각하시는지 궁금합니다!

2024-01-08 17:46 UTC, ryan-son requested changes
홍, 에피, Step 1 수행하시느라 고생 많으셨습니다.

전반적으로 타입별 역할을 나누고 인터페이스를 추상화하여 유연한 구조를 만드는 데 집중하신 것으로 파악됩니다. 유연한 구조를 만드는 것이 목적이라면 어느정도 목적을 달성하셨다고 볼 수 있을 것 같습니다. 한편으로는 어떤 효용을 얻을 수 있었는지가 분명하지 않다고 보이는 점도 있습니다. 모든 타입이 일관성 있게 의존성 분리를 통해 제어 역전(Inversion of Control)을 이루고 있지 않으며 ViewControllerFactory는 실제 Release 환경에서만 사용할 수 있는 인스턴스를 생성한다는 점이 그랬습니다. 상황에 맞게 의존성을 제공하고, 테스트할 수 있는 구조를 만들기 위해 유연성을 고려하셨다면, 어떤 의존성을 분리하고, 어떤 것을 분리하지 않아도 될지에 대한 고민을 해보시면 도움이 될 것입니다.

## 질의응답
### UITableViewCell 과 같은 view가 도메인 모델인 Contact를 직접 가지는 구현
UITableViewCell과 같은 요소가 도메인 인스턴스를 소유하고 didSet과 같은 프로퍼티 옵저버를 통해 UI 업데이트 작업을 수행하는 경우 편의성과 직관성이라는 장점이 있지만 말씀하신 것처럼 View 요소가 도메인 모델 인스턴스에 의존하게 된다는 단점이 있습니다. 반면 메서드를 통해 전달하는 방식은 View가 도메인 모델 인스턴스를 소유하지 않고 UI 프로퍼티 설정에만 사용함으로써 UI 표현이라는 역할에 충실할 수 있습니다. 셀의 재사용 측면에서 바라보면 도메인 모델을 인스턴스 프로퍼티로 다루는 경우 재사용 시 해당 프로퍼티를 UI 요소의 속성과 함께 nil 상태로 초기화해주어야 한다는 번거로움도 있을 것 같네요.

### required init(coder:)의 구현
코드로 UI를 구성하는 경우 해당 이니셜라이저가 호출되지 않을 것임을 확신할 수 있으므로 fatalError를 사용해도 괜찮다는 의견입니다. 저는 이런 경우에 available attribute를 통해 해당 이니셜라이저 인터페이스를 호출할 수 없도록 방지합니다.

```swift
@available(*, unavailable)
required init?(coder: NSCoder) {
    fatalError("...")
}
```
![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/69730931/a0b90925-b737-4a26-94ac-4d104f8d09d3)

### table view가 data source를 직접 소유하는 형태도 괜찮을까?
응집도 측면에서 생각해볼 수 있는 괜찮은 선택지입니다. DataSource가 UITableView 인스턴스를 요구하여 순환참조 발생이 우려된다면 deinit을 통해 해당 인스턴스가 의도한 시점에 메모리 해제가 되는지 살펴보시면 될 것 같습니다.

궁금하신 점 있으시면 언제든지 말씀해주세요~

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/FileExtension.swift
> +}
파일 확장자를 열거형으로 구성하신 이유가 있으실까요? 케이스의 String 변환을 쉽게 지원하실 의도라면 string 프로퍼티 대신 RawValue를 활용해볼 수 있을 것 같습니다.
```swift
enum FileExtension: String { ... }

FileExtension.json.rawValue // "json"
```

- [Implicitly Assigned RawValues - Swift Language Guide](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations/#Implicitly-Assigned-Raw-Values)

FileExtension 인스턴스 조건에 따른 처리를 염두에 두시고 타입을 구성했고, 상황에 따라 커스텀 파일 확장자 인스턴스를 필요로 한다면 주로 사용하거나 예상되는 파일 확장자를 타입 인스턴스로 선언하고, 필요에 따라 커스텀 인스턴스를 생성하여 사용하여 유연성을 부여할 수도 있습니다. 상황과 의도에 맞추어 구성하시면 됩니다.

```swift
struct FileExtension: RawRepresentable {
    static let json = Self(rawValue: "json")

    let rawValue: String

    init(rawValue: String) {
       self.rawValue = rawValue
    }
}
```

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/ListContactViewControllerFactory.swift
> +}
1. ListContactUseCase가 의존성 주입을 받을 수 있음에도 ContactRepositoryImpl 인스턴스만을 주입 받는 방식이므로 실제 환경에서의 ListContactViewController 인스턴스 생성에만 사용할 수 있을 것 같네요. ViewController 인스턴스를 생성하는데 필요한 의존성을 신경쓰지 않아도 되니 편하기는 하지만 상황에 따라 의존성을 선택할 수 없으니 일장일단이 있는 방법이라고 할 수 있을 것 같습니다.
2. Factory 인스턴스가 필요없다면 열거형 타입으로 변경할 수 있을 것 같네요.

1번과 같이 의존하는 타입의 인스턴스를 편리하게 다루기 위해 Dependency Injection(DI) Container, Composition Root에서 의존성 객체 그래프를 조합하는 방식과 같은 개념을 이용할 수 있습니다. 관심이 있으시다면 향후에 [Swinject](https://github.com/Swinject/Swinject), [Swift Dependencies](https://github.com/pointfreeco/swift-dependencies), [Pure](https://github.com/devxoul/Pure) 같은 의존성 주입 프레임워크 오픈소스들을 참고해보세요.

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/ReusableCell.swift
> +}
멋지네요. 여기에서 확장해서 `ReusableCell`을 만족하는 `UITableView`의 `register`와 `dequeueReusableCell` 메서드에서 `reuseIdentifier` 요소를 제거해볼 수도 있을 것 같습니다.

```swift
tableView.register(ContactListCell.self)

let cell: ContactListCell = tableView.dequeueReusableCell(for: indexPath)
```

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
> +}
1. BundleResourceManager가 내부적으로 Bundle.main 인스턴스에 의존하고 있어 별도의 번들을 이용하고자 하는 경우에 이 타입을 사용하기 어려워질 수 있겠네요. 이러한 의존성은 인스턴스 프로퍼티로 구성하고 이니셜라이저를 통해 주입받을 수 있도록 하거나, 메서드를 통해 대상 번들을 전달받을 수 있도록 구성하는 것이 좋을 것 같습니다.
2. 오타 정정: BundleResourseError -> ...Resource...

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/BundleResource/BundleResourseError.swift
> +}
LocalizedError 프로토콜을 통해 에러 이유를 로깅하기 편하게 구성해보는 것도 좋을 것 같습니다.

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +    private let jsonDecoder: JSONDecoder = .init()
JSONDecoder는 다른 타입과 달리 의존성 주입 대신 초깃값을 제공한 이유가 있을까요?

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +        return try BundleResourceManager().getData(from: fileName, extension: .json)
BundleResourceManager 인스턴스는 인터페이스를 추상화하고 느슨하게 결합하는 것이 좋겠네요. 왜 그럴까요?

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Domain/ListContact/ListContactModel.swift
> +}
이런 경우에는 자체적으로 지원하는 [Result](https://developer.apple.com/documentation/swift/result) 타입을 활용해볼 수도 있을 것 같습니다. 혹시 Result 타입 대신 이렇게 구성하신 특별한 이유가 있으셨을까요?

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Domain/ListContact/ListContactUseCase.swift
> +    weak var presenter: ListContactPresentable?
Delegate 패턴을 통해 UseCase -> ViewController 의존성을 느슨하게 만들어주신 점이 인상적이네요. UseCase는 ContactRepository와 달리 인터페이스를 추상화하시지 않은 이유가 있으실까요?

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Domain/Model/ContactList.swift
> +    }
CRUD를 미리 구현해두셨네요. 로직을 다루는 UseCase에서 에러 처리를 하도록 만들어 책임을 분리하신 점도 좋은 포인트라고 생각합니다. 
1. 수정 후 결과를 반환하신 건 테스트를 위함인가요?
2. ContactList를 class로 설계하신 의도는 무엇인가요?

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Domain/Model/ContactList.swift
> +        return (0 ..< self.contacts.count).contains(index)
아래 표현도 동일한 결과를 낼 수 있습니다. 참고하세요~

```swift
return self.contacts.indices.contains(index)
```

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/ListContact/View/ContactListCell.swift
> +    }()
속성을 지정해 인스턴스를 생성하셨네요. 클로저의 개념을 잘 이해하고 계시는군요.

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/ListContact/View/ContactListView.swift
> +final class ContactListView: UITableView {
`ContactListTableView`와 같은 이름을 사용하면 상속하는 타입을 파악할 수 있어 구현을 이해하는 데 도움이 될 수 있습니다.

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/ListContact/ViewController/ListContactViewController.swift
> +            let contacts = successInfo.contacts.map { contact in ContactListItem.contact(contact) }
한 줄로 작성하신 걸 보니 코드를 간소화시키고 싶으신 욕구가 있으신 것 같네요. map이 요구하는 매개변수의 타입이 `(Contact) throws -> T`임을 이용해 아래와 같이도 작성할 수 있습니다.

```swift
let contacts = successInfo.contacts.map(ContactListItem.contact)
```

2024-01-08 17:46 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/ListContact/ViewController/ListContactViewController.swift
> +            print("no such file")
1. 로그를 조금 더 자세히 남겨볼 수 있을까요? fail 인스턴스에서 전달한 error를 이용할 수 있을 것 같습니다.
2. 로그와 함께 사용자가 이해할 수 있도록 에러를 표시해보는 로직을 추가해볼 수도 있겠네요.

2024-01-10 00:52 UTC, hyeffie commented on ContactManager/ContactManager/Common/FileExtension.swift
> +}
문자열 리터럴을 사용하는 것 보다는 문자열 값을 저장해두고 사용하면 좋을 것 같아서 열거형을 선택했던 것 같아요. 항상 프레임워크들의 api를 보면서 열거형 대신 타입 프로퍼티를 사용하는 구현은 왜 이렇게 구현한 걸까 궁금했었는데 런타임에 인스턴스를 만들어서 사용하기 위함인지는 몰랐어요. 너무 좋은 방법인 것 같아서 반영해보려고 합니다!

2024-01-10 01:09 UTC, hyeffie commented on ContactManager/ContactManager/Common/ReusableCell.swift
> +}
register는 반영해봤습니다! 그런데 dequeueReusableCell의 경우는 한 테이블 뷰에 한 종류 이상의 셀을 사용하는 경우가 있을 수 있으니까 UITableView extension에 추가하기는 애매한 것 같다고 느껴지더라고요. 제가 위 코드의 의도를 잘 이해하지 못한 걸까요..?

2024-01-10 01:23 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/ListContact/ViewController/ListContactViewController.swift
> +            print("no such file")
관련해서 로그를 출력하는 코드와 alert를 표시하는 코드를 presentation 로직에 함께 추가해보았는데요. 발생한 로그를 여러 계층에서 나누지만 결과적으로는 view controller에서 전달받은 에러를 처리하고 있는데, 사용자에게 표시되지 않는 로그는 어디에서 처리하는 게 적절한지 고민되더라고요. 라이언은 어느 위치에서 처리하는 게 좋다고 생각하시나요? @ryan-son

2024-01-10 01:26 UTC, hyeffie commented on ContactManager/ContactManager/Domain/ListContact/ListContactModel.swift
> +}
특정 use case에서 사용되는 타입임을 명시하기 위함이었는데, Result를 사용하는 것도 충분히 괜찮은 것 같아서 반영해보았습니다!

2024-01-10 01:33 UTC, hyeffie commented on ContactManager/ContactManager/Domain/ListContact/ListContactUseCase.swift
> +    weak var presenter: ListContactPresentable?
use case는 화면에 의존적이라고 생각하고, 구현이 교체되는 경우를 고려하지 않아서 추상화하지 않았던 것 같아요. 사실 use case의 추상화에 대해서 줄곧 궁금해했었는데, 혹시 라이언은 어떻게 생각하시나요?

2024-01-10 01:35 UTC, hyeffie commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +    private let jsonDecoder: JSONDecoder = .init()
디코더의 decoding strategy 등을 설정해야 하거나, 커스텀해서 사용하게 될 시나리오를 고려해보지 않아서 추상화나 주입을 사용하지 않았던 것 같아요. 

지금 보니까 주입받을 게 아니라면 굳이 속성으로 가지고 있어야 할 이유도 없는 것 같다는 생각이 들어서 우선 일회성으로 만들고 해제하도록 구현을 수정해두려고 합니다.

혹시 라이언은 디코딩 객체도 추상화하시는 편이신가요?

2024-01-10 02:46 UTC, hyeffie commented on ContactManager/ContactManager/Domain/Model/ContactList.swift
> +    }
원래는 하나의 ContactList를 참조할 생각으로 class 로 구현했습니다. 처음 구현에서는 use case가 ContactList를 참조하는 방식으로 구현되어서 get을 비롯해 다른 연산에서도 화면에 반영할 데이터를 리턴해야 했는데요. repository 계층을 추가하고, json 파일 디코딩 로직을 추가하는 과정에서 get 외의 기능들의 구현들에 변화를 반영해야 했던 게 누락된 것 같습니다. 이 부분을 수정하는 과정에서 생긴 질문이 있는데 별도의 코멘트에 작성하도록 하겠습니다!

2024-01-10 04:31 UTC, hyeffie commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +        return try BundleResourceManager().getData(from: fileName, extension: .json)
지금 구현으로는 ContactRepositoryImpl에서 BundleResourceManager에 의존하고 있어 분리가 어려워요. getData를 인터페이스로 제공해서 결합도를 낮추면 번들에 접근하는 구현 외에 다른 구현을 사용할 수 있을 것 같아요.

2024-01-10 05:00 UTC, hyeffie commented on ContactManager/ContactManager/Common/ListContactViewControllerFactory.swift
> +}
구현할 당시에는 해당 로직을 SceneDelegate와 분리하는 방향에 대해서만 생각하고 로직을 이동시키기만 했지, 환경에 따라 의존성을 선택하는 측면에 있어서는 고민해보지 못했던 거 같아요. 
제가 DI에 대한 사전지식이 충분하지 않아서 공유해주신 자료를 바탕으로 학습한 후에나 적용해 볼 수 있을 것 같더라고요. 기회가 된다면 학습 후에 프로젝트에 적용해보도록 하겠습니다. 감사합니다!

2024-01-10 05:16 UTC, hyeffie commented
라이언 안녕하세요. 리뷰 내용 모두 확인했고, 제안해주신 내용 반영해서 올려두었습니다!

추가로 위에 코멘트 해주셨던 ContactList 구현과 관련해서 핵심 객체를 변경하고 결과를 처리하는 데에 있어 항상 고민되던 부분이 있어 질문드리고 싶은 내용이 있는데요.

ContactList 인스턴스를 참조해서 ContactList 내부에 Contact 배열을 변경하는 add, update, delete을 처리하는 방법에 다음의 방법들이 있다고 생각하는데 어떤 게 가장 적절한 방법인지 궁금합니다.

1. ContactList 연산 후 변경된 최신 배열을 직접 리턴하는 방법
2. ContactList 연산은 직접 리턴하지 않고, ContactList 연산을 호출한 위치에서 다시 getContacts를 호출해서 결과를 사용하는 방법
3. 배열에 대해 변경이 발생했을 때 didSet에서 notification를 post 하고, 변경을 반영해야 하는 곳에서(view controller) noti를 받았을 때 use case의 getContacts를 호출하는 방법

혹시 위에 있는 선택지보다 더 좋은 방식이 있다면 제안 부탁드리겠습니다..!

2024-01-11 02:46 UTC, ryan-son approved these changes
에피, 홍, Step 1 수행하시느라 고생 많으셨습니다!

추가 코멘트 참고해보시고 필요하신 내용은 반영해보시면 좋을 것 같습니다.
리뷰하면서 ContactList, ListContact와 같은 이름이 유사한 목적으로 혼용되는데, 이유가 있으셨던걸까요?

>ContactList 인스턴스를 참조해서 ContactList 내부에 Contact 배열을 변경하는 add, update, delete을 처리하는 방법에 다음의 방법들이 있다고 생각하는데 어떤 게 가장 적절한 방법인지 궁금합니다.
>1. ContactList 연산 후 변경된 최신 배열을 직접 리턴하는 방법
>2. ContactList 연산은 직접 리턴하지 않고, ContactList 연산을 호출한 위치에서 다시 getContacts를 호출해서 결과를 사용하는 방법
>3. 배열에 대해 변경이 발생했을 때 didSet에서 notification를 post 하고, 변경을 반영해야 하는 곳에서(view controller) noti를 받았을 때 use case의 getContacts를 호출하는 방법

세 가지 중에 선택한다면 2번을 선택할 것 같습니다. 인터페이스가 가장 직관적이고 오해할만한 부분이 없기 때문입니다. 1번은 편의성은 고려되었지만 Create, Update, Delete의 결과가 전달한 연락처 인스턴스 자체인지, 배열인지에 대한 오해가 있을 수 있고(removeFirst와 같은 인터페이스는 삭제한 인스턴스를 반환함), 3번은 1:N 통신이 필요없고, 이러한 변경 사항을 감지하기 위해 NotificationCenter를 사용해야 한다는 내용이 팀에 공유되어야하기에 불편한 점이 있을 것 같네요.

추가 궁금하신 사항은 회의실에서 이야기 나눠보시죠. Step 2도 화이팅입니다!

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/AlertableError.swift
> +}
추상화 계층을 추가해서 변경에 유연하게 대응할 수 있게 구성하셨네요. 👍 ErrorAlertConfig에 필요에 따라 프로퍼티를 추가, 변경, 제거하더라도 AlertableError에 영향을 주지 않을 수 있겠어요.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/ErrorAlertPresentableViewController.swift
> +        let defaultAction = UIAlertAction(title: "확인", style: .default)
AlertableError 인스턴스를 통해 okActionTitle을 받았으니 이곳에 적용해볼 수 있을 것 같네요.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/ErrorAlertPresentableViewController.swift
> +        }
추가 액션은 다수 전달 받을 수 있도록 배열이나 variadic parameters로 구성하면 조금 더 범용성 있게 사용할 수 있을 것 같아요.
- [Function/Variadic Parameters - Swift Language Guide](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/functions/#Variadic-Parameters)

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Common/ReusableCell.swift
> +}
이런 사용 케이스로 고려해볼 수 있을 것 같네요. 연락처 셀과 광고 셀이 선택적으로 dequeue될 수 있다는 가정입니다.

```swift
case .contact(let contact):
    let cell: ContactCell = tableview.dequeueReusableCell(for: indexPath)
    cell.update(with: contact)
    return cell

case .advertisement(let advertisement):
    let cell: AdvertisementCell = tableview.dequeueReusableCell(for: indexPath)
    cell.update(with: advertisement)
    return cell
}
```

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
> +    }
기본값으로 사용하는 인스턴스가 있다면 미리 설정해두는 것도 좋겠네요.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
> +        let target = Bundle.main
주입 받은 인스턴스를 사용할 수 있게 만들 수 있을 것 같습니다.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +    private let jsonDecoder: JSONDecoder = .init()
주입해야할 의존성이 있고, 그렇지 않아도 될 의존성이 있다고 생각합니다. 사용하기 전 런타임에 초기화가 필요한 데이터베이스나 비결정론적 동작/알고리즘을 가지는 random, Date() 등의 메서드와 같은 Volatile Dependency는 주입해야할 의존성, 반대로 결정론적 동작, 알고리즘을 가지는 의존성은 분리하지 않아도 될 의존성이라고 볼 수 있겠네요. 따라서 저는 디코딩 객체까지는 추상화하지 않고, 필요한 프로퍼티를 설정해서 인스턴스 프로퍼티 또는 전역에 선언해두는 편입니다.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Domain/ListContact/ListContactUseCase.swift
> +    weak var presenter: ListContactPresentable?
UseCase가 View와 로직 간의 중개 역할만 수행하고 의존성 이외의 상태를 가지지 않는다면 추상화 레벨을 더할 필요는 없다고 생각합니다. 필요한 상태는 주입할 의존성 인스턴스를 조작해서 의도한 상태를 만들 수 있기 때문입니다.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Domain/ListContact/ListContactUseCase.swift
> +}
`fetchAllContacts`가 결과를 반환하는 구조도 고려해볼 수 있을 것 같은데, Presentable 계층을 추가하신 이유는 무엇이었나요?

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/ListContact/ViewController/ListContactViewController.swift
> +            print("no such file")
말씀하신 로그는 Side effect 요소라고도 볼 수 있을 것 같습니다. 별도의 로거 타입을 정의해서 발행한 로그를 Stack 형태로 상태 보존해두고, 외부에서 참조 가능한 형태로 만들어 발생시켰던 side effect가 의도했던 대로 발생했는지 확인할 수 있는 구조로 만들어볼 수 있을 것 같습니다. 로거는 디버그 모드에서 사용될 목적이므로 공용 인스턴스를 만들어 필요한 곳에서 사용할 수 있으니 필요한 위치에서 사용하면 될 것 같습니다.

2024-01-11 02:46 UTC, ryan-son commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +
Repository라는 이름을 가진만큼 requestContacts가 상황에 따라 로컬 또는 네트워크를 통해 연락처를 가지고 오는 케이스를 추가로 고려해볼 수 있을 것 같아요. 현재 요구사항에는 없는만큼 두 분이 논의만 진행해보시면 좋을 것 같습니다.

2024-01-11 02:46 UTC, merged