연락처 관리 앱 [STEP 2] LJ, 라마
tasty-code/ios-contact-manager-ui pull request #65
Opened 2024-01-08 08:16 UTC by ijs1103

# [연락처 관리 앱] Step 2 - PR

멤버 : @ijs1103, @llamang

리뷰어 : @yim2627

---

# 요구 사항

## Step 2

- 추가 기능을 구현하기 전에 동작에 대한 `UML`을 작성하여 PR에 추가합니다.(2023.10.12 수정)
    - 클래스 다이어그램, 액티비티 다이어그램, 시퀀스 다이어그램 중 필요한 UML을 선택하여 작성합니다.
- 연락처 목록 화면의 우상단 버튼을 통해 연락처 추가 화면에 진입할 수 있습니다.
- 오토 레이아웃과 스택 뷰를 활용하여 화면을 레이아웃합니다.
- 각 필드에 맞는 키보드 종류를 지정합니다.
- 취소 버튼을 선택하면 정말 취소할 것인지 묻도록합니다.
- 저장 버튼을 선택하면 입력한 정보가 올바르게 입력되었는지 확인하도록 합니다.
    - 이름은 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다.
    - 나이는 숫자로만 입력해야하며, 세 자리수 이하여야 합니다.
    - 연락처는 중간에 `-`로 구분하며, `-`는 두 개가 존재해야 합니다.
        - `-`을 제외하고 숫자는 9자리 이상이어야 합니다.

---

# 액티비티 다이어그램

요구 사항을 코드로 구현하기 전에, 로직이나 조건에 따라 처리되는 흐름을 먼저 파악하고 싶어서 Activity Diagram을 그렸습니다.
a4a7286251162dfbba3d2117bbd72a0dbfbb859e

[액티비티 다이어그램](https://github.com/ijs1103/ios-contact-manager-ui/blob/main/docs/ContactManager_Step2_ActivityDiagram.png)

2024-01-15 11:39 UTC, yim2627 requested changes
안녕하세요 LJ, 라마! 

PR에 자세히 전부 작성해주셔서 제가 달리 질문드릴게 크게 없네요 

자잘한 질문들과 여러분들이 작성하신 고민했던 것들, 질문에 대해서 말씀드리겠습니다.

## 고민하신 것, 질문 사항 피드백
### 패턴 사용 
LJ와 라마가 작성해주신 UI관련 팩토리, 빌더, 컴포넌트 등은 실제 현업에서도 **DesignSystem** 등에서 많이 사용되고 있습니다. 
많이 고민하신 티가 나서 정말 대단하시다고 느껴졌어요. 
팩토리, 빌더 패턴 등등은 코드가 분산 및 역할을 나누며, 사용처에서 매우 간단히 가독성 좋게 사용할 수 있다는 장점이 있다고 생각합니다. 
다만 여러 패턴의 혼용은 가독성을 해칠 수 있고 여러 보일러플레이트를 야기할 수 있는 단점이 있다고 생각합니다. 또한 코드의 응집도가 떨어지고, 분산이 될 수도 있겠네요. (별게 아닌데 타고타고타고 들어가야 구현부를 볼 수 있는 경우 등) 

### 클로저 주입
**클로저 사용 부분**에서 말씀드릴 것은 이니셜라이저를 통해 CoreDataManager -> ContactListVC ->  NewContactVC로 주입해주는 과정에서 가독성을 해치는 것 같다는 생각이 들었습니다. 
이 부분은 취향차이라서 따로 말씀드릴 것은 없지만, 여러분들이 사용해주신 Delegate를 여기서 적용할 수도 있습니다. 또한 CoreDataManager의 기능중 하나인 **추가**를 사용하는 곳은 NewContactVC이기 때문에 CoreDataManager 자체를 주입해주는 것도 좋을 것 같습니다. 
추가를 하는 곳은 결국 NewContactVC이니 ContactListVC에서 핸들러를 받아 사용하는 것은 조금 어색해보일 수 있다는 생각이 들었어요.

### Validator등의 열거형
Validator 등의 타입은 역할이 분명하기때문에 나눠주신 점이 굉장히 가독성에 도움이 되었습니다. 다만 **열거형만 사용하는 이유**를 여쭤보고싶습니다. 이 부분은 이후 DM이나 답글로 답변 부탁드리겠습니다.

### UINavigationBar 설정을 위한 configureNavigationBar 메서드 (UIViewController+)
 이 부분은 회사마다 다 다를 것 같습니다. 어차피 rootVC에 NavigationController를 씌우면 이후 이동되는 화면에는 Present를 제외하곤 적용이 되기떄문에 이때는 상관이 없을 것 같습니다. 
하지만 Present를 하는 경우엔 얘기가 다른데 이때 NavigationController를 사용하면 간단하기도 하고, 프로젝트에 영향을 주는 비용을 소모하지도 않기때문에 저는 NavigationController를 씌워 구현하는 방법을 선호합니다. 
NavigationBar를 직접 생성하진 않고 차라리 그 부분 커스텀이 필요하다면 커스텀뷰를 만들어 얹었던 경험이 있습니다.

### 연락처 포매팅 기능 구현
 해당 타입은 Enum Static으로 전부 구현해주셔서 사용하기 편하게끔 만드셨다는 생각이 들어 따로 피드백 드리지 않았습니다. 위에서 질문드린 **열거형만 사용하는 이유 + 전역 변수, 함수는 어느 곳에 저장되고, 어떤 장단점이 있는지** 말씀해주세요.

### 폴더 구조
 이 부분은 케바케가 엄청나게 강한 부분이라 따로 말씀은 안드리려했지만, 말씀드리면 우선 깔끔하게 잘 해주신 것 같습니다. 하지만 Model이라는 폴더 네이밍이 조금 어색하다는 생각이 들어요. 
그것 빼곤 다 괜찮은 것 같습니다. 
여기서 좀 더 깔끔해지려면 특정 부분을 기준으로 잡고 한 뎁스 더 들어가 폴더링하는 것도 방법이겠네요! 

그리고 현재 테스트 모델이 남겨져 있어 신규 연락처 저장 후 앱 종료 -> 재시작시 남아있어야 할 데이터가 남아있지 않는 문제가 있습니다. 수정 부탁드려요!

스텝 2 정말 고생 많이하셨고 고민 많이 하신 것처럼 보여서 다시 한번 대단하다고 느꼈습니다.   
궁금하신 점은 언제든지 DM주세요!

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/NewContactViewController.swift
> +    typealias AddContactHandler = (_ contact: Contact) throws -> Void
typealias를 사용하셨네요! typealias는 어떤 역할을 할까요?

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Controller/NewContactViewController.swift
> +    typealias AddContactHandler = (_ contact: Contact) throws -> Void
`(_ contact: Contact) throws -> Void`만 따로 typealias로 지정해주신 이유가 있을까요?

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Model/ContactData.swift
> +]
테스트 모델은 지우시는게 좋습니다.

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Model/ContactManager.swift
> +    }
기본값을 넣어주신 이유가 있나요?

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Service/AlertService.swift
> +    weak var viewController: UIViewController?
weak를 사용해주셨군요! 👍👍
어떤 이유때문에 weak를 사용해주셨는지가 궁금합니다!

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Service/AlertService.swift
> +            .build()
👍👍

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Service/PhoneNumberFormatter.swift
> +        }
enum의 이니셜라이저는 왜 실패가능한 이니셜라이저일까요?

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Service/PhoneNumberFormatter.swift
> +        return regex?.stringByReplacingMatches(in: digits, range: nsRange, withTemplate: template)
정규식까지 👍

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Util/RegexHelper.swift
> +}
👍 👍

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/View/InputView.swift
> +    }()
굳이 lazy로 선언 할 필요가 없어보이는데 lazy를 붙이신 이유가 있을까요? 컨벤션인가요?

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Util/InputValidator.swift
> +}
다른 Util성 타입들도 그렇고, Enum과 Static의 조합을 많이 사용하시는 이유가 궁금합니다.

2024-01-15 11:39 UTC, yim2627 commented on contact-manager/contact-manager/Sources/Util/LabelFactory.swift
> +}
이런 부분은 클로저로 충분히 가능하기때문에 개인적으론 따로 Factory를 생성하지 않는 것 같습니다. 파일만 많아지는 것 같아서요!

2024-01-16 12:56 UTC, llamang commented on contact-manager/contact-manager/Sources/Controller/NewContactViewController.swift
> +    typealias AddContactHandler = (_ contact: Contact) throws -> Void
> typealias를 사용하셨네요! typealias는 어떤 역할을 할까요?

`typealias`를 사용해서 기존 타입에 별칭을 선언하면, 프로그램 내에서 해당 별칭으로 기존 유형을 참조할 수 있습니다. 

특히 클로저와 같은 복잡한 타입을 처리할 때, 코드를 더 읽기 쉽고 유지 관리하기 쉽게 만들 수 있습니다.

참고로, `typealias`는 새 유형을 생성하지는 않습니다.

[Type Alias Declaration](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/declarations/#Type-Alias-Declaration)

2024-01-16 12:57 UTC, llamang commented on contact-manager/contact-manager/Sources/Model/ContactManager.swift
> +    }
> 기본값을 넣어주신 이유가 있나요?

`ContactManager` 생성자를 통해 연락처 목록을 초기화할 수 있는 옵션을 제공한 것입니다.
만약 초기 연락처 목록을 제공하지 않으면, 비어있는 연락처 목록을 가지도록 매개변수에 기본값을 할당했습니다.

2024-01-16 13:00 UTC, llamang commented on contact-manager/contact-manager/Sources/Service/AlertService.swift
> +    weak var viewController: UIViewController?
> weak를 사용해주셨군요! 👍👍 어떤 이유때문에 weak를 사용해주셨는지가 궁금합니다!

약한(weak) 참조는 참조하는 인스턴스를 강력하게 유지하지 않는 참조이므로, ARC가 참조된 인스턴스를 삭제하는 것을 막지 않습니다. 이 동작은 참조가 강한 참조 순환(strong reference cycle)의 일부가 되는 것을 방지합니다.

강한 참조 순환(strong reference cycle)은 두 클래스 인스턴스가 서로에 대한 강력한 참조를 보유하여 각 인스턴스가 다른 인스턴스를 활성 상태로 유지하는 경우 발생할 수 있습니다.

2024-01-16 13:00 UTC, llamang commented on contact-manager/contact-manager/Sources/Service/PhoneNumberFormatter.swift
> +        }
> enum의 이니셜라이저는 왜 실패가능한 이니셜라이저일까요?

초기화 시에 제공된 매개변수가 적절한 열거형 케이스와 일치하지 않으면, 초기화가 실패할 수 있기 때문입니다.

[Failable Initializers for Enumerations](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization/#Failable-Initializers-for-Enumerations)

2024-01-16 13:02 UTC, llamang commented on contact-manager/contact-manager/Sources/Util/InputValidator.swift
> +}
> 다른 Util성 타입들도 그렇고, Enum과 Static의 조합을 많이 사용하시는 이유가 궁금합니다.

인스턴스별로 독립된 상태를 가질 필요가 없을 때, 인스턴스 생성 방지를 위해 해당 조합을 사용합니다.

`Enum`은 클라이언트가 `let inputValidator = InputValidator()` 방식으로 인스턴스를 만들 수 없는 타입입니다. 

물론 `Struct`나 `Class`에서도 생성자에 `private` 접근 제어자를 붙일 수 있지만 실수로 깜박하거나 번거로운 작업일 수 있습니다.

하지만 `Enum` 타입은 별도의 내부 구현 확인 및 인스턴스 생성을 시도하지 않아도 명확히 알 수가 있습니다.

2024-01-16 13:06 UTC, llamang commented on contact-manager/contact-manager/Sources/Model/ContactData.swift
> +]
삭제했습니다!

2024-01-16 13:13 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/Controller/NewContactViewController.swift
> +    typealias AddContactHandler = (_ contact: Contact) throws -> Void
> (_ contact: Contact) throws -> Void만 따로 typealias로 지정한이유

해당상황처럼 타입이 비교적 길 경우에 typealias를 적용하여 코드의 간결성을 높였습니다.

2024-01-16 13:16 UTC, ijs1103 commented on contact-manager/contact-manager/Sources/View/InputView.swift
> +    }()
`arrangedSubviews` 에 속한 인스턴스들의 초기화가 된 것을 보장받기 위해 lazy 속성으로 선언하였습니다.

2024-01-16 13:26 UTC, llamang commented
# PR 메시지 추가 내용

## `addContactHandler: (_ contact: Contact) throws -> Void` 클로저

저희가 클로저를 선택했던 이유는, NewContactVC에 `ContactManager.addContact` 메서드에만 접근하도록 제한하고 싶었습니다.

그래서 처음에는 클로저 주입 대신에 delegate 패턴을 적용해 봤습니다. 하지만 `contactManager.addContact` 메서드가 에러를 던질 때, 다시 NewContactVC로 넘겨주어야 하므로 구현이 간편한 클로저 주입 방식으로 변경했습니다.

하지만 Contact을 추가(add)하는 작업은 NewContactVC의 이름에 따라 NewContactVC에서 처리하는 것이 적절하다는 생각이 듭니다. 

그래서 이번에는 클로저나 delegate 방식이 아닌, `ContactManager` 인스턴스의 주입을 선택했습니다.

대신, `ContactAdding` 프로토콜을 활용해서 NewContactVC가 `ContactManager.addContact` 메서드만 접근할 수 있도록 제한했습니다.

## `updateTableViewHandler: () -> Void` 클로저

NewContactVC에서 Contact을 추가한 후에 ContactListVC의 연락처 목록을 relaod 하기 위한 명시적인 클로저입니다. 

NewContactVC 입장에서는 해당 클로저가 무엇인지 그리고 할당되었는지와 상관없이, 해당 Modal이 닫힐 때 실행하는 이벤트 핸들러를 `onDismiss: (() -> Void)?` 클로저로 주입하는 것으로 변경했습니다.

```swift
init(contactManager: ContactAdding, onDismiss: (() -> Void)? = nil)
```

## Enum + Static

인스턴스별로 독립된 상태를 가질 필요가 없을 때, 인스턴스 생성 방지를 위해 해당 조합을 사용합니다.

`Enum`은 클라이언트가 `let inputValidator = InputValidator()` 방식으로 인스턴스를 만들 수 없는 타입입니다.

물론 `Struct`나 `Class`에서도 생성자에 `private` 접근 제어자를 붙일 수 있지만 실수로 깜박하거나 번거로운 작업일 수 있습니다.

하지만 `Enum` 타입은 별도의 내부 구현 확인 및 인스턴스 생성을 시도하지 않아도 명확히 알 수가 있습니다.

## 전역 변수 및 함수의 저장 위치와 장단점

전역/정적 프로퍼티와 메서드는 메모리의 데이터 영역에 저장됩니다.

인스턴스화가 필요 없고 특정 인스턴스에 의존하지 않는 것이 장점입니다.

앱의 어느 곳에서나 접근 가능하다는 것이 양날의 검이 될 수 있는데, 한 곳에서 변경하면 모든 곳에 영향을 미치므로 의도치 않은 부작용이 발생할 수 있으며 전역 상태 관리가 어려워질 수 있습니다.

또한, mocking 할 수 없기 때문에 테스트 코드를 작성하는 데 어려움을 겪을 수 있습니다.

## 연락처 목록 영구 저장 기능

연락처 목록의 영구 저장은 이번 프로젝트의 요구 사항이 아니라서 구현하지 않았습니다.

2024-01-17 11:25 UTC, yim2627 approved these changes

2024-01-17 11:26 UTC, merged