연락처 관리 앱 [STEP 2] 미르, 루피
tasty-code/ios-contact-manager-ui pull request #66
Opened 2024-01-12 04:21 UTC by kimdj1102

안녕하세요~ @FirstDo

미르, 루피 입니다! 연락처 관리 앱 STEP2 PR 보냅니다!
두번째 PR 잘 부탁드립니다~😀

## 프로젝트 구현 요구사항
### STEP 2 - 연락처 추가 기능 구현
- 추가기능을 구현하기 전에 동작에 대한 UML 을 작성하여 PR에 추가합니다.(2023.10.12 수정)
    - 클래스 다이어그램, 액티비티 다이어그램, 시퀀스 다이어그램 중 필요한 UML을 선택하여 작성합니다.
- 연락처 목록 화면의 우상단 버튼을 통해 연락처 추가 화면에 진입할 수 있습니다.
- 오토 레이아웃과 스택뷰를 활용하여 화면을 레이아웃합니다.
- 각 필드에 맞는 키보드 종류를 지정합니다.
- 취소 버튼을 선택하면 정말 취소할 것인지 묻도록합니다.
- 저장 버튼을 선택하면 입력한 정보가 올바르게 입력되었는지 확인하도록 합니다.
    - 이름은 사용자가 중간에 띄어쓰기를 하더라도 띄어쓰기를 제거합니다.
    - 나이는 숫자로만 입력해야하며, 세 자리수 이하여야 합니다.
    - 연락처는 중간에 -로 구분하며, -는 두 개 존재해야 합니다.
        - -을 제외하고 숫자는 9자리 이상이어야 합니다.

## 🤔고민이 되었던 점
#### UI를 스토리보드가 아닌 코드로 구현을 해보는 부분에 있어 고민을 했습니다.
- UI를 스토리보드로 구현을 하게되면 구현하면서 label이 어디에 들어가고 버튼이 어디에 들어가고 눈으로 확인하면서 볼수 있어 편하다는 장점이 있지만 코드리뷰를 받을때 시뮬레이터를 돌려보지 않는 이상 보기어렵다는 불편함이 있는 것과 코드로 UI를 구현을 하는 공부를 해보고 싶어 코드로 구현을 해봤습니다. 구글링을 통해 정보를 많이 얻긴했지만 코드로 UI를 구성하니 코드가 다소 복잡해보일순 있지만 스토리보드로 오토레이아웃을 잡을때보다 에러가 나는 부분을 정확히 캐치할수 있어서 좀더 편하다는 장점을 찾았습니다.

#### 새연락처 뷰에서 정보를 추가했을때 메인뷰에 어떻게 전달할까 고민을 했습니다.
- 정보들을 추가하면 메인뷰에 전달하는 방법으로는 델리게이트 패턴을 적용했습니다. 이전 프로젝트에서 경험을 한적도 있고, detailVC 할일을 다른객체에게 위임을 하는 방식으로 연락처추가에서 할일을 메인뷰에 위임을 하므로 그 정보들을 넘겨 추가하도록 구현을 해줬습니다.
```swift
 @objc func plusButtonTapped() {
     //...
     detailVC.delegate = self
     //...
 }
class ContactDetailViewController: UIViewController {
    //...
    weak var delegate: ContactDelegate?
    //...
    @objc func setupButtonAction() {
        //...
        delegate?.add(contact: new)
        //...
    }
}
```
#### 정보가 올바르게 입력되는 유효성검증을 어떻게 해야하나 고민을 했습니다.
- protocole을 입력하는 메서드에 채택을 해줬습니다. 프로토콜 메서드에 이름, 나이, 전화번호에 대한 유효성검증을 해줬는데, 이름에는 split으로 공백단위로 나눈다음, reduce고차함수를 통해 공백으로 나눈 String을 합쳐주도록 해줬고, 나이와 전화번호는 정규식을 통해 숫자와 하이픈이 들어가야 검증을 통과하는 식으로 구현을 해줬습니다.
```swift
 func setName(_ name: String) -> Bool {
        let setName = name.split(separator: " ").reduce("") { $0 + $1 }
        return !setName.isEmpty
    }
    
    func setAge(_ age: String) -> Bool {
        let setAge = age.split(separator: " ").reduce("") { $0 + $1 }
        let regex = "^([1-9]{1})?([0-9]{1,2})$"
        return NSPredicate(format: "SELF MATCHES %@", regex).evaluate(with: setAge)
    }
    
    func setNumber(_ number: String) -> Bool {
        let regex = "^0([0-9]{1,2})-?([0-9]{3,4})-?([0-9]{4})$"
        return NSPredicate(format: "SELF MATCHES %@", regex).evaluate(with: number)
    }
```
#### 전화번호를 입력할때 하이픈이 자동으로 들어갈수 있는 방법을 고민했습니다.
- String확장을 통해 formmater라는 프로퍼티를 만들어줘서 처음에는 string의 갯수를 9,10,11개에 대한 하이픈만 지정해줬더니 Index의 오류가 계속났었습니다. 9,10,11갯수 이외의 값에 대한 Index를 지정을 안해줘서 오류가 나는것 같아서 String 갯수마다 switch문으로 나눠 Index에 하이픈을 넣어주겠다라고 지정을 해줬더니 실행이 되는 것을 확인했습니다.
```swift
switch stringWithhypen.count {
        case 3...5:
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.startIndex, offsetBy: 2))
        case 6...9:
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.startIndex, offsetBy: 2))
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.endIndex, offsetBy: 5 - count))
        case 10:
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.startIndex, offsetBy: 3))
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.endIndex, offsetBy: -4))
        case 11:
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.startIndex, offsetBy: 3))
            stringWithhypen.insert("-", at: stringWithhypen.index(stringWithhypen.endIndex, offsetBy: -4))
        default:
            break
        }
```

## 🙏조언을 구하고 싶은 점 
#### 파일 폴더링 관련

<img src="https://hackmd.io/_uploads/H1okfmCua.png" width="300" height="500"/>   .

- 현재 위의 사진 기준으로 파일 폴더링을 진행했습니다. Resources와 Sources를 큰 갈래로 분류하고, Resource에는 Extension과 Storyboard, Delegate 및 Asset을 넣어주었고, Source에는 Model, View, Controller를 넣어주었습니다. 참고할만한 소스가 많이 없어서 일단은 이렇게 분류해두었는데, 혹시 더 괜찮은 방법이 있다면 조언 부탁드립니다 :)

2024-01-15 00:21 UTC, FirstDo requested changes
두분 고생하셨습니다.
프로젝트 요구사항에 맞게 잘 작성해주시고, 코드도 깔끔하게 작성해주셔서 저도 더 신나서 열심히 리뷰를 할 수 있었습니다 :)

## 잘 하신점

### 프로퍼티 옵져버 활용

아주 적절하게 활용해 주신것 같습니다
프로퍼티 옵져버는 특히 model이 업데이트되었을때, view를 업데이트 하는데 정말 좋은것 같습니다
RxSwift나 Combine을 사용하지 않고도 (부분적으로나마) 리액티브한 UI를 구성할 수 있다는점이요!

### 코드베이스 UI로 작성

리뷰하기도 편하고, Storyboard는 UI가 복잡해질수록 오히려 파악하기 어렵다는 문제가 있습니다
저는 CodeBase를 훨씬 더 선호합니다

### LifeCycle 매서드 활용

사용도 사용인데, 매서드를 사용함에 있어서 문서를 정확히 읽고 사용했다는느낌을 받을수 있어서
정말 좋았습니다!!!

## 개선점

### 콘솔에 오토레이아웃 에러가 뜹니다

Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600002152b70 UIStackView:0x107407210.centerX == ios_contact_manager_ui.DetailView:0x10aa06530.centerX   (active)>",
    "<NSLayoutConstraint:0x600002152b20 H:|-(10)-[UIStackView:0x107407210]   (active, names: '|':ios_contact_manager_ui.DetailView:0x10aa06530 )>",
    "<NSLayoutConstraint:0x600002152ad0 UIStackView:0x107407210.trailing == ios_contact_manager_ui.DetailView:0x10aa06530.trailing - 20   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002152b70 UIStackView:0x107407210.centerX == ios_contact_manager_ui.DetailView:0x10aa06530.centerX   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

고쳐주세요 ㅎㅎ

## 질문에 대한답변

당연히 정답은 아니며! 두분만의 방법을 같이 고민하고 찾아가는거 자체가 폴더링 실력(?)을 늘릴수 있는 방법일것 같습니다 :)

우선 Resoures, Sources를 나누신점은 너무 좋습니다

- Asset, Info, LaunchScreen등은 모두 Resource에 위치해야합니다
- Service(Manager)와 Model을 구분해야합니다

현재는 뷰가 작아서 괜찮지만, 언젠가는
많아질수록 Controllers도 1000개, Views는 3000개가 되겠죠??
한 폴더안에 파일이 1000개 들어있는것부터 문재입니다

저라면 아래처럼 Domain별로 묶을것 같습니다

<img width="481" alt="스크린샷 2024-01-15 오전 9 20 02" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/69573768/d7ef956d-e9cd-4e0f-ab1d-4cc74f4c18a2">

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/Extensions/String+.swift
> +    }
`blanck` 오타가 났네요!
reduce 고차함수를 쓰신점이 좋습니다.

다만 제 생각엔 그냥 한줄로 써도 충분할것 같다는 생각이 듭니다

```swift
return self.split(separator: " ").reduce("") { $0 + $1 }
```

더 직관적으로는 아래처럼 쓸 수도 있습니다

```swift
return self.replacingOccurrences(of: " ", with: "")
```

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/Extensions/String+.swift
> +    public var formmater: String {
요기는 public을 붙인 이유가 무언인가요??

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/Extensions/ViewController+.swift
> +    }
좀 더 확장성이 있는 Alert이 되었네요!
고민해서 개선하신점 정말 좋습니다!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/SceneDelegate.swift
> +    }
`neviVC` -> `naviVC`?
스토리보드를 없애시고 코드 베이스로 변경하신점도 좋습니다!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +}
델리게이트의 이름은 일을 맡길 주체가 되는게 좋을것 같아요

ex) `TableViewDelegate`, `CollectionViewDelegate`

여기서는 `ContactDetailVC`가 해야할 일을 위임하는거니까 `ContactDetailDelegate` 가 좀 더 적절할것 같습니다

추가로 ContactDelegate는 여러곳에서 채택할수가 있죠?

ex)

Contact2ViewController도 ContactDelegate를 채택할 수가 있습니다
이러면 `ContactDelegate` 파일 위치를 어디에 둬야할지 애매해질 수 있어요

그래서 해당 프로토콜은 ContactDetailVC 파일에 위치시키는게 더 적절합니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +        cell.accessoryType = .disclosureIndicator
`cell.accessoryType = .disclosureIndicator`
요런친구들은 cell 내부적으로 수행하는게 좋을것 같습니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    }
프로퍼티 옵져버를 사용해서 model (contact)가 변경될때마다 Label이 업데이트되도록 하신점은 좋습니다

다만 아래 로직은 한번만 설정되면 되는데, contact에 값이 업데이트 될때마다 수행해줄 필요가 없을것 같네요

```swift
nameTextField.keyboardType = .default
ageTextField.keyboardType = .numberPad
phoneNumberTextField.keyboardType = .phonePad
```

항상 이렇게 작성하게 된 이유가 가장 중요합니다.
추후 사전과제 하실때도 마찬가지이고요..!
면접관이 물어봤을때, 논리적으로 대답할 수 있어야 합니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    }
이친구는 왜 존재하는지 아실까요??

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    }
`updateConstrants`가 꼭 필요한 상황은 아닌것 같지만,
찾아보시고, 문서를 읽어보신후 잘 작성하신것 같아서 정말 좋았습니다!!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    let nameLabel: UILabel = {
private 접근제어자를 붙일 수 있는 친구들은 모두 붙여주세요
왜그래야할까요??

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/CustomCell.swift
> +final class CustomCell: UITableViewCell {
`CustomCell`보다 더 적절한 이름이 있을것 같습니다
final 키워드는 너무 좋습니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/CustomCell.swift
> +    }
Cell을 만들때마다 해당 코드를 써줘야하는데, UITableViewCell을 extension해서 일괄적으로 적용하는것이 좋아보입니다!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/CustomCell.swift
> +    }
프로퍼티 옵져버의 적절한 활용인것 같습니다 :)

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/CustomCell.swift
> +    let contactNameLabel: UILabel = {
private 처리 가능한 친구들은 모두 붙여주세요!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Models/Verification.swift
> +}
정규식과 프로토콜을 활용한 아이디어는 정말 좋습니다!

다만 Parser를 굳이 프로토콜로 구현하지 않은것처럼
Veritication도 마찬가지로 객체를 만들어서 하는게 좀 더 일반적인 방식일것 같네요..!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Models/ContactManager.swift
> +    var contacts: [Contact] = []
private(set)을 활용하면 read-only 프로퍼티를 만들 수 있습니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +}
프로토콜 요구사항 매서드가 아닌이상 extension으로 굳이 구분할 필요가 없어보입니다!
이렇게 하신 이유가 있을까요?

매서드를 나누신건 좋으나
같은 로직끼리 뭉쳐있는게 더 중요하다고 생각하고
tableView관련은 모두 한곳에서 처리하는게 더 좋아보입니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +        detailVC.modalPresentationStyle = UIModalPresentationStyle.automatic
`modalPresentationStyle`의 기본값이 automatic이여서 굳이 쓸 필요 없을것 같습니다!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +                                     tableView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0)])
스크린샷을 참고하면 UI에 약간문제가 있습니다
보통 테이블뷰 상하단을 SafeArea에 맟추지말고 View 전체영역에 맞춰주세요..!

![simulator_screenshot_2E3D31A6-9523-4F2F-8607-89D02B5CCD05](https://github.com/tasty-code/ios-contact-manager-ui/assets/69573768/97799c97-d7ff-4e45-ac3f-8be101f07d00)

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +    }()
아래에서 이왕 lazy var를 사용했다면
tableView관련 작업도 여기서 해주면 좋을것 같네요 (제약 거는거 제외)
나머지 프로퍼티들도 private 잊지말아주세요!

추가적으로 lazy var를 사용한다면 문제가 있을 수 있는데
어떤문제가 발생할 수 있을까요?

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +}
완벽한것 같네요..!!

`contactManger.add(contact: contact)`

contact가 중복되고 있는데 굳이 그럴 필요가 없어보입니다

-> `contactManger.add(contact)`가 더 깔끔해보입니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +    lazy var navigationBar: UINavigationBar = {
이렇게 navigationBar를 따로 만드는 방법도 있겠으나,
ContactDetailViewController 자체를 UINavigationController에 임베드 한 후 해당 Navi를 present 하는 방법도 있습니다

후자의 경우에는 오토레이아웃을 잡아줄 필요가 없다는점이 장점이겠네요..!

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +    }
기본적인 것뿐만아니라 좀 더 심화적인 lifecycle 매서드들을 잘 활용하고 계신것 같습니다!!
특히 super를 호출 안하신점이 문서를 정확히 읽고 작성하신것 같아서 너무 좋습니다!!!

VC lifeCycle, View lifeCycle, App lifeCycle은 면접 단골 질문이니 꼭 잘 알아두시면 좋을것 같아요 :)

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        detailView.phoneNumberTextField.addTarget(self, action: #selector(edit), for: .editingChanged)
해당 selector는 detailView 자체적으로 처리해도 충분할것 같아요
VC까지 끌고올 이유가 있을까요??

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        navigationBar.trailingAnchor.constraint(equalTo: safeArea.trailingAnchor).isActive = true
어떨때는 .isActive 방식을쓰고, 어떨때는 NSConstraint 방식을 쓰는데, 하나로 통일하시는편이 좋을것 같네요!
코드의 일관성도 중요합니다

2024-01-15 00:21 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        navigationBar.setItems([navItem], animated: true)
프토퍼티 선언에 lazy var 를 썼다면, 이런 속성설정들은 프로퍼티 초기화시 수행하는게 좋아보입니다 :)

2024-01-16 01:05 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/Extensions/String+.swift
> +    }
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/1dfaa29293cc37fca3b2838456ef0b6a9712a24a)에서 수정했습니다!

2024-01-16 01:06 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/SceneDelegate.swift
> +    }
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/34ce501c27a63c9db7ea0ec7bfc35b355e872b2b)에서 네이밍 수정했습니다.

2024-01-16 01:07 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/2ef3879a449a00bfe6252f3c4c513c3b0f7a20c5)에서 수정했습니다.

2024-01-16 01:09 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +        cell.accessoryType = .disclosureIndicator
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/5a1d1d54b8f568e5a385653186969222ad1bfc5b)에서 수정했습니다

2024-01-16 01:11 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    }
말씀주신바와 같이 키패드는 항상 업데이트 해줄필요없이 한번만 설정되어야 한다고 생각하여 [해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/6a87229c644829142391f8a4d5f3917e6689a6a4)에서 수정해줬습니다!

2024-01-16 01:21 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    let nameLabel: UILabel = {
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/6a87229c644829142391f8a4d5f3917e6689a6a4) pirvate을 함으로써 해당scope에서만 사용이 가능하도록 다른 scope에서는 접근제어를 하기위해 사용해야한다고 생각합니다.

2024-01-16 01:22 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/CustomCell.swift
> +final class CustomCell: UITableViewCell {
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/6a87229c644829142391f8a4d5f3917e6689a6a4)에서 ContactDetailCell이라고 수정해줬습니다

2024-01-16 01:23 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/CustomCell.swift
> +    }
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/3d992442b6b6f2e69fff4f591783cb32a241f08a)에서 수정해줬습니다

2024-01-16 01:26 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Models/Verification.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/56eb31672dc2a8c4f95c4da1e240e56e43ab163c)에서 수정해줬습니다만, 궁금한게 일반적인 방식이라는 것이 통일성(?)을 위해 해줘야한다는 말씀이실까요?

2024-01-16 01:29 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +    }()
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/13db46a2d918ff23ed8591b1d27a328c92f6d96f)에서 수정해줬습니다.

2024-01-16 01:31 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/3d992442b6b6f2e69fff4f591783cb32a241f08a)에서 수정해줬습니다

2024-01-16 01:31 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +        detailVC.modalPresentationStyle = UIModalPresentationStyle.automatic
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/3d992442b6b6f2e69fff4f591783cb32a241f08a)에서 수정해줬습니다

2024-01-16 01:36 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +                                     tableView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: 0)])
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/c42a39db11bc5e9d4e6a987e110c1748231c0dd5)에서 top을 superView로 하여 화면 끝까지 보이게 하였고, bottom은 구현요구사항에 가려지는 부분이 있어 safeArea를 활용하였고, view의 배경색을 흰색을 주게 수정해줬습니다.
<img width="223" alt="스크린샷 2024-01-16 오전 10 34 13" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/148876644/3357c1af-a6a3-4086-bfb0-01ceab8ffa4b">

2024-01-16 01:41 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        detailView.phoneNumberTextField.addTarget(self, action: #selector(edit), for: .editingChanged)
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/dfbab5f084fd67b0fbf84d08a4106925c47b6c7a) VC에서가 아닌 detailView에서 자체적으로 처리하는게 맞다고 생각해 수정해줬습니다.

2024-01-16 01:42 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +}
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/dfbab5f084fd67b0fbf84d08a4106925c47b6c7a)에서 수정해줬습니다.

2024-01-16 01:44 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        navigationBar.trailingAnchor.constraint(equalTo: safeArea.trailingAnchor).isActive = true
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/dfbab5f084fd67b0fbf84d08a4106925c47b6c7a)에서 일관성있게 수정해줬습니다.

2024-01-16 01:47 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        navigationBar.setItems([navItem], animated: true)
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/0b68aee423c7387b975ad291657ba633cac01faf)에서 메서드를 또 만들필요없이 지연저장속성에 정의하여 프로퍼티가 초기화되면 수행되도록 설정해줬습니다.

2024-01-16 01:50 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +    lazy var navigationBar: UINavigationBar = {
[해당커밋](https://github.com/tasty-code/ios-contact-manager-ui/pull/66/commits/4cd58ae2c3bf760b8d93bad3dbfcf0736a06cfeb)에서 네비게이션바를 따로 만드는 것이 아닌 네비게이션형식으로 띄우도록 하니 네비게이션바의 오토레이아웃도 잡아줄 필요도 없고 조금더 가독성 측면에서 좋아보인다고 생각하여 수정해줬습니다.

2024-01-16 02:14 UTC, kimdj1102 commented on ios-contact-manager-ui/ios-contact-manager-ui/Resources/Extensions/String+.swift
> +    public var formmater: String {
잘못 넣었습니다 수정했습니다 😅

2024-01-16 02:34 UTC, kimdj1102 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Models/ContactManager.swift
> +    var contacts: [Contact] = []
```
private(set) var contacts: [Contact] = []
```
read-only 프로퍼티 생성 후 에러를 던지는 `parse()`함수를 만들어 주어 `ContactViewController`에서 에러를 받아 처리할 수 있게끔 해주었습니다. 
```
func parse() throws {
        do {
            contacts = try AssetDecoder<[Contact]>().parse(assetName: "MOCK_DATA")
        } catch {
            throw error
        }
    }

```
위의 parse()함수에서 바로 ContactViewController에 alert를 present를 하는 방법을 고민해보았지만 방법을 찾지못해 일단 error만 던져준 후, 

```
// ContactViewController.swift

 private func parse() {
        do {
            try contactManger.parse()
        } catch {
            let alert = showErrorAlert(title: nil, error.localizedDescription, actions: [UIAlertAction(title: "취소", style: .default)])
            present(alert, animated: true)
        }
    }
```

ContactViewController에서 error를 받아 present 해줍니다.

2024-01-16 02:43 UTC, kimdj1102 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +    }()
lazy var의 단점
- 해당 변수를 만들어 사용할 때 생성하기 때문에 속도 저하가 일어날 수 있고,
- 다중 스레드에서 해당 변수에 접근했을 때, 한번만 초기화 되는것이 보장되지 않는다

결국 thread safe하기 위해서는 추가적인 로직이 들어가야 합니다.

2024-01-16 03:07 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    }
UIView가 NSCoding이란 프로토콜을 채택하고 있어 그안에 required init이 존재하는데 서브클래스에서 새로 지정생성자를 정의해줘서 슈퍼클래스의 생성자를 상속받지 않기 때문에 슈퍼클래스의 생성자를 직접구현해야하며, fatalError("init(coder:) has not been implemented")의 경우는 코드로 뷰를 구성했으므로 스토리보드일 때만 불러야하는 이생성자는 스토리보드가 아니면 호출이 안되도록 해주는 부분입니다.

2024-01-16 03:24 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    }
잘 알고 계시네요! 좋습니다 :)

2024-01-16 03:24 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    let nameLabel: UILabel = {
접근제어자를 붙였을때 얻는 이점은 뭐가 있을까요?

2024-01-16 03:34 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Models/ContactManager.swift
> +    var contacts: [Contact] = []
고민하신 방향과 해결방법 모두 좋네요! `ContactManager`는 VC를 모르니까 당연히 직접 Alert을 띄울수 없습니다

지금처럼 thorw를 던져도되고, 클로져를 넘겨받는 방법도 있겠네요!
클로져 콜백방식도 정말 많이 사용하곤 합니다 ㅎㅎ

```swift
func parse(_ completion: () -> Void) {
        do {
            contacts = try AssetDecoder<[Contact]>().parse(assetName: "MOCK_DATA")
        } catch {
            completion()
        }
}

// VC

func parse() {
  contactManager.parse {
            let alert = showErrorAlert(title: nil, error.localizedDescription, actions: [UIAlertAction(title: "취소", style: .default)])
            present(alert, animated: true)
   }
}


```

2024-01-16 03:35 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactDetailViewController.swift
> +        detailView.phoneNumberTextField.addTarget(self, action: #selector(edit), for: .editingChanged)
좋습니다! 항상 각 객체들의 역할을 명확하게 구분하는것이 좋은 코드를 짜는 첫걸음인것 같아요

2024-01-16 03:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Controllers/ContactViewController.swift
> +    }()
맞습니다 멀티스테드 환경에서는 약간 주의해야할 상황이 생길수도 있습니다

반대로, 사용시점까지는 메모리에 올라오지않기때문에, 오히려 성능에 도움을 줄 수 있는 부분도 있겠네요

2024-01-16 03:37 UTC, FirstDo commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Models/Verification.swift
> +}
통일성을 말씀드리는것이 아닌,
보통 프로토콜을 저런식으로 사용하지는 않는다는 말이었습니다

좀 더 자세히 말씀드리면
Protocol은 주로 다음경우에 많이 사용합니다

1. Delegate Pattern

델리게이트 패턴을 구현하는경우

2. 추상화

Protocol의 최대 장점입니다


사실 구현은 자유니깐 기존 방식도 절대 잘못된것은 아닙니다만,
단순히 setName, setAge, setNumber 라는 매서드를 사용하기 위한 `Verification` 프로토콜은 익숙한 방식은 아닌것 같네요!

2024-01-16 03:38 UTC, FirstDo approved these changes

2024-01-16 03:38 UTC, merged

2024-01-16 05:35 UTC, mireu930 commented on ios-contact-manager-ui/ios-contact-manager-ui/Sources/Views/DetailView.swift
> +    let nameLabel: UILabel = {
모듈간의 의존성을 최소화해서 유지보수가 향상될수 있다는 이점이 있을수 있습니다!