연락처 관리 앱 [Step2] 댄, Sidi
tasty-code/ios-contact-manager-ui pull request #67
Opened 2024-01-12 08:34 UTC by eensungkim

Step 2
멤버 : @eensungkim, @jus1234
리뷰어 : @keeplo

연락처 관리 앱 프로젝트의 두번째 Step입니다! 
정리하여 PR 드립니다. 감사합니다!

# 이번 스텝을 통해서 배운 점
- 프로토콜 활용하여 필요한 기능만 위임하기
- 프로토콜을 활용한 다형성 구현
- 오토레이아웃과 constraint
- Navigation Controller 없이 UINavigationBar 활용하기
- UIAlertController 활용하기

# 구성
## Model
### Contact.swift
- Contact 구조체
    - property : 이름, 전화번호, 나이

### Contacts.swift
- Contacts 모델 클래스
    - property: [해시값: Contact 구조체]
    - method: 정렬된 연락처 반환, Contact 추가, 삭제, 변경, JSON 파일 로드
### ContactsProtocol.swift
- delegation 을 위한 프로토콜

## View
### ContactsTableView.swift
- 연락처 테이블 뷰 클래스
### ContactsAdditionModalView.swift
- 연락처 추가 모달 화면 뷰 클래스
### ContactsNavigationBar.swift
- 연락처 리스트 화면 내비게이션 바 뷰 클래스

## Controller
### ContactListViewController.swift
- 연락처 뷰 컨트롤러
- ContactsApproachable 로 정렬된 연락처 받아오는 기능 위임받음
### ContactsAdditionModalViewController.swift
- 새 연락처 뷰 컨트롤러
- ContactsManageable 로 연락처 추가/변경/삭제 기능 위임받음
- 유효성 검사 메서드

# 질문
- **질문 : 구조체 타입이 여러 개체에 위임하는 경우 같은 데이터를 서로 공유하기 위해서 매번 값을 다시 복사해서 전달해 주어야 하는 것일까요? 클래스로 변경해서 해결하면서 떠오른 방법 중에, delegate 가 데이터를 변경하고 난 뒤에 다른 뷰컨트롤러의 delegate를 다시 지정해주는 방법이 있었습니다. 
클래스로 변경해서 해결하는 방법 외에, 혹시 구조체를 사용해서 여러 개체에 위임을 하더라도 데이터가 상호공유될 수 있는 방법이 있을지 궁금합니다.**
- 배경 : 지난번 조언해주셨던 객체지향 패러다임을 나름대로 적용해 보기 위해, ContactsManageable 프로토콜과 ContactsApproachable 프로토콜을 구현했습니다.
이를 바탕으로 ContactsViewController에는 정렬된 연락처를 가져오는 기능만 위임하고, ContactsAdditionModalViewController에는 연락처의 추가/변경/삭제 기능을 위임하고자 했는데요.
- 문제 : 모달 컨트롤러의 delegate 가 연락처를 추가하더라도, 기존 연락처 화면이 위임받은 인스턴스와 데이터가 공유되지 않는 것을 발견했습니다. 이는 구조체 타입이 값을 복사해서 전달하기 때문으로 이해되는데요.
- 해결한 방법 : Contacts 구조체를 클래스로 변환해 주는 것으로 문제를 해결했습니다.

2024-01-15 09:04 UTC, keeplo requested changes
두 분 Step 2 진행하시느라 고생하셨습니다!
기능에 문제 없이 잘 동작하네요! 아주 좋습니다!

전체적으로 크리티컬한 문제점은 없는것 같아요!
OOP 라거나 설계에 대해서 리뷰를 남겼습니다 확인해보시고 함께 고민해보면 좋을것 같아요!

---
### 질문에 관한 답변
말씀해주신 것처럼 구조체는 복사가 되기 때문에 말씀하신 형태는 구현하기 힘들 것 같아요
TCA 라는 아키텍처 구조는 값타입으로 `Source of Truth` 상태값을 유지하는 형태를 
공유하는 방식이 있긴한데 UIKit 기반에 설계라면 말씀하신 상황에서는 참조타입을 이용하는게 좋아요!
Objective-C 에서 Swift로 넘어오면서 값타입을 좀 더 활용하는 형태로 개선되긴했지만
참조영역이 꼭 나쁜 것만은 아니니 적절하게 잘사용하는것도 좋을것 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var contacts: Array<Contact>
Model 역할을 하는 ContactApproachable 개체가 존재하는데,
ViewController 내부에 프로퍼티를 추가로 지정하신 의도가 있을까요?

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    var delegate: ContactsApproachable?
delegate 패턴을 사용해주셨는데 살짝 어색하게 느껴집니다.
위 구조 같이 작성하는 경우는 특정 동작에 대해서만 위임하는 형태로 구성하는 걸로 알고 있습니다.

`Cocoa MVC` 디자인 패턴을 의도하신게 맞다면,
Model 개체는 동작을 위임 하는 형태보다는 
View가 그려지기 위한 DataSource 역할로 존재하는게 좀 더 올바른 방향성이 아닐까 생각합니다.

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/24707229/648443a6-9012-4e21-b22f-d7dc96d55640)

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +        }
클로저 프로퍼티를 작성해주셨군요!

클로저는 참조타입이기 때문에 self 영역을 캡쳐하게되면 참조되어 retain count가 증가하게됩니다
[weak self] 작성하여 참조카운트가 올라가지 않도록 조치를 취하면 좋을것 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/UIViewControllerExtension.swift
> +extension UIViewController {
extension 확장을 이용해서 모든 뷰컨에서 Default 얼럿 컨트롤러를 작성하셨군요?!
굉장히 센스 있는 구성인 것 같아요! 🙌

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactsNavigationBar.swift
> +        additionButton.action = #selector(ContactsViewController.presentContactsAdditionModalView)
저는 이렇게 구현하는걸 처음봐서 궁금한점이 있습니다.

ContactsViewController 인스턴스가 2개 이상 존재하면 각 인스턴스의 `presentContactsAdditionModalView()`메서드가 동작하지 않나요?

이런 부분도 고려한다면 혹시 위험성은 없는지 궁금합니다!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            isSeoulNumber = text.starts(with: "0") && text[text.index(after: text.startIndex)] == "2"
가독성이 많이 떨어지는 것 같습니다.
처음 두 문자를 "02" 와 비교하는 형태로 구성해볼 수 없을까요?

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +        textArray[of] = "-"
`of` 전치사를 그대로 쓰는것보다 내부에서 사용할 파라미터명을 추가해주는게 좋을것 같아요!

그리고 index 의도로 사용된다면 of 보다 at 전치사가 어울리지 않을까 싶어요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    }
네이밍을 조금 더 고민해보면 좋을것 같습니다!
아무래도 저처럼 구현에 참여하지 않은 사람이 이 코드를 수정하는 경우가 생긴다면 
설계된 동작 원리를 빠르게 파악해야하는데 설명 없이 코드만으로 이해하기에 쉽지 않은것 같습니다.

특히 네이밍 규칙이 동사형으로 작성되지 않은 부분도 있고 한글 어순으로 작성된 표현이 있다면
영문 문법 형태로 맞춰주는게 좀 더 이해하기 편할것 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            isSeoulNumber = text.starts(with: "0") && text[text.index(after: text.startIndex)] == "2"
이번 기회에 String 관련된 메서드를 활용하기위해 학습해보면 좋을것 같아요!
`Substring` 개념과 `String.index` 그리고 `Array(String)` 등을 활용하면 좀 더 개선할 수 있을것 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    private var invalidationByTextField: Dictionary<UITextField, InvalidationInput>
이런 부분들은 저장 프로퍼티로 남기지 않고 해결할 수 없을까요?

좀 더 편리하긴 한데 연산 프로퍼티로 해결할 수 있다거나 
ViewController가 점유할때 메모리가 남지 않는 좋은 방향은 없을지 한번 고민해보면 좋을것 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    private var sortedTextField: Array<UITextField>
이 부분은 연산 프로퍼티로 바로 바꿀 수 있을것 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    @objc func saveButtonDidTapped() {
네이밍을 한번만 더 고민해보면 좋을거 같아요!

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
>          contactsTableView.tableView.dataSource = self
이 부분에 리뷰를 남기지만 많은 영역에서 동일한 부분이 많이 있습니다.
이 리뷰를 기준으로 전체적인 코드에서 확인 해주세요!

OOP 에 관련한 학습을 하다보면 `클린코드`라는 개발서적이 있습니다
디미터 법칙(Law of Demeter) 과 기차충돌 (Train Wreck) 에 관한 부분이 있는데
이 용어와 어떤 원리인지 학습하고 현재 코드에서 고민해보면 좋을것 같아요!

`Contact` 같은 자료구조가 아닌 경우에는 디미터 법칙이 지켜지는게 좋을것 같아요!
Java 같이 OOP 대표적인 다른 언어에서도 프로퍼티에 직접 접근하기 보다 getter, setter 메서드를 따로 두도록 권장하는데요,
ViewController 에서 self.view 프로퍼티로 커스텀 View를 작성하는 형태라면 
addTarget 이나 .text = "새로운 문자" 같은 다양한 동작에 관한 부분을 디미터 법칙을 지켜서 설계되는게 좋을것 같아요!

전체적으로 많은 부분에서 View 프로퍼티를 직접 사용하는 경우가 있는데 확인하고 설계를 고민해주시면 좋을것 같습니다.

2024-01-15 09:04 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Enumeration/InvalidationInput.swift
> +    case phoneNumber
저는 개인적으로 `UITextField` 를 Key 값으로 갖는것 보다 만들어주신 이 enum이 Key 값이 되고
이 case 에 따러서 `UITextField`가 지정되는 방향이 좋지 않을까 생각합니다.

enum-case 의 목적이 그런 형태가 될 수 있다고 생각해요!

2024-01-16 02:14 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +        textArray[of] = "-"
at 전치사로 변경하고 내부에서 사용할 파라미터명으로 index 를 넣어주었습니다. 🙏

2024-01-16 02:15 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            isSeoulNumber = text.starts(with: "0") && text[text.index(after: text.startIndex)] == "2"
"0" 으로 시작하고, "02" 가 아닌 경우를 함께 AND 조건으로 묶었습니다!

2024-01-16 02:27 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var contacts: Array<Contact>
view 에 보이는 데이터와 dataSource 가 다른 속성으로 있어야 한다고 생각했었습니다.

아래에 주신 리뷰를 함께 반영하여, dataSource 역할을 만들고 이를 통해 모델에서 데이터를 가져오는 것으로 변경했습니다.

2024-01-16 02:28 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +        }
반영했습니다!

2024-01-16 02:28 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    var delegate: ContactsApproachable?
dataSource 역할로 변경했습니다.

2024-01-16 02:38 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactsNavigationBar.swift
> +        additionButton.action = #selector(ContactsViewController.presentContactsAdditionModalView)
저희도 궁금해서 이번에 새로운 인스턴스를 하나 생성하고 실험을 해봤는데요.
말씀주신 것처럼 타입으로 지정이 되었음에도, 알아서 잘 찾아서 하나의 뷰컨트롤러 인스턴스의 메서드만 실행하는 것을 확인할 수 있었습니다.
일단 결과적으로 한번만 실행되기 때문에 말씀해주신 위험성은 없었지만, 왜 그렇게 동작하는지는 추가로 알아봐야 할 것 같습니다.

2024-01-16 02:47 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    }
수정 반영했습니다. 추후 유효성 검사 로직을 추가할때 한번 더 체크해 보겠습니다!

2024-01-16 05:30 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    var delegate: ContactsApproachable?
이 부분 관련해서 질문이 있어서 작업사항 push 한 뒤에 질문 남기도록 하겠습니다. 🙏

2024-01-16 05:30 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    private var invalidationByTextField: Dictionary<UITextField, InvalidationInput>
수정해보았습니다!

2024-01-16 05:30 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    private var sortedTextField: Array<UITextField>
수정해보았습니다!

2024-01-16 05:34 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    @objc func saveButtonDidTapped() {
savingButtonDidTapped 로 변경해 보았습니다.
말꼬가 의도한 내용이 아닐 수 있을 것 같아서, 그런 경우라면 의견 부탁드릴께요!

2024-01-16 06:38 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Enumeration/InvalidationInput.swift
> +    case phoneNumber
반영하여 수정했습니다!

2024-01-16 06:59 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var contacts: Array<Contact>
`ContactApproachable` 개체가 존재하는데, `ViewController` 내부에 프로퍼티를 추가한 이유를 먼저 말씀 드리면 `Controller`와 `Model`의 역할과 책임이 구분되어 있다고 생각했습니다. `Model`은 비즈니스 로직을 담당하고 `Controller`는 이벤트의 처리를 담당해야 한다고 생각했습니다. 연락처를 저장하고 관리하는 비즈니스 로직은 `Model`이 담당하고 연락처를 보여주는 것은 `Controller`가 담당하는 영역이라 `ContactApproachable`가 존재하지만 해당 객체를 통해 뷰에 보여질 데이터를 읽는 기능만 수행을 하고 뷰에 보여지는 데이터는 `Controller`가 책임을 가지는게 맞다고 생각했습니다. 셀을 그릴때, 각 셀마다 `ContactApproachable`로 직접 접근해서 데이터를 읽어오면 `Model`이 불필요한 책임을 너무 많이 가지게 된다고 생각했습니다. `Model`의 책임과 `Controller`의 책임을 정확하게 나누는 것이 어렵긴 한데 말꼬가 `contacts`와  `ContactApproachable`가 둘 다 존재하는 것에 의문을 가지신 이유가 `ContactApproachable` 객체가 `TableView`의 `dataSource`로서의 역할도 수행하는 것이 맞기 때문에 그런것인지 궁금합니다!

2024-01-16 08:49 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    }
훨씬 간결하고 이해하기 쉬워진것 같아요!

2024-01-16 10:56 UTC, keeplo requested changes
처음 접하는 개념이 있다보니 충분히 어려우실 거에요!
가능하면 간접적으로 리뷰를 남기는게 좋지만 
Step 진행과 현재 프로젝트의 요구사항이 우선이기 때문에
직접적으로 언급했습니다!

적용해보시면서 이해하시면 좋을것 같습니다
부가적인 설명이 필요하시면 디엠주세요!

### Request Changes
1. 불필요한 파일제거
   : 스토리보드와 ViewController.swift 파일은 사용하지 않으므로 두 파일 모두 제거해주세요
   두 파일 제거하는 과정에서 에러가 발생할 수 있습니다 관련 리서치가 필요하실거에요!
2. UIViewController 초기화
   : 지금처럼 코드로 설계하시는 경우에는 커스텀 초기화를 이용할 수 있습니다
   `의존성주입` 키워드도 학습하면 좋고, 전체적으로 UIViewController 초기화를 커스텀으로 수정하면 좋을것 같아요!
3. 디미터 법칙 
   : View 개체 내부에 프로퍼티에 직접 접근하는건 좋지 않습니다. View 개체에 연산프로퍼티 또는 함수등을 추가해서 `ViewController`가 view의 내부 프로퍼티에 직접 접근하지 못하게 수정해주세요!
   
> Tip: 네부 프로퍼티를 `private` 접근제어자를 모두 작성하면 초기화를 통한 의존성 주입/디미터법칙을 자동으로 지키게 됩니다!

2024-01-16 10:56 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    }
단순 get 연산프로퍼티 일 경우에는 

~~~swift
private var sortedTextField: Dictionary<TextField, UITextField> {
     [
          .name : contactsAdditionModalView.nameTextField,
          .age : contactsAdditionModalView.ageTextField,
          .phoneNumber : contactsAdditionModalView.phoneNumberTextField
     ]
}
~~~

이런식으로 get 부분을 생략하셔도 됩니다

2024-01-16 10:56 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var contacts: Array<Contact>
자세하게 설명해주셔서 감사합니다! 두 분에 의도는 더 명확하게 이해가 되었어요!
조금 더 명확한 구분을 해주면 좋을것 같아서 설명을 조금더 드리겠습니다!

우선 책임에 관해 이야기 해보겠습니다.
> ContactApproachable로 직접 접근해서 데이터를 읽어오면 Model이 불필요한 책임을 너무 많이 가지게 된다고 생각했습니다.

이 부분은 다시 고민해보면 좋을것 같아요.. 제가 이해하는 책임에 기준은 각 객체에 있습니다.
`Contacts` 개체의 책임을  `ContactApproachable` 타입으로 축소?! (제한)해주고, 
`ContactApproachable` 개체의 유일한 책임은 `sorted()` 메서드 밖에 없어요
`Controller` 입장에서는 저 메서드 이외의 어떤 것도 알 수가 없습니다.

마찬가지로 `ViewController` 의 책임은 `TableView`를 그려주는거고 그 역할을 충분히 잘해주고 있어요!
DataSource (TableView를 그려줄 데이터) 는 주어진 `ContactApproachable` (Model)을 이용했을 뿐이지 
Model에 책임을 전가하는 형태는 아니라고 생각합니다.

각 책임은 각 객체에게 있는 거고, 각 객체를 분리해서 보았을때 할 수 있는 역할만 바라보면 좋을것 같아요!

--- 
두번째로 말씀해주신 비즈니스 로직 관련해서도 이야기 해보겠습니다.

비즈니스 로직을 위해서 현재 설계에 sorted() 또는 View 만을 위한 DTO를 통한 ViewData 형태로 
View 를 그려주는 공간에서 데이터를 한번 거치는 구조도 어색하지 않습니다.

보통 그런 구조는 ViewModel 이나 Presenter 를 포함하는 MVVM, MVP 같은 구조에서 많이 사용됩니다.
하지만 만약 그런 구조를 원하신다면 오히려 `Model` 개체에서는 fetch/ read 같은 형태로 데이터를 불러온다거나 
private(set) 같은 접근으로 `source of truth`를 가져오고 `Controller` 개체에서 `sorted` 처리를 해주는게
좀 더 비즈니스 로직을 위한 처리로 구분되고 `Model` (`Contacts`) 개체에는 단순 CRUD 책임과 역할만 줄 수 있을것 같아요!

2024-01-16 10:56 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    @objc func saveButtonDidTapped() {
`saveButton`의미가 `저장버튼`으로 이해해서 말씀드린 부분이었어요!
함수의 네이밍은 동사형으로 작성하면 좋을것 같아요 `(did)TappedSave(ing)Button` 같은 네이밍이 좀더 나을것 같아요

API Design Guidelines 는 완전 습관이 될때까지 계속 확인 해주시면 좋을것 같아요!
단순 getter를 의미하는 경우라면 반환값을 표현하는 네이밍 또는 form등의 네이밍을 작성하고 이외의 경우에는 
동사형으로 네이밍하는게 좋습니다

2024-01-16 10:56 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +        contactsAdditionModalView.phoneNumberTextField.delegate = self
~~~swift
// ContactsAdditionModalViewController.swift
viewDidLoad() {
   contactsAdditionModalView.delegate = self
}

// ContactsAdditionModalView.swift
final class ContactsAdditionModalView {

   weak var delegate: UITextFieldDelegate? {
        didSet { self.phoneNumberTextField.delegate = self.delegate }
    }

}
~~~

디미터 법칙이 아직 낯설다고 하셔서 조금 직접적으로 코드 예시를 드릴게요!
`ContactsAdditionModalViewController` 개체는 
`contactsAdditionModalView` 개체에만 접근하는게 좋아요!
내부 프로퍼티는 가능하면 알 수 없는 구조로 만들어야 캡슐화를 지키고 결합도를 낮출수 있습니다!

2024-01-16 10:56 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
`UIViewController` 초기화를 커스텀으로 만드실 수 있습니다

~~~swift
init(a: A) {
   self.a = a

   super.init(nibName: nil, bundle: nil)
}
~~~

같은 형태로 구현하실 수 있어요
Stortboard를 사용하는 경우에는 어쩔 수 없지만 
프로퍼티를 `internal`(default) 또는 그 이상의 접근제어로 바꾸고 외부에서 직접 접근하는것 보다
초기화를 통해서 주입해주는 방향이 좋습니다!

`의존성주입` 키워드도 공부해보시면 좋을것 같아요!

2024-01-17 01:30 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    }
생략했습니다!

2024-01-17 01:31 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    @objc func saveButtonDidTapped() {
handleSaveButtonTap() 으로 변경했습니다.

2024-01-17 01:32 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +        contactsAdditionModalView.phoneNumberTextField.delegate = self
코드 예시를 참조하여 별도의 메서드로 분리해서 적용했습니다!

2024-01-17 01:32 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
적용해 보았습니다!

2024-01-17 13:13 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +            tableView.reloadData()
단순히 .(dot) 체이닝을 벗어나는 걸로는 디미터 법칙을 지켜지지 않습니다.
이 부분도 똑같이 메서드로 만들 수 있습니다!

tabView 프로퍼티를 외부에서 직접 접근하는건 
UIViewController가 ContactsView에 추가로 UITableVIew 까지 의존하게 됩니다

2024-01-17 13:14 UTC, merged