[
tasty-code/ios-contact-manager-ui pull request #68
Opened 2024-01-12 11:37 UTC by yoruck2

@junbangg
안녕하세요, 알라딘!
**`STEP2 PR`** 보내드립니다! 확인 부탁드립니다!

---
## 🧐 고민했던점

- ### Content Compression Resistance Priority
    - `StackView`에 `label`과 `textField`를 넣어 구현했습니다.
    - 하지만, 아래 이미지와 같이 `textField`의 `input` 값이 길어지면 연락처 `label`이 줄어지는 이슈가 발생하였습니다.
    - 따라서, 연락처 `label`의 `content compression resistance priority`를 `textField`보다 높여 해당 이슈를 해결하였습니다.
    ![image](https://hackmd.io/_uploads/HJ1XOGtua.png)
    
- ### 사용자 입력 유효성 검사
    - `InputValidator`라는 구조체를 생성하여 사용자 입력에 대한 유효성 검사를 할 수 있게 구현했습니다. 
    - 이름, 나이, 연락처에 대한 유효성 검사 함수를 `validateInput`에 캡슐화 후 은닉화 했습니다.
    - 또한, `Result` 타입을 `return`하여 에러핸들링을 구현했습니다. 
        ```swift
        func validateInput(nameTextField: UITextField,
                           ageTextField: UITextField,
                           phoneNumberTextField: UITextField) -> Result<Contact, Error> {
            do {
                let name = try validateNameInput(nameTextField: nameTextField)
                let age = try validateAgeInput(ageTextField: ageTextField)
                let phoneNumber = try validatePhoneNumberInput(phoneNumberTextField: phoneNumberTextField)
                return .success(Contact(name: name, phoneNumber: phoneNumber, age: age))
            } catch {
                return .failure(error)
            }
        }
        ```
        
- ### 전화번호 포맷팅
    - `String Extension`을 통해 사용자가 전화번호 입력 시 자동으로 하이픈(-)을 생성할 수 있게 처리하였습니다.
    - 지역번호(02, 031 등), 기업 대표번호(15XX, 16XX 등), 일반 휴대폰 번호에 대한 분기 처리를 하여 각 연락처의 특성에 따라 하이픈(-)을 지정할 수 있게 구현했습니다.
        ```swift
        extension String {
            func formattingPhoneNumber() -> String {
                let count = self.count
                let divider: Character = "-"
                var phoneNumber = self
        
                if phoneNumber.hasPrefix("02") {
                    switch count {
                    case 3...5:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 2))
                    case 6...9:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 2))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: 5 - count))
                    case 10:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 2))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: -4))
                    default:
                        break
                    }
                } else if phoneNumber.hasPrefix("15") || phoneNumber.hasPrefix("16") || phoneNumber.hasPrefix("18") {
                    switch count {
                    case 5...9:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 4))
                    default:
                        break
                    }
                } else {
                    switch count {
                    case 4...6:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 3))
                    case 7...10:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 3))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: 6 - count))
                    case 11:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 3))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: -4))
                    default:
                        break
                    }
                }
        
                return phoneNumber
            }
        }
        ```

## 🤔 조언을 얻고 싶은 부분

- ### NotificationCenter VS Delegate Pattern
    - 현재 `AddContactViewController`는 `modal`로 `present`하고 있습니다.
    - 따라서, `ContactListViewController`의 `Lifecycle`에 관여할 수 없어 이벤트를 발생시키기 위해 `NotificationCenter`와 `Delegate Pattern` 도입에 대해 고민했습니다.
    - `contactManager` 객체를 새 연락처를 등록하는 `AddContactViewController`를 생성할 때 주입하고 있기 때문에 `ContactListViewController`와 같은 객체를 바라보고 있어 `tableView`를 `reload()`만 해줘도 알맞게 업데이트가 되고 있습니다.
    - `NotificationCenter`는 1:N의 관계를 가질 때, `Delegate Pattern`은 1:1의 관계를 가질 때 활용하는 차이가 있다는 점을 알게 되어 이후 `STEP`서 연락처를 수정하는 기능이 생긴다면 해당 `View`에서도 `post`를 해주면 `ContactListViewController`가 구독하고 있기 때문에 확장성 또한 고려할 수 있다는 판단이 들어 `Delegate Pattern`가 아닌 `NotificationCenter`를 선택하였습니다.
    - 이러한 고민과 선택에 대해 알라딘의 의견이 궁금합니다!
    
- ### 전화번호 포맷팅 로직의 가독성과 효율성
    - 명세서가 조금 수정되어 `UITextField`에 실시간으로 `input`을 판별하여 하이픈(-)을 추가해줘야 했습니다.
    - 하지만, 현재 전화번호 포맷팅을 하는 로직이 기능 구현에 너무 집중되어 가독성과 효율성을 챙기지 못한 것 같다는 생각이 듭니다.
    - 지금 방법 이외에 다른 방법으로 로직을 리팩토링할 수 있을 지 궁금합니다!
        ```swift
        extension String {
            func formattingPhoneNumber() -> String {
                let count = self.count
                let divider: Character = "-"
                var phoneNumber = self
        
                if phoneNumber.hasPrefix("02") {
                    switch count {
                    case 3...5:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 2))
                    case 6...9:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 2))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: 5 - count))
                    case 10:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 2))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: -4))
                    default:
                        break
                    }
                } else if phoneNumber.hasPrefix("15") || phoneNumber.hasPrefix("16") || phoneNumber.hasPrefix("18") {
                    switch count {
                    case 5...9:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 4))
                    default:
                        break
                    }
                } else {
                    switch count {
                    case 4...6:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 3))
                    case 7...10:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 3))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: 6 - count))
                    case 11:
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.startIndex, offsetBy: 3))
                        phoneNumber.insert(divider, at: phoneNumber.index(phoneNumber.endIndex, offsetBy: -4))
                    default:
                        break
                    }
                }
        
                return phoneNumber
            }
        }
        ```

2024-01-16 11:21 UTC, junbangg requested changes
수고하셨습니다!!

크 UML 잘 봤습니다~ UML을 개인적으로 꽤 좋아해서, 지금도 복잡스럽거나 처음 보는 레거시 코드 다룰때 프로젝트 시작하기 전에 잘 사용한답니다:) 연습 자주 해놓으시면 좋을것 같아요!

mark 주석으로 코드 정리하는거 잘 봤습니다..! private method 들도 extension으로 빼면 더 보기 좋을것 같긴한데,,이건 제 개인적인 스타일 일 수도 있을것 같네요ㅎ

### Notification 에 대한 고민
1. 
> ContactListViewController가 구독하고 있기 때문에 확장성
혹시 여기서 말씀하신 확장성은 어떤것일까요?🤔

Notification에 대한 저의 의견을 드리자면, 저는 좀 반대파 이긴 해요..! 그래서 Delegate 으로 가능한 일은 일단 Delegate 을 더 선호 하고요. 
NotificationCenter로만 구현이 가능한 일들도 충분히 있어요, 한쪽 화면에서 어떤 일이 발생했는데, 다른 쪽 화면에 어떤 정보를 보내거나 일을 시켜야 할때, 또는 그게 여러 가지 화면일때? 그럴때는 다른 방법이 많지 않아서 사용할 수 있을것 같네요.

근데 시간이 지날 수록, NotificationCenter 는 굉장히 관리하기 힘들어지기도 하고, 히스토리 파악도 어려워질때도 있고, 처음 만들어진 목적과 다르게 사용하기 시작해서 예상하지 못한 버그가 발생하는 경우도 많이 봤어요,,! 
그래서 저의 개인적인 성향은, 가능하다면 피한다! 가 되겠습니다~

### 전화번호 포맷팅 로직의 가독성과 효율성

가독성에 대해서는 , 코멘트 남겼어요 해당 코드에!!
그리고 효율성! 은 어떤것을 말씀하시는걸까요?!

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/Array+.swift
> +}
오홍 👍

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/String+.swift
> +    func formattingPhoneNumber() -> String {
연산프로퍼티로도 사용할 수 있겠군요 (개취의 영역이지만, 두분은 기준이 있으실까요?)

그리고 네이밍이 formatPhoneNumber() 또는 formattedPhoneNumber는 어떠신가요?

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/UIViewController+.swift
> +    }
해당 메서드는 지금 두가지 일을 하고 있는것 같은데
이름은 그 중에 한가지만 표현한것 같네요..!

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +                       phoneNumberTextField: UITextField) -> Result<Contact, Error> {
오 요렇게 Result 타입을 사용하게 된 계기(?) 고민 스토리가 궁금하군요.! 
아주 좋습니다👍

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/String+.swift
> +    func formattingPhoneNumber() -> String {
근데 이거 코드가 좀 길긴하네요! 
적절히 쪼갤 수 있는 방법은 없을까요?🤔

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        NotificationCenter.default.addObserver(self,
loadData 의 결과와 밑에 있는 노티피케이션이 쏴지는 일이 서로 의존적이지는 않나요??
즉, loadData가 제대로 됐을때만 tableVIew가 reload 되어야하는걸까요?? (질문입니다)

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            })
👍

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            let cell: UITableViewCell = tableView.dequeueReusableCell(withIdentifier: ContactTableViewErrorCell.identifier,
👍

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +            !name.isEmpty
이건 그냥 제 개인적인 스타일인데, ! 보다 그냥 `name.isEmpy == false ` 도 가독성 측면에서 나쁘지만은 않더라고요..! 
꼭 따르실 필요는 없습니다~

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +            let convertAgeToInt = UInt(age),
convertAgeToInt 는 약간 메서드명 같네요?🤔

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    }
요거 굉장히 많이 보이는데, 프로토콜을 활용하여 프로퍼티를 제공하는 방법은 어떠신가요??

```
protocol 멋진이름 {
    static var identifier: String { get }
}

// Default Implementation
extension 멋진이름 {
    static var identifier: String {
        return String(describing: self)
    }
}
```
그리고 사용하고싶은 타입에 채택하면 끝..!

2024-01-16 11:21 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewErrorCell.swift
> +class ContactTableViewErrorCell: UITableViewCell {
final 가능할것 같네용

2024-01-16 12:03 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactTableViewCell.swift
> +    }
오..! 반영해 보겠습니다!

2024-01-16 12:04 UTC, yoruck2 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +            let convertAgeToInt = UInt(age),
convertedAgeToInt...?

2024-01-17 07:29 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +            !name.isEmpty
문맥이 어색해서 고민이었는데 훨씬 나은 것 같습니다!

2024-01-17 07:32 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/String+.swift
> +    func formattingPhoneNumber() -> String {
> 연산프로퍼티로도 사용할 수 있겠군요 (개취의 영역이지만, 두분은 기준이 있으실까요?)

아...연산프로퍼티로 구현할 수 있다는 점을 간과했습니다...명세서가 중간에 변경된 내용이라 너무 급하게 구현한 것 같네요ㅠ

> 그리고 네이밍이 formatPhoneNumber() 또는 formattedPhoneNumber는 어떠신가요?

반영했습니다!

2024-01-17 07:34 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/UIViewController+.swift
> +    }
> 해당 메서드는 지금 두가지 일을 하고 있는것 같은데 이름은 그 중에 한가지만 표현한것 같네요..!

그러면 `addAction`과 `present`하는 부분을 분기하거나 함수 네이밍을 `makeAndShowAlert`으로 변경하는 것이 좋을까요?

2024-01-17 07:50 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/InputValidator.swift
> +                       phoneNumberTextField: UITextField) -> Result<Contact, Error> {
이름, 나이, 전화번호의 입력값에 대한 유효성을 검증하면서 에러를 `throw`하게 구현했습니다. 
해당 메서드를 각각 선언하여 검증을 하려고 하니 공통된 로직이 있어 캡슐화 및 은닉화를 할 수 있다고 생각했습니다. 
또한, `catch`된 `error`를 또 다시 `throw`하지 않고 `Error` 타입으로 반환할 수 있게 `Result` 타입을 사용했습니다.
뿐만 아니라, 유효성 검사를 마친 뒤 `contactManager.addContact(contact: contact)`를 통해 값을 넣어주기 때문에 `Result` 타입에 `Contact`와 `Error`를 반환할 수 있게 구현했습니다.

2024-01-17 08:40 UTC, Changhyun-Kyle commented
> 수고하셨습니다!!
> 
> 크 UML 잘 봤습니다~ UML을 개인적으로 꽤 좋아해서, 지금도 복잡스럽거나 처음 보는 레거시 코드 다룰때 프로젝트 시작하기 전에 잘 사용한답니다:) 연습 자주 해놓으시면 좋을것 같아요!

감사합니다!

> mark 주석으로 코드 정리하는거 잘 봤습니다..! private method 들도 extension으로 빼면 더 보기 좋을것 같긴한데,,이건 제 개인적인 스타일 일 수도 있을것 같네요ㅎ

반영해보겠습니다!

> ### Notification 에 대한 고민
> 
> > ContactListViewController가 구독하고 있기 때문에 확장성
> > 혹시 여기서 말씀하신 확장성은 어떤것일까요?🤔

우선, 앞서 PR에서 말씀드렸던 것과 같이 `연락처를 편집하는 뷰`가 만들어진다면 `새 연락처를 수정하는 뷰`에서 dismiss 시 `tableView.reload()`하는 로직을 동일하게 수행하기 때문에 같은 `notification`을 `post`해주면 된다고 판다하여 확장성이 있다고 생각했습니다!

> Notification에 대한 저의 의견을 드리자면, 저는 좀 반대파 이긴 해요..! 그래서 Delegate 으로 가능한 일은 일단 Delegate 을 더 선호 하고요. NotificationCenter로만 구현이 가능한 일들도 충분히 있어요, 한쪽 화면에서 어떤 일이 발생했는데, 다른 쪽 화면에 어떤 정보를 보내거나 일을 시켜야 할때, 또는 그게 여러 가지 화면일때? 그럴때는 다른 방법이 많지 않아서 사용할 수 있을것 같네요.
> 
> 근데 시간이 지날 수록, NotificationCenter 는 굉장히 관리하기 힘들어지기도 하고, 히스토리 파악도 어려워질때도 있고, 처음 만들어진 목적과 다르게 사용하기 시작해서 예상하지 못한 버그가 발생하는 경우도 많이 봤어요,,! 그래서 저의 개인적인 성향은, 가능하다면 피한다! 가 되겠습니다~

알라딘의 의견에 충분히 동감합니다! 아래 코드처럼 데이터 전달이 아닌 이벤트를 발생시키는 트리거 역할이라 Notification을 썼지만, `STEP3`를 조금 진행하다보니 연락처 편집에 대한 뷰는 `modal`이 아닌 `navigation`을 활용하게 되어 `notificationCenter`를 사용할 이유가 사라진 것 같아 `delegate` 패턴으로 수정하여 반영했습니다!

```swift
    @objc
    private func updateUI() {
        contactTableView.reloadData()
    }
```

> ### 전화번호 포맷팅 로직의 가독성과 효율성
> 가독성에 대해서는 , 코멘트 남겼어요 해당 코드에!! 그리고 효율성! 은 어떤것을 말씀하시는걸까요?!

모든 조건을 `if문`으로 분기하고 `String`의 `count`를 통해 모든 범위를 확인하는 점이 하드코딩(?)처럼 느껴져서 효율성이 떨어진다고 생각했습니다🥺

2024-01-18 04:54 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        NotificationCenter.default.addObserver(self,
현재 코드에서는 `Notification`을 구독(`addObserver`)하는 역할을 하고 `post`를 하는 것이 아니기 때문에 `loadData()`의 결과와 `Notification`의 실행함수인 `contactTableView.reloadData()`는 독립적이라고 생각합니다!

2024-01-18 14:24 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/UIViewController+.swift
> +    }
makeAlert() 로 하면 alert이 리턴 되어서 나와야할것 같고, 그게 아니라면 그냥 통틀어서 presentAlert() 도 나쁘지 않을것 같습니다 개인적으로!

2024-01-19 01:00 UTC, Changhyun-Kyle commented on ios-contact-manager-ui/ios-contact-manager-ui/Extension/UIViewController+.swift
> +    }
반영했습니다!

2024-01-19 06:20 UTC, junbangg approved these changes

2024-01-19 06:20 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Utils/TypeIdentifiable.swift
> +protocol TypeIdentifiable {
이름 멋진데요!👍

2024-01-19 06:20 UTC, junbangg commented on ios-contact-manager-ui/ios-contact-manager-ui/Utils/UpdateContactDelegate.swift
> +}
Delegate 으로 바꾸셨군요?? 비슷한 상황을 노티 delegate 두 방법 모두 적용 해보신게 아주 좋네요ㅎㅎ

2024-01-19 06:21 UTC, merged