연락처 관리 앱 [STEP 2] Andy, Tommy
tasty-code/ios-contact-manager-ui pull request #70
Opened 2024-01-15 04:29 UTC by andyanappdev

> 리뷰어 : @minsson
버드 : @angryeon7 @andyanappdev
> 

안녕하세요. (쏘스윗한)민쏜-! 항상 자세한 코멘트 감사드려요!!
이번 STEP2도 피드백 마구마구 부탁드립니다! 즐거운 하루 보내세요🍀

---

## 프로젝트 구조

해당 파일들이 추가되었습니다.

****Folder Structure****

├──  App
 │  ├── Delegate
 │   │   └── AppDelegate
 │   │   └── SceneDelegate
├──  Model
 │   │ └── Contact
 │   │ └── ContactManager
 │   │ └── 📁ContactDelegate
├──  View
 │   │ └── ContactsView
 │   │ └── ContactTableViewCell
 │   │ └── 📁ContactDetailView
├── ViewController
 │   │ └── ContactsViewController
 │   │ └── 📁AddContactViewController
└───

---
## Sequence Diagram

<img width="711" alt="스크린샷 2024-01-08 오후 4 18 50" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/89269326/5f15c143-35a3-4ae4-b535-8ac42ecb5316">

---

## 프로젝트 설명 (Code Base UI)

MVC (Model-View-Controller) 패턴을 기반으로 View와 Controller를 분리하려고 노력했습니다.

STEP2 구현 부분

1. **`AddContactViewController` 클래스:**
    - `ContactManager`를 의존성 주입으로 받아 새로운 연락처를 추가하는 뷰 컨트롤러.
    - `UITextField` 에서 이름, 나이, 연락처를 입력받습니다.
    - Save 버튼이 눌리면
        - 입력된 정보가 유효한지 확인 한 후, 유효하지 않다면 Alert 메시지를 표시합니다.
        - 입력된 정보가 유효하다면 `ContactManager`를 통해 새로운 연락처를 추가하고, 이를 `delegate`를 통해 `ContactsViewController`에 알립니다.
2. **`ContactsViewController` 클래스:**
    - 테이블 뷰를 통해 연락처 목록을 표시하고, "Add" 버튼을 통해 새로운 연락처를 추가할 수 있는 기능을 제공합니다.
    - 새로운 연락처를 추가할때에는 `AddContactViewController`를 modal로 표시하고, 새로운 연락처가 추가되면 테이블 뷰를 reload합니다.
3. **알림 및 유효성 검사:**
    - `AddContactViewController`에서는 이름, 나이, 연락처에 대한 유효성 검사를 수행하고, 유효하지 않을 경우 적절한 알림 메시지를 보여줍니다.
    - 알림 메시지는 `presentSaveFailureAlert` 에서 message만 바뀌어 사용됩니다.

---

## 조언을 얻고 싶은 부분 🤔

- saveTapped 메서드가 너무 많은 일을 하고 있다고 생각이 됩니다.
- 현재 saveTapped 메서드의 역활
    1. 각각의 필드의 유효성 판별
    2. 판별 결과에 따른 Alert 표시
    3. 새로운 Contact 객체를 생성 후 저장
    
    ```swift
    @objc private func saveTapped() {
            guard let name = addContactView.accessNameTextField().text?.replacingOccurrences(of: " ", with: ""),
                  let ageString = addContactView.accessAgeTextField().text,
                  let age = Int(ageString),
                  let contactNumber = addContactView.accessContactNumberTextField().text,
                  isValidName(name),
                  isValidAge(age),
                  isValidContactNumber(contactNumber)
            else {
                if let name = addContactView.accessNameTextField().text, !isValidName(name) {
                    presentSaveFailureAlert(message: "입력한 이름 정보가 잘못되었습니다.")
                } else if !isValidAge(Int(addContactView.accessAgeTextField().text ?? "")) {
                    presentSaveFailureAlert(message: "입력한 나이 정보가 잘못되었습니다.")
                } else if let contact = addContactView.accessContactNumberTextField().text, !isValidContactNumber(contact) {
                    presentSaveFailureAlert(message: "입력한 연락처 정보가 잘못되었습니다.")
                }
                return
            }
           
            let addNewContact = Contact(name: name, age: ageString, contactNumber: contactNumber)
            delegate?.addNewContact(newContact: addNewContact)
            dismiss(animated: true, completion: nil)
        }
    ```
    
- STEP 2의 명세서에는 “저장 버튼을 선택하면 입력한 정보가 올바르게 입력되었는지 확인하도록 합니다.” 라고 명시되어 있습니다.
    - 그래서 TextField의 delegate를 활용하여 유저로 부터 입력되는 값을 확인하는 방법은 불필요 할것 같고
    - 그러자니 saveTapped 메서드가 많은 일을 담당하는 것 같고
    - 메서드의 역할 분리가 필요하시다고 판단되시는지?
    - 해당 코드를 좀더 발전 시킬수 있는 방향성에 대한 아이디어를 알려 주세요

2024-01-16 14:32 UTC, minsson requested changes
안녕하세요, 앤디, 토미!
Step 2 수행하시느라 고생 많으셨습니다!!

### 좋은 점
- 전반적으로 네이밍이 깔끔한 편이어서 읽기 편했어요.
- 은닉화/캡슐화에 대해 고민하고 시도해보신 흔적도 있었는데, 보완하면 좋을 부분이 있지만 멋진 시도였다고 생각해요.
- 폴더 구조를 깔끔하게 나눠주신 점도 좋았어요.
- Mark 주석으로 코드를 나눠주셔서 객체 내에서 메서드들을 찾아다니기도 편했어요.
- 코드베이스 UI를 시도해보신 것도 좋았어요.

### 아쉬운 점
- 연락처를 입력할 때, 실제 앱이라면 `-`를 입력할 수 없는 상황이에요. 키패드가 NumberPad이기 때문이에요. 즉, 현재로서는 무조건 연락처 에러가 발생하기 때문에 사용할 수 없는 앱이에요. 연락처에 `-`를 자동으로 삽입할 방법은 없을까요?
- Alert에서 아니오/예 에서 UIAlertAction.Style이 적절하게 지정되지 않았어요.
- 요구사항의 올바른 사용자 입력 예시에 나와 있는 모든 '나이'의 입력 방법에 대응하지 못하고 있어요.

### 질문 답변
자세한 코드 리뷰는 코드에 코멘트로 남겨두었으니 생략하고, 여기에서는 말씀하신 '조언을 얻고 싶은 부분'에 대해 다뤄볼게요! 남겨주신 질문이 길어 여기에 옮기지는 않고, 바로 답변 드릴게요.

말씀해주신 것처럼 saveTapped()라는 메서드는 여러 책임을 갖고 있어요.
- 입력 값 검증
- 오류 처리 및 Alert 띄우기
- 새로운 연락처(Contact) 생성 및 저장
- 화면 닫기 (dismiss)

또, 지금 로직에서는 검사할 수 있는 모든 걸 다 검사한 후, 뭔가 잘못되면 다시 이름, 나이, 연락처 순서대로 하나씩 점검하고 있어요. 즉, 불필요한 검사를 다시 반복하고 있고, 이로 인해 가독성도 떨어져요. 이 부분은 역할, 책임과는 별개로 점검해보셨으면 좋겠어요.

이 중 dismiss는 어쩔 수 없는 부분이니 넘어가고, 위의 세 가지를 담당할 각각의 메서드를 만들면 좋을 것 같아요. 별도의 객체를 만드는 방법도 있지만, 제 생각에는 별도의 객체를 만들지 않고 AddContactViewController의 메서드로 만들어도 충분할 것 같아요. 

그런데 말로만 하면 위에서 나눠놓은 책임에 따라 딱딱 나눌 수 있을 것 같지만, 막상 구현해보면 그렇게 깔끔하게 맞아떨어지지 않을 거예요. 값을 언래핑해서 추출하고, 그걸 다시 validation하는 메서드에 각각 전달하고, 근데 그 과정에서 에러 Alert는 어디에서 띄워야할지도 애매하고... 제가 생각하기에는 그런 이유로 두 분이 saveTapped()의 책임이 여러 개라는 걸 아시면서도 한 메서드에 코드를 몰아넣으실 수 밖에 없었을 것 같아요.

그런 부분이 문제라면 구조를 조금 바꿔 아래처럼 접근해보면 어떨까요?
- Error 프로토콜을 채택한 ContactInputError라는 에러 타입을 만든다.
- validateInput라는 에러를 던지는 메서드를 만들고, 문제가 있으면 에러를 던진다.

위 과정에서 do-catch를 적절히 활용해보면 좋을 것 같아요. 제가 제안드리는 건 정답도 아니고, 제 생각을 다 말씀드리면 하나의 방향만을 강요하게 되는 것 같아 생각의 일부만 말씀드렸으니, 간단하게 참고만 하시고 두 분 생각대로 진행해보시면 좋을 것 같아요.

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
1) 요구사항의 `올바른 사용자 입력 예시`의 두번째 경우, 세번째 경우를 입력하면 false가 나와요. 요구사항을 지킬 수 있도록 수정해주세요.
2) guard-let 바인딩 등 다른 언래핑 방법도 고려 가능한데, 어떤 이유로 if-let을 선택하셨나요? 이 맥락에서 guard-let을 쓴다면 지금과 어떤 게 달라질까요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
3. `age`는 그냥 age인데, 언래핑하느라 `ageValue`라는 불필요한 네이밍을 떠올리는 게 불편하지 않았나요? Syntax 측면에서 아래 같은 구조로 쓰는 것도 가능해요. 단순 언래핑 용도라면 아래처럼 쓰시면 돼요.
```swift
if let age {
  print(age)
}
```

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.textAlignment = NSTextAlignment.center
`NSTextAlignment`라는 타입을 명시해주신 이유가 궁금해요.

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.textColor = .black
기본 색상을 사용하는 경우 가급적이면 처음부터 다크모드까지 고려하는 편이 좋아요. 다크모드로 전환하면 백그라운드가 검은색이 되는데, 이때 글자도 검은색인 상태로 유지되어 보이지 않게 돼요. `.black` 대신 `.label`을 쓰면 아주 간단하게 이 문제를 해결할 수 있어요. 지금 그렇게 중요한 건 아니니 가볍게 검색해보시면 좋을 것 같아요.

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 16)
`UIFont`라는 타입을 명시해주신 이유가 궁금해요.

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }()
`lazy` 키워드를 지우면 에러가 발생할텐데, 왜 이런 에러가 발생하고, 왜 `lazy` 키워드를 쓰면 에러가 발생하지 않는지 설명해주실 수 있나요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        self.backgroundColor = .white
앞에서 UILabel의 색상을 `.black`보다는 `.label`로 하면 좋다고 말씀드렸는데, 여기서는 어떤 걸 쓰면 좋을까요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
`configureUI`라는 네이밍이 너무 광범위하게 느껴져요. 범위를 좀 좁힐 수 있을까요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
제가 추측하기에는 은닉화와 캡슐화에 대해 고민하신 것 같아요. 그런데 현재로서는 `nameTextField`, `ageTextField`, `contactNumberTextField`에서 `private let` 대신 `let`으로 선언하는 것과 사실상 동일해보여요.

- 어떤 이유로 이 메서드들을 정의해주셨나요?
- 이 메서드를 통해 얻은 것과 잃은 것에 대해 자세히 말씀해주실 수 있나요?
- 호출부에서 이 메서드들을 사용할 때는 어땠나요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
- `configureConstraints()` 메서드를 init 함수에서 호출하면 어떻게 되나요?
- `configureUI()` 메서드는 init 함수에서 호출하지만, `configureConstraints()` 메서드는 `updateConstraints()` 안에서 호출한 이유가 무엇인가요?
- `updateConstraints()` 메서드는 무엇인가요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
- `UIAlertAction.Style`에서 "예"에 `.default`를, "아니오"에 `.destructive`를 설정해주셨는데, 어떤 기준으로 설정하셨나요? 
- `cancel`, `destructive`, `default`가 있는데, UX적으로 어떤 차이가 있나요?

2024-01-16 14:32 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
guard-let 바인딩의 개행 컨벤션은 어떤 기준으로 쓰고 계신가요?

2024-01-17 01:42 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.textColor = .black
감사합니다. 민쏜
프로젝트 명세서에는 색상에 대한 언급이 없었지만
추후에 lable의 색상을 바꿔 가면서 시안성이 어떤 것이 더 좋을지 test해보려고 미리 선언해 두었습니다.
색상을 설정할때에는 당연히 다크모드에 대한 고려를 했어야 되는데 생각도 못하고 있었내요 ㅜㅜ
정말 감사합니다.
색상을 기본값이 아닌 다른것으로 설정할 경우 항상 다크모드에 대한 고려를 함께 해야 한다는 것을 이번기회를 통해서 확실히 머리속에 넣었습니다.

2024-01-17 02:00 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
- 현재 프로젝트의 알렛메세지가 “정말로 취소하시겠습니까?”이기 때문에 주의를 요하는 액션은 “예” 버튼인데 코드를 작성하면서 아니오가 부정적인 작업이라고 착각한것같습니다.
- 긍정적이거나 중립적인 액션은 `.default`로, 주의를 요하는 액션은 `.destructive`로 표현합니다.
"예" 버튼이 일반적이거나 긍정적인 작업을 나타내므로 `.default` 스타일을 사용한 것이고, "아니요" 버튼이 부정적인 작업을 나타내므로 `.destructive` 스타일을 사용하게되었습니다. → 착각했습니다..

`UIAlertAction.Style`에서는 주로 다음 세 가지 스타일을 사용합니다:

1. **Default (.default):** 이는 기본 액션으로, 일반적인 액션에 사용됩니다. 사용자가 일반적으로 예상하거나 기본적인 선택을 나타내는 버튼에 이 스타일을 사용합니다. 주로 긍정적이거나 중립적인 작업에 대한 버튼에 할당됩니다.
2. **Cancel (.cancel):** 이는 주로 모달 팝업이나 액션 시트에서 '취소' 액션으로 사용됩니다. 
3. **Destructive (.destructive):** 이 스타일은 사용자에게 주의가 필요하거나 부정적인 결과를 초래할 수 있는 액션에 사용됩니다. 주로 데이터 삭제 또는 중요한 작업을 수행하는 버튼에 이 스타일을 할당합니다.

2024-01-17 02:10 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.textAlignment = NSTextAlignment.center
우선 저는 개인적인 프로젝트를 할때에는 무조건 해당타입 속성 그리고 할당 값을 모두 표기 하도록 하자는 주의 입니다.
그 이유는 첫번째, 아직 학습중이고 해당 값이 어떤 타입에 어떤 속성에 값을 할당 하고 있는지는 알고 사용해야 된다고 생각하기 때문입니다.
두번째, 초보자 또는 다른 기술 stack을 사용하는 개발자가 나의 코드를 볼때 빨리 이해할수 있도록 작성하자는 생각을 가지고 있습니다. (저를 위한 것이기도 합니다. 저는 Flutter 개발도 같이 하고 있어서 한동안 iOS 개발 안하다가 다시 Swift 코드를 보면 한눈에 이해 못할때도 있고해서...)
물론 IDE 에서 제공해주는 편리한 기능을 사용해서 가독성도 높이고 간단하게 값을 할당해주어도 되지만 저만의 원칙을 정하고 지키려고 합니다.
하지만 이번 STEP을 진행하면서 빨리 빨리 끝내야 한다는 것에만 포커스를 두고 진행하다보니 디테일이 너무 떨어 진 부분 스스로 반성하고 인정합니다. 일관성도 없고 ㅜㅜ

PS. 아래 UIFont 타입 명시와 같은 맥락이라 이곳에만 comment 남기도록 하겠습니다.

2024-01-17 02:28 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }()
처음 코드를 작성했을때에는 stackView를 인스턴스화 할때 arrangedSubviews 를 설정해 주지 않고
따로 configureUI 메서드를 생성해서 stackView에 추가해주는 코드를 작성했는데
그러다 보니 해당 stackView의 구성이 한눈에 들어 오지 않고 가독성에 있어서도 불리하다고 판단해서 지금의 코드의 형태로 변경 하였습니다.
lazy 키워드를 사용한 이유는 해당 stackView의 구성이 될 label들이 아직 초기화 생성되지 않았기 때문에 lazy로 선언해서 메모리 주소를 확보해 두고 나중에 stackView에 접근하여 메모리에 올릴때 그때 해당 label들과 함께 구성되게 하기 위해서 입니다.

정리
초기화 시점에 모든 속성들이 동시에 메모리 공간에 저장되므로 어떤 한가지 속성이 다른 속성에 접근할 수가 없다.
그렇지만, 지연 저장 속성을 이용 하는 경우 지연으로 저장된 속성은 먼저 초기화된 속성에 접근 할 수 있게된다.

2024-01-17 04:29 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        self.backgroundColor = .white
iOS 13 이후

1. UIColor.systemBackground 사용

2. Resolved Color 
시스템의 라이트 / 다크 모드와 관계 없이 특정 View에 설정된 UITraitCollection에 맞춰서 정해진 색상을 반환

3. Dynamic Provider
UITraitCollection에 따라서 색상을 리턴할 수 있는 기능을 지원한다. 코드로 라이트 / 다크 모드에 대한 분기 처리가 필요할 때 사용

2024-01-17 06:09 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
한 줄에 표현될 수 있으면 한 줄에 표현하려고 하지만, 바인딩 할 값이 많거나 길어질 경우 여러 줄로 나누고 있었습니다. 이전에는 모두 한 줄로 표현했지만 이번 코드의 경우 바인딩 할 값이 길어져 여러 줄에 걸쳐 표현하였지만 일관성을 유지하는 것이 중요하다는 것을 알고 수정하도록 하겠습니다.

2024-01-17 07:16 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
민쏜이 지적해주신 사항에 대해 저도 자세히 보니 변수가 아닌 상수이기 때문에 굳이 직접적인 접근을 막을 필요까지 없다고 저도 판단이 됩니다.

- 메서드들을 정의한 이유
기본적으로 저는 속성에 직접적인 접근을 모두 차단하고 해당 속성의 값이 필요한 경우 getter를 정의 하던 또는 메서드를 통해서 가져 갈수 있도록 설계를 합니다. (주로 getter를 활용 하는 편입니다. - Flutter 개발시)
ContactManager 에서 fetchAllContacts 메서드로 contactList를 받아가도록 구현이 되어 있어서 이번에도 getter가 아닌 메서드로 구현했던것 같습니다.
사실 이미 contact 속성을 didSet으로 구현하고 접근 가능하도록 해두었다는것 부터 저의 논리와 상충 된다는 것을 저도 잘 알고 있습니다. 
화면 상태에 관련된 것들을 따로 모아서 class를 생성해서 캡슐화 시키고 뷰모델을 만들어서 그 값의 변경이 필요할시 deep copy해서 값을 변경하고 변경된 값을 다시 재할당 해주고 해야 하는데 이번 프로젝트에 모두 다 적용시켜서 가려고 하니 페어코딩 진행의 한계로 인하여 포기한 부분 입니다.
(코드상 상수이기 때문에 외부에서 값을 변경 할수도 없지만 그냥 원천적으로 접근도 막아두고 getter로 해당값을 받아 가게 하는 것이 개인적으로 심리적 안정감을 가지게 됩니다. 즉 모든것을 다 막아두어야 맘이 편해지는... 
저 스스로도 못 믿고 협업하는 다른 개발자에게 어떠한 여지조차 주지 않게 차단해 한다고 생각 합니다. 즉 휴먼에러가 발생할수 있는 포인트를 모두 제거해야할 의무와 책임은 저에게 있다고 생각합니다.)

- 얻은것과 잃은것
얻은것 : 은닉화를 통해 객체 외부에서 내부 데이터의 접근 통제가 가능
잃은것 : 사용하지 않아도 될 메모리를 메서드를 이용함에 따른 낭비 발생, 호출부에서의 가독성 저하 (저는 2가지만 생각이 나는데 혹시 민쏜이 더 정확하게 알려 주시면 감사하겠습니다.)

- 호출부에서의 사용 편의성
불편했습니다. 굳이 private를 고집한다고 가정한다면 매서드 보다 getter가 가독성면에서는 아주 조금더 좋아 보입니다.

2024-01-17 07:55 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/AddContactViewController.swift
> +    }
'if let'은 일반적으로 특정 작업을 수행하거나 옵션에 값이 있는 경우에만 확인하려는 경우에 사용됩니다

guard let은 빠른 종료가 핵심으로 특정 조건이 충족되었는지 확인하고 싶을 때 사용합니다. 여러 옵션을 처리할때 코드를 더 읽기 쉽게 만들 수 있습니다. 

```swift
private func isValidAge(_ age: Int?) -> Bool {
    guard let ageValue = age, 0 < ageValue && ageValue <= 999 else {
        return false
    }
    return true
}

```

수정된 버전에서는 조건이 충족되지 않으면 함수가 false를 반환하고 조기 종료됩니다. 

특정 조건이 충족되었는지를 확인하는 메서드이기때문에 guard let이 더 효율적이라고 판단하여 수정하였습니다.

2024-01-17 08:35 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
- `configureConstraints()` 메서드를 init 함수에서 호출하면 어떻게 되나요?
    - 만약 `configureConstraints()` 메서드를 `init` 함수에서 직접 호출한다면, 해당 메서드는 초기화 단계에서 호출됩니다.
- `updateConstraints()` 메서드는 무엇인가요?
    - `updateConstraints()` 메서드는 `UIView` 클래스에서 상속받은 메서드로, 레이아웃 업데이트를 수행할 때 호출되는 메서드입니다. 
    → 이 메서드를 오버라이드하여 레이아웃 업데이트 시 필요한 작업을 수행할 수 있습니다.
    객체의 제약조건이나 레이아웃이 동적으로 변할 때 해당 메서드에서 제약을 추가하거나 수정함으로써 레이아웃 업데이트에 대응할 수 있다!!
- `configureUI()` 메서드는 init 함수에서 호출하지만, `configureConstraints()` 메서드는 `updateConstraints()` 안에서 호출한 이유가 무엇인가요?
    - `updateConstraints()`는 레이아웃 시스템에 의해 호출되는 메서드로 이 메서드는 레이아웃을 업데이트할 필요가 있을 때 자동으로 호출됩니다.
    `updateConstraints()`에서 `configureConstraints()`를 호출함으로써, 레이아웃이 변경되는 시점에 필요한 제약조건을 설정
    → 이는 객체가 생성된 후에 레이아웃이 변경될 때마다 호출되므로, 동적인 레이아웃 변경에 적합하기때문에 현재 저희 프로젝트에 적합하지않다고 판단하여 수정하도록 하겠습니다.

2024-01-17 08:39 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
수정 반영하도록 하겠습니다.

2024-01-17 14:34 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.textAlignment = NSTextAlignment.center
좋은 취지라고 생각해요! 특히 첫번째 이유가 인상적이네요! 학습에 많은 도움이 될 것 같아요. 다만 어디에는 명시하고, 어디에는 명시하지 않아, 코드를 읽을 때 '이건 특별히 이유가 있어서 명시한 걸까?'라는 의문이 들었어요. 일관성을 유지해주시면 더 좋을 것 같아요.

2024-01-17 14:39 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        label.textColor = .black
그런 관점에서 .system이 붙은 색상들도 좋아요. 기본적으로 다크모드에 다 대응하고 있어서요. 디자이너가 있다면 알아서 다 정의해주시겠지만, 디자이너 없이 개인 앱을 만드실 때 특히 유용해요!

2024-01-17 14:41 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }()
좋아요! 나중에 여유가 되면 지연 저장 속성이 초기화되는 시점이 언제길래 '지연'이라는 말을 사용하는 건지도 공부해보면 좋겠네요.

2024-01-17 14:43 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +        self.backgroundColor = .white
오.. 저도 잘 모르는 개념이네요..! 제가 말씀드리고 싶었던 건 1번이었어요 ☺️

2024-01-17 15:16 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
그런 의도라면 메서드를 만들어 값을 넘겨받는 게 나을 수도 있겠다는 생각이 들어요. 
은닉화, 캡슐화가 다른 건 다 숨기고 딱 필요한 것만 넘겨주는 건데, UITextField 자체를 통째로 넘긴다는 점이 특히 의아했어요.

```swift
// 모델 객체 (새로운 모델까지는 불필요하다고 생각하면 네임드 튜플로 넘기는 방법도 있을 것 같아요)
struct ContactInput {
  let name: String
  let age: Int
  let contactNumber: String
}

func currentContactInput() -> ContactInput {
  // 필요한 모든 textField.text 값에 접근
  // 필요시 텍스트 필드의 값들 언래핑 등 처리
  let contactInput = ContactInput(name: ..., age: ..., contactNumber: ...)
  return contactInput
}

let currentContactInput: ContactInput = addContactView.fetchCurrentContactInput()
```

2024-01-17 15:25 UTC, minsson commented
고생하셨습니다! 빠르게 Step 3로 넘어가봅시다! 🚀

2024-01-17 15:25 UTC, merged

2024-01-17 15:28 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactDetailView.swift
> +    }
우와 왜 저는 이렇게 생각을 하지 못했을까요?
저에게 필요한 것은 필요한 단지 textField.text 값인데... 이것을 처리하기 위해 textField를 통째로 넘기는 무식한 방법을 사용했다는 것을 민쏜을 통해서 느끼게 되었습니다.
정말 감사합니다.
앞으로 이와 유사한 상황이 생긴다면 필요한 값들을 뽑아서 그것만 넘겨 주도록 하겠습니다.