연락처 관리 앱  [STEP 2] Hong, Effie
tasty-code/ios-contact-manager-ui pull request #73
Opened 2024-01-16 05:16 UTC by hyeffie

라이언(@ryan-son) 안녕하세요. 늦은 PR로 돌아온 에피(@hyeffie), 홍(@ujhong7)입니다!

이번 스텝에서는 연락처를 추가할 수 있는 새로운 화면을 표시하고, 사용자 입력을 처리해야 하는 요구사항이 있었고 다음 작업을 중심으로 구현을 추가했습니다.
- 입력을 위해 반복해서 사용해야 하는 뷰를 하나로 묶어 커스텀 뷰을 만들었습니다. 해당 뷰가 다르게 표시하고, 다르게 동작해야 할 부분은 생성 시점에 전달받도록 구현했습니다.
- 새로운 화면을 표시하고, 사라지게 하는 로직을 presenting view controller나 presented view controller가 아닌 제 3의 객체인 Coordinator에게 위임하도록 구현했습니다.
- 입력 필드에서 입력을 할 때마다 입력을 검증해 유효하지 않은 입력을 막고, 입력을 원하는 형식으로 표시하도록 구현했습니다.
- (현재 입력이 유효한지에 관한 정보를 필드 아래에 표시하는 구현을 하고 있었는데요. 이 부분이 엣지 케이스가 많은 부분이라 구현이 어렵기도 하고, 여러 상황에 대응하도록 하려면 좀 더 제네릭한 구현이 필요하다고 생각해서 들어내기로 결정했습니다!)

올려둔 코드에 대한 자세한 설명은 코멘트를 통해 작성하도록 하겠습니다. 이번 리뷰도 잘 부탁드리겠습니다!

2024-01-16 05:22 UTC, hyeffie commented
다음은 저희 프로젝트의 주요한 데이터 흐름을 관련 있는 객체들의 관계로 그려본 클래스 다이어그램입니다.
```mermaid
classDiagram

class ListContactUseCase {
		<<struct>>
		-ContactRepository repository
		-ListContactPresentable presenter
		+fetchAllContacts()
}

ListContactUseCase --> ContactRepository
ListContactUseCase --> ListContactPresentable

class ListContactPresentable {
		<<protocol>>
		+presentListContact(Result<ListContactModel.SuccessInfo, Error>)
}

class ContactRepository {
		<<protocol>>
		+requestContacts() [Contact]
}

class ContactRepositoryImpl {
		-ContactList contactList
		-FileProvidable fileProvider
		-JSONDecoder jsonDecoder
		+requestContacts() [Contact]
		-getContactsFromBundle() Data
}

ContactRepositoryImpl ..|> ContactRepository

class ListContactViewController  {
		-listContactUseCase ListContactUseCase
		-contactListView() ContactListTableView()
		-ContactListDataSource contactListDataSource
		-setupViews()
		+presentListContact(Result<Success, Failure>)
		-showErrorAlert(AlertableError)
}

ListContactViewController ..|> ListContactPresentable
ListContactViewController --> ListContactUseCase
```
ListContact 관련 객체들로 그리고 있지만 이번 스텝에서도 같은 흐름을 유지하도록 구현했으니 참고용으로 읽어주세요 :)

2024-01-16 05:47 UTC, hyeffie commented on ContactManager/ContactManager/App/SceneDelegate.swift
> +        self.coordinator = coordinator
의존성 주입 관련해 추천해주신 내용 아직 반영하지 못했지만, 지난 스텝에서 구현했던 Factory에 관해서 좀 더 고민해 볼 필요가 있는 것 같아서 제거했습니다. 이번 코드는 이전 계층에서 생성해서 전달하는 식으로 구현하고 있습니다.

2024-01-16 06:54 UTC, hyeffie reviewed
제안해주신 셀프 리뷰 방식으로 코멘트를 달아보았습니다 😃

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/App/SceneDelegate.swift
> +        self.coordinator = coordinator
의존성 주입 관련해 추천해주신 내용 아직 반영하지 못했지만, 지난 스텝에서 구현했던 Factory에 관해서 좀 더 고민해 볼 필요가 있는 것 같아서 제거했습니다. 이번 코드는 이전 계층에서 생성해서 전달하는 식으로 구현하고 있습니다.

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Common/ContactMakable.swift
> +    }
ContactFactory 로 use case가 request로 전달받은 내용을 validate하고 contact 를 생성하고 있습니다. 즉, use case는 실제로 addContact를 호출하기 전에 input validating과 contact 생성을 위해 markable 계층을 포함하고, view(InputView)에서 입력 자체를 검증하고 유효성을 검증하는 로직을 두고 있도록 따로 구현한 것이죠. 
처음에는 입력을 검증하는 조건이 중복되지 않나 해서 재사용할 수 있도록 하는 방법도 고민해보았는데, 조건을 구현하고 사용하는 방식이 달라서 어쩔 수 없이 분리하게 되었는데요. 이런 식으로 입력 시점의 유효성 검증과 엔티티 생성 시점의 유효성 검증을 분리하는 것이 일반적인 구현인지, 아니면 조건을 재사용할 수 있는 좋은 방식이 있을지 궁금합니다.

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Common/ContactMakable.swift
> +    }
또 Contact를 만들고 있지만 주요한 기능은 validation인데요. Factory라는 이름을 붙이는 게 적당한지, 또 ContactFactory라는 이름은 어떤지 라이언의 의견이 궁금합니다..!

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Common/Formatter.swift
> +typealias InputFormatter = (String) -> String
InputView를 사용하면서 각 필드의 조건에 따라 입력에 대해 포매팅 및 유효성 검증 로직을 다르게 처리할 수 있도록 클로저를 전달받도록 구현했습니다. 그런데 이 부분을 구현하면서 포매팅 로직을 `클로저`로 구현하는 것과 `인터페이스를 만들고 구현체를 만드는 것` 중 어느 게 나을지 고민되더라고요. 지금 생성 시점 때문인지 view controller가 포매팅 로직을 선언하고 있으니 더 무거워 보이기도 하고요. 라이언 의견은 어떠신가요?

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContactError.swift
> +}
요구사항은 아니지만 취소 버튼 이벤트가 발생했을 때 확인 alert 메시지를 띄우는 기능을 구현했습니다. 이 에러도 alert 를 띄우기 위해 필요한 에러 중 하나입니다!

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContact.swift
> +}
입력된 내용을 use case에 전달하기 위해서 Request 타입이 필요했는데요. 기존 ListContact(Model) 구현도 Result의 success 케이스에서 전달하는 데이터 타입을 선언하고 있거든요. 두 기능의 일관성을 위해 네임스페이스 위해 enum 안에 nested로 구현하던 방식을 유지하기로 했습니다.

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContact.swift
> +}
지금 생각해보니 ListContact.SuccessInfo를 사용하는 Result 관련 typealias를 추가하는 것도 좋을 것 같네요...!

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContactUseCase.swift
> +    }
AddContact도 기존 ListContactUseCase와 비슷한 양상으로 구현했습니다. 그리고 원래 Bundle 에 있는 json 파일 데이터를 가져오는 로직은 불필요해진 것 같아 제거했습니다!

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContactUseCase.swift
> +    }
contact 를 생성하는 로직은 Factory(ContactMakable) 에 메시지를 보내고, 취소 가능 여부에 대한 검증은 내부적으로 하고 있어 구현의 위치가 적절한지 고민됩니다. 바로 취소할지를 판단하는 로직은 비교적 간단한데 이것도 분리하는 게 맞을까요? 라이언은 어떻게 생각하시나요?

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +    }()
추가 화면에서 공통적인 view를 가지고 있는 입력 필드를 하나의 view로 묶었다. UIView 서브 클래스이지만, 하위 뷰를 관리하고 뷰 이벤트를 처리하는 delegate 로직을 구현하고 있는 객체입니다. InputView는 현재 필드 이름과 입력 포매팅 로직을 전달받아 생성되고, 이때 전달받은 포매팅 로직을 입력을 처리하는 delegate 메소드에 활용하고 있습니다.

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +    }()
이 클래스를 구현할 때 지금 구현처럼 UIView를 서브 클래싱해서 View라고 이름 지을지, ViewController로 만들고 scene 에 대한 view controller에 child 로 추가할지 고민이 길었는데요. 고민 끝에 view controller 에서는 self.view에 접근하는 코드 등이 복잡해지는 것보다, view가 하위 뷰 이벤트에 대한 작업을 처리를 하는 편이 구현이 간단해지겠다는 판단 하에 UIView를 서브클래싱하고 view로 분류하기로 결정했습니다. 라이언은 이 같은 결정에 대해, 또 이런 케이스에 대해 어떻게 생각하시는지 궁금합니다..!

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Routing/Coordinator.swift
> +}
화면 전환에 coordinator 패턴을 적용해 source, destination view controller 대신 coordinator 가 전환을 책임질 수 있도록 구현했습니다.

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Routing/AppCoordinator.swift
> +    }
AppCoordinator 가 첫화면에 진입하기 위해 ListContactCoordinator를 직접 생성하고 있습니다!

2024-01-16 06:54 UTC, hyeffie commented on ContactManager/ContactManager/Routing/ListContactCoordinator.swift
> +    }
use case 를 생성하고 view controller에 주입하고 있습니다. use case를 scene 단위로 구현하고 있기 때문에 이렇게 구현했던 건데, ListCoordinator에서 use case를 생성하는 게 괜찮은 방법일까요? 의존성 주입 측면에서 리뷰해주시면 많은 도움이 될 것 같습니다 ...!

2024-01-16 07:20 UTC, ujhong7 commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
>  }
파라미터 기본값을 추가했습니다. [관련 코멘트] https://github.com/tasty-code/ios-contact-manager-ui/pull/64#discussion_r1448179312)

2024-01-16 07:28 UTC, ujhong7 commented on ContactManager/ContactManager/Common/ContactValidationError.swift
> +enum ContactValidationError: Error {
ValidationError는 어떤 폼 입력이나 일반적인 데이터 검증 시 발생하는 오류를 발생할 때 사용되고 , ContactValidationError는 연락처와 관련된 유효성 검사 오류를 발생할 때 사용됩니다. 역할이 다르고, throw 되는 위치가 다른 만큼 좀 더 직관적인 이름이 필요할 것 같습니다. 혹시 추천할만한 이름이 있을까요?..

2024-01-16 07:51 UTC, ujhong7 commented on ContactManager/ContactManager/Common/ContactValidationError.swift
> +}
ValidationError는 어떤 폼 입력이나 일반적인 데이터 검증 시 발생하는 오류를 발생할 때 사용되고 , ContactValidationError는 연락처와 관련된 유효성 검사 오류를 발생할 때 사용됩니다. 역할이 다르고, throw 되는 위치가 다른 만큼 좀 더 직관적인 이름이 필요할 것 같습니다. 혹시 추천할만한 이름이 있을까요?..

2024-01-16 07:51 UTC, ujhong7 commented on ContactManager/ContactManager/Common/ErrorAlertPresentableViewController.swift
>          }
함수나 메서드에 여러 개의 동일한 타입의 인자를 전달할 수 있는 가변 매개변수를 활용했습니다. UIAlertAction...은 presentErrorAlert 함수에 여러 개의 UIAlertAction을 전달할 수 있도록 합니다. 함수를 호출할 때 additionalAction 파라미터에 여러 개의 UIAlertAction을 전달할 수 있습니다.

2024-01-16 07:51 UTC, ujhong7 commented on ContactManager/ContactManager/Common/ListContactViewControllerFactory.swift
> -enum ListContactViewControllerFactory {
기존에 주입을 위한 객체 생성을 담당하는 Factory 구현 제거했습니다.

2024-01-16 07:51 UTC, ujhong7 commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
>      }
파라미터 기본값을 추가했습니다. [관련 코멘트] https://github.com/tasty-code/ios-contact-manager-ui/pull/64#discussion_r1448179312)

2024-01-16 07:51 UTC, ujhong7 commented on ContactManager/ContactManager/Data/ContactRepository.swift
> +    func addContact(_ newContact: Contact) throws
연락처 추가에 대응했습니다.

2024-01-16 07:51 UTC, ujhong7 commented on ContactManager/ContactManager/Domain/Model/ContactList.swift
> +        self.contacts.insert(newContact, at: 0)
추가된 엔티티를 테이블의 상단에 표시하기 위해 구현을 수정했습니다.

2024-01-16 19:35 UTC, ryan-son requested changes
에피, 홍, Step 2 수행하시느라 고생 많으셨습니다.

코디네이터 패턴에 의존성 분리 작업으로 고민하실 부분이 많으실 것 같은데 멋지게 수행해주셨네요.
셀프리뷰를 통해 의도를 앞서 설명해주셔서 의도와 질문을 파악하기 좋았습니다.
현재로도 머지가 가능한 수준이지만 미미한 수정 사항과 생각해볼 거리를 남겨두었으니 필요하신 부분은 적용해보시거나 생각해보시면 좋을 것 같습니다.
다음 스텝으로 넘어가도 좋다고 생각하시면 메시지로 알려주세요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/App/SceneDelegate.swift
> +    var coordinator: AppCoordinator?
해당 인스턴스 프로퍼티를 통해 코디네이터 인스턴스의 참조를 유지하지 않으면 어떤 일이 일어나나요?

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Common/ContactMakable.swift
> +    }
1. View 계층에서는 키보드를 통해 입력하거나 붙여넣은 input을 입력 단위마다 검증해야하며 포매팅 등 추가 기능이 포함될 수 있으므로 로직이 엔티티 생성 단계에서의 유효성 검증과는 분리될 수 있다고 생각합니다.
2. 인스턴스 생성을 편리하게 할 수 있다는 점에서 Factory라는 이름은 적절해보입니다. 유사하게 Producer, Generator 등 다양한 이름을 사용할 수 있지만 변경할 필요는 없어보이네요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Common/ContactValidationError.swift
> +}
역할이 다르다는 점은 이해했지만, 텍스트 필드에 입력할 때마다 실시간으로 에러 메시지를 표시하는 것이 아니라면 결국 사용될 포인트는 저장 시점의 얼럿으로 보이네요. 실제로 ValidationError를 준수하는 에러 타입들은 사용되고 있지 않다는 점으로 미루어보아 ContactValidationError 이외에 ValidationError를 준수하는 에러 타입들은 필요 없는 것이 아닐까요?
아마 실시간으로 에러 문구를 텍스트필드 아래에 표시하는 기능을 들어내다 제거하시지 못한 게 아닌가 싶네요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Common/ContactValidationError.swift
> +}
프로젝트 요구사항에 따른 것이겠지만, 실제 환경에서는 조금 더 자세한 이유를 제시하는 것이 좋을 것 같다는 의견입니다.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Common/ErrorAlertPresentableViewController.swift
>          }
좋은 포인트네요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Common/Formatter.swift
> +typealias InputFormatter = (String) -> String
ViewController에서 InputView 인스턴스를 생성할 때 클로저 형태로 전달하는 것은 보기에 부담스러울 수 있지만 간편하게 사용할 수 있다는 장점도 있어보입니다.  재사용될 필요가 있거나, 상황에 따라 검증 또는 포매팅 로직이 변경되어야 할 경우에는 해당 로직을 다루는 타입을 만드는 것도 고려해볼 수 있을 것 같습니다.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
>          ) else {
타겟 번들 인스턴스를 지금처럼 타입의 인스턴스 프로퍼티로 두는 것과 메서드의 매개변수로 받는 것 중에 어떤 것이 더 괜찮은 접근이라고 생각하시나요?

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Data/ContactRepository.swift
>      }
실제로 throw 하지 않는데 throws가 달려있군요. 이후에 만약 중복된 연락처는 예외처리가 필요하다면 어느 위치에서 수행하면 좋을까요?

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Domain/AddContact/AddContact.swift
> +}
저는 타입 이름이 다소 길 수는 있어도 `Result<ListContact.SuccessInfo, Error>`가 주는 의미가 확실하니 새로운 이름을 생각해 typealias를 만들지 않아도 괜찮지 않을까라고 생각해요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Domain/AddContact/AddContactUseCase.swift
> +    }
진행하신 것처럼 하셔도 되고, 조금 더 타입에 역할을 부여하시고 싶으시다면 `AddContact.Request` 타입에 검증 기능을 나눠줘도 괜찮을 것 같네요. 그럼 메서드를 분리해서 따로 의미를 부여할만큼 이해하기 어려운 로직은 아닐 것 같아요. 마찬가지로 `ContactFactory`에서 검증할 때도 Contact 타입의 각 프로퍼티를 커스텀 프로퍼티로 만들어 검증 조건을 나누어 줄 수 있을 것 같습니다.

```swift
guard request.isValid else { ... } // isValid, fieldsAreFilled 등
```

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Domain/Model/ContactList.swift
> +        self.contacts.insert(newContact, at: 0)
연락처는 이름을 기준으로 오름차순 정렬이 일반적으로 보이는데, 추가한 것을 최상단에 위치시키는 정책을 선택한 이유는 무엇이었나요?

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +    }()
UIViewController의 기능까지 필요하지 않다면 UIView로 구성하는 것이 합리적이라고 생각합니다. InputView를 UIViewController로 구성하는 선택지를 고민하신 이유를 알려주실 수 있으실까요?

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +        stack.addArrangedSubview(UIView())
빈 뷰를 통해 텍스트 정렬 조건을 맞추는 것도 가능한 선택지이지만, `fieldNameLabel`의 `textAlignment`으로도 왼쪽, 중간, 오른쪽 정렬 각 요구사항에 맞게 대응할 수 있을 것 같네요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +        guard string.isEmpty == false else { return true } // 지울 때
필요한 주석이라 남겨두셨을까요?

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +    private let fieldNamelabel: UILabel = {
```suggestion
    private let fieldNameLabel: UILabel = {
```

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    }
이렇게 작성하는 것도 괜찮을 것 같네요. empty subsequences를 생략하는 기본 설정 덕에 split이 components 메서드에 비해 성능이 좋지만, 이 케이스에서는 유의미하지 않습니다.

```swift
return input.split(whereSeparator: \.isWhitespace).joined()
// or
return input.components(separatedBy: .whitespaces).joined() // Foundation 프레임워크 필요
```

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    }
`min(_:_:)` 메서드 이용하면 formattedAge 변수를 사용하지 않을 수도 있겠네요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    }
1. 입력할 때 `-`를 입력하지 않는 것처럼, 지울 때도 `-`를 직접 지우지 않도록 구성해볼 수 있을 것 같아요.
2. 첫번째 자리가 0인지 여부보다는 자리수에 따라 포매팅 방식을 결정해보면 좋을 것 같아요. 현재 구현으로는 02-123-1234와 같은 케이스를 만족할 수 없을 것 같아요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    }
가능하다면 save와 saveNewContact와 같이 수행하는 동작을 설명하기보다 사용자의 액션 또는 일어난 이벤트에 따라 메서드 이름을 짓는 것이 좋을 수 있습니다. 사용자가 save 버튼을 탭했을 때 사용자 활동을 기록하는 동작을 포함해야 한다면, 자신의 동작을 설명하는 메서드 이름보다 일어난 이벤트를 기준으로 이름 지어진 메서드가 이런 동작을 포함하기 좋기 때문입니다. 예를들어 save라면, `saveButtonTapped`, `onSaveTappped`, `didTapSaveButton`과 같은 이름이 될 수 있습니다. UI 또는 특정 이벤트에 따라 수행되는 로직이 있다면 고려해보시면 좋을 것 같네요.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    private static let title = "새 연락처"
타입 프로퍼티가 프라이빗 인스턴스 메서드들 사이에 있으니 조금 어색하네요. 요소들의 정렬 기준을 세워보면 좋겠습니다.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +                }
작성 취소는 돌이킬 수 없는 데이터 제거 기능이므로 Human Interface Guidelines의 권장에 따라 destructive style을 적용하는 것이 좋을 것 같습니다.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Routing/Coordinator.swift
> +}
코디네이터 패턴을 적용해보시니 어떠셨나요? 장단점과 어떤 경우에 사용하면 좋을지를 정리해보시면 좋겠습니다.

2024-01-16 19:35 UTC, ryan-son commented on ContactManager/ContactManager/Routing/ListContactCoordinator.swift
> +    }
네, 괜찮습니다. 코디네이터 타입과 코디네이터에 연관된 타입들을 묶어서 패키지로 분리해도 알지 못하는 타입이 없기 때문입니다. 필요한 의존성이 상위 수준에서 공유되거나 컨트롤될 필요가 있다면 `ContactRepository` 케이스처럼 주입 받아 사용하시면 됩니다.

2024-01-17 06:31 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContact.swift
> +}
오 그렇군요...! 그렇다면 유지하도록 하겠습니다 ㅎㅎ

2024-01-17 06:36 UTC, hyeffie commented on ContactManager/ContactManager/Common/ContactValidationError.swift
> +}
이 부분과 더불어 InputView의 뷰 관련된 구현도, 나중에 여유가 되면 로직을 추가해서 구현해보고 싶은 마음에 제거를 보류했던 것 같습니다 😅 깨끗하게 제거해서 올려두도록 하겠습니다 :)

2024-01-17 07:05 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContactUseCase.swift
> +    }
> 진행하신 것처럼 하셔도 되고, 조금 더 타입에 역할을 부여하시고 싶으시다면 AddContact.Request 타입에 검증 기능을 나눠줘도 괜찮을 것 같네요. 그럼 메서드를 분리해서 따로 의미를 부여할만큼 이해하기 어려운 로직은 아닐 것 같아요.

Request에 계산 속성을 구현해서 다음처럼 활용해 보았는데, 제대로 이해한 게 맞을까요? 
```swift
enum AddContact {
    struct Request {
        let name: String
        let age: String
        let phoneNumber: String
        
        var isEmpty: Bool {
            return name.isEmpty && age.isEmpty && phoneNumber.isEmpty
        }
    }
}

struct AddContactUseCase {
    ...
    func confirmCancel(request: AddContact.Request) {
        do {
            guard request.isEmpty else { throw AddContactError.someFieldIsFilled }
            presenter?.presentCancelConfirmation(result: .success(()))
        } catch {
            presenter?.presentCancelConfirmation(result: .failure(error))
        }
    }
}
```

말씀해주신 것처럼 valid한 상태를 기준으로 구현하게 되면 현재 구현에서 구현을 모두 반전시켜야 하는 비용이 있어서 cancel 케이스를 위한 속성으로 isEmpty를 만들었습니다! 확인되면 머지하겠습니다. [구현 브랜치](https://github.com/hyeffie/ios-contact-manager-ui/tree/feedback/step2-cancel)

2024-01-17 07:06 UTC, hyeffie commented on ContactManager/ContactManager/Domain/AddContact/AddContactUseCase.swift
> +    }
> 마찬가지로 ContactFactory에서 검증할 때도 Contact 타입의 각 프로퍼티를 커스텀 프로퍼티로 만들어 검증 조건을 나누어 줄 수 있을 것 같습니다.

이 부분은 제가 잘 이해하지 못 한 것 같은데요.. 🥲 검증 조건으로 valid한 상태인지를 검증하는 로직을 Request 타입으로 옮기는 방향을 제안하신 걸까요?

2024-01-17 07:20 UTC, hyeffie commented on ContactManager/ContactManager/Common/Formatter.swift
> +typealias InputFormatter = (String) -> String
간단하게 구현만 해봤습니다! 일단 view controller 코드가 깔끔해지는 건 확실한 것 같네요 ㅎㅎ [구현 브랜치](https://github.com/hyeffie/ios-contact-manager-ui/tree/feedback/step2-formatter)

2024-01-17 07:27 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +    }()
고민했던 이유는 각각 입력 필드만의 독립적인 영역을 갖기에는 controller 가 적절하지 않을까 라는 생각에서 였습니다. 그렇지만 UIViewController를 서브클래싱 하기에는 제가 생각하는 역할과는 다르다고 판단해서 결과적으로 UIView를 선택하게 된 것 같습니다.

2024-01-17 07:29 UTC, hyeffie commented on ContactManager/ContactManager/Domain/Model/ContactList.swift
> +        self.contacts.insert(newContact, at: 0)
앗 정렬 기능에 대해서는 고민해보지 않았어요....! 목록 상에 추가된 아이템을 바로 보여주기 위해서 첫번째 요소로 insert 하는 방향을 골랐던 것 같습니다 😅

2024-01-17 07:39 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    }
감탄하는 이모지가 필요합니다.. 로직을 이렇게까지 비용 측면에서 고민해 본 적이 없었어요..

2024-01-17 07:46 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/AddContact/ViewController/AddContactViewController.swift
> +    }
이 부분 항상 고민됐던 부분인데 반영해보겠습니다 :)

2024-01-17 07:57 UTC, ujhong7 commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
> +        guard let url = targetBundle.url(
주입 받은 인스턴스를 사용했습니다. [관련코멘트] https://github.com/tasty-code/ios-contact-manager-ui/pull/64#discussion_r1448179720

2024-01-17 07:57 UTC, ujhong7 commented on ContactManager/ContactManager/App/SceneDelegate.swift
> +    var coordinator: AppCoordinator?
앱의 네비게이션 흐름을 담당하므로, 해당 코디네이터의 참조가 없으면 네비게이션 흐름을 정상적으로 관리할 수 없게 됩니다. 새로운 화면으로의 전환, 화면 스택의 관리 등이 올바르게 이루어지지 않을 것이고 scene(_:willConnectTo:options:) 메서드에서 새로운 AppCoordinator를 생성하고 시작하는데, 이 부분이 실행되지 않거나 오류가 발생한다면 앱의 초기화에 문제가 생길 수 있습니다.

2024-01-17 07:57 UTC, ujhong7 commented on ContactManager/ContactManager/Data/BundleResource/BundleResourceManager.swift
>          ) else {
프로퍼티로 두는 경우 Bundle.main은 앱의 기본 번들을 나타내므로 여러 곳에서 쉽게 참조할 수 있고 앱이 실행되는 동안 변하지 않습니다. 하지만 특정 번들에 대한 다른 작업을 수행할 때 코드 수정이 필요합니다.
매개변수로 받는 경우 특정 상황에 다른 번들이 필요한 경우 해당 상황에 따라 동적으로 변경할 수 있고 특정 클래스나 모듈에서 의존성을 주입하고자 할 때 유용합니다. 하지만 코드가 길어질 수 있습니다.
따라서 코드의 복잡성을 줄이고 앱의 실행 중에 변경되지 않는 값이기 때문에 프로퍼티로 두는 것이 더 좋은것 같습니다.

2024-01-17 07:57 UTC, ujhong7 commented on ContactManager/ContactManager/Routing/Coordinator.swift
> +}
의존성 분리를 통해 단일 책임을 갖을 수 있다는 장점이 있었고 코드의 양이 많아지면서 복잡해질 수 있고 비용이 많이 든다는 단점이 있었습니다.

2024-01-17 08:08 UTC, hyeffie commented on ContactManager/ContactManager/Data/ContactRepository.swift
>      }
에러는 repository에서 발생하고 중복 값에 의해 중복 에러가 날테니까 처리는 사용자가 볼 수 있는 레벨까지 내려와야 할 것 같아요.

2024-01-17 08:09 UTC, hyeffie commented on ContactManager/ContactManager/Presentation/AddContact/View/InputView.swift
> +        guard string.isEmpty == false else { return true } // 지울 때
지우겠습니다 😇

2024-01-20 12:13 UTC, merged