연락처관리 앱 [STEP2] Hoi, Harry
tasty-code/ios-contact-manager-ui pull request #77
Opened 2024-01-16 08:08 UTC by happykwon

@songda515

안녕하세요, 다나
Hoi(@happykwon), Harry(@hemil0102)입니다!
연락처관리 앱 STEP2 PR입니다.
바쁘신 와중에 리뷰를 해주셔서 감사합니다. ☺️

## 🔍 What is this PR?

STEP 2 기능 구현

- STEP 2-1 두번째 ViewController Modal 구현
- STEP 2-2 ViewController간 데이터 이동 및 TableView에 적용
- STEP 2-3 textField별 유효성 검증

## 🗂️ Project Directory

```swift
├── README.md
└── ios-contact-manager-ui
    ├── Controller
    │   ├── AddContactViewController.swift
    │   ├── AppDelegate.swift
    │   ├── ContactListViewController.swift
    │   ├── SceneDelegate.swift
    │   └── mockJson.json
    ├── Enum
    │   ├── JsonParsingError.swift
    │   └── TextFieldError.swift
    ├── Extension
    │   ├── PhoneNumberFormatter.swift
    │   └── UIViewController + Extension.swift
    ├── Model
    │   ├── Contact.swift
    │   └── JsonDecoder.swift
    ├── View
    │   ├── Assets.xcassets
    │   │   ├── AccentColor.colorset
    │   │   │   └── Contents.json
    │   │   ├── AppIcon.appiconset
    │   │   │   └── Contents.json
    │   │   └── Contents.json
    │   └── Base.lproj
    │       ├── LaunchScreen.storyboard
    │       └── Main.storyboard
    ├── ios-contact-manager-ui
    │   └── Info.plist
    └── ios-contact-manager-ui.xcodeproj
        ├── project.pbxproj
        ├── project.xcworkspace
        │   ├── contents.xcworkspacedata
        │   ├── xcshareddata
        │   │   ├── IDEWorkspaceChecks.plist
        │   │   └── swiftpm
        │   │       └── configuration
        │   └── xcuserdata
        │       └── kwontaeho.xcuserdatad
        │           └── UserInterfaceState.xcuserstate
        └── xcuserdata
            └── kwontaeho.xcuserdatad
                └── xcschemes
                    └── xcschememanagement.plist
```

## 📝 PR Point

### 1. Modal 구현

- UINavigationController()를 통해서 Modal 화면을 present()로 생성
- 데이터 전달 델리게이트 패턴 SendDataDelegate 프로토콜 구현

### 2. textField 구현

- 키보드 타입 지정
    - 이름 .emailAddress
    - 나이 .numberPad
    - 전화번호 .phonePad
- 모든 필드 공백 입력시 자동 제거 구현
    - removeEmptySpaceCharacter() 메서드를 통해서 데이터를 저장할 때 제거
- 번호별 연락처 입력 textField “-” 기호 자동 생성 구현
    
    String 타입에 extension 메서드를 통해서 전화번호 Format 변경을 구현
    
    이후 UITextFieldDelegate의 shouldChangeCharactersIn 메서드를 통해서 실시간으로 입력 값이 입력될 때 마다 전화번호의 Format을 업데이트 해줍니다. 
    
    ```swift
    extension String {
        
        func extractNumbersFromStrings() -> String {
            return self.components(separatedBy: CharacterSet.decimalDigits.inverted).joined()
        }
        
        func formatPhoneNumber() -> String {
            let phoneNumberText = self.extractNumbersFromStrings()
            var formattedText = phoneNumberText
            let symbol:Character = "-"
            
            guard phoneNumberText.isEmpty == false else {
                return ""
            }
            
            if phoneNumberText.hasPrefix("02") || phoneNumberText.hasPrefix("0") == false {
                switch phoneNumberText.count {
                case 3...5:
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 2))
                case 6...9:
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 2))
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 6))
                case 10:
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 2))
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 7))
                default:
                    break
                }
            } else {
                switch phoneNumberText.count {
                case 4...6:
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 3))
                case 7...10:
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 3))
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 7))
                case 11:
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 3))
                    formattedText.insert(symbol, at: formattedText.index(formattedText.startIndex, offsetBy: 8))
                default:
                    break
                }
            }
            return formattedText
        }
    }
    ```
    
- 유효성 검사 구현
    - 이름
    공백만 아니라면 유효성 검증을 통과하게 구현했습니다.
    
    ```swift
    guard let name = removeEmptySpaceCharacter(nameTextField), name.isEmpty == false else { return presentNameAlert() }
    ```
    
    - **나이**
    function을 통해 주어진 조건에 맞지 않는다면 presentAgeAlert() 호출하도록 코드를 구현했습니다.
    
    ```swift
    //saveButton부분
    guard let age = removeEmptySpaceCharacter(ageTextField), age.isEmpty == false else { return presentAgeAlert() }
    guard checkAgeTextField(age: age) else { return  presentAgeAlert() }
    
    //나이 textfield 유효성 검증 코드
    private func checkAgeTextField(age: String) -> Bool {
            guard let ageNumber = Int(age), 0 < ageNumber, ageNumber <= 999 else {
                return false
            }
            return true
        }
    
    //유효하지 않은 값이라면 Alert호출
    private func presentAgeAlert() {
            presentAlert(title: "\(TextFieldError.ageTextFieldError.ErrorMessage)", message: "", confirmTitle: "확인")
        }
    ```
    
    - 전화번호
    
    ```swift
    //saveButton부분
    guard let phoneNumber = removeEmptySpaceCharacter(phoneNumberTextField), phoneNumber.isEmpty == false else { return presentPhoneNumberAlert() }
    guard checkPhoneNumberTextField(for: phoneNumber) else { return presentPhoneNumberAlert() }
    
    //전화번호 textfield 유효성 검증 코드
    private func checkPhoneNumberTextField(for phoneNumber: String) -> Bool {
            let onlyNumber = phoneNumber.extractNumbersFromStrings()
            let regexPattern = "^[0-9]+-[0-9]+-[0-9]+$"
            
            guard checkDigitsOver(number: 9, for: onlyNumber) else {
                print("\(TextFieldError.phoneNumberTextFieldError.ErrorMessage)")
                presentPhoneNumberAlert()
                return false
            }
            
            do {
                let regex = try NSRegularExpression(pattern: regexPattern)
                guard regex.firstMatch(in: phoneNumber, options: [], range: NSRange(location: 0, length: phoneNumber.count)) != nil else {
                    print("\(TextFieldError.phoneNumberTextFieldError.ErrorMessage)")
                    return false
                }
                return true
            } catch {
                print("\(TextFieldError.phoneNumberTextFieldError.ErrorMessage)")
                return false
            }
        }
        
        private func checkDigitsOver(number: Int, for phoneNumber: String) -> Bool {
            if phoneNumber.count < number {
                return false
            } else {
                return true
            }
        }
    ```
    

### 4. STEP1 검증관련 UI 및 코드 일부 삭제

- 차기 STEP3 구현을 위해 일부 삭제, 수정 코드를 보존하였고 실제 UI 구현은 아직 되지 않았습니다. 주석된 코드는 이와 관련된 것이 있으므로 삭제될 예정입니다.

## 📸 Screenshot

구현 내용 | 구동 영상1(성공) | 구동 영상2(실패)
-- | -- | -- 
구동화면 |  ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-16 at 16 29 29](https://github.com/tasty-code/ios-contact-manager-ui/assets/149054154/32f7c1ce-9b04-4f58-b6f3-ef8121ce23c7) | ![Simulator Screen Recording - iPhone 15 Pro - 2024-01-16 at 16 29 57](https://github.com/tasty-code/ios-contact-manager-ui/assets/149054154/344468c5-5258-46e9-8d74-c997b5aa3f61) |

## **+** 질문 및 고민한 부분

## 고민한 부분

### 1. 리팩토링

- !가 들어가야 하는 부분을 최대한 줄이려고 노력했습니다. 특히 아래와 같은 경우 이중부정? 같은 코드가 되어 버려서 처음 보는 사람이 혼란을 느낄 수 있는 여지가 있다고 생각했습니다.

```swift

guard let name = removeEmptySpaceCharacter(nameTextField), name.isEmpty == false else { return presentNameAlert() }

guard let name = removeEmptySpaceCharacter(nameTextField), !name.isEmpty else { return presentNameAlert() }
 [...]

2024-01-16 16:59 UTC, songda515 requested changes
STEP2 고민 많이 해주신것 같네요! 고생많으셨어요.
고민했던 부분과 질문들에 대해서 개별적으로 코멘트 남겼습니다 🙇‍♀️

- 추가로, UML 작성이 이번 스텝에서 필요한 과정으로 알고 있는데 확인부탁드립니다!

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +}
오!! 델리게이터 패턴을 이용하셨군요 👏
질문1의 답변이긴한데, 델리게이터 역할을 한다면 프로토콜은 `~~Delegate` 정도로 네이밍하는게 일반적인것 같아요. 
여기서는 SendData 보다는 좀더 수행하는 메소드와 관련있는 이름으로 지어주면 좋을것 같네요.
델리게이터가 많아지더라도 특정 역할에 맞게 이름을 지어주면 큰 문제는 없어보여요.

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +        guard let name = removeEmptySpaceCharacter(nameTextField), name.isEmpty == false else { return presentNameAlert() }
고민1의 답변인데요~!
`!` 를 쓰지 않는 이유가 제가 이해하기로는 강제옵셔널을 하지 않기 위해서이지 않을까 싶은데요! 🤔 
`!name.isEmpty` 같은 부정문의 `!` 는 사용해도 되지 않을까 싶네요..! 
요건 저도 잘못 이해하고 있는걸수도 있어서, 한번 캠프에서 질문드려보면 좋을것 같습니다!

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Model/Contact.swift
> +    var age: String
나이는 왜 int 에서 string 으로 변경된건가요? 👀

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Model/JsonDecoder.swift
> +            throw JsonParsingError.encodingError }
에러를 세부적으로 꼼꼼하게 처리해주셨네요.. 🫢 :+1:

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Enum/JsonParsingError.swift
> +    var ErrorMessage: String {
질문 5. localizedDescription 답변입니다~!
고민해주신대로 제가 생각했을때에도 현재 시점에는 `LocalizedError` 을 사용하거나, 따로 변수를 설정하거나 비슷할 것 같구요.
`LocalizedError` 는 다국어앱을 지원하는 경우 `NSLocalizedString` 를 활용한다면 더욱 유용한것으로 보이구요. 🤔 
현재로서는 프로토콜이 채택한 errorDescription 변수명을 활용한다는 규칙적인 장점 정도 있어보이네요!~
- 변수명은 카멜케이스로 써주시면 좋을것 같습니다!

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            print("\(JsonParsingError.fileLoadError.ErrorMessage)")
질문6 관련해서 추가 질문인데요, 
해당 catch 블럭 내에서 `JsonDecoder.loadData()` 메소드에서 throws 된 에러가 전달되지 않는게 문제인걸까요? 👀

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Extension/PhoneNumberFormatter.swift
> +        if phoneNumberText.hasPrefix("02") || phoneNumberText.hasPrefix("0") == false {
질문 2 답변입니다. 
입력을 해야할때마다 포맷을 적용해야하는거라면, 글자수에 따른 어느정도의 하드코딩이 불가피할것같긴 하네요 😅

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +            return false
질문3 답변입니다~!
여기서 true 로 설정한다면, 이미 `textField.text` 에 포맷된 문자열이 들어간 후에 추가적으로 `string` 이 뒤에 입력된다고 보시면될것 같아요.
- 디버깅을 해보시면 `string` 에는 한 문자열씩 들어오는것을 확인할 수 있습니다. 
- 여기서 반환값을 `true` 로 설정한다는것은 `textField.text = formattedPhoneNumber` 를 적용하겠다는 의미가 아닌, `string` 을 `textField.text` 에 추가한다는 의미가 됩니다!


문서는 이미 확인해보셨겠지만, 인자로 전달된 range 와 string 이 어떤 값인지 한번 확인해보시는걸 추천드릴게요 🙇‍♀️
> true if the specified text range should be replaced
https://developer.apple.com/documentation/uikit/uitextfielddelegate/1619599-textfield

2024-01-16 16:59 UTC, songda515 commented on ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        self.present(navigationViewController, animated: true)
4번 질문 답변입니다.
UINavigationController 의 하위로 설정하는것과 delegate 가 연결되는것은 연관이 없을것 같아요. 
Cancel, Save 버튼이 안나올수는 있을 것 같은데요. 혹시 이부분 때문에 그렇게 생각하신걸까요?

스토리보드에서의 화면 이동에 대해서는 이 문서를 확인해보면 좋을것 같아요.
코드에 작성해주신것처럼 present 메소드를 써도 무방합니다.
https://developer.apple.com/documentation/uikit/resource_management/customizing_the_behavior_of_segue-based_presentations

2024-01-17 06:07 UTC, happykwon commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +}
485af7b06041c54f0c93c8280f7f95993050807d
변경 완료했습니다 :)

2024-01-17 06:14 UTC, happykwon commented on ios-contact-manager-ui/Extension/PhoneNumberFormatter.swift
> +        if phoneNumberText.hasPrefix("02") || phoneNumberText.hasPrefix("0") == false {
답변 감사합니다 👍

2024-01-17 06:28 UTC, hemil0102 commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +        guard let name = removeEmptySpaceCharacter(nameTextField), name.isEmpty == false else { return presentNameAlert() }
아하, 지난 리뷰에서 !를 사용하는 것이 개발자마다 선호하는 사람이 있고 아닌 사람이 있다고 하여서, 질문을 드렸습니다. 

지난 리뷰에서는 부정의 부정 같은 상황에서 2번 읽기에 번거로우니 상황에 따라서 !을 자제하라고 하였는데, 
isEmpty도 어찌보면 값이 없다라는 부정의 의미와 !가 붙어서 부정의 부정 같은 상황이 되어서 문의했습니다. 
그런데 저번 리뷰에서도 개인의 취향이라 강제적인 것은 아니어서 답은 없는 것 같아요! 😆 
저는 !와 i 기호가 조금 헷갈려서 가급적 == 형식으로 풀어쓰려고 하곤 있어요.

2024-01-17 06:32 UTC, hemil0102 commented on ios-contact-manager-ui/Model/Contact.swift
> +    var age: String
해당 부분 텍스트 필드의 입력이 string 을 옵셔널로 받아오는데, 나이가 숫자이긴 하지만 입력된 값이 문자라면 문자적인 접근으로 처리해서 문자로 저장해주는게 형변환을 해주지 않아도 되어서 편하지 않을까? 란 접근 방식으로 변경되었습니다. 

다만, 데이터 형태가 프로퍼티의 원래 사용 의도와 같아야 한다면 Int로 해주어야할 것 같은데, 어떤 것을 권장하시는지 궁금합니다! 만약에 Int를 선호(?) 아니면 가이드 자체가 데이터 원래 의도와 맞춰야 한다면 바꿔야할 것 같습니다.

2024-01-17 06:33 UTC, hemil0102 commented on ios-contact-manager-ui/Model/JsonDecoder.swift
> +            throw JsonParsingError.encodingError }
감사합니다. 😁 다른 팀의 코드를 보면 Result Type도 사용하고 있는 것 같은데 저희는 우선 enum을 활용하는 것을 잘 연습하고 다음 단계로 넘어가고 싶어서, enum으로 처리해주었습니다.

2024-01-17 06:38 UTC, hemil0102 commented on ios-contact-manager-ui/Enum/JsonParsingError.swift
> +    var ErrorMessage: String {
답변 감사합니다~! 
실수로 대문자가 들어갔는데, 말씀해주신대로 수정하였습니다. 👍
4189396259f3b675b04ffe6481064f2ea4d2af37

2024-01-17 06:42 UTC, hemil0102 commented on ios-contact-manager-ui/Extension/PhoneNumberFormatter.swift
> +        if phoneNumberText.hasPrefix("02") || phoneNumberText.hasPrefix("0") == false {
감사합니다~!

2024-01-17 06:53 UTC, hemil0102 commented on ios-contact-manager-ui/Controller/ContactListViewController.swift
> +            print("\(JsonParsingError.fileLoadError.ErrorMessage)")
어... 어제 확인할 때는 상위 에러만 호출되었는데, 오늘은 하위 에러도 같이 호출되네요. 이 부분은 해결되었습니다.

2024-01-17 07:07 UTC, hemil0102 commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +            return false
아하 답변 감사합니다. 덕분에 이해가 더 명료하게 되었어요. 주말에 저쪽을 좀 굴려봤는데 백키를 누르면 range에 length가 추가되고, 문자가 2개씩 삭제되거나 3개씩 삭제되는 경우가 있어서, 로직이 잘 와닿지 않아서 하드코딩(?) 방식으로 포맷을 맞춰줬습니다. 

그 이전에는 실시간으로 -을 추가하고 삭제하는 것을 구현했는데 잘 되지 않았습니다.  예를 들어 textField.text = text.append("-") 하고 당시에는 return에 대한 이해도가 낮아서 글자가 계속 2개씩 추가되 3개씩 삭제되고 하여서 @.@; 이번에 말씀해주신 답변 들으니 조금 명료해졌는데, 추가로 더 트라이해볼게요~ (다만 요번 프로젝트 마감 기한이 얼마 없어서! 다른 작업 이후에 추가로 더 해보겠습니다. )

2024-01-17 07:20 UTC, hemil0102 commented on ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        self.present(navigationViewController, animated: true)
아, 이건 상황이 조금 복잡해서 설명이 잘 될지 모르겠는데... 
현재는 아래 코드와 같이 네비게이션 컨트롤러를 구성해주어, 모달이 네비에 포함되어서 present되고 있습니다. 

`let navigationViewController = UINavigationController(rootViewController: nextViewController)`

그리고 저희는 델리게이트를 네비가 아닌 모달 컨트롤러 안에 구현을 해주었어요. 
이 경우에는 present로 네비를 띄우면 네비가 우리가 지정한 identifier의 모달뷰와 연결되어서 뜨기때문에... 

`nextViewController.delegate = self`
코드를 통해서 연결이 됩니다. 그래서 현재 코드는 문제가 없습니다. 

다만 저 단계 이전에는 아래 코드로 작성을 했었는데요. 

```swift
guard let naviViewController = self.storyboard?.instantiateViewController(withIdentifier: "navi") else { return }
guard let modalViewController = self.storyboard?.instantiateViewController(withIdentifier: AddContactViewController.className) as? AddContactViewController else { return }

modalViewController.delegate = self
navigationViewController.modalPresentationStyle = .automatic
self.present(navigationViewController, animated: true)```

위 경우에서 네비만 present만 띄워서 그런지 delegate 형성이 되질 않았어요. 
instantiateViewController로 뷰를 만들어주면 뷰 자체는 형성되었으니 delegate가 형성이 되었을꺼라 기대했는데,
navi와 modal 연결이 되지 않아서 형성이 안되어서 navi로 띄워준 창에서의 모달이 실제 저 코드의 모달이 아니었던 것인지, 

저 상황에서 delegate가 형성되지 않은 것이 왜인지가 궁금했습니다!

2024-01-17 14:12 UTC, songda515 commented on ios-contact-manager-ui/Controller/AddContactViewController.swift
> +        guard let name = removeEmptySpaceCharacter(nameTextField), name.isEmpty == false else { return presentNameAlert() }
아하 😯 이전 리뷰어분의 의견이었군요~! 
네네 이부분은 취향에 맞게 작성하시고, 같이 코드를 작성하시는 분이랑 맞추시는게 가장 좋아요 😄👏

2024-01-17 14:22 UTC, songda515 commented on ios-contact-manager-ui/Model/Contact.swift
> +    var age: String
지금은 텍스트 입력을 받아서 처리하기때문에 String 이 더 편하게 느껴지실 수 있을것 같아요.
(지금 기능 명세서엔 없지만) 나이에 따라 정렬같은 기능이 필요하다면 Int 형태일때 더 편할 수 있겠죠! 
프로젝트 명세에 맞춰 적절하게 해주시면 됩니다 🙇‍♀️

2024-01-17 14:23 UTC, songda515 commented on ios-contact-manager-ui/Model/JsonDecoder.swift
> +            throw JsonParsingError.encodingError }
네~! Result Type 도 다음기회에 공부해보시면 좋겠네요! 🙌

2024-01-17 14:55 UTC, songda515 commented on ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        self.present(navigationViewController, animated: true)
작성해주신 이전 단계 코드에서는 navigationVC 와 modalVC 의 관계가 형성되지 않아서, 
delegate 가 형성되지 않았다 보다는 `modalVC 가 present 되지 않았다.` 로 보입니다 
(안됐던 케이스에 대해 코드를 공유해주시니 이해하기 좋네요  :+1:)
- 그래서 PR 에 올려주신 코드에서는 navi 와 modal 이 연결되어서 present 도 잘 되고, delegate 도 연결이 잘 되는게 맞습니다.

해결은 잘 해주셨는데요. 제가 답변드렸던 것중에 `UINavigationController 의 하위로 설정하는것과 delegate 가 연결되는것은 별개라는점`이 잘 이해가 되시면 좋겠네요~! 😅🙏 

- 아래 코드를 띄우면 nextVC 는 잘 뜨고 delegate 도 잘 설정되어있는데 naviagtionController 에 포함되지 않아, cancel, save 버튼은 뜨지 않겠죠?
- 여기서 delegate 가 잘 설정되었는지 확인하시고싶다면 `delegate` 객체를 디버깅포인트로 찍어보거나, navigationItem 외에 다른 버튼을 추가해서 동작수행하도록 해보시면 될거에요.

```swift
guard let nextViewController = self.storyboard?.instantiateViewController(withIdentifier: AddContactViewController.className) as? AddContactViewController else { return }
nextViewController.delegate = self
nextViewController.modalPresentationStyle = .automatic
self.present(nextViewController, animated: true)
```

`navigationController` 를 사용해보면서 기본 사용법은 조금 익숙해지신것 같지만, 케이스별로 공부해보시면 좋을것 같아요!
AddContactViewController 의 cancel, save 버튼을 설정해주신 `navigationItem` 
그리고 `present`, `push` 에 대해서도 학습해보시면 이해가 더 잘 되실거에요 🤗

2024-01-17 14:57 UTC, songda515 approved these changes
코멘트 꼼꼼히 확인해주셔서 감사합니다~! 😊
STEP2 는 머지하도록 할게요. STEP3 도 화이팅하세요! 🙌

2024-01-17 14:57 UTC, merged