연락처 관리 앱 [STEP 2] 폴, 세제
tasty-code/ios-contact-manager-ui pull request #78
Opened 2024-01-16 08:29 UTC by suojae3

# Tasty Code

**리뷰어:** <br/>
@cherrishRed

**버드:** <br/>
@earths-voluble
@suojae3

안녕하세요 Red!
두번째 PR 잘부탁드립니다 ☺️

---

<br/>

## 프로젝트 소개

### 파일 구조

<pre>

ios-contact-manager-ui/
│ 
├── App/
│    ├── AppDelegate.swift
│    ├── SceneDelegate.swift
│    └── MainCoordinator.swift
│
├── View/
│    ├── HeaderView.xib
│    ├── HeaderView.swift
│    ├── PhoneBookTableViewCell.xib
│    └── PhoneBookTableViewCell.swift
│
├── ViewController/
│    ├── RegisterViewController.storyboard
│    ├── RegisterViewController.swift
│    ├── PhoneBookViewController.swift
│    └──ViewController+Extension.swift
│
└── Model/
     ├── PhoneBook.swift
     ├── PropertyWrapper.swift
     └── User.swift

</pre>

### 다이어그램

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/126137760/48b20227-8123-453f-9680-82e73199109c)

---

<br/>

## 고민한 부분

### 객체간의 의존성을 최대한 낮추어보기

####  뷰전환 관리하는 코디네이터 객체 생성

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/126137760/d567f788-f24f-48c4-9b65-c07a7bf8f394)

기존 코드에서는 비교적 사이즈가 큰 객체인 뷰컨트롤러간 뷰전환 때문에 의존성이 있는 상태였습니다. 
이를 끊어주기위해 코디네이터 객체를 만들어 각 뷰컨 객체 생성 및 델리게이트 패턴을 이용해서 뷰전환을 구현했습니다.

#

### 단방향으로 데이터를 수정하고 델리게이트 패턴을 통해 업데이트 하기

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/126137760/d0168093-3cda-4b34-8090-3d4a4f51e526)

주어진 문제는 레지스터 뷰컨에서 정보를 입력하면 메인뷰컨의 테이블뷰를 통해 바뀐 정보를 반영해야 했습니다.
두 뷰컨간의 델리게이트나 클로저로 연결하면 코디네이터를 쓴 의미가 없기 때문에 레지스터 뷰컨은 전화번호부를 추가하고 
전화번호부가 추가되면 이를 반영하기위해 reload tableview 이 호출되었어야 했습니다.

이를 해결하기 위한 로직으로 계산속성을 통해 새로운 값이 들어오면 콜백함수를 호출시켜 테이블뷰를 리로드 하는 방법을 사용했습니다

#

### categorizedContectInfo의 리팩토링
categorizedUserInfo라는 이름으로 바꾸면서 단순한 [User]구조로 개편했습니다. 리팩토링을 통해 User의 정보에 접근하고 셀을 구성하는 것이 쉬워졌습니다.

### 전화번호 포맷 검증
전화번호 포맷의 구현에 있어 정규식과 조건문 사이에서 고민했습니다. 한국 전화번호까지는 조건문과 간단한 정규식으로 구현이 가능했지만, 더 정교한 번호 검증 및 해외 전화번호까지 커버하는 함수를 구현하기 위해서는 정규식 사용이 불가피할 것 같아 정규식에 대해 알아보고 싶습니다.
### 새롭게 알게 된 점
extension의 활용 및 UIAlertController
이전 프로젝트에서는 UIAlertController를 싱글톤 클래스로 구현했는데, 이번 프로젝트를 진행하면서 UIViewController의 extension으로 구현하면 구현도 사용도 깔끔하다는 것을 느끼게 되었습니다.
이번 프로젝트를 통해 extension을 활용한 타입의 확장 및 코드 정리에 대해 많은 것을 배웠습니다.

#

<br/>

## 해결하지 못한 부분 

### 컨테이너의 강한 참조 문제 해결 실패

기존에 계획했던 것은 컨테이너 객체에서 의존성을 관리하고 코디네이터 객체에서 뷰컨을 사용할 때는 컨테이너에서 가져다 쓰려고 했지만 컨테이너에 등록했던 뷰컨들이 강한참조로 인해 메모리해제가 안되었습니다.

weak으로 참조해보려 했으나 이렇게 할시 등록되기도 전에 바로 메모리에서 해제되어 결국에는 컨테이너를 버리게 되었습니다.

2024-01-16 16:51 UTC, cherrishRed requested changes
폴 세제 너무 수고하셨습니다!
많은 고민을 하고 코드를 작성하신게 느껴졌습니다!

## ✨ 고민한 부분에 대한 답변 

### 객체간의 의존성을 최대한 낮추어보기 
Coordinator를 만드셔서 VC 간의 의존성을 낮추려고 하신 부분 좋았습니다!
사실 지금은 VC 가 2개 밖에 없고, 서로 관련이 없는 VC도 아니기 때문에 의존성이 있어도 괜찮다고 생각합니다.  그러나 미래를 보면, Coordinator를 만들어 관리 하면 참 좋지요!

### 단방향으로 데이터를 수정하고 델리게이트 패턴을 통해 업데이트 하기 
registerVC 가 phoneBook 정보를 가지고 있는데, 사실 registerVC에게 이 정보가 필요한가 싶습니다. 

의존성을 떨어트리고 싶다고 이야기 하신 것에 반해서, phoneBook 객체를 거의 모든 클래스가 가지고 있네요. 이 부분을 조금 고민해서 수정해 보셨으면 합니다.  
delegate 패턴을 적극 활용해 보세요.  delegate의 메서드의  파라미터로 정보를 넘길 수도 있습니다.   ### categorizedContectInfo의 리팩토링 User 라는 객체를 만드신 것은 정말 좋았습니다!

### 전화번호 포맷 검증
조건문과 정규식중에 꼭 하나를 선택하야 하는 것은 아닙니다.  조건문이 잘하는 부분이 있고, 정규식이 잘하는 부분이 있는 거니까요. 이부분은 다양한 시도를 해보셨으면 좋겠습니다. 

### 컨테이너의 강한 참조 문제 해결 실패 컨테이너가 결국 사라지게 되었군요.. 컨테이너 자체가 꼭 존재하지 않아도 괜찮으니, 지금은 어느 부분에 어떤 정보가 있어야 하는지, 어떤 뷰에 어떤 정보를 가지고 있어야 하는지를 생각해보시면, 나중에 컨테이너를 사용하게 될 때는 방법을 찾을 수 있을 것 같아요!  ### 패턴 
두분 코드를 보면서 생긴 궁금증인데요,
혹시 어떤 형태로 구조를 생각하고 계신가요? 일반적으로 사용하는 MVC또는 MVVM 같은 패턴을 사용하고 계신가요? 아니면 두분이 따로 생각하는 구조가 있으신 걸까요?

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/App/MainCoordinator.swift
> +}
`Coorninator` 오타가 있네요 😉

`Coordinator` 프로토콜안에 `goToRegisterViewController()` 메서드가 존재하는 것은 조금 어색한 것 같아요.
`Coordinator`라는 이름이 `RegisterCoordinator`가 되거나, `goToRegisterViewController()`가 사라져야 할 것 같네요.

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/App/MainCoordinator.swift
> +        registerViewController.modalPresentationStyle = .formSheet
formSheet 는 무슨 스타일 인가요?

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/PhoneBook.swift
> +}
protocol의 시작은 꼭 대문자로 해주세요!

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/RegisterViewController.swift
> +    }
`condition` 이라는 파라미터가 메서드를 호출하는 입장에서 어떤 정보를 넣어야 할지 네이밍이 모호한 것 같아요.
`condition` 을 두개의 파라미터로 나누더라도, 용도를 명확하게 드러내는 것을 좋을 것 같습니다.

그리고 ; 사용대신, 줄을 바꿔주세요!
```swift 
guard input.count >= condition.0 else {
    print("2글자 이상의 이름을 입력해 주세요.")
    return false
}
```

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/App/Container.swift
> +//}
불필요한 코드는 지우셔도 됩니다!

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/PhoneBook.swift
> +    var categorizedContactInfo: [User] = [
property wrapper 를 사용하셨군요!
비교적 최근에 나온 문법인데, 재밋게 활용하신 것 같습니다!
property wrapper를 사용하신 이유는 뭘까요?

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/ViewController+Extension.swift
> +}
alert 을 VC에 extension 으로 구현하신 부분 좋습니다!

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/RegisterViewController.swift
> +    }
이걸 외부에서 호출할 일이 없다면, private 이 필요할 것 같네요!

2024-01-16 16:51 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/PropertyWrapper.swift
파일이름이 propertyWrapper 인것 나중에 혼란을 일으킬 수 있을 것 같습니다.
마치 protocol 이나 class 가 파일이름인 것 같이요.

2024-01-17 01:10 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/PhoneBook.swift
> +    var categorizedContactInfo: [User] = [
최근 SwiftUI 신문물을 접하면서 `@State`, `@EnvironmentObject`가 굉장히 좋다고 느껴졌습니다!
유킷으로도 분명 구현할 수 있을거라 생각했고 스유에서 커맨드를 타고 들어가보니 property wrapper를 발견해서 사용해보았습니다.

이렇게 `property wrapper`를 통해 전화번호부 이외에 또다른 속성이 추가될 경우 @NotifyInfoChange를 통해 데이터 변화를 다른 객체에게 손쉽게 전달할 수 있다는 점에서 매력적으로 느껴졌습니다!

2024-01-18 08:36 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/App/MainCoordinator.swift
> +}
헉.. 오타.. 감사합니다

자식 코디네이터를 만들어 프로토콜-델리게이트 패턴을 통해 뷰 전환 구현 방향으로 수정했습니다!

2024-01-18 08:38 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/PropertyWrapper.swift
추가적으로 프로퍼티 랩퍼에 프로토콜 델리게이트 패턴을 추가하여 유저 데이터 전달을 구현해보았습니다!

이로써 메인뷰컨과 데이터 객체간의 의존성을 끊을 수 있었습니다!

2024-01-18 08:39 UTC, suojae3 commented
<img width="520" alt="image" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/126137760/7fbaf4bb-5219-4b1c-97fd-9b30e69a15af">

추가적으로 프로퍼티 랩퍼에 프로토콜 델리게이트 패턴을 추가하여 유저 데이터 전달을 구현해보았습니다!
이로써 메인뷰컨과 데이터 객체간의 의존성을 끊을 수 있었습니다!

2024-01-18 08:53 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/App/MainCoordinator.swift
> +        registerViewController.modalPresentationStyle = .formSheet
`formSheet` modalPresentationStyle이 기본값으로 설정된 스타일입니다. 
pageSheet 과 함께 정중앙에 관련 내용을 보여주는 스타일입니다

이때 아이폰 환경에서는 'formSheet' 과 'pageSheet'의 차이가 안나타나지만
 아이패드 환경에서는 아래 사진과 같은 차이를 보이게 됩니다.

![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/126137760/cc642d5a-691b-4403-93df-fc689667cd97)

2024-01-18 08:53 UTC, suojae3 commented on ios-contact-manager-ui/ios-contact-manager-ui/ViewController/RegisterViewController.swift
> +    }
감사합니다 :)

2024-01-18 11:04 UTC, cherrishRed approved these changes
세제 폴 수고하셨습니다!

코멘트 남긴 부분 수정하신 것 잘 보았습니다!

다른 부분에 대해서 댓글 남겨 놓았는데, 다음 PR 에서 수정하시면 될 것 같습니다!

그리고 다음 PR 에서는 어느 부분이 Model 이고 어느부분이 View 이고 어느 부분이 Controller 인지 표시해서 저에게 알려주세요!
PR문에 쓰셔도 되고, 코멘트로 남기셔도 됩니다 ☺️

수고하셨습니다! 화이팅 입니다!!

2024-01-18 11:04 UTC, cherrishRed commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/NotifyContactInfoChange.swift
> +}
`NotifyContactInfoChange` 라는 네이밍이 구조체가 가지기 적절한 네이밍은 아닌것 같습니다. 
그리고, propertyWrapper 의 적절한 사용도 아닌 것 같네요. 
마치 propertyWrapper 를 쓰기 위해 코드를 억지로 집어 넣은 느낌이 있습니다. 
특히 안에 들어가 있는 delegate 는 오히려 혼란인 것 같습니다. 

의존성 분리도 중요하지만, 가독성도 중요합니다. 
특히 이 부분은 phonBook 에 있어도 될 것 같은 코드 인데, 오히려 가독성이 안 좋아 진 것 같습니다. 

이부분에 대해서 어떻게 하면 가독성을 더 높일 수 있을지 생각해보셨으면 좋겠습니다!

2024-01-22 08:37 UTC, merged