연락처 관리 앱 [STEP 2] Jin, 이안
tasty-code/ios-contact-manager-ui pull request #79
Opened 2024-01-16 09:38 UTC by wlsdud-dev

리뷰어: @Mino777

버드: @wlsdud-dev, @ianK0909

마이노! 안녕하세요.

스텝2 PR을 드디어 보내게 되었네요.
생각보다 기능을 구현하는 데 시간이 오래 걸렸어요.
중간에 요구사항이 바뀌면서 더 힘들었던 것 같아요.
업데이트된 내용을 구현하려고 머리를 써봤는데 바뀐 요구사항에 맞추지 못했네요.못했네요.‍  😵‍💫

---

## UML
![image](https://github.com/tasty-code/ios-contact-manager-ui/assets/87616297/bb34a8ae-4af1-454b-9ade-e18232b002c6)

## 고민사항

### 1. 데이터 전달 방식
    
싱글톤, 델리게이트, 노티피케이션센터, 프로퍼티 전달, 클로저 전달 중에 어떤 방식을 써야 이번 프로젝트에 적절한 방식인지 공부하고 찾아봤지만, 어떤 게 좋은 방법인지 해답을 찾지 못했습니다.

마이노의 의견이 궁금합니다.

2024-01-17 07:00 UTC, Mino777 requested changes
안녕하세요!! Jin, 이안!

STEP 2 진행하시느라 정말 수고 많으셨습니다!!🥳

작성해주신 UML의 경우 Flow Chart에 가까운 것 같습니다!
그리고 선을 그리실 때 최대한 직각으로 깔끔하게 그려주시면 좋을 것 같네용
또 조건문 분기에 대한 표현이 없는 것 같아요! 분기를 표현해주는 레이블도 추가하시면 더 명확할 것 같습니다👍

---------------------------------------------------------------------------------------

## 코멘트

### 칭찬 드리고 싶은 점
- 순서도를 작성하신 점👏
- CustomTableViewCell을 사용해보신 점👏
- Delegate 패턴을 사용해보신 점👏

---------------------------------------------------------------------------------------

### 고민했던점
> 데이터 전달 방식

해당 고민에 대해선 우선 정답은 없습니다.
상황에 따라 각각 장단점이 존재하고, 모든 방식들을 이해한 뒤 주어진 상황에 따라 적절한 방식을 선택해야 합니다.

그리고 지금 이런 고민을 하는것은 정말 당연하고, 고민 하시는 것 자체가 정말 좋은 부분입니다.

제가 추천드리는건 우선 학습단계에서는 최대한 싱글톤, 노티피케이션을 통한 데이터 전달은 자제하는것이 좋습니다. 두 방식의 경우 객체지향 프로그래밍, 프로토콜 지향 프로그래밍에 대한 이해도를 높이는것에 적절하지 않은 패턴들입니다.
모든 방식에 대해 최소한의 이해를한 다음 최대한 delegate 패턴, 의존성 주입(프로퍼티, 메서드, 클로저 등등) 등을 통한 화면 간의 데이터 전달을 실제 프로젝트에 사용하시면서 익숙해지시고 왜 이런식으로 전달을 하는게 좀 더 좋은 방향일까에 초점을 맞춰서 계속해서 고민해보시는 시간을 가져보면 좋을 것 같아요. 고민하는 시간이 많으면 많을수록 그 고민들이 나중에 큰 자산이됩니다!

그리고 이런 고민들에 대한 질문을 하실 땐 어떤 고민을 했고, 어떤식으로 해결하려고 노력해봤는지, 자신이 이렇게 생각하는 이유 등을 써주시면 고민에 대한 방향을 잡아드리기 훨씬 쉽습니다.

결론은 이런 고민들에 대해서 스트레스 받지 마시고, 이런 고민을 할때마다 성장할 수 있는 타이밍이 왔다고 생각하시고 즐겁게 고민하시면 좋을 것 같습니다ㅎㅎ

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +}
Delegate 패턴을 사용하셨네요!

보통 Delegate 네이밍의 경우 ~Delegate 접미사를 붙여주는것이 명확합니다!
그리고 단순히 send라는 의미보단, 더 명확하게 추가라는 뜻이나 만약 나중에 더 확장될 예정이라면 수정이라는 뜻의 네이밍을 해주거나, 좀 더 포괄적으로 연락처 데이터 델리게이트 라는 네이밍도 좋아보입니다!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +class AddedContactViewController: UIViewController {
final 키워드를 쓰는 class가 있고, 안쓰는 class가 있네요?
의도적으로 하신걸까요?! 의도적이라면 어떤 이유가 있었을까요?!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +        let addedName = nameTextField.text
private을 사용한 메서드와 사용하지 않은 메서드가 있네요!

의도적으로 하신걸까요?! 그렇다면 이유가 무엇일까요?

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +        guard let name = addedName?.components(separatedBy: [" "]).joined(), String(name).count != 0 else {
components, joined 메서드에 대해 설명해주세요!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
에러처리 좋습니다👍

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +                ageText.allSatisfy({ $0.isNumber }),
allSatisfy 메서드에 대해 설명해주세요!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +                String(ageText).count <= 3,
동료 개발자가 3이라는 숫자를 봤을때 바로 알기 어려울 수 있을 것 같아요!

네임스페이스를 통해 매직넘버를 관리해보면 좋을 것 같습니다!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
fetch~ 메서드들에 유효성 검사 로직들이 점점 복잡해지네요!

세가지 메서드 모두 유효성 검사 로직들을 개별 메서드로 분리해볼까요?!

그리고 만약 시간이 되신다면 정규표현식에 대해서도 학습해보시면 좋을 것 같습니다!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    var delegate: SendContactData?
지금 같은 경우 Modal + 단방향 참조 케이스이기 때문에 메모리누수가 발생하지는 않겠지만,
delegate를 사용하는 경우 순환 참조가 발생하는 케이스가 많기 때문에 delegate를 선언할 땐 항상 weak 키워드로 정의하여 잠재적인 메모리 누수를 방지해주는게 좋습니다💪

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    func addDistinguished() {
네이밍이 조금 모호한 것 같아요! 최대한 간단한 단어로 네이밍하는것이 좋습니다.
연락처를 추가한다, 저장한다, 수정한다 등의 네이밍이 좋아보이네요!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
name, age, phoneNumber 초기화의 경우 Result 블록 안에서도 가능합니다!

```swift
       let isAdded = Result {
          let name = try fetchName()
          let age = try fetchAge()
          let phoneNumber = try fetchPhoneNumber()
          return (name, age, phoneNumber)
        }
        switch isAdded {
        case .success(let (name, age, phoneNumber)):
```

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
해당 메서드도 유효성 검사를 분리해볼 수 있겠네요!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ContactCustomCell.swift
> +class ContactCustomCell: UITableViewCell {
CustomCell을 사용해보셨군요!! 너무 좋습니다👍👍

CustomCell을 사용할 때 중요하게 생각해보시면 좋은 prepareForReuse() 메서드에 대해서 학습해보시면 좋을 것 같습니다!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
>  class ViewController: UIViewController {
그냥 ViewController 보단 좀 더 명확하게 prefix를 붙여서 ~ViewController 라고 네이밍 해주시는게 좋습니다!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +            }
지금처럼 DispatchQueue 객체의 클로저를 사용하는 경우 대부분 강한 참조를 해도 순환 참조가 되지 않기에 대부분의 경우 weak self를 사용하지 않아도 되긴 합니다.
하지만 보통의 클로저를 사용할 때 self를 참조해야된다면 꼭 weak self 를 통해 약한 참조를 하시는 습관을 들이시면 좋습니다!
해당 내용이 이해가 안가신다면, 순환참조, 클로저 캡처 등의 키워드로 학습해보시면 좋을 것 같습니다👍

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +    private let cellIdentifier = "ContactCustomCell"
명확한 변수명 좋습니다!👍

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
>      }
조금 더 MVC 패턴을 확실하게 써보고 싶으시다면, 해당 메서드와 같은 데이터를 디코딩하고 로드해주는 작업의 경우 Model 레이어에서 하는게 좋습니다.

만약 시간이 되신다면 ViewController가 최대한 UI의 역할만 할 수 있도록 해당 로직도 Model 레이어로 옮겨보시면 좋을 것 같습니다!👍

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +        }
assert, precondition, fatal error 이렇게 세개에 대해서 설명해주세요!

해당 메서드들은 디버깅을 위한 메서드라고 생각하기에 디버그 모드일때만 사용을 하는것이 좋습니다. 전 개인적으로 디버그 모드에서도 사용하진 않습니다. 어떤 경우에도 어플리케이션을 일부러 크래시나게 하는 코드는 절대 좋지 않습니다.

해당 부분도 알럿을 띄워주는 방향으로 바꿔보시면 좋을 것 같습니다~!

2024-01-17 07:00 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +
이 부분도 precondition 보단, 그냥 ContactCustomCell을 리턴해주는 것이 좋을 것 같습니다.

2024-01-17 07:38 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +class AddedContactViewController: UIViewController {
꼼꼼하게 확인 하지 못했습니다. 현재로서는 해당뷰컨을 상속 할 일이 없어 final 키워드를 붙여주는게 더 좋은 퍼포먼스를 보여줍니다.

2024-01-17 07:40 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +        let addedName = nameTextField.text
확인하지 못했습니다. private 을 하면 은닉화가 되어 안정성이 올라가고 final 키워드와 마찬가지로 성능면에서 이점이 있습니다.

2024-01-18 02:41 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +        guard let name = addedName?.components(separatedBy: [" "]).joined(), String(name).count != 0 else {
`components` 메서드는 `separatedBy` 매개변수 의 문자 값을 이용해 문자열에서의 문자값 기준으로 긴문자열을 문자열로 분리하고 매개변수로 입력한 문자값을 제거한 쪼개진 문자열을 배열을 반환하는 메서드입니다.
`joined` 메서드는 배열을 하나의 배열로 만들어 값을 반환하는 메서드입니다. ( `[String, String...]` → `String` )

2024-01-18 02:42 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +                ageText.allSatisfy({ $0.isNumber }),
배열의 값이 모두 조건에 맞는지에 따라 bool 값을 반환하는 메서드입니다.

2024-01-18 04:35 UTC, ianK0909 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +}
델리게이트 이름을  더 명확하게 addedContactDelegate 로 변경하였습니다.

2024-01-18 07:54 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +                String(ageText).count <= 3,
```swift
enum NumberNameSpace {
    static let ageDigitLimit = 3
    static let phoneNumberMin = 9
    static let hyphenRule = 2
}
```
열거형으로 네임스페이스를 만들어 줬습니다.

2024-01-18 07:54 UTC, ianK0909 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +
``` swift
guard let customCell: ContactCustomCell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as? ContactCustomCell else { return ContactCustomCell() }
```
리턴을 return ContactCustomCell() 바꿔주었습니다.
이해가 잘 안되는게 있어서요.  ContactCustomCell 타입캐스팅을 실패한 경우에는 ContactCustomCell() 생성해서 반환해주면 빈창만있는 ContactCustomCell 반환되는건가요??

2024-01-18 07:56 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    var delegate: SendContactData?
```swift
protocol addedContactDelegate: AnyObject {
     func addNewContact(name: String, age: Int, phoneNumber: String)
}

final class AddedContactViewController: UIViewController {
    
    weak var delegate: addedContactDelegate?
```
ARC에 대해 학습 했는데 실제 코드에 적용할때는 고려를 안할때가 많네요. 지적 감사합니다.

2024-01-18 07:58 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    func addDistinguished() {
유효성 검사를 하는 메서드기 때문에 `validateContant` 으로 네이밍을 변경했습니다.

2024-01-18 08:03 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
불필요하게 var를 쓰는것 같아 고민 되었던 부분인데 감사합니다.

2024-01-18 08:06 UTC, sskim99 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +        }
얼럿을 뛰어주는것으로 변경하였습니다.

assert - 특정 조건을 체크하고, 조건이 성립되지 않으면 메세지를 출력,강제종료(debug bulid시)
precondition -  특정 조건을 체크하고, 조건이 성립되지 않으면 강제종료,메시지 출력(실제 배포되는 앱, debug 둘다 가능)
fatal error - 출력하고, 조건 없이 항상 실행 종료

2024-01-18 08:06 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +            }
ARC에 대해 아직 부족한 부분이 많은것 같습니다. 좀 더 공부할 수 있는 기회가 되었습니다!

2024-01-18 08:07 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/ViewController.swift
>  class ViewController: UIViewController {
`ContactViewController` 로 좀 더 명확하게 바꿔 주었습니다.

2024-01-18 08:08 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/ContactCustomCell.swift
> +class ContactCustomCell: UITableViewCell {
CustomCell을 사용할 때 중요하게 생각해보시면 좋은 prepareForReuse() 메서드에 대해서 학습해보시면 좋을 것 같습니다!

`dequeueReusableCell` 메서드를 이용해 셀이 재사용 될 때, 재사용되는 셀의 attribute 설정이이 초기화가 되지 않아 `prepareForReuse()` 메서드를 이용해 셀을 초기화 설정을 해줍니다.

2024-01-18 08:21 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
[76325b4](https://github.com/tasty-code/ios-contact-manager-ui/pull/79/commits/76325b4a872e6f41b7493a7096c3b45e3431f88f) 스텝2 바뀐 명세서로 수정을 하였는데 구현을 하다보니 텍스트 필드 델리게이트와 addTaget을 둘다 사용하는 형태가 되었습니다.
사실 텍스트필드 델리게이트만 사용하여 구현하려 했는데 그럴 경우 `phoneNumberTextField.text = phoneNumber.formatConversionPhoneNumber()` 구문 때문에 반환값을 false로 줄 수 밖에 없어 `textField`에서는 입력받는 값을 정규식 해주고 addTaget에서는 하이픈을 넣어주는 기능으로 사용 했습니다.
델리게이트만 사용하려면 하이픈을 넣어주는 로직을 전부 바꾸는 방법밖에 없을까요?

2024-01-18 08:34 UTC, wlsdud-dev commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
```swift
private func validateContant() {
    let isAdded = Result {
        let name = try fetchName()
        let age = try fetchAge()
        let phoneNumber = try fetchPhoneNumber()
        return (name, age, phoneNumber)
    }
    switch isAdded {
    case .success(let (name, age, phoneNumber)):
        addConditionSucceed(name: name, age: age, phoneNumber: phoneNumber)
    case .failure(let error):
        guard let error: AddedContactError = error as? AddedContactError else { return }
        showAlert(title: "", message: error.errorMessage)
    }
}

private func addConditionSucceed(name: String, age: Int, phoneNumber: String) {
    delegate?.addNewContact(name: name, age: age, phoneNumber: phoneNumber)
    self.dismiss(animated: true)
}
```
성공했을때 처리 하는 부분도 있어 메서드가 두가지 기능을 한다고 판단하여 기능을 분리 했습니다.
마이노의 의도와 맞는지 궁금합니다.
그리고  `addConditionSucceed` 메서드명이 `addCondition`이 더 좋은지 궁금합니다.
혹시나 .success 뿐만 아니라 다른 메서드에서 호출이 일어날 가능성을 고려해 Succeed 접미사를 붙여줬지만
적절한 네이밍인지 의문이 듭니다.

2024-01-19 12:25 UTC, Mino777 approved these changes
Step 2 진행하시느라 고생 많으셨습니다!!

요구사항을 충족시키지 못하거나, 기능 구현에 시간이 너무 많이 드는 느낌이 드셔도 너무 조급해 하지 않으셨으면 좋겠습니다!

요구사항 충족에 집중하기 보단, 이번 프로젝트를 수행함에 있어 읽고 참고해야 하는 문서를 통한 학습 및 이번 프로젝트 수행시 제약사항을 지키는 부분을 가장 중요하게 생각 하시면서 프로젝트 진행하시면 좋을 것 같습니다😊

앞으로의 프로젝트들도 빠이팅입니다💪

2024-01-19 12:25 UTC, Mino777 commented on ContactManager/ContactManager/Etc/ExtensionString.swift
> +    func formatConversionPhoneNumber() -> String {
가독성이 너무 안좋은 것 같아요!

전화번호 유형에 대한 로직들과 하이픈을 넣어주는 로직도 각각의 메서드로 분리해볼 수 있을 것 같네요.

```swift
func formatConversionPhoneNumber() -> String {
        guard self.isEmpty == false else { return "" }

        let hyphen = "-"
        var formattedNumber = self

        if self.hasPrefix("02") {
            formattedNumber = 별도 메서드
        } else if self.starts(with: "15") || self.starts(with: "16") || self.starts(with: "17") || self.starts(with: "18") {
            formattedNumber = 별도 메서드
        } else { // 기타 번호
            formattedNumber = 별도 메서드
        }

        return formattedNumber
    }

```

이런 느낌으로 리팩토링 해보면 좋을 것 같네용

2024-01-19 12:25 UTC, Mino777 commented on ContactManager/ContactManager/NameSpace/AddedViewNameSpace.swift
> +}
네임스페이스 좋습니다~!

2024-01-19 12:27 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +        let addedName = nameTextField.text
private을 통해 은닉화를 한다고 해서 성능적으로 향상이 되진 않습니다!

2024-01-19 12:29 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
함께 사용한다고 해서 문제될 부분은 없습니다.
또 지금 같은 상황에선 addTarget, delegate를 같이 사용하는 것이 더 자연스러워 보입니다!
각각의 메서드가 역할이 나누어져 있기 때문에 지금같이 함께 사용하는게 가독성이나 유지보수성을 보았을때도 더 좋아보이네요👍

2024-01-19 12:38 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/AddedContactViewController.swift
> +    }
저의 의도는 validate 로직과 실제 수행 로직을 분리하면 좋겠다는 의도였습니다!
지금 메서드는 유효성 체크도하고, 실제 체크된 result값으로 수행까지 하고있기에 책임이 두가지네요!

메서드명의 경우 저라면 성공 여부에 대한 의미보단, 연락처를 추가한다는 본질적인 의미의 메서드명을 지을 것 같습니다.

2024-01-19 12:43 UTC, Mino777 commented on ContactManager/ContactManager/ViewController/ViewController.swift
> +
넵 셀의 컴포넌트 초기화 작업이 없다면, 빈창만 있는 셀이 반환됩니다.
prepareForReuse 메서드를 통해 컴포넌트들에 기본값을 넣어주거나, 오류임을 유저에게 알려줄 수 있는 형태의 값을 넣어주면 빈창만 있는 셀이 반환되진 않겠네요!

2024-01-21 05:08 UTC, merged