연락처 관리 앱 [Step3] 댄, Sidi
tasty-code/ios-contact-manager-ui pull request #83
Opened 2024-01-18 07:35 UTC by eensungkim

Step 3
멤버 : @eensungkim, @jus1234
리뷰어 : @keeplo

연락처 관리 앱 프로젝트의 마지막 Step입니다! 
정리하여 PR 드립니다. 감사합니다!

# 이번 스텝을 통해서 배운 점
- OOP 와 디미터 법칙
- 철저한 은닉화 및 캡슐화
- 검색 바의 활용
- 프로토콜 및 typealias 의 활용
- delegate 와 dataSource 의 활용
- 의존성 주입 학습
- Dynamic Type 적용

# 구성
## Model
### Contact.swift
- Contact 구조체
    - property : 이름, 전화번호, 나이

### Contacts.swift
- Contacts 모델 클래스
    - property: 기초데이터, 정렬배열
    - method: 정렬된 연락처 반환, Contact 정렬, 필터링, 배열, 추가, 삭제, 변경, JSON 파일 로드
### ContactsProtocol.swift
- delegation 을 위한 프로토콜

## View
### ContactsTableView.swift
- 연락처 테이블 뷰 클래스
### ContactsAdditionModalView.swift
- 연락처 추가 모달 화면 뷰 클래스
### ContactsNavigationBar.swift
- 연락처 리스트 화면 내비게이션 바 뷰 클래스
### ContactsTableViewCell.swift
- 연락처 테이블 뷰 셀 커스텀 클래스

## Controller
### ContactListViewController.swift
- 연락처 뷰 컨트롤러
- ContactsApproachable 로 정렬된 연락처 받아오는 기능 위임받음
### ContactsAdditionModalViewController.swift
- 새 연락처 뷰 컨트롤러
- ContactsManageable 로 연락처 추가/변경/삭제 기능 위임받음
- 유효성 검사 메서드
### UIViewControllerExtension.swift
- 알럿 기능

# 질문
한글 초성을 비교하는 과정에 대해 질문이 있습니다.
유저가 한글 초성을 입력했을 때(e.g. "ㄱㅋ"), 연락처 이름의 초성을 분해해 가져와서 비교하는 로직을 구현하려 했었는데요. 이 과정에서 "ㄱㅋ" 을 한 글자("ㄱㅋ".count == 1)로 처리를 하는 것을 발견할 수 있었습니다. 그래서 저희는 의도적으로 공백을 추가하여 글자들을 서로 맞춰주도록 구현을 했는데요.
컨트롤하기 어렵고 공식 문서에서 별도의 정보를 찾기 어려운 상황이 발생했을 때, 말꼬는 어떤 방식으로 문제를 해결해 나가시는지 궁금합니다!
Contacts.swift #46 참조

2024-01-18 13:39 UTC, keeplo requested changes
Step 3 까지 빠른시간에 PR을 전달해주셨군요! 
고생하셨습니다

이번 PR도 역시 동작에 큰 이슈 없이 잘 작동하는것 확인했습니다.

---
### 질문 답변
저는 초성까지는 경험해보지 못했어요!
코드 작성하신거 보고 깜짝 놀랐습니다. 이런 시도까지 해보시다니 너무 좋습니다!!
저는 현재 구현하신것도 좋아보여요

몇가지 이슈가 있는건 한글 입력에서 온전히 글자 완성이 되시나요?
시뮬에서 안되서 테스트 못 해본게 좀 아쉽네요.. ㅜㅜ

제 나름대로 코드를 좀 간소화 해봤는데
고차함수 학습에 도움되지 않을까해서 남겨봅니다
~~~swift
let inputUnicodeScalars = condition.decomposedStringWithCompatibilityMapping.unicodeScalars
if condition.count == inputUnicodeScalars.count {
   sortedContacts = sortedContacts.filter { contact in
      let nameArray = Array(contact.name)
      let nameCharacters: [String] = nameArray
         .compactMap({ String($0).decomposedStringWithCompatibilityMapping.unicodeScalars.first })
          .map({ String($0) })
      let inputCharacters: [String] = inputUnicodeScalars
          .map({ String($0) })
               return nameCharacters.contains(inputCharacters)
           }
       return
}
~~~

보통 이런 방향보단 영문에 대소문자 구분을 주로하는데 독특했어요 ㅎㅎ
반대로 영문 대소문자 구분없이 검색되는것도 고민해보시면 좋을것 같아요!

검색은 제가 구현을 많이 못해봐서 좋은 팁들을 못드리네요 ㅠㅠ

--- 

전반적으로 리뷰 남긴것 한번씩 고민해보시거나 수정해보시길 바래요..
언제나 질문이나 이상하게 느껴지시는게 있다면 꼭 이번 주차 아니더라도 언제든 디엠주세요!
토론은 대환영입니다!

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            .phoneNumber : contactsAdditionModalView.getTextField(type: .phoneNumber)
프로퍼티로 직접 접근하는 것과 다를게 없습니다.
단순 데이터를 반환해서 사용하는 것과 디미터법칙을 어기는 현재 구현처럼 사용하는건 분명 다릅니다.

~~~swift
extension ContactsAddtionModalView {
    public func setDelegate(delegate: UITextFieldDelegate?) {
        self.delegate = delegate
    }
    
    func getText(type: TextField) -> String? {
        switch type {
            case .name:             return nameTextField.text
            case .age:              return ageTextField.text
            case .phoneNumber:      return phoneNumberTextField.text
        }
    }
}

extension ContactsAdditionModalViewController {
    private func validateTextFields() -> String? {
        var message: String? = nil
        
        for field in TextField.allCases {
            guard let text = contactsAdditionModalView.getText(type: field) else {
                return nil
            }
            let regexTest = NSPredicate(format: "SELF MATCHES %@", field.regex)
            message = message == nil && !regexTest.evaluate(with: text) ? field.message : message
        }
        
        return message
    }
}
~~~

이런 형태처럼 자료구조 형태로 반환해주는게 좋습니다.

현재처럼 구현하면 View 에 존재하는 TF 개체는 retain Count가 2개로 시작하게 됩니다.

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    public func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
접근제어자를 추가하셨군요

default `internal` 이 아닌 `public` 으로 선언하신 의도가 있을까요?

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    @objc public func handleSaveButtonTap() {
마찬가지로 public 제어자를 추가하신 의도가 궁금합니다

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +            let tableView = contactsView.getTableView()
이러한 형태는 직전코드와 큰 차이가 없게 됩니다.
원칙적X, 실수유발 가능성O
> 현재도 `디미터법칙`을 어기는 코드입니다.
> View 코드는 구현가능한 코드이니 가급적 디미터법칙을 지켜주시는게 좋아요

View 개체와 VC 개체가 모두 알고 있는 (같은 접근제어수준)인 자료구조(구조체)를 반환하는 형태로 구현하는 방향이 좋을것 같아요!

setDelegate나 제가 이번 리뷰에 예시로 보여드린 getText 메서드처럼 View 개체 내부에서 `tableView.reloadData()` 호출하는 메서드를 추가해주세요!

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +        contactsAdditionModalView.getTextField(type: .phoneNumber).text = previousContact?.phoneNumber
이 부분도 커스텀 셀 레이블 텍스트 추가하는 것처럼 메서드를 추가해서 구현해주세요
내부 프로퍼티의 존재를 인지해서 해당 개체의 내부사항(.text)에 접근하는 구조는 계속하는 디미터 법칙을 위해하는 형태입니다

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var dataSource: ContactsDelegate?
`Delegate` 명칭이 좀 어색합니다!

초기화를 통해 프로퍼티로 주입되는 부분은 위임보다 
`의존성주입`개념으로 다가가주시는게 좋습니다.

Delegate 패턴은 말그대로 `위임`이라고 표현이 가능한 이유가
참조가능한 개체의 메서드를 프로토콜이라는 매개체를 이용해서 공개(두개채 모두 인지하도록)하고
다른 개체에서 디미터법칙을 어기지 않고 대신 사용가능하게 해줍니다.

`private var dataSource: ContactsDelegate?`
이 개체는 delegate 패턴보다는 VC 개체의 프로퍼티로 의존될 개체의 `의존성주입` 개념으로 봐주셔야 합니다.
두 개체간에 관계를 위해 채택되는 프로토콜이 없고, `.delegate = self` 같은 구조가 아닌것도 
다른 점으로 확인하실 수 있습니다.

프로토콜을 이용해서 추상화를 거쳐주신 부분은 SOLID 원칙을 지켜주는데 도움이되는 아주 좋은 방향이지만
단순히 프로토콜을 사용했다고 해서 위임 또는 Delegate로 네이밍하거나 같은 의미로 받아들이시면
굉장히 혼동을 줄 수도 있고 다른 개발자들과 소통오류가 생길 수도 있습니다.

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +        contactsView.setDelegate(delegate: self)
디미터법칙을 잘지켜주셨군요 아주 좋습니다 🙌

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Contacts.swift
> +
이 동작을 할때 `sortedContacts` 프로퍼티도 업데이트해주는 게 데이터 신뢰도를 올릴 수 있지 않을까요?

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactsProtocol.swift
> +    func filter(by condition: String)
혹시 필터링은 VC의 영역으로 보는건 어떻게 생각하시나요?

이전 리뷰에서 언급했던 `책임`의 기준을 생각해보면 좋을것 같아요!

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactsTableViewCell.swift
> +    }
오오.. 혹시 Objective-C를 학습하신적이 있으신가요? NSString 정말 오랜만에 보내요 ㅎㅎ
저희 교육과정에서 `!`강제 언래핑은 사용하지 않는게 규칙이니 사용하지 않는게 좋을것 같아요!

~~~swift
static var className: String { String(describing: self) }
~~~
형태로 작성하시면 동일한 기대 동작을 할 수 있습니다!

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactsProtocol.swift
> +typealias ContactsDelegate = ContactsManageable & ContactsApproachable
타입을 연계해서 묶는 `typealias`를 사용해주셨군요! 👍
다양한 Swift 기능을 이용하면 정말 다양한 구현을 할 수 있을것 같아요!

2024-01-18 13:39 UTC, Marcorable commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            delegate?.update(previousContact)
이 부분 코드가 잘 이해되지 않는데 
delete 를 동작하는 이유가 있는지 알 수 있을까요?

`previousContact` 자체는 그대로고 내부 프로퍼티를 모두 바꾸어 줬는데
업데이트 동작만 하면 되지 않나요?

2024-01-19 01:28 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            .phoneNumber : contactsAdditionModalView.getTextField(type: .phoneNumber)
"디미터 법칙" 을 키워드로 검색했을 때, 단순하게는 . 을 없애는 것이라고도 볼 수 있다는 말들을 찾아볼 수 있었는데요.
클린코드 책에서 말씀해주신 부분만을 찾아서 읽어봤을 때에는, 자료구조인지 객체인지에 따라 .을 많이 써서 접근하더라도 디미터법칙을 준수하는 형태가 될 수 있다는 말을 하고 있더라구요.

이번에 다시 한번 짚어주시는 내용을 통해서,
UITextField 와 같은 객체를 다시 전달해봤자 결국은 내부의 객체가 가진 속성(또는 메서드) 에 다시 접근하는 결과를 낳기 때문에,
최대한 외부에서 사용해야 할 최종적인 값만 전달하고 그 외는 캡슐화를 통해 안전하게 처리해야 한다는 것으로 이해했습니다.

getText(), setText() 를 만들어 수정했으니 확인 부탁드리겠습니다~! 🙇

2024-01-19 01:30 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +            let tableView = contactsView.getTableView()
수정 완료했습니다.
상세한 답변은 https://github.com/tasty-code/ios-contact-manager-ui/pull/83#discussion_r1458174849 댓글로 갈음하겠습니다!

2024-01-19 01:30 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +        contactsAdditionModalView.getTextField(type: .phoneNumber).text = previousContact?.phoneNumber
위와 마찬가지입니다! 수정 완료했습니다. 🙏

2024-01-19 01:40 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Contacts.swift
> +
주신 의견대로 sorted 를 호출할 때, 내부 sortedContacts 에 업데이트 되도록 변경했습니다.

2024-01-19 01:40 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/View/ContactsTableViewCell.swift
> +    }
더 깔끔한 것 같아요! 변경했습니다. 🙏

2024-01-19 01:46 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            delegate?.update(previousContact)
hashValue 로 접근하고 해당 해시 값의 내부 프로퍼티만 변경해 주었다고 생각했는데,
실제 동작 과정에서 내부 프로퍼티가 변경되는 경우 hashValue 가 함께 변경되는 것을 확인하게 되었습니다.
그러다 보니 데이터를 저장하는 레포지토리에 아예 새로운 값이 추가되는 현상이 있어서,
간단하게 기존 것을 지워주는 것으로 해결을 해보았습니다.

2024-01-19 01:48 UTC, jus1234 commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var dataSource: ContactsDelegate?
말씀 주신대로 `delegate`와는 의미가 맞지 않는 듯해 `ContactsModel`이라는 타입명으로 변경했습니다. 혹시 `의존성 주입`이라는 의미가 이 타입명에 포함되어야 한다고 생각하셔서 말씀하신 거라면 의존성 주입 개념을 반영한 네이밍 예시가 궁금합니다!

2024-01-19 07:19 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var dataSource: ContactsDelegate?
처음에는 패턴을 활용하는 방법에 있어서 크게 차이가 없다고 생각해서 쉽게 delegate 를 붙였었는데요.
설명을 통해 의존성 주입으로 보아야 하는 근거를 조금 더 명확하게 알 수 있었습니다!

ContactsModel 이라는 명칭으로 수정했습니다! 🙏

2024-01-19 07:25 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    public func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
크게 의도가 있었던 것은 아닙니다.
현재 프로젝트 기준으로 볼 때 둘 사이에 차이가 없기도 하고, public 이 붙어있음으로 인해 해당 메서드가 외부에서 호출이 가능한 메서드라는 점이 명확히 보인다고 생각해서 일괄적으로 붙여주었었습니다.

2024-01-19 07:25 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    @objc public func handleSaveButtonTap() {
위와 동일합니다. 😅

2024-01-19 07:35 UTC, eensungkim commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactsProtocol.swift
> +    func filter(by condition: String)
근본적으로 VC의 영역이라고 보는게 적절하다는 데에 저희도 동의가 되었는데요.
화면을 그리기 위해 필요한 데이터가 Contacts에 있고, 테이블뷰가 그려지기 위해 호출되는 tableView(_:numberOfRowsInSection:) 메서드가 Contacts 의 배열을 가져와야 하기 때문에 여기에 넣었습니다.

2024-01-20 03:27 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            .phoneNumber : contactsAdditionModalView.getTextField(type: .phoneNumber)
제가 언급한 내용뿐만아니라 사소해보이는 내용도 블로그 몇줄로 이해하면 안되고 그런 원칙의 원인과 CS 내부적인 사항까지 꼭 파악하셔야합니다!

디미터법칙의 근간은 .을 벗어나는게 아니라
각 개체간의 관계, 공개범위와 캡슐화에 관련된 부분입니다.

2024-01-20 03:29 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +    public func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
Public은 모듈 외부에서도 사용 가능하다는 부분이 되므로 분명 default `internal` 과 다른 동작을 야기합니다.

특별한 의도가 아니라면 default 상태로 두는게 좋아보여요~

2024-01-20 03:31 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsAdditionModalViewController.swift
> +            delegate?.update(previousContact)
이런 상황이 도래하면 Hashable 을 이용하려던 CRUD 시스템을 리펙토링하는게 맞습니다. (우선순위가 높습니다)

만약 이대로 급한불끄자고 우선순위를 낮추고 다른 업무를 처리하다보면
많은 부분에서 update 메서드는 의미없이 delete를 의무 사용하게되고
다른 제3자가 함께 개발하면 그마져도 모르고 실수 할수 있습니다.

2024-01-20 03:38 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactsProtocol.swift
> +    func filter(by condition: String)
제가 경험한 레퍼런스들을 이용한다면 `enum` 을 통해 `filter` / `default` dataSource 상태를 구분하고

~~~swift
var filteredContacts: [Contant] { 
   model.contacts.filter ({
   // filter 동작
   })
}

tableView(_:numberOfRowsInSection:) {
   switch searchingState {
      case .`defatult`:  model.contacts.count
      case .filter:           filteredContacts.count
   }
}
~~~

이런 예시코드로 할거 같아요!

2024-01-20 03:41 UTC, keeplo commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactsViewController.swift
> +    private var dataSource: ContactsDelegate?
> 말씀 주신대로 `delegate`와는 의미가 맞지 않는 듯해 `ContactsModel`이라는 타입명으로 변경했습니다. 혹시 `의존성 주입`이라는 의미가 이 타입명에 포함되어야 한다고 생각하셔서 말씀하신 거라면 의존성 주입 개념을 반영한 네이밍 예시가 궁금합니다!

네이밍에 의존성주입이 들어가야하는 건 아닙니다! `delegate` 또는 `위임`의 의미가 빠지가만 하면 될것 같아요!

2024-01-20 07:35 UTC, merged