Step3
tasty-code/ios-contact-manager-ui pull request #87
Opened 2024-01-18 11:29 UTC by angryeon7

> 리뷰어 : @minsson
> 버드 : @angryeon7 (토미) @andyanappdev (앤디)

안녕하세요. 민쏜-! 벌써 마지막 PR이네요ㅜㅜㅜ
프로젝트를 진행하면서 많이 응원도해주시고(스윗의 대명사,,,) 피드백도 잘해주셔서 너무너무 감사했습니다😭
프로젝트는 끝나지만,, 종종 질문하러 DM드리겠습니다ㅎㅎ 즐거운 주말 보내세요🙋🏼

---

## 프로젝트 구조

해당 파일들이 추가되었습니다.

****Folder Structure****

├──  App
 │  ├── Delegate
 │   │   └── AppDelegate
 │   │   └── SceneDelegate
├──  Model
 │   │ └── Contact
 │   │ └── 📁ContactInput
 │   │ └── ContactManager
 │   │ └── 📁ContactDelegate
 │   │ └── 📁ContactInputError
├──  View
 │   │ └── ContactsView
 │   │ └── ContactTableViewCell
 │   │ └── ContactDetailView
 │   │ └── 📁ContactCustomTableViewCell
├── ViewController
 │   │ └── ContactsViewController
 │   │ └── AddContactViewController
└───

## 프로젝트 설명 (Code Base UI):

1. **saveTapped() 메서드의 책임 분리:**
    - `saveTapped()` 메서드는 취소 얼럿의 메세지를 자동으로 던지는 기능을 가지고 있습니다. 이를 통해 취소 얼럿에 대한 로직이 메서드 외부로 분리되어 코드의 가독성이 향상되었습니다.
    - 불필요한 검사 삭제
2. **은닉화와 캡슐화의 반영:**
    - 필요한 데이터들을 `ContactDetailView` 내부에서 캡슐화하고, 메서드를 통해 외부로 전달하는 방식으로 캡슐화를 구현하였습니다.
    - 이로써 데이터의 은닉성이 향상되었습니다.
3. **검색 기능:**
    - 네비게이션 아이템을 활용하여 네비게이션 바에 검색 기능을 내장시켰습니다.
    - `UISearchController`를 사용하여 검색 바와 결과를 관리하며, 텍스트 입력 시 테이블 뷰의 리스트를 필터링하여 화면에 표시하는 로직을 구현하였습니다.
4. **테이블뷰 셀 편집 - 삭제 기능 구현:**
    - 테이블뷰 셀을 스와이프하여 삭제할 수 있는 기능을 구현하였습니다.
    - `UITableViewCell`의 `editingStyle` 메서드를 활용하여 해당 셀의 ID를 확인한 후, `ContactManager`를 통해 연락처를 삭제하는 로직을 구현하였습니다.
5. **커스텀 뷰셀 구현:**
    - `ContactCustomTableViewCell` 클래스를 생성하여 테이블 뷰 셀의 커스터마이징을 구현하였습니다. 
6. **연락처 정보 변경의 재사용:**
    - 동일한 화면에서 텍스트 필드의 값 유무에 따라 상태를 저장하고, 상태에 따라 다른 로직을 구현하여 코드의 중복을 피하였습니다.
    - 이를 통해 유사한 기능을 가진 두 상황에서 코드의 재사용성이 증가하였습니다.

### 조언을 얻고 싶은 부분 🤔

현재 `DetailContctViewController` 에서 동일한 화면에서 상황에 따라 다른 동작을 수행하는 로직을 별도의 메서드로 분리하지 않고, 상태 변수를 활용한 방식으로 구현하였습니다.

1. `DetailContctViewController`에서 연락처 정보를 변경하는 부분에서 상태를 저장하고, 상태에 따라 다른 로직을 구현하는 방식 사용하였습니다. 이 로직에 대해 어떻게 생각하시나요?
1. 개선할 점이 있다면 어떤 부분인지 알고싶습니다.

2024-01-21 16:17 UTC, minsson requested changes
안녕하세요, 앤디, 토미!
그러게요, 벌써 저희가 함께 한 3주가 끝났네요. 아쉬워요.
그래도 언제든 연락주셔도 되니, 어떤 용건으로든 편하게 연락 주시면 좋겠어요.

마지막 스텝이니만큼, 저도 더 열심히 해봤습니다..! 특히 Step 1, Step 2에서부터 언급하면 그 부분을 수정하느라 진행 속도가 많이 더뎌질 것 같아서 언급하지 않았던 부분들도 여기서는 조금 언급해보려고 해요. 그렇기 때문에 종합 코멘트와 코드 코멘트 여러 곳에서 아쉬운 점에 대해 많이 말씀드리겠지만, 두 분이 뭔가를 잘못해서가 아니라, 제가 아는 한도 내에서라도 사소한 것까지 말씀드리고 싶은 제 마음에서 비롯된 거라고 생각해주시면 좋겠어요. 오히려 두 분이 너무 잘해주셔서 언급드릴 수 있는 부분이니까요.

## 기능 구현 측면에서 아쉬웠던 점
1. 연락처 조회 화면의 테이블 뷰와 Search Bar의 Cancel 버튼, 새 연락처 화면에는 Dynamic Fonts가 적용되어 있지 않아요.
2. 새 연락처에서 이름을 입력할 때 한글을 입력할 수 없어요. 
3. Search Bar의 활성화 유무와 무관하게 Cancel 버튼이 상시 노출되어 있어요.
4. Search Bar가 활성화되어 있지 않을 때 Cancel 버튼을 누르다 탭 영역이 조금만 Cancel 버튼 바깥으로 가도 Search Bar가 활성화돼요.
5. Search Bar가 활성화되어 키보드가 올라오면, 키보드가 컨텐츠를 가려서 6-7번째 연락처부터는 스크롤링을 해도 볼 수가 없어요.
6. 테이블 뷰에서 최근 탭했던 row가 계속 활성화되어 있어요. 탭한 순간만 색이 변했다가 다시 원래 색으로 돌아오는 게 자연스러울 거예요.
7. (Optional) Search Bar가 활성화 되어 키보드가 올라왔을 때, 유저 입장에서는 테이블 뷰 스크롤을 내리며 키보드를 쓸어내리는 경험이 익숙할 거예요. 이 방식으로 키보드를 내리는 기능도 있으면 좋겠어요.

## 질문 답변

> 조언을 얻고 싶은 부분 🤔
현재 DetailContctViewController 에서 동일한 화면에서 상황에 따라 다른 동작을 수행하는 로직을 별도의 메서드로 분리하지 않고, 상태 변수를 활용한 방식으로 구현하였습니다.
>
> DetailContctViewController에서 연락처 정보를 변경하는 부분에서 상태를 저장하고, 상태에 따라 다른 로직을 구현하는 방식 사용하였습니다. 이 로직에 대해 어떻게 생각하시나요?
개선할 점이 있다면 어떤 부분인지 알고싶습니다.


두 분이 이런 방식으로 구현하신 건 "새 연락처"와 "연락처 수정" 화면의 UI가 동일하기 때문일 거예요. 기능도 비슷해보이고요. 때문에 코드 중복을 피하고자 하셨던 거라고 이해했어요.

제 개인적인 의견을 말씀드리자면, 저는 좋지 않은 구현 방식이라고 생각해요. 처음 보는 사람 입장에서 이해하기 어렵고, 분기처리가 점점 더 지저분해질 여지가 있고, 예외에도 대응하기 힘들어진다는 문제가 있기 때문이에요.

현재 문제의 분기처리는 아래와 같아요.
- isPresentedModally가 true인지, false인지에 따른 분기처리 발생
- 이니셜라이저를 통해 contact를 받았는지의 여부에 따른 분기처리 발생

두 경우 모두 하나씩 살펴볼게요.

- isPresentedModally가 true인지, false인지에 따른 분기처리 발생
```swift
if isPresentedModally {
    self.dismiss(animated: true, completion: nil)
} else {
    navigationController?.popViewController(animated: true)
}
```
만약 이 분기만 있었다면, 제 생각에는 이니셜라이저를 통해 Save 버튼이 눌렸을 때 실행될 코드를 closure로 전달 받으면 지금 구조를 벗어나지 않으면서도 이 문제를 간단하게 해결할 수 있었을 것 같아요.

- 이니셜라이저를 통해 contact를 받았는지의 여부에 따른 분기처리 발생
```swift
if contact == nil{
    addNewContact(name: currentContactInpt.name, age: currentContactInpt.age, contactNumber: currentContactInpt.contactNumber)
} else {
    updateContact(name: currentContactInpt.name, age: currentContactInpt.age, contactNumber: currentContactInpt.contactNumber)
}
```
이런 방식의 분기처리는 최대한 피했으면 좋겠어요. 극단적으로 말씀드리자면, 이런 분기처리를 하는 것보다는 "새 연락처" 화면과 "기존 연락처 수정" 화면의 UI가 아무리 같더라도, 코드를 그대로 복사 + 붙여넣기 해서 새로운 객체를 만드는 편이 낫다고 생각해요. 

contact가 언제 nil이고, 언제 그렇지 않은 경우도 이해하기 어렵고, 왜 이런 구분 기준을 가져야 하는지도 이해하기 어려워요. 지금은 코드의 길이가 짧고 프로젝트가 워낙 간단해서 몇 분만 투자하면 이해할 수 있지만, 복잡한 UI와 기능을 가진 상용 프로젝트라면 이런 식의 분기가 하나하나 쌓여 스노우볼이 되어 굴러올 거예요. 유지보수하기 매우 어려운 코드를 만드는 지름길이라고 생각해요. 

왜 이렇게 말씀드리냐면, 전 직장에서 레거시 코드 중에 이런 파일이 있었기 때문이에요. 뷰 컨트롤러 하나 안에서 이런 식의 변수들이 10개 이상 있었고, 각 메서드마다 그 변수들을 다양하게 조합한 분기처리가 있었는데, 그 코드에 대해 설명해줄 사람도, 문서도 없는 상황이었어요. 이해하기도 힘들고, 어디를 건들면 어디가 터질지 몰라 너무 불안했었어요. 이렇게 쌓이고 쌓이다 '처음부터 다시 만들어야 돼요'라는 말이 나오는 거라는 걸 이해할 수 있었던 좋은 경험이었어요.

그럼 어떻게 하면 좋을까요? 일단 생각나는 방식을 쉬운 것부터 난이도 순서대로 나열해볼게요.
- enum 타입을 만들고, 케이스로 각 화면의 역할을 나누고, 그리고 그 case를 통해 분기처리하는 방법
  - 이 방법은 지금보다 가독성이 좋아지기는 하겠지만 본질적으로 별 차이는 없을 것 같아요.
- 상속을 활용하는 방법
  - UI를 갖고 있는 부모 뷰컨트롤러를 만들고, 자식 뷰컨트롤러에서 로직만 오버라이드해서 사용할 수 있을 거예요.
- 프로토콜과 프로토콜의 기본구현을 활용하는 방법
  - 공통 UI는 프로토콜의 기본 구현을 활용해 정의하고, 공통으로 호출되면서도 로직이 달라져야 하는 것들은 프로토콜의 요구사항으로 만들 수 있어요.
- 컴포지션을 활용하는 방법
  - 이 방법은 좀 더 복잡해요. 지금보다는 나중에 시도해보면 좋을 것 같아요. 우선 언급만 해둘게요.

저는 우선 상속을 통해 구현하는 방법을 추천 드리고 싶어요. Swift가 POP라고 해서 무조건 상속은 피하려는 분들도 계시지만, 애초에 UIKit 자체가 상속을 바탕으로 만들어져 있어요. 상속 자체를 활용해보는 경험도 좋은 경험이 될 거라고 생각해요. 상속이 익숙해지면 그 아래의 방법도 활용해보시고요!

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInputError.swift
> +}
에러를 별도로 정의해주셨군요! 아주 좋습니다. 다만 에러 케이스의 네이밍이 어색하게 느껴지네요. Swift의 URLError 타입을 보고, 각 에러 케이스들이 어떤 네이밍으로 정의되어 있는지 살펴보면 좋겠어요.

[Swift - URLError](https://developer.apple.com/documentation/foundation/urlerror)

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInputError.swift
> +}
또, errorMessage보다는 errorDescription이라는 네이밍이 더 자연스러울 것 같아요. 이와 관련해서 errorDescription이라는 네이밍을 사용하는 LocalizedError 프로토콜도 살펴보시면 좋겠어요.

[Swift - LocalizedError](https://developer.apple.com/documentation/foundation/localizederror)

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInput.swift
> +}
지난 주의 피드백을 바로 적용하셨군요! 저번에도 말씀 드렸듯이 더 좋은 접근법이 있을 수 있으니 더 고민해보시면 좋을 것 같아요~!

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInput.swift
> +}
이 코드와 직접적인 관련이 있는 건 아니지만, 나중에 여유가 된다면 DTO, Entity 등에 대해서도 공부해보고 이 코드에 대해 다시 한번 생각해보셔도 재미있을 것 같아요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        contactsView.contactsTableView.register(ContactCustomTableViewCell.self, forCellReuseIdentifier: "ContactCustomTableViewCell")
Cell의 ReuseIdentifier를 String으로 작성해놓으니 조금 불안하네요. `ContactTableViewCell`에서 사용하신 것처럼 identifier를 static으로 쓰면 어떨까요?

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        guard let reusableCell = tableView.dequeueReusableCell(withIdentifier: "ContactCustomTableViewCell", for: indexPath) as? ContactCustomTableViewCell else {
Cell의 ReuseIdentifier를 String으로 작성해놓으니 조금 불안하네요. ContactTableViewCell에서 사용하신 것처럼 identifier를 static으로 쓰면 어떨까요?

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        definesPresentationContext = true
이 코드는 어떤 의도로 작성하셨나요? 지우면 어떻게 되나요?

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        searchController.obscuresBackgroundDuringPresentation = false
이 코드는 어떤 의도로 작성하셨나요? 지우면 어떻게 되나요?

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        searchController.searchBar.showsCancelButton = true
이 코드는 어떤 의도로 작성하셨나요? 지우면 어떻게 되나요?

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        detailContactViewController.toggleIsPresentedModally()
DetailContactViewController를 하나 만들어놓고 "새 연락처" 화면일 때와 "연락처 수정" 화면 용도로 공통으로 사용하면서 isPresentedModally 프로퍼티를 바꾸는 방식이 좋은지에 대한 의문이 있어요.

우선은 이건 논외로 하고, 단순히 이 메서드 자체에 대해 생각해볼게요.

저 개인적으로는 이 메서드의 효용을 잘 모르겠어요. 이 메서드를 통해 DetailContactViewController의 외부에서도 private var인 isPresentedModally를 사실상 set할 수 있게 되었어요. 이런 용도라면 차라리 isPresentedModally를 var로 열어놓고, 외부에서 `detailContactViewController.isPresentedModally.toggle()` 같은 방식으로 변환하는 게 나을 수도 있다는 생각이 들어요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +    }
`searchController.searchBar.text?.isEmpty`와 `isSearchBarEmpty`는 같은 의미로 보이는데, `isSearchBarEmpty`라는 연산 프로퍼티를 별도로 만들어주신 이유가 무엇인가요? 별도로 만들 때와 안 만들 때 어떤 장단점이 있나요?

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        return searchController.isActive && !isSearchBarEmpty
`isSearchBarEmpty`, `isFiltering` 모두 외부에서 사용하지 않는 것 같아요. 접근제어가 필요해보여요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +        try isValidContactNumber(contactNumber)
호출부에서 보면 메서드명이 어색해보여요. is로 시작하는 네이밍을 보면 리턴 타입이 Bool 타입일 거라고 예상하게 돼요. validate로 시작하는 네이밍이 좋을 것 같아요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +        let name = currentContactInpt.name.replacingOccurrences(of: " ", with: "")
사소하지만 validate라는 네이밍 안에서 String을 가공하는 로직을 직접적으로 갖고 있는 게 적절한지 의문이에요. validate하기 전에 가공한 후, 가공된 값을 validate하는 게 더 자연스러울 수 있겠다는 생각이 들어요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
`cancelButtonTapped()` 라는 네이밍이 더 좋을 것 같아요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
여기도 isPresentedModally에 의해 분기처리가 되어 발생하는 아쉬움 중 하나예요. 일단 이와는 별개로, 네이밍만 살펴볼게요. 메서드 네이밍을 보면 moveToContactsViewScreen라고 되어있는데 굳이 DetailViewController를 띄우기 전의 화면에 대한 정보가 메서드명에 반영되어야 할 이유가 없어보여요. 만약 ContactsViewScreen이 아니라 다른 화면에서도 DetailViewController에 진입할 수 있게 된다면 이 네이밍은 유효하지 않게 될 거예요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
이 메서드 자체에 대해서는 다른 코멘트에서 언급했으니 생략할게요. 문법 측면에서, Bool 타입에는 `toggle()`이라는 메서드가 있어요. 즉, `isPresentedModally.toggle()`이라고 쓸 수 있어요.

[Swift - toggle()](https://developer.apple.com/documentation/swift/bool/toggle())

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
- saveButtonTapped()라는 네이밍이 더 좋아보여요.
- do-catch를 활용한 건 좋습니다!
- currentContactInput의 오타는 수정해주세요.
- validateInput과 currentContactInput은 서로 라인을 바꿔주는 게 더 자연스러울 것 같아요. currentContactInput 다음에 validateInput이 있으니 마치 동작이 연결되는 것 같은 인상을 줘요. 
- 이왕 Alert를 띄우는만큼, 예상치 못한 에러가 발생하는 경우에도 Alert을 띄우는 게 좋겠어요. 이런 경우에는 보통 "알 수 없는 에러가 발생했습니다. 고객센터로...." 라는 식의 에러를 띄우더라고요. 참고로, 필요하다면 ContactInputError에도 unknown이라는 케이스를 정의할 수 있어요. [Swift - URLError](https://developer.apple.com/documentation/foundation/urlerror)에도 unkown이라는 케이스가 있어요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +            }
여기도 isPresentedModally에 의해 분기처리가 되어 발생하는 아쉬움 중 하나예요. 이 객체 자체를 완전히 이해하고 있지 않으면 왜 contact에 의해 이런 분기가 발생하는 건지 알 수 없어요. 왜 contact가 nil인 경우가 있는지, 그리고 그렇지 않은 경우는 무엇인지, 왜 각 경우에 따라 addNewContact를 실행하거나 updateContact를 실행하는지 알기 어려워요. 이 코드를 처음 보는 사람은 DetailViewController 전체의 코드를 훑어보며 추측해야할 거예요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
다른 파일에서 아래와 같이 `ContactInput`이라는 모델 객체를 만들어주셨는데, `updateContact`와 `addNewContact`에서도 활용하면 어떨까요?
```swift
struct ContactInput {
    let name: String
    let age: String
    let contactNumber: String
}
```

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +            }
또, 전반적인 구조와는 별개로 `addNewContact(name:age:contactNumber)`와 `updateContact(name:age:contactNumber)`는 기존에 정의해두신 `ContactInput` 객체를 이용하는 방식으로 바꾸면 아래와 같이 호출할 수 있어요.

- 현재
```swift
addNewContact(name: currentContactInpt.name, age: currentContactInpt.age, contactNumber: currentContactInpt.contactNumber)

updateContact(name: currentContactInpt.name, age: currentContactInpt.age, contactNumber: currentContactInpt.contactNumber)
```

- 수정 후
```swift
addNewContact(using: currentContactInput)

updateContact(with: currentContactInput)
```

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactCustomTableViewCell.swift
> +final class ContactCustomTableViewCell: UITableViewCell {
UITableViewCell을 상속하는 뭔가를 만든다면 모두 다 Custom이므로, 네이밍에 Custom임을 별도로 언급하지 않아도 괜찮을 것 같아요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactCustomTableViewCell.swift
> +    }
이 부분은 저번 스텝에서부터 좀 궁금했었는데, 어떤 이유로 프로퍼티 옵저버를 사용해서 구현하셨나요? 예를 들어 `configure(with contact: Contact)`라는 식의 메서드를 만들 수 있는데, 이 방식을 선택하신 이유가 궁금해요. 저는 이런 방식을 처음 봐서 어떤 장단점이 있는지 궁금해요.

2024-01-21 16:17 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +    }
- updated가 아니라 update가 되는 게 자연스러울 것 같아요. 

- 제가 이전 스텝에서 언급하지 않았었는데, Contact 객체에서 id와 관련해, 다음 프로젝트부터는 유사한 상황에서 UUID 타입을 활용해보시면 좋을 것 같아요.

2024-01-23 14:57 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInput.swift
> +}
넵 알겠습니다.
Remote DB 에서는 API -> DTO -> data model
Local DB 에서는 DAO -> Entity -> data model
위와 같이 알고 적용해서 사용하고 있습니다. 혹시 제가 잘못 알고 있다면 간단하게라도 알려 주시면 감사하겠습니다. ^^

2024-01-23 15:11 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactCustomTableViewCell.swift
> +final class ContactCustomTableViewCell: UITableViewCell {
알겠습니다.
앞으로는 네이밍에 별도로 Custom임을 언급하지 않도록 하겠습니다.
다만 이번의 경우 기존의 ContactTableViewCell을 삭제하지 않고 남겨 두고 있어서 (사용되지는 않지만 혹시나 다시 변경할 경우를 대비해서) 차이를 두기 위해서 적용해보았습니다.

2024-01-23 15:24 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        contactsView.contactsTableView.register(ContactCustomTableViewCell.self, forCellReuseIdentifier: "ContactCustomTableViewCell")
말씀해 주신대로 수정하여 commit 하였습니다.

2024-01-23 15:24 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        guard let reusableCell = tableView.dequeueReusableCell(withIdentifier: "ContactCustomTableViewCell", for: indexPath) as? ContactCustomTableViewCell else {
말씀해 주신대로 수정하여 commit 하였습니다.

2024-01-23 15:55 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        detailContactViewController.toggleIsPresentedModally()
민쏜의 의견을 듣고 생각을 해보았습니다.
모든 속성에 접근 제한을 걸고 오로지 method를 통해서만 속성의 값을 받아가거나 혹은 필요하면 값을 바꾸는 행위를 하도록 한다는 일관성을 유지 하는 것 말고는 그닥 이득이 없다고 생각 합니다. (searchbar를 위해 한 속성을 열어 두기는 했지만요 ㅜㅜ)
사실 저는 속성의 값을 외부에서 바꾸는 행위 자체를 지양 하자는 주의 입니다만...
이번 프로젝트에 MVC 아키텍처 적용 및 설계 자체를 만족할만한 수준 까지 끌어 올려서 시작하지 못한 부분도 있고 각 STEP 마다 어떤 요구 사항이 주어지는 미리 알지 못하고 그때그때 대응하다 보니 구현에만 급급해서 쉬운 길을 선택하다 보니 허술한 부분이 많은것 같습니다.

의견 주신 부분을 반영하여 commit 하였습니다.

2024-01-23 16:02 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
앗 실수로 button을 빠뜨린듯 합니다.
저는 항상 어떤 버튼이 눌리는 액션의 경우 버튼명+Buttton+Tapped 메서드 명을 사용하고 있습니다.
바로 수정해서 commit 하였습니다.

2024-01-23 16:05 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
넵 위에서 언급하신 내용 수정완료 했습니다. bool 값을 변경하는 경우 간단히 toggle 메서드를 사용하면 편리 하죠

2024-01-24 13:30 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInput.swift
> +}
앤디가 실제로 그렇게 적용해서 사용하신다면, 어떤 이유로 그 객체들을 나누는 거라고 생각하시나요? 가령 모델 객체를 하나만 두고 필요할 때마다 타입을 변환해가며 사용하고, 어디서는 필요하고 어디서는 필요 없는 프로퍼티가 있다면, 일단 모델 객체가 최대한 많은 프로퍼티를 포함하게 만들어서 사용하면 모델 객체 하나로도 여기저기서 다 쓸 수도 있을텐데요.. 그렇게 많은 종류로 나누면 어떤 게 좋아지는 건가요?

2024-01-25 01:17 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInput.swift
> +}
아 저의 말의 의미는
Remote 와 Local에서 사용자 정의 data model로 변환시키주는 아이들의 명칭의 차이가 있다는 것을 말하고 싶었던 것입니다.
결국 역할은 똑같은데 명칭의 차이가 있다고 알고 있습니다.
물론 마지막의 data model을 Remote냐 Local 이냐에 따라 각각 만들어 두지는 않아요

2024-01-26 11:23 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInputError.swift
> +}
invalid를 사용한다는것을 계속 isVaild로 사용한것같습니다!! 수정하였습니다.

2024-01-26 11:36 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +    }
우선 `isSearchBarEmpty`를 사용하여 해당 조건이 무엇을 나타내는지 더 명확하게 표현하고 싶었습니다.
또한 `isSearchBarEmpty`를 여러 번 사용할 수도 있겠다라고 생각하여 간편함과 가독성을 위해 작성하였습니다.
따라서 코드의 가독성과 이해를 높이기 위해, 명확하고 간결한 이름을 사용하였습니다.

2024-01-26 11:56 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        definesPresentationContext = true
- `searchController.searchBar.placeholder = "연락처 검색"`: 검색 바에 표시될 플레이스홀더 텍스트를 설정하는 부분입니다. 지우면 "연락처 검색"이라는 텍스트가 검색 바에 보이지않습니다.
- `searchController.searchBar.showsCancelButton = true`: 검색 바에 취소 버튼을 표시할지 여부를 결정하는 부분입니다. 지우면 취소 버튼이 사라집니다. -> 네비게이션바에 만들어서 취소버튼이 필요하다고 판단했습니다.
- `navigationItem.searchController = searchController`: `ContactsViewController`의 `navigationItem`에 설정된 `UISearchController`를 연결하여 네비게이션 바에 검색 바를 표시합니다. 지우면 검색바가 사라집니다.
- `definesPresentationContext = true`: `true`로 설정하면 현재 뷰 컨트롤러가 화면에 표시될 때 검색 컨트롤러가 활성화됩니다. 지워도 해당 코드에서는 큰 변화가 없으나 뷰가 추가될 경우 이상이 생길 수 있습니다.

2024-01-26 11:59 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        searchController.obscuresBackgroundDuringPresentation = false
- `searchController.searchResultsUpdater = self`: 이 부분은 `UISearchController`가 검색 결과를 업데이트할 때 호출되는 객체를 지정하는 것입니다. 지우면 검색 결과가 업데이트되지 않을 것이며, 검색 동작이 제대로 작동하지 않을 것입니다.
-  `searchController.obscuresBackgroundDuringPresentation = false`: 이 부분은 검색할 때 화면의 배경을 어둡게 할지 여부를 결정하는 것입니다. 지우면 검색 중에 화면이 어두워지게 됩니다.

2024-01-26 12:06 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        searchController.searchBar.showsCancelButton = true
- `searchController.searchResultsUpdater = self`: 이 부분은 `UISearchController`가 검색 결과를 업데이트할 때 호출되는 객체를 지정하는 것입니다. 지우면 검색 기능이 작동하지 않을 것입니다.
- searchController.obscuresBackgroundDuringPresentation = false: 이 부분은 검색할 때 화면의 배경을 어둡게 할지 여부를 결정하는 것입니다. 지우는면 변화는 없지만 true일 경우 검색 중에 화면이 어두워지게 됩니다.
- `searchController.searchBar.placeholder = "연락처 검색"`: 검색 바에 표시될 플레이스홀더 텍스트를 설정하는 부분입니다. 지우면 연락처 검색의 텍스트가 나타지않습니다.
- `searchController.searchBar.showsCancelButton = true`: 검색 바에 취소 버튼을 표시할지 여부를 결정하는 부분입니다. `true`로 설정하면 취소 버튼이 나타납니다. 지우면 검색 바에 취소 버튼이 나타나지 않을 것입니다.

2024-01-26 12:07 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        return searchController.isActive && !isSearchBarEmpty
추가하여 수정하였습니다

2024-01-30 14:08 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
다른 화면에서도 DetailViewController에 진입한다면 해당 네이밍이 유효하지 않게 된다는 부분을 전혀 고려하지 못했습니다. ㅜㅜ
그렇다면 DetailViewController에 진입한 이전화면이라는 의미로 moveToPreviousScreen 이라고 변경하여 commit 하였습니다.

2024-01-30 15:09 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +            }
우와~ 왜 저는 이렇게 생각을 하지 못 했을까요?
만들어 두고도 간편하게 코드를 줄여서 사용이 가능한데 활용을 못하고 있었습니다.
민쏜이 알려 주신데로 코드 수정하여 commit 완료 하였습니다.

2024-01-30 15:15 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +    }
바로 위의 Comment에서 알려주신 대로 적용하면서 같이 수정되었습니다.

2024-01-30 15:28 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/View/ContactCustomTableViewCell.swift
> +    }
사실 cell의 내용이 변경되면 어짜피 reload 되기 때문에 의미가 없는것 같습니다.
처음에는 속성감시자로 설정해두면 그 값들이 변화될때마다 반영해줄수 있겠내 라는 생각으로 구현했었습니다.

2024-01-30 15:32 UTC, andyanappdev commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +    }
해당 method 이름과
아래에서 contactManager에서 콜하는 method 모두 updateContact로 수정하여 commit 하였습니다.

2024-01-31 01:08 UTC, andyanappdev commented
현재 DetailContctViewController 에서 동일한 화면에서 상황에 따라 다른 동작을 수행하는 로직을 별도의 메서드로 분리하지 않고, 상태 변수를 활용한 방식으로 구현하였습니다.

사실 완전 동일한 화면(DetailContactView)으로 이동하는 것이지만 서로 다른 화면 이동 방식을 선택하여 구현한 이유에 대한 설명이 없었던거 같아 추가 comment로 남기려고 합니다.
**셀을 선택하여 DetailContactView (수정화면)로  이동 하는 경우**
선택된 셀에 대한 구체적인 행위를 하기 위해 한 댑스 더 들어 간다는 것을 사용자에게 전달하기 위함
** + 버튼을 눌러서 DetailContactView (입력화면)로 이동 하는 경우**
새로운 정보를 입력 생성한다는 의미를 전달하기 위함

이런 사용자 경험을 선택한 구현을 한 것이 결과적으로 저에게는 아주 큰 도움이 된것 같습니다.
민쏜의 생각과 다양한 개선 방법을 알수 있었기 때문입니다.
감사합니다.

2024-01-31 01:17 UTC, angryeon7 commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/DetailContctViewController.swift
> +        let name = currentContactInpt.name.replacingOccurrences(of: " ", with: "")
stirng을 처리하는 메소드를 생성하여 분리하였습니다!!

2024-02-13 12:36 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Models/ContactInput.swift
> +}
앗.. 제가 생각했던 바랑은 조금 다르네요. 저의 경우에는 DTO, Entity만 사용하고 있어요. Data Layer에서는 DTO를 사용하고, Presentation Layer에서는 Entity를 사용하고 있어요. 가령 네트워킹을 한다면, 서버로부터 받아오는 응답은 DTO로 받고, 거기서 뷰를 그릴 때 필요한 프로퍼티만 추려서 Entity로 변환해주고, 뷰에서는 Entity를 사용하는 방식이에요. 이 방식이 정답이라는 게 아니라, 이렇게 용도에 따라 모델 객체를 여러 개로 나누는 방법도 있다는 걸 말씀드리고 싶었어요.

2024-02-13 12:40 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +        definesPresentationContext = true
명세서에는 Cancel 버튼이 표시되어 있지 않은데, 명시적으로 showsCancelButton을 true로 설정해 취소 버튼을 만드신 이유가 궁금했었어요. 애플의 기본 앱들을 사용해봐도 취소 버튼을 디폴트로 표시하고 있지는 않고요. 때문에 저 개인적으로는 제거하는 편이 좋다고 생각했었어요.

2024-02-13 12:50 UTC, minsson commented on Contact-Manager-iOS/Contact-Manager-iOS/Controllers/ContactsViewController.swift
> +    }
이건 정말 개인 취향인 것 같기도 하고, 저도 어떻게 하는 게 더 좋을지 확신이 없는데요.. 저 개인적으로는 이런 용도의 연산프로퍼티는 사용하지 않는 편이에요. 저라면 `searchController.searchBar.text?.isEmpty`를 썼을 것 같아요. 코드를 처음 보는 사람 입장에서는 isSearchBarEmpty가 정말 내가 아는 그런 의도가 맞는지 파악하기 위해 Jump to definition을 해서 `searchController.searchBar.text?.isEmpty`를 살펴봐야할 수도 있다고 생각하기 때문이에요. (전 직장에서의 제 경험담이에요 🥲) 다시 말해, 비록 `searchController.searchBar.text?.isEmpty`라는 코드가 지저분해보일 수는 있지만, UIKit을 하는 이상 누구나 읽으면 이해할 수 있는 코드기 때문에 길고 지저분하더라도 그냥 쓰는 편이 더 낫다고 생각해요.

다시 한번 말씀드리지만, 이건 말그대로 제 생각일 뿐이에요. 두 분에게 이런 생각을 하는 사람도 있다는 걸 말씀드리고 싶었어요. 두 분이 생각해보시고 더 선호하시는 방향으로 진행하시면 될 것 같아요.

2024-02-13 12:58 UTC, minsson commented
두 분 정말 고생하셨습니다! 기한이 마감되어 다른 프로젝트를 진행하면서도 기존 프로젝트에 신경쓰는 게 쉽지 않으셨을텐데, 두 분이 함께 고쳐나가신 걸 보고 정말 대단하시다고 생각했어요. 앞으로도 화이팅이에요! 🙌

2024-02-13 12:58 UTC, merged