연락처 관리 앱 [STEP 2] NERO, Nnn
tasty-code/ios-contact-manager-ui pull request #88
Opened 2024-01-18 13:36 UTC by ODDNERO

# 연락처 관리 앱 프로젝트

**그린**(@GREENOVER), 안녕하세요~!

이번 PR은 STEP 2와 STEP 3 필수 구현인 연락처 삭제 부분을 같이 포함했습니다!
잘 부탁드립니다 😸

## 🗂️ 폴더 구조

```
ios-contact-manager-ui/
├── 📂 Model/
│ ├── 📄 ContactManager.swift
│ └── 📄 Person.swift
├── 📂 View/
│ ├── 📄 LaunchScreen.storyboard
│ └── 📄 Main.storyboard
├── 📂 Controller/
│ ├── 📄 ContactListViewController.swift
│ └── 📄 DetailViewController.swift
└── 📂 Support/
  ├── 📄 UIViewController+.swift
  └── 📄 String+.swift
```

## 🏗️ UML
![Untitled-2](https://github.com/tasty-code/ios-contact-manager-ui/assets/144796294/e156c216-93ed-4340-9018-4bcb769420f9)

<br/>

## 🛠️ 새로 추가된 것

+ **UUID** 적용
+ DetailViewController 생성
+ 화면 전환 **Modal** 구현
+ **델리게이트 패턴**을 통해 데이터 전달
+ **Alert** 생성
+ 전화번호 양식 **Hyphen**(-) 자동 완성 기능
+ **스와이프 액션**을 통한 삭제 기능 
+ 테스트 코드 stub으로 분리
+ Singleton → **의존성 역전 주입**

<br/>

## 📝 참고 사항

프로젝트 구현 내용에 내부 저장 데이터 부분이 포함되어 있지 않아서 Coredata는 구현하지 않았습니다! 대신 **SceneDelegate를 통해 데이터를 불러오도록** 리팩토링하였습니다

<br/>

## ❓ 질문 사항

1. **데이터 전달 방식**에 대하여
[ 프로토콜 델리게이트 / 클로저 / KVO / 노티피케이션 / 리스폰더 체인 ]
- **그린**은 자주 사용하시는 데이터 전달 방식이 있나요? 어떤 방식을 추천하시나요?
- 현업에서 주로 사용하는 방식이 있나요? 
- 현재 프로젝트에서는 무엇이 제일 적절할까요? 🤔
2. 각 구역마다 **`MARK: -` 주석**으로 나눠서 표시하는 것에 대해 어떻게 생각하시나요?
- 저는 읽기 편해서 마냥 좋다고 생각했는데 ‘함수나 변수로 표현할 수 있다면 주석을 달지 마라’라는 말을 책에서 보고, 편의를 위해서 다 달아 놓는 게 과연 좋은 것일까? 하는 의문이 생겼습니다 (현재 코드에는 그렇게 달지 않은 상태입니다)
그런데 MARK 주석은 문단을 나눠서 정리해 주는 느낌이라 그냥 주석과는 성격이 다르기도 하고, extension 활용처럼 깔끔함을 위해 마구마구 써도 괜찮을지…? **그린**의 의견을 여쭙고 싶습니다
4. `saveButtonTapped()`가 너무 많은 것을 담고 있어서 내부 코드를 줄이고 싶은데, 어떻게 분리하는 게 좋을까요? 
**그린**이라면 여러 접근 중에 어떤 방식으로 하실 것 같은지 여쭤봅니다! 🙋🏻

```swift
@IBAction func saveButtonTapped(_ sender: UIBarButtonItem) {
        let name = nameTextField.text ?? ""
        let age = ageTextField.text ?? ""
        let phoneNumber = phoneNumberTextField.text ?? ""
        
        let namePattern = "^[a-zA-Z가-힣]*$"
        let agePattern = "^[0-9]{1,3}$"
        let phoneNumberPattern = "^\\d{2,3}-\\d{3,4}-\\d{4}$"
        
        let isNameValid = NSPredicate(format: "SELF MATCHES %@", namePattern).evaluate(with: name)
        let isAgeValid = NSPredicate(format: "SELF MATCHES %@", agePattern).evaluate(with: age)
        let isPhoneNumberValid = NSPredicate(format: "SELF MATCHES %@", phoneNumberPattern).evaluate(with: phoneNumber)
        
        switch true {
        case !isNameValid:
            self.showMessageAlert(message: "입력한 이름 정보가 잘못되었습니다")
        case !isAgeValid:
            self.showMessageAlert(message: "입력한 나이 정보가 잘못되었습니다")
        case !isPhoneNumberValid:
            self.showMessageAlert(message: "입력한 연락처 정보가 잘못되었습니다")
        default:
            let personData = Person(name: name, age: Int(age) ?? 0, phoneNumber: phoneNumber)
            model?.addPerson(person: personData)
            
            updateContactdata()
            self.dismiss(animated: true)
        }
    }
```

<br/>

## 📸 스크린샷
<img width="1000" alt="Untitled" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/144796294/d6636195-e8e1-419d-b5f2-881eb60bb817">

<br/>
<br/>

2024-01-19 01:06 UTC, GREENOVER requested changes
스텝 2 너무 고생 많으셨습니다!!
전체적으로 스텝 1 리팩토링에 거쳐 스텝2,3 필수 구현까지 완료해주셨네요ㅎㅎ
이번 PR 리뷰에서는 좀 더 보완될 수 있는 부분들과 리팩토링 포인트를 가지고 남겨보겠습니다!
***
### 칭찬 드리고 싶은 부분
- 파일과 폴더 그룹핑 등 분리가 아주 잘 되었네요 💯
- 프로토콜 사용 아주 나이스해요! 💯
- 전체적으로 코드가 잘 나눠져있고 가독성도 좋아요 💯
- 얼럿 공통으로 빼셔서 사용하는거 아주 인상 깊었습니다ㅎㅎ 💯
***
### 궁금하신 부분에 대한 저의 의견
- 데이터 전달 방식에 대하여
  - 사실 이 부분에 대해 어떤것이 정답이고 추천이다라는것은 없을것 같아요..!
  상황마다 코드 스타일마다 다를것이기에, 추천보다는 현재 프로젝트 상황에 맞춰봤을때 저라면 여러분들이 구현하신것처럼 딜리게이트 패턴이나 클로저로 구현했을것 같습니다ㅎㅎ
  물론 KVO, 노피티케이션 모두 사용은 가능하겠지만 딜리게이트 패턴을 이용하는것이 좀 더 깔끔하고 적합하다고는 느껴집니다.
  KVO, 노티피케이션도 다른 환경에선 딜리게이트나 클로저보다 더 적절하고 심플하게 들어맞는 상황들이 분명 있을거에요.
  그렇기에 결론적으로는 상황마다 우선순위로 삼는것이 다르지만 현재 프로젝트에선 지금과 같은 구현 전 좋습니다!
- 각 구역마다 MARK: - 주석으로 나눠서 표시하는 것에 대해 어떻게 생각하시나요?
  - 저는 일단 동의합니다.
  물론 메서드나 변수 네이밍을 가장 직관적이고 가독성 좋게 가져가는것은 MARK 주석을 다나 안다나 추구해야될것이라고 생각해요.
  마크 주석을 달지 않는것이 좋다라는 의견도 있을 수 있겠지만, 어떤 한쪽이 정답이 아닌 스타일의 차이이기 때문에 여러분들이 느끼셨을때 마크 주석을 활용하는것이 팀원간 서로 다 좋다라고 한다면 적극적으로 사용해도 전 좋다고 생각합니다.
- saveButtonTapped()가 너무 많은 것을 담고 있어서 내부 코드를 줄이고 싶은데, 어떻게 분리하는 게 좋을까요?
  - 아하 리뷰 코멘트로도 남겨보긴 했는데요..!
  현재 유효성 검사를 하는 부분들을 메서드로 분리해도 훨씬 가독성이 좋아질것 같아요~!
  saveButtonTapped는 정보를 가지고 저장하는 역할만 가져가고 유효성 자체는 다른 메서드 로직을 태우면 지금 고민하시는 부분이 조금 덜어지지 않을까 생각합니다 🙋🏻
***
### 보완되면 좋을 부분
- 현재 기획상으로는 이름에 띄워쓰기가 있으면 자동으로 공백을 제거하고 저장해주는데 그 기능이 빠진것 같아요 🥲
한번 체크해보셔도 좋을것 같습니다!
- 이건 기획에는 없지만, 연락처를 저장하면 이름의 알파벳 기준으로 순차 정렬을 해주면 좀 더 사용성이 좋을것 같습니다!
***
다시 한번 긴 여정 고생 많으셨습니다 여러분!
많이 힘드셨을텐데 끝까지 잘 완주를 해주신 여러분께 박수를 👏👏👏
우선은 리팩토링 지점을 남겨둬서 Request Changes로는 남겨두겠습니다!
언제든지 재리뷰 혹은 머지 요청 해주세요~!

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/UIViewController+.swift
> +extension UIViewController {
공통적으로 사용할 수 있게 한 부분 너무너무 좋네요 👍

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/UIViewController+.swift
> +    func showMessageAlert(title: String? = nil,
요런 개행 스타일은 어떠신가요?
다른 부분들과 통일될것 같기도하고 현재 개행보다 가독성이 좀 더 있지 않을까 싶어서요..!
```swift
func showMessageAlert(
  title: String? = nil
  ...
  completion: (() -> ())? = nil
) { 
  ...
}
```
저는 주로 이런 파라미터 개행 스타일을 많이 이용하는데 장점은 메서드명도 길어지고 파라미터 정의도 길어질때 빛을 발휘하더라구요..!
정답은 아니니 이런것도 있다~ 정도 보시면 좋을것 같아요ㅎㅎ

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/String+.swift
> +import UIKit
UIkit 요소가 사용되지 않기에 Foundation만으로도 충분할것 같습니다 🤔

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/String+.swift
> +        }
조건문에서 사실 offsetBy에 들어갈 값외 코드가 중복되는 느낌인데 합쳐서 로직을 간소화 해보면 어떨까요~?
예를들어 저는 이런식도 있다고 생각했습니다!
```swift
func addPhoneNumberHyphen() -> String {
    var formatText = self.components(separatedBy: CharacterSet.decimalDigits.inverted).joined()
    
    guard !formatText.isEmpty else {
        return ""
    }
    
    let hyphen: Character = "-"
    let prefix = formatText.hasPrefix("02") ? 2 : 3
  
    let firstHyphenIndex = formatText.index(formatText.startIndex, offsetBy: prefix)
    
    if formatText.count >= prefix + 1 {
        formatText.insert(hyphen, at: firstHyphenIndex)
    }
    
    if formatText.count > prefix + 4 {
        let secondHyphenIndex = formatText.index(formatText.endIndex, offsetBy: -4)
        formatText.insert(hyphen, at: secondHyphenIndex)
    }
    
    return formatText
}
```
정말 예시이며, 핵심은 prefix를 이용해보는거일것 같아요ㅎㅎ

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Person.swift
> +    var uuid: String
UUID값을 String 타입으로 사용하시는 이유가 궁금합니다 🙋🏻

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +    func deletePerson(inputUuid: String) {
UUID는 키워드(약어) 같은거라 UUID로 가는것이 더 나을것 같아요!
즉, 소문자 혹은 대문자로 다 표현하고 카멜케이스 적용이 오히려 잘 안하는 추세긴해서요..!
대표적으로 ID, URL과 같은것들이 속할것 같습니다 🙋🏻

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        self.model?.readContacts()
실제 해당 메서드를 통한 반환값이 사용되지 않는것 같아서, 만약 사용되지 않을 경우도 있다면, 해당 메서드에 @discardableResult을 붙여 사용해보는것도 좋습니다ㅎㅎ

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
>          let detailVC = storyboard?.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
강제 타입 캐스팅을 하고 있는데, 타입이 다르거나 매칭이 안된다면 런타임 에러가 나지 않을까요..!?
as?를 사용하면서 if let 옵셔널 바인딩을 이용하는건 어떠신가요? 🙋🏻

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +}
LGTM 👍👍👍

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +        let isPhoneNumberValid = NSPredicate(format: "SELF MATCHES %@", phoneNumberPattern).evaluate(with: phoneNumber)
각각 혹은 통합해서 유효성 검사를 위한 메서드를 만들어 Bool을 반환해봐도 좋을것 같아요!

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +        switch true {
if else가 아닌 switch true로 하신 이유가 궁금합니다🙋🏻
잘못되었다는건 전혀 아니고 가독성에서 조금 더 나아보이셨는지 등 선택하신 이유가 단순히 궁금해서요..!ㅎㅎ

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +    private func keyboardSetUp() {
setup은 보통 한단어로 표현해서 카멜 케이스를 따로 적용하는걸 잘 못보긴해서 공유드립니다..!
한번 다른 라이브러리 같은 코드들에선 어떻게 사용하는지 찾아봐도 좋은 레퍼가 될것 같아요 😃

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +extension DetailViewController {
아래 메서드들이 모두 private해도 된다면 private extension으로 선언해도 좋을것 같아요~!

2024-01-19 01:06 UTC, GREENOVER commented on ios-contact-manager-ui/ios-contact-manager-ui/SceneDelegate.swift
> +        let stub: [Person] = [
stub 데이터를 Model > Person에 위치시키면 SceneDelegate 코드가 좀 더 간결해지고 관심사도 그쪽이 조금 더 맞아 보이는데 어떻게 생각하시나요~?

2024-01-20 06:35 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/ContactManager.swift
> +    func deletePerson(inputUuid: String) {
UUID로 통일하였습니다 🫡🫡

2024-01-20 06:41 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/String+.swift
> +import UIKit
리뷰 반영하여 String+, Person, ContactManager 파일 임포트 부분 Foundation으로 변경했습니다!

2024-01-20 06:50 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
> +        self.model?.readContacts()
readContacts 메서드에 @discardableResult 추가했습니다! Warning 메시지가 사라지네요! 👍🏻👍🏻

2024-01-20 06:56 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/ContactListViewController.swift
>          let detailVC = storyboard?.instantiateViewController(withIdentifier: "DetailViewController") as! DetailViewController
`!` 사용은 항상 주의하겠습니다...! 해당 부분 `if let` 옵셔널 바인딩으로 수정하였습니다 🙇🏻‍♀️

2024-01-20 06:58 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +}
LGTM 약어도 처음 알고 가네요!! 👏🏻👏🏻😸

2024-01-20 07:03 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +        let isPhoneNumberValid = NSPredicate(format: "SELF MATCHES %@", phoneNumberPattern).evaluate(with: phoneNumber)
```swift
func isInputTextValid(name: String, age: String, phoneNumber: String) -> [String: Bool] {
        let namePattern = "^[a-zA-Z가-힣]*$"
        let agePattern = "^[0-9]{1,3}$"
        let phoneNumberPattern = "^\\d{2,3}-\\d{3,4}-\\d{4}$"
        
        let isNameValid = NSPredicate(format: "SELF MATCHES %@", namePattern).evaluate(with: name)
        let isAgeValid = NSPredicate(format: "SELF MATCHES %@", agePattern).evaluate(with: age)
        let isPhoneNumberValid = NSPredicate(format: "SELF MATCHES %@", phoneNumberPattern).evaluate(with: phoneNumber)
        
        return ["name": isNameValid, "age": isAgeValid, "phoneNumber": isPhoneNumberValid]
    }
```
메서드 분리하여 Bool값을 딕셔너리로 반환하도록 리팩토링하였습니다!! 🫡

2024-01-20 07:09 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +        switch true {
개인적으로 switch가 각 케이스들을 읽기에 더 가독성이 좋다고 생각해서 스위치로 구현했었습니다!
그런데 이번에 메서드 분리하고 스위치 사용이 조금 어려워져서 if else로 변경했습니다 😅😅

2024-01-20 07:13 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +    private func keyboardSetUp() {
Setup이 한 단어인데 저렇게 썼었네요...! 🙀 바로 수정하였습니다!

2024-01-20 07:41 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Controller/DetailViewController.swift
> +extension DetailViewController {
private extension으로 수정하였습니다! private 기준이 아직 어려운 것 같네요 😹

2024-01-20 10:02 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Model/Person.swift
> +    var uuid: String
UUID를 생성을 `UUID().uuidString`으로만 하는 줄 알고 있었는데, 그냥 `.uuid`로 생성하면 Int로 생성할 수 있었군요 🙀
저는 `.uuidString`으로 생성했기 때문에 Person이 가진 UUID의 타입도 String으로 줬었습니다!

2024-01-20 10:39 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/UIViewController+.swift
> +    func showMessageAlert(title: String? = nil,
<img width="546" alt="image" src="https://github.com/tasty-code/ios-contact-manager-ui/assets/144796294/3930cf72-6ea1-4192-b475-fef182c803b7">

한 칸씩 밀려 있던 부분 이렇게 수정하였습니다!

2024-01-21 07:02 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/SceneDelegate.swift
> +        let stub: [Person] = [
stub 데이터를 Person에 옮겨 static으로 두고, 
ContactManager에서 `Person.makeStubData()`로 접근하여 contactList에 포함하도록 리팩토링하였습니다! 
```swift
final class ContactManager {
    var contactList = [Person]()
    
    init() {
        contactList = Person.makeStubData()
    }
```

2024-01-21 08:01 UTC, ODDNERO commented on ios-contact-manager-ui/ios-contact-manager-ui/Support/String+.swift
> +        }
예시도 작성해 주시다니... 🥹👍🏻👍🏻👍🏻 감사합니다 
prefix 사용이 아직 어려운 것 같아서, 리팩토링은 일단 너무 길었던 `addPhoneNumberHyphen()` 메서드를 쪼갠 후 삼항연산자에 적용하는 것으로 진행해 보았습니다! 
```swift
    func addPhoneNumberHyphen() -> String {
        ...
        
        text = text.hasPrefix("02") ?
        addHyphenSeoulNumber(text, hyphen) : addHyphenNumber(text, hyphen)
        
        return text
    }
    
    func addHyphenSeoulNumber(_ text: String, _ hyphen: Character) -> String {
        var formatText = text
        
        switch formatText.count {
        case 3...5:
        ...
```
prefix를 이용해 계산하는 것... 꼭 공부해 보겠습니다 😹

2024-01-21 23:12 UTC, merged